### ISSUE TITLE
Add `vagrant settings` command to get a vm settings from the cli

### ISSUE THREAD

**Issue by malinoff** [mitchellh/vagrant#6668] opened 2015-12-15 11:01 UTC
This is quite useful in cases when VMs are defined dynamically (Vagrantfile is ruby, after all).
Settings may be used, for example, to dynamically identify connection protocol (ssh or winrm) which should be used by external tools to connect to VMs.

**Comment by sethvargo** [comment] 2015-12-15 15:52
Hi @malinoff 

Thank you for opening an issue. That being said, I'm not exactly sure what you mean. Could you provide some examples?

**Comment by malinoff** [comment] 2015-12-15 16:55
@sethvargo sure.
Given the following Vagrantfile:
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.provider :virtualbox do |vb|
    vb.customize [
      "modifyvm", :id,
      "--cpuexecutioncap", "50",
      "--memory", "256",
    ]
  end

  config.vm.define "app" do |app|
    app.vm.network :private_network, ip: "10.100.0.10"
  end

  config.vm.define "db" do |app|
    app.vm.box = "windows"
    app.vm.network :private_network, ip: "10.100.0.20"
    app.vm.communicator = "winrm"
    app.vm.provider :virtualbox do |vb|
      vb.customize [
        "modifyvm", :id,
        "--cpuexecutioncap", "100",
        "--memory", "1024",
      ]
    end
  end
end
```
I'd like to be able to run `vagrant settings` and get something like (probably with an option to get more machine-parseable output, like json) this, similarly to `vagrant ssh-config`:
```bash
app
  vm.box debian/jessie
  vm.network
    private 10.100.0.10
  vm.communicator ssh
  vm.provider
    virtualbox
      --cpuexecutioncap 50
      --memory 256

db
  vm.box windows
  vm.network
    private 10.100.0.20
  vm.communicator winrm
  vm.provider
    virtualbox
      --cpuexecutioncap 100
      --memory 1024
```

This will allow external tools to dynamically construct connection strings, for example, by getting the communicator value. I believe that other settings like manually set private addresses are useful too.

**Comment by oliver-dungey** [comment] 2015-12-15 17:06
+1, great idea. I'd like it to spit out the current settings of the VM rather than the settings in the Vagrantfile. I hunted for this feature just last week when I couldn't remember If I had re-provisioned my VM's after making changes to my Vagrantfile.

**Comment by malinoff** [comment] 2015-12-15 17:22
I should also tell another reason to have this feature - highly customized Vagrantfiles. I have a legacy project where the previous ops team have literally developed a Vagrantfile-based deployment tool, with yaml-based configuration files and merging different environment-based specific configuration files.
Obviously, this Vagrantfile is not `grep`able, nor parseable. It can only be processed by Vagrant itself.

**Comment by sethvargo** [comment] 2016-06-01 03:53
Hi there,

I am going to close this as a duplicate of https://github.com/mitchellh/vagrant/issues/6184, which is targeted for 2.0. Thanks!

**Closed by sethvargo** 2016-06-01 03:53 UTC
Labels: core, enhancement
