### ISSUE TITLE
1.9.1 default: Warning: Authentication failure. Retrying... 

### ISSUE THREAD

**Issue by nootfly** [mitchellh/vagrant#8204] opened 2017-01-14 12:42 UTC
### Vagrant version
Vagrant 1.9.1

### Host operating system
macOs 10.12.2

### Guest operating system
ubuntu/trusty64

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder "myFiles/", "/home/vagrant/shared"

end
```

### Debug output
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...

### Expected behavior
I should login the VM.

### Actual behavior
I cannot login.

### Steps to reproduce
1. I switch to another network
2. vagrant up

**Comment by FibreFoX** [comment] 2017-01-14 21:42
Maybe related to https://github.com/mitchellh/vagrant/issues/8157

**Comment by nootfly** [comment] 2017-01-14 22:58
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

~/vagrant/myVM
☺  vagrant ssh                                                                                                                  (ruby-2.3.0)
vagrant@127.0.0.1's password:

it requires a password.

**Comment by kikitux** [comment] 2017-01-15 06:17
@nootfly can you test with box `hashicorp/precise64` ?

We only provide the boxes under hashicorp org in atlas.

If this is an issue with the box, you should try to reach canonical

**Comment by vrioche** [comment] 2017-01-15 12:34
Same issue here on Ubuntu 16.04 host, after I've tried to launch a packaged ubuntu/trusty64 box. I think the problem isn't box related because every other packaged boxes doesn't work.

**Comment by FibreFoX** [comment] 2017-01-15 12:37
I suspect something is up with virtualbox ... similar problems on https://github.com/mitchellh/vagrant/issues/8157 just with windows host. Seems not box related :(

**Comment by mauricioabreu** [comment] 2017-01-16 17:11
I don't think it is related to the box as @FibreFoX said above.
I use centos/7 box and it happens to me. After fixing this (restarting network, restarting macOS and other random attempts to fix this) it returns to happen.

**Comment by kikitux** [comment] 2017-01-26 08:03
Hi, if you can share a debug log when this happens, that will help to move this faster

**Comment by sully7** [comment] 2017-02-05 18:49
Same problem on Windows 10 as well.

**Comment by richard-scott** [comment] 2017-02-19 20:43
I get this on an Ubuntu 16.04 host starting a bento/debian VM in VirtualBox...  Funny thing is that if I open a new terminal session while the main one is not connecting I can run 'vagrant ssh'  and get I to the VM.

**Comment by rmezar** [comment] 2017-02-24 02:36
Solved http://www.gisremotesensing.com/2016/06/solution-vagrant-box-authentication.html

**Comment by FibreFoX** [comment] 2017-02-24 08:00
@rmezar You mean the used box is the culprit? I personally had a different source of problem, but I am surprised that the authorized_keys of the BOX should be responsible for this ...

**Comment by richard-scott** [comment] 2017-02-24 09:40
My problems were fixed by running this before "vagrant up":

```
export SSH_AUTH_SOCK=""
```

For some reason the ssh-agent was causing a conflict.

**Comment by chrisroberts** [comment] 2017-03-02 19:18
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2017-03-02 19:18 UTC
Labels: waiting-reply
