### ISSUE TITLE
Provision command to refresh environment variables

### ISSUE THREAD

**Issue by vmrob** [mitchellh/vagrant#4334] opened 2014-08-11 22:58 UTC
I'm falling short on what might be appropriate syntax as Vagrant is still relatively new to me, but let me explain the relevant feature and use case as best as I can:

There are cases where a basebox may not have all of the system environment variables pre-configured. One such case is where Chef is both installed _and_ used in the same Vagrantfile. When this is the case, the user has to go out of the way to provide a means to sync up environment variables with the ssh process or WinRM process (is this possible?). The only workaround on Windows I'm aware of is to explicitly specify the chef binary location using `chef.binary_path = 'c:/opscode/chef/bin'`. This obviously doesn't work as a general solution.

My proposal is to include provisioner utility that simply disconnects ssh/winrm and then reconnects to the guest VM. I think this would provide a simple workaround that may have more use cases than I'm stating here.

**Comment by buckleytom** [comment] 2015-01-21 21:18
:+1:

**Comment by iDVB** [comment] 2015-06-18 14:13
Is there a fix for this? I'm still seeing a `The term 'puppet' is not recognized as the name of a cmdlet` error when trying to provision puppet and then run it. Can only ever see the vars set when RDP
'n in.  Sounds similar to the issue mentioned here... https://tickets.puppetlabs.com/si/jira.issueviews:issue-html/PUP-3471/PUP-3471.html

But not sure if anyone has narrowed it down to whether its a Puppet or Vagrant issue?

**Comment by ryanewtaylor** [comment] 2016-01-11 21:45
I am believe that I am running into this issue as well when trying to install _and use_ chocolatey from the same Vagrantfile. This would be a welcome addition. Has there been any updates on this?

**Comment by StefanScherer** [comment] 2016-01-12 16:52
Perhaps https://github.com/chocolatey/chocolatey-test-environment/blob/master/shell/NotifyGuiAppsOfEnvironmentChanges.ps1 might help sending a notification.

I personally use multiple provision scripts which work around the problem. If one chocolatey package adds a directory to the PATH the next provision script gets the updated envs from the new WinRM login. Work for me this way: https://github.com/StefanScherer/docker-windows-box/blob/master/Vagrantfile#L34-L41

**Comment by ryanewtaylor** [comment] 2016-01-12 17:04
@StefanScherer I added https://github.com/chocolatey/chocolatey-test-environment/blob/master/shell/NotifyGuiAppsOfEnvironmentChanges.ps1 as well and that resolved an issue on the guest virtual machine not updating the PATH but it did not seem to address the issue of the WinRM session not getting the updated environment paths.

I use separate provision scripts as well but for some reason this does not seem to skirt around the issue. For instance I have:

```
config.vm.provision "shell", path: "./scripts/InstallChocolatey.ps1"
config.vm.provision "shell", path: "./scripts/NotifyGuiAppsOfEnvironmentChanges.ps1"
config.vm.provision "shell", path: "./scripts/InstallApps.ps1"
```

`./scripts/InstallApps.ps1 simply installs ConEmu. It looks like this:

```
$env:Path += ";C:\ProgramData\chocolatey\bin"
chocolatey feature enable -n=allowGlobalConfirmation
choco install conemu
chocolatey feature disable -n=allowGlobalConfirmation
```
However, without the first line hard coding the path, the shell script fails as it cannot find a path to `choco`. It's very strange as most repos I find using Vagrant do not seem to have this issue. The only solid reference to this is this ticket.

FWIW I have documented the issue and my current attempts on StackOverflow.

**Comment by ferventcoder** [comment] 2016-01-12 19:50
Here's a possible fix - https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Update-SessionEnvironment.ps1

**Comment by ferventcoder** [comment] 2016-01-12 19:51
It's what choco uses internally during the powershell runs to ensure the paths get updated. We have refreshenv that we have for cmd.exe, but nothing exposed to users for ensuring powershell is updated.

**Comment by ferventcoder** [comment] 2016-01-12 19:52
There are also some notes on how it overwrites any current environment vars - so use with care. 

* https://github.com/chocolatey/choco/issues/295
* https://github.com/chocolatey/choco/issues/129

**Comment by sethvargo** [comment] 2016-05-29 22:06
Hi @vmrob 

Is this still an issue now that Vagrant automatically installs Chef for you?

**Comment by sethvargo** [comment] 2016-07-19 01:53
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by sethvargo** 2016-07-19 01:53 UTC
Labels: enhancement, waiting-reply
