### ISSUE TITLE
OS X host w/ NFS shared folder fails when private NIC is before auto_config:false NIC

### ISSUE THREAD

**Issue by megahall** [mitchellh/vagrant#5376] opened 2015-02-22 03:59 UTC
Using the following shared folder and virtual network interface list on OS X with an Ubuntu 14.04 guest raises this error:

    No guest IP was given to the Vagrant core NFS helper. This is an
    internal error that should be reported as a bug.

It raises the error when the stanzas are in this order:

    config.vm.synced_folder ".", "/vagrant", type: "nfs"
    # DPDK interface
    config.vm.network "public_network", auto_config: false, :nictype => "82545EM"
    # Host Stack interface (for testing sensor)
    config.vm.network "public_network", auto_config: true, :nictype => "82545EM"
    # NFS interface (for shared folder)
    config.vm.network "private_network", type: "dhcp"

It does **NOT** raise the error anymore in this order:

    config.vm.synced_folder ".", "/vagrant", type: "nfs"
    # NFS interface (for shared folder)
    config.vm.network "private_network", type: "dhcp"
    # DPDK interface
    config.vm.network "public_network", auto_config: false, :nictype => "82545EM"
    # Host Stack interface (for testing sensor)
    config.vm.network "public_network", auto_config: true, :nictype => "82545EM"

Not being familiar with the guts of Vagrant, I suspect it gets confused by an `auto_config: false` interface appearing earlier in the list than the `private_network` interface for NFS.

This error is kind of obscure and maybe not super urgent but I thought it deserved to be documented for posterity.

**Comment by sethvargo** [comment] 2015-07-10 20:42
Hi there,

I just tried to reproduce the issue using Vagrant 1.7.3 and I do not get an error in either scenario. I am going to close this issue because I think it has been fixed, but if the latest release of Vagrant is still not working, can you please post the complete Vagrantfile and the result of the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html) and we can reopen? Thanks!

**Closed by sethvargo** 2015-07-10 20:42 UTC
Labels: bug, synced-folders/nfs

**Comment by megahall** [comment] 2015-07-10 20:55
I am good with closing. I mainly wanted to document in case other people ran into it.
