### ISSUE TITLE
Regression: NFS synced folders broken on multi-user systems

### ISSUE THREAD

**Issue by rhalkyard** [mitchellh/vagrant#6200] opened 2015-08-26 21:33 UTC
https://github.com/mitchellh/vagrant/commit/6ff15fb breaks NFS synced folders on multi-user systems:

```
user1@host: vagrant1$ vagrant up
...
user1@host: vagrant1$ ls -l /tmp/exports
-rw-r--r--. 1 user1 user1 235 Aug 26 16:08 /tmp/exports
```

Then, if another user on the same system tries to bring up a VM:

```
user2@host: vagrant2$ vagrant up
...
==> vagrant2: Pruning invalid NFS exports. Administrator privileges will be required...
cp: cannot create regular file ‘/tmp/exports’: Permission denied
==> vagrant2: Pruning invalid NFS exports. Administrator privileges will be required...
cp: cannot create regular file ‘/tmp/exports’: Permission denied
...
==> vagrant2: Exporting NFS shared folders...
==> vagrant2: Preparing to edit /etc/exports. Administrator privileges will be required...
cp: cannot create regular file ‘/tmp/exports’: Permission denied
```

The aftermath varies depending on the permissions of /tmp/exports, but in this case, where /etc/exports was empty to begin with, it ended up containing only user2's export, since /tmp/exports was stuck at what it looked like after user1's actions.

**Comment by danielsand** [comment] 2015-11-04 11:13
hey,

that is not a bug/problem of vagrant - its a problem of your local linux setup.
If you create a group 'vagrant' and put the user1 and user2 inside chgrp /tmp/exports to the vagrant group + addition group writing flag it will work.

**Comment by sethvargo** [comment] 2015-11-07 23:19
Hi @rhalkyard 

As Daniel said, this is not a problem with the NFS synced folder. You either need to specify the permissions or create a user that has the proper permissions.

**Comment by rhalkyard** [comment] 2015-11-07 23:43
I disagree, @sethvargo. This is not an issue with permissions on /etc/exports. It is an issue with permissions on a temporary file created by Vagrant, and a regression in functionality from previous versions.

In my view, the issue is threefold: first off, Vagrant is creating a temporary file with a fixed, hardcoded name (/tmp/exports), rather than using a randomly generated filename, as is widely considered best practice. Secondly, Vagrant is not deleting the temporary file once it is done with it. Thirdly, if Vagrant is unable to overwrite an already existing copy of the file, it silently continues, rather than failing with an error.

Creating /tmp/exports and setting open permissions on it will work around the issue, but since /tmp is, by definition, transient, and the file is getting created by Vagrant in the first place (rather than being already present in the system), it is a Vagrant bug.

**Comment by danielsand** [comment] 2015-11-19 11:14
@rhalkyard sorry if this sounds offensive :)
But This is no problem of Vagrant :D
In a Common Vagrant User setup you use Vagrant and whatever Virtual provider want to use one your local development environment. 
Which is in a common way - a single user :) not multiple.
If you want to use vagrant on a multiuser environment then you need to tweak your Local System setup to give the right permissions so that any user could access /tmp/exports and work with it.
I catch your gist on what you want to do - but i dont see the reason a having multiple users running vagrant on one Laptop.
and as an idea of progress: What kind of local Dev Setup you have which requires multiple users ? 
honestly - your the first one i have seen this kind of local setup for vagrant... and im working with vagrant for over 4+ Years and used it in a bunch of companies. 
None had the concept of multiple local users vagrant setups.

**Comment by rhalkyard** [comment] 2015-11-19 20:17
I wouldn't say I'm offended, just disappointed. Generating randomized names for temp files, removing them after use, and checking for errors on filesystem actions are all well-established good practices, whether running on a multiuser system or not. Maybe I'm just old-fashioned, but to me, software should be designed to coexist gracefully with other users unless it has a very good reason not to.

The project that we're using Vagrant for is a fairly complex one, with potentially large numbers of VMs, and pretty significant RAM requirements – 6-8GB per VM is a bare minimum. We've written some wrappers around Vagrant that can scale a deployment from 2 or so VMs running on a developer's laptop, to 10+ running on shared build servers with obscene amounts of RAM. It's on those shared build servers where we're running into this issue. While I can accept that Vagrant's main intended use case is for a single developer on a single machine, I don't think it unreasonable to expect it to work on multiuser systems – after all, it worked just fine for us until 1.7.4.

**Comment by mitchellh** [comment] 2015-11-19 20:43
It may not be a problem, but I think this is fixable. We can just remove that file after we copy it back. I'll reopen and do that today.

**Comment by rhalkyard** [comment] 2015-11-19 21:52
Thanks! I really appreciate it. I'd have opened a PR myself, but the interest didn't seem to be there until now.

**Comment by jameskyle** [comment] 2016-06-20 20:50
I ran into this issue today on a multi-user server. As @rhalkyard mentioned, creating randomly named temp files for each calling user is the standard way to handle it. Given the nature of the file, it may even be more appropriate to store it in ~/.vagrant.

**Comment by thatsk** [comment] 2016-09-08 14:27
Hats off!!!!!!!!!!!

**Comment by thatsk** [comment] 2016-09-08 14:27
Helped alot

**Comment by chrisroberts** [comment] 2016-12-08 21:37
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Closed by chrisroberts** 2016-12-08 21:37 UTC
Labels: host/linux, synced-folders/nfs
