### ISSUE TITLE
WinRM ip address / connection error with vmware-workstation plugin

### ISSUE THREAD

**Issue by diseq** [mitchellh/vagrant#6027] opened 2015-07-23 09:14 UTC
Vagrant: 1.7.4
vagrant-vmware-workstation: 3.2.9

I use vagrant-vmware-workstation to connect to the win10x64-enterprise from https://github.com/boxcutter/windows.

Debug log:
```
DEBUG vmware: VM state requested. Current state: running
 INFO subprocess: Starting process: ["C:\\Program Files (x86)\\VMware\\VMware Workstation/vmrun.exe", "list"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
ERROR warden: Error occurred: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
```

vagrant terminates before provisioning.

**Comment by sethvargo** [comment] 2015-08-06 20:14
Duplicate of https://github.com/smdahlen/vagrant-hostmanager/issues/157

**Closed by sethvargo** 2015-08-06 20:14 UTC

**Comment by StefanScherer** [comment] 2015-08-12 14:29
I have the same issue with this environment:
Host OSX 10.10.4, VMware Fusion 7.1.2, the following vagrant plugins
```
$ vagrant plugin list
winrm-fs (0.2.2)
vagrant-multiprovider-snap (0.0.14)
vagrant-pristine (0.3.0)
vagrant-share (1.1.4, system)
vagrant-vmware-fusion (3.2.11)
```

As you can see, I do not have the `vagrant-hostmanager` plugin.
I also use a Windows 10 guest from boxcutter/windows as well as joefitzgerald/packer-windows.

I think I have to dig deeper...

**Comment by Dwaynekj** [comment] 2015-11-24 18:31
@StefanScherer Were you able to resolve this? I doing something similar to you (utilizing packer-windows) https://github.com/Dwaynekj/packer-windows/tree/parallels

**Comment by StefanScherer** [comment] 2015-11-24 22:13
@Dwaynekj In the meantime I could solve my Win10 problems by updating winrm and winrm-fs. My setup at the moment looks like

```
$ vagrant plugin list
winrm (1.3.5)
winrm-fs (0.2.3)
vagrant-hostmanager (1.6.1)
vagrant-multiprovider-snap (0.0.14)
vagrant-pristine (0.3.0)
vagrant-share (1.1.4, system)
vagrant-triggers (0.5.2)
vagrant-vmware-fusion (4.0.2)
```

Had another issue yesterday with a Win2016TP4 VM which can be fixed with https://github.com/mitchellh/vagrant/issues/6580#issuecomment-159081554
