### ISSUE TITLE
Can't mount /vagrant share on Windows7 and virtualbox provisioner

### ISSUE THREAD

**Issue by lukaszjakubek** [mitchellh/vagrant#5983] opened 2015-07-17 14:19 UTC
Can't mount /vagrant share on Windows7 host and linux debian 8 guest. Using virtualbox provider and no additionals shares configuration in Vagrantfile.

Vagrant 1.7.3
Virtualbox 5.0.0 r101573

Console output:
````
==> default: Attempting graceful shutdown of VM...
==> default: Forcing shutdown of VM...
==> default: Checking if box 'debian/jessie64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 => 8080 (adapter 1)
    default: 3306 => 11306 (adapter 1)
    default: 9000 => 9000 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
GuestAdditions 5.0.0 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Mounting shared folders...
    default: /vagrant => E:/Documents/Aplisys/Projekty/vagrant-webdev
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chown `id -u vagrant`:`id -g vagrant` /vagrant

Stdout from the command:



Stderr from the command:

stdin: is not a tty
chown: changing ownership of ���/vagrant���: Not a directory
````

Virtualbox has strange entry in shared folders settings:
![2015-07-17 16_14_07-oracle vm virtualbox manager](https://cloud.githubusercontent.com/assets/7151151/8749055/18120758-2c9f-11e5-897c-1b6d3d340692.png)

**Comment by sethvargo** [comment] 2015-07-17 19:34
Closing as a duplicate of https://github.com/mitchellh/vagrant/issues/5933 which will be fixed in 1.7.4. Sorry about that!

**Closed by sethvargo** 2015-07-17 19:34 UTC
