### ISSUE TITLE
vagrant up exits with "The file which defines networking interfaces for VMware Fusion could not be found."

### ISSUE THREAD

**Issue by danielmt** [mitchellh/vagrant#8285] opened 2017-02-14 16:43 UTC
### Vagrant version
Vagrant 1.9.1
Plugins:
vagrant-share 1.1.6
vagrant-vmware-fusion 4.0.15

### Host operating system
macOS 10.12.3

### Guest operating system
Ubuntu Linux 16.04 (bento)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
end
```
### Debug output
https://gist.github.com/danielmt/fbe445f523ee4d1a355bb0ac6fcc9384

### Expected behavior
Run the image using VMWare Fusion.

### Actual behavior
Nothing works with VMWare Fusion.
Bringing machine 'default' up with 'vmware_fusion' provider...
The file which defines networking interfaces for VMware Fusion
could not be found. Please verify Fusion is installed properly
and try again. If this problem persists, please contact
support.

### Steps to reproduce
1. Install VMWare 8.5.3
2. Install Vagrant 1.9.1 and vagrant-vmware-fusion
3.vagrant init && vagrant up

This is happening in a recently installed machine, with the first install of both vmware and vagrant.

**Comment by danielmt** [comment] 2017-02-20 18:41
After contacting support and, doing a more thorough investigation, the problem lies in VMWare Fusion on Sierra only.
The VMWare installation should not be done as usual (double clicking the app on the dmg), instead, one should copy the app to Applications folder, and launch from it, only on Sierra.

**Comment by chrisroberts** [comment] 2017-02-28 21:57
Glad you got it sorted out! Closing this up.

**Closed by chrisroberts** 2017-02-28 21:57 UTC
Labels: bug, provider/vmware

**Comment by allaire** [comment] 2017-04-26 13:22
@danielmt Thanks! Did you know the cause?

**Comment by danielmt** [comment] 2017-04-27 16:19
@allaire Nope, only that standard installation of VMWare causes this, probably not installing the necessary drivers (networking, etc). As I stated in my last reply, on Sierra you should copy the VMWare Fusion app to Applications, instead of running from the dmg, and it fixes the issue.

**Comment by AnalogJ** [comment] 2017-04-27 18:28
I just ran into the same issue. Dragging the VMware installer to the Applications folder didn't help though :S

**Comment by danielmt** [comment] 2017-04-27 19:48
@AnalogJ You might have to uninstall it first, deleting the following directories manually:
- /Library/Application Support/VMware
- /Library/Application Support/VMware Fusion
- /Library/Preferences/VMware Fusion
- ~/Library/Application Support/VMware Fusion
- ~/Library/Caches/com.vmware.fusion
- ~/Library/Preferences/VMware Fusion
- ~/Library/Preferences/com.vmware.fusion.LSSharedFileList.plist
- ~/Library/Preferences/com.vmware.fusion.LSSharedFileList.plist.lockfile
- ~/Library/Preferences/com.vmware.fusion.plist
- ~/Library/Preferences/com.vmware.fusion.plist.lockfile
- ~/Library/Preferences/com.vmware.fusionDaemon.plist
- ~/Library/Preferences/com.vmware.fusionDaemon.plist.lockfile
- ~/Library/Preferences/com.vmware.fusionStartMenu.plist
- ~/Library/Preferences/com.vmware.fusionStartMenu.plist.lockfile

**Comment by AnalogJ** [comment] 2017-04-28 23:43
Yeah, I did that, doesn't help. I used https://gist.github.com/pwnsdx/8bf29a7e87a78addc3a3db5f08c197f8/7003e161c6eaa89d3ac0df9bc42212341c9676e8 to cleanup VMWare completely

I found that when installing `VMware-Fusion-8.5.6-5234762.dmg` I didn't have this issue, but then I ran into https://github.com/mitchellh/vagrant/issues/6775 which is blocking me completely right now

**Comment by jerm** [comment] 2017-11-16 05:18
I'm still having this issue on 8.5.{6,7,8}, on Sierra and high sierra.  I've done the above cleanup. I've upgraded vagrant to 2.0.1, but also had the problem on 1.9.something... recently.

Was there ever a resolution to this?

**Comment by sobrinho** [comment] 2017-12-12 23:39
Just closing and opening VMWare after installing solved the issue for me.

Right after you install it, it opens the VMWare.

Close (kill) and open again, it will fix.

**Comment by yangmillstheory** [comment] 2017-12-14 05:07
I'm running Vagrant 1.9.7 and macOS 10.12.6. The fix works for me. Without it a bunch of networking-related config files are missing in `/Library/Preferences/VMware Fusion`.

**Comment by shanemcd** [comment] 2018-01-31 01:37
I resolved this issue by running:

```
$ sudo /Applications/VMware\ Fusion.app/Contents/Library/vmnet-cli --configure
```

**Comment by legal90** [comment] 2018-02-18 08:59
Hi all,
I've run into the same issue with VMware Fusion 10 on macOS 10.13.3 Hight Sierra.
That command provided the following output:

```
$ sudo /Applications/VMware\ Fusion.app/Contents/Library/vmnet-cli --configure
Password:
Configuring Bridged network vmnet0
Configuring hostonly network vmnet1, probing for unused subnet ...
Configuring NAT network vmnet8, probing for unused subnet ...
Failed to create DHCP configuration file for network vmnet1
Failed to create DHCP configuration file for network vmnet8
Failed to configure default network settings
Stopped all configured services on all networks
```
Actually, network preferences were not actually created:
```
$ ls -la /Library/Preferences/VMware\ Fusion/
total 16
drwxr-xr-x   5 root  wheel   160 Feb 18 09:45 .
drwxr-xr-x  81 root  wheel  2592 Feb 18 09:41 ..
-r--r--r--   1 root  wheel    31 Feb 18 09:42 lastLocationUsed
-rw-r--r--   1 root  wheel   689 Feb 18 09:41 license-fusion-100-e4-201704
drwxr-xr-x@ 10 root  wheel   320 Feb 18 09:42 thnuclnt
```
Re-installing doesn't solve that.

## Solution
_Note: Verified on macOS 10.13 Hight Sierra only_
Root issue: https://kb.vmware.com/s/article/2151770

Go to `System Preferences -> Security & Privacy -> General`.
In the bottom of windows you will see the message _"System software from vendor "VMware, Inc." was blocked from loading."_ 
Just click _"Allow"_ next to it and the issue is solved. System reboot is not required.

**Comment by akliegman** [comment] 2018-02-20 21:40
This solution worked for me! @legal90 . Thank you so much!

**Comment by thiagoalves** [comment] 2018-10-20 13:39
@legal90 's solution is the killer. I just had to reinstall VMWare Fusion to make it work. Thanks
