### ISSUE TITLE
Undefined method 'create' for VMware Fusion 6

### ISSUE THREAD

**Issue by ajlanghorn** [mitchellh/vagrant#5556] opened 2015-04-03 18:41 UTC
Recently, I installed VMware Fusion 6 (because I had a licence for it, and I don't have for 7 -- yet!). Vagrant has previously been working absolutely fine with VirtualBox. When bring up a Vagrant box with `vagrant up`, I get the following:

```
$ vup
/Users/ajlanghorn/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.5/lib/vagrant-vmware-fusion/provider.rb:44:in `machine_id_changed': undefined method `create' for HashiCorp::VagrantVMwarefusion::Driver:Module (NoMethodError)
	from /Users/ajlanghorn/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.5/lib/vagrant-vmware-fusion/provider.rb:27:in `initialize'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:127:in `new'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:127:in `initialize'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/vagrantfile.rb:75:in `new'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/vagrantfile.rb:75:in `machine'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:537:in `machine'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:168:in `block in with_target_vms'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:192:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:192:in `block in with_target_vms'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:174:in `each'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:174:in `with_target_vms'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/up/command.rb:67:in `block in execute'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:268:in `block (2 levels) in batch'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:266:in `tap'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:266:in `block in batch'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:265:in `synchronize'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:265:in `batch'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/up/command.rb:58:in `execute'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:42:in `execute'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:292:in `cli'
	from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.6.5/bin/vagrant:174:in `<main>'
```

Any clues?

**Comment by ajlanghorn** [comment] 2015-04-03 19:06
Thanks for appropriately tagging, @sethvargo!

**Comment by phinze** [comment] 2015-04-03 20:03
Hi @ajlanghorn, sorry for the trouble!

Do you think you could provide a `Vagrantfile` that generates the issue for you. That way I can try to get a reproduction case together.

**Comment by ajlanghorn** [comment] 2015-04-03 21:51
@phinze Sure - it was the basic Vagrantfile generated using vagrant init
ubuntu1404 which uses this box:
https://github.com/kraksoft/vagrant-box-ubuntu/releases/download/14.04/ubuntu-14.04-amd64.box

Let me know if you prefer the actual Vagrantfile as a Gist.

On Friday, 3 April 2015, Paul Hinze <notifications@github.com> wrote:

> Hi @ajlanghorn <https://github.com/ajlanghorn>, sorry for the trouble!
>
> Do you think you could provide a Vagrantfile that generates the issue for
> you. That way I can try to get a reproduction case together.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellh/vagrant/issues/5556#issuecomment-89407331>.
>


--

**Comment by phinze** [comment] 2015-04-03 21:58
Works for me - I'll let you know what I find from trying it out over here. :+1:

**Comment by ajlanghorn** [comment] 2015-04-03 22:16
Great; thanks. Let me know if you want me to test anything out for you,
@phinze :)

On Friday, 3 April 2015, Paul Hinze <notifications@github.com> wrote:

> Works for me - I'll let you know what I find from trying it out over here. [image:
> :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellh/vagrant/issues/5556#issuecomment-89432543>.
>


--

**Comment by ajlanghorn** [comment] 2015-04-05 20:13
I uninstalled Fusion and Vagrant and re-installed them at their latest versions (6.0.5 and 1.7.5 respectively), and after a minor bit of futzing, this appears to now be resolved. I'm not sure why it occurred in the first place!

**Comment by phinze** [comment] 2015-04-07 22:29
Weird! Well I guess I'm going to go ahead and close this for now. If it crops up as an issue for anybody else I'll try and take another dive. :+1: 

Glad to hear it's all sorted for you though. Feel free to reach out if you run into any other issues.

**Closed by phinze** 2015-04-07 22:29 UTC
Labels: bug, provider/vmware
