### ISSUE TITLE
'vagrant destroy -f' fails when Docker containers share a common image built from Dockerfile.

### ISSUE THREAD

**Issue by nrvale0** [mitchellh/vagrant#8563] opened 2017-05-05 16:11 UTC
### Vagrant version

```pre
$ vagrant --version
Vagrant 1.9.4
```
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### Host operating system

```pre
$ facter | grep lsb
lsbdistcodename => TwentyFive
lsbdistdescription => Fedora release 25 (Twenty Five)
lsbdistid => Fedora
lsbdistrelease => 25
lsbmajdistrelease => 25
lsbrelease => :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
os => {"name"=>"Fedora", "family"=>"RedHat", "release"=>{"major"=>"25", "full"=>"25"}, "lsb"=>{"distcodename"=>"TwentyFive", "distid"=>"Fedora", "distdescription"=>"Fedora release 25 (Twenty Five)", "release"=>":core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch", "distrelease"=>"25", "majdistrelease"=>"25"}}
$ uname -a 
Linux atacama 4.10.13-200.fc25.x86_64 #1 SMP Thu Apr 27 20:39:25 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

### Guest operating system
Various Docker containers. I am using the Vagrant Docker provider with Docker version:

```pre
$ docker --version
Docker version 17.04.0-ce, build 4845c56
```

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|

  config.vm.provider "docker"

  nodes = [
    'consul0',
    'vault0',
    'nomad-server0',
    'nomad-client0',
    'nomad-client1',
    'nomad-client2'
  ]

  nodes.each do |node|
    
    config.vm.define "#{node}" do |n|
      n.vm.hostname = "#{node}"
      n.vm.provider "docker" do |d|
        d.name = "#{node}"
        d.remains_running = true

        # Use the official Docker images for Consul and Vault and
        # build a custom image for Nomad because an official image
        # does not exist.
        case
        when "#{node}".include?("consul")
          d.image = "consul"
        when "#{node}".include?("vault")
          d.image = "vault"
        else
          d.build_dir = "."
        end
      end
    end
    
  end
end
```

### Debug output

https://gist.github.com/nrvale0/fde1e0f6ad1ff03e65dbf82fb778cb96

### Expected behavior
'vagrant destroy -f' results in kill of all containers and rmi of all container images built from bundled Dockerfile.

### Actual behavior
Destroy operation fails because multiple containers share an image and Docker will not rmi a container image if a container exists which is using the image.

### Steps to reproduce
1. Copy the Vagrantfile somewhere convenient.
1. (vagrant up && vagrant destroy -f) > /tmp/log 2>&1

### References
None of which I am aware.

**Comment by chrisroberts** [comment] 2017-05-16 02:32
Duplicate of #7245

**Closed by chrisroberts** 2017-05-16 02:32 UTC
Labels: duplicate, enhancement, provider/docker
