### ISSUE TITLE
vagrant up --provider=hyperv not working

### ISSUE THREAD

**Issue by 0re1** [mitchellh/vagrant#7521] opened 2016-06-26 16:27 UTC
Vagrant is not running properly in the latest Windows insider preview (build 14366) build on hyper-v. powershell version 5.1.14366. I would also appreciate any temporary workaround as VirtualBox is working neither in Windows insider preview properly (network adapters). Thanks a lot for your help!
### Vagrant version

Vagrant 1.8.4
### Host operating system

Windows 10 Insider Preview build 14366
### Guest operating system

Ubuntu 14.04
### Vagrantfile - I know it should be config.vm.box = "johnpbloch/homestead" but it doesn't matter

``` ruby
Vagrant.configure("2") do |config|
  config.vm.box = "johnpbloch/laravel"  
end
```
### Debug output

https://gist.github.com/0re1/24bb7a001d6cd2807b4138068c4f05ea
and also stacktrace from within the loop here:
https://gist.github.com/0re1/80367bcce86fa996fccee9d65865662f
### Expected behavior

The powershell subprocess should stop.
### Actual behavior

The process is trapped in an infinite loop
### Steps to reproduce  I know the box name is "johnpbloch/homestead" but it doesn't matter - as above
1. run `vagrant init johnpbloch/laravel`
2. run `vagrant up --provider=hyperv --debug`
### References

Haven't found any

**Comment by sethvargo** [comment] 2016-06-26 18:42
Hi @0re1 

Thank you for opening an issue. This seems to be an issue in the `vagrant-hostupdater` plugin; that's where the infinite loop is occurring from the stack trace. Can you please uninstall all plugins and see if the issue reproduces?

**Comment by 0re1** [comment] 2016-06-26 19:44
I haven't installed any plugin AFAIK. I have installed clean Vagrant several times today. After running command `vagrant plugin uninstall vagrant-hostupdater` I got
`The plugin 'vagrant-hostupdater' is not installed. Please install it first.`
So I think it isn't this issue...

**Comment by 0re1** [comment] 2016-06-26 19:54
Hi @sethvargo,

Thanks for your reply. I have uninstalled both `vagrant-hostsupdater` and `vagrant-triggers` plugin but nothing helped. `vagrant-share` cannot be uninstalled as it is system plugin. The issue persists. The symptoms are identical...

**Comment by sethvargo** [comment] 2016-06-26 19:56
Hi @0re1 

Can you please run [Vagrant in debug mode](https://www.vagrantup.com/docs/other/debugging.html) and gist the new output with those plugins removed?

**Comment by 0re1** [comment] 2016-06-26 20:02
https://gist.github.com/0re1/3898216f9aa6cabaa5173d87aa92641e

**Comment by 0re1** [comment] 2016-06-26 20:05
Also I waited over a minute if it somehow times out or something but it didn't.

**Comment by 0re1** [comment] 2016-06-26 20:15
I have just found out there is a nice diff feature for gisting so there it is. Note that I have installed Vbox so there are some extra lines... I could uninstall vbox + vagrant and get a new debug if needed.
https://gist.github.com/0re1/24bb7a001d6cd2807b4138068c4f05ea/revisions

**Comment by sethvargo** [comment] 2016-06-27 14:34
Hi @0re1 

It does not look like you're getting an infinite loop anymore from that debug output. Does the process just hang after that line?

**Comment by 0re1** [comment] 2016-06-27 17:19
Hi @sethvargo 

Yes, it hangs. I have also modified the subprocess.rb file (added @logger.debug("*")) to see if the subprocess while loop was left or not and it wasn't - stars were being printed on and on (not part of the original debug log). Also in process explorer I have two ruby interpreter processes one utilizing whole CPU core and one utilizing 0. But I couldn't bare it and today I installed clean Windows 10 - no insider stuff. Hopefully it will work after I install all things later today...

**Comment by chrisroberts** [comment] 2016-12-08 23:04
@0re1 Is this behavior still being seen in the latest release of Vagrant?

**Comment by 0re1** [comment] 2016-12-09 10:06
I don't know I would have to install Windows 10 Insider Preview - I have installed normal Windows 10 Pro (as mentioned in previous post) and Vagrant was running there OK (there were problems with shared folders (Samba) and network setting but I believe it was some bug in Hyper-V (Hyper-V Manager and Virtual Switch Manager) - I am now back to using VirtualBox...)

**Comment by chrisroberts** [comment] 2017-03-02 00:54
I'm going to close this up then. Please open a new issue if you experience the problem again. Thanks!

**Closed by chrisroberts** 2017-03-02 00:54 UTC
Labels: bug, host/windows, waiting-reply
