### ISSUE TITLE
Grouping multiple machines into a single target

### ISSUE THREAD

**Issue by jgrowl** [mitchellh/vagrant#5819] opened 2015-06-10 21:58 UTC
Is there currently a way to group multiple machines into a single target?

For example, I have a server that is actually comprised of 4 different logical parts. When I want to restart the server, I would ideally like to do something like:

```
vagrant reload server
```

Instead of:

```
vagrant reload server-part1 server-part2 server-part3 server-part4
```

It gets tedious having to specify every part for halt, destroy, up, etc.

If there isn't currently a way, is there any interest in a pull request for such a feature?

**Comment by edmorley** [comment] 2015-06-11 10:55
As a workaround for now, you could use the regex support:
`vagrant up /server-part[1-4]/`
`vagrant up /server-*/`
etc

**Comment by jgrowl** [comment] 2015-06-11 22:56
@edmorley Thanks, I hadn't seen that. My individual parts actually aren't named like that, it was just an example. I suppose I could add a common prefix like that.

**Comment by edmorley** [comment] 2015-06-11 23:01
If you want to catch all of the machines just use `/*/` - though perhaps we need an `all` option too?

**Comment by sethvargo** [comment] 2015-06-15 19:56
Hello there - this is a duplicate of https://github.com/mitchellh/vagrant/issues/5596. Let's track that issue please. Thanks! :smile:

**Closed by sethvargo** 2015-06-15 19:56 UTC
