### ISSUE TITLE
Incorrect error message "was not found configurated for this Vagrant environment"

### ISSUE THREAD

**Issue by 0xABAB** [mitchellh/vagrant#7044] opened 2016-02-17 09:25 UTC
```
The machine with the name 'foo-dev' was not found configured for this Vagrant environment.
```

yet

'foo-dev' is not anywhere to be found recursively (`grep -R foo-dev "$(dirname Vagrantfile)"` returns no results).

So, I would like to know how Vagrant comes up with the string `foo-dev`. Preferably you should also track user input, such that you can answer such queries in the error messages.

**Comment by sethvargo** [comment] 2016-02-17 16:15
Hi @0xABAB 

Thank you for opening an issue. Could you please share your complete Vagrantfile as well as the output of the command in [debug mode](https://www.vagrantup.com/docs/other/debugging.html)?

**Comment by 0xABAB** [comment] 2016-02-17 21:26
I already removed all related files and started over. This is something which is quite common unfortunately with multi-machine Vagrant development (and it's also terribly slow, because there is no parallel deployment + parallel provisioning)(and in the case of Ansible there is no task level parallelism either). 

I did find the issue, which was that foo-dev was a file in the .vagrant directory. So, apparently, whatever consistency model you have, is wrong. In short, the way to fix this is before outputting that error, first checking whether they user actually requested that to be done (i.e. whether it is in the Vagrantfile). 

foo-dev was a symbol, which *was* at some point in the Vagrantfile. I am certain that it wasn't there when I reported this issue. There is also no need to debug this problem with that Vagrantfile. What needs to be done is that you show via a proof the absence of this particular issue. Once you fail, you will have found the bug. 

You can also choose to not fix this bug and then perhaps someone will just get sick of these billion error messages in Vagrant and build something new, which doesn't have architectural flaws (lack of parallelism comes to mind).  

P.S. I only use Ansible; I do *not* endorse it. I think Ansible is a tool envisioned by small minded people.

**Comment by mfowlewebs** [comment] 2016-02-24 16:24
This got posted to our local tech slack for the lulz, as an example of terrible people behaving terribly. The whole thing is demeaning demanding and insulting, and it finishes with a final spit in the face of other people. Nice job dude, you've been printed out and hung on a wall, as a reminder to not be a shitty to other people.

**Comment by sethvargo** [comment] 2016-02-24 18:32
Hi all,

I am going to close this issue because there is no clear way to reproduce this issue. If someone is able to reproduce this issue, please supply a Vagrantfile and the steps issues to produce this error using our new issues template (which will automatically populate when you create an issue). Thanks! :smile:

**Closed by sethvargo** 2016-02-24 18:32 UTC
Labels: waiting-reply
