### ISSUE TITLE
1.9.3 breaks SMB folder mount in some cases

### ISSUE THREAD

**Issue by bbrala** [mitchellh/vagrant#8409] opened 2017-03-24 17:38 UTC
https://github.com/mitchellh/vagrant/commit/9f393fc1e0c1f0ceefb3f94b22f0bcb5b170371e#diff-bf465b6dacb9c082b82335d7df35bce4R18 

Seems there is a typo in this piece of code. Shouldn't it be `guestpath` instead of `guest_path`?

**Comment by Ratman9000** [comment] 2017-03-24 17:58
This is a duplicate of issue #8404

**Closed** 2017-03-24 20:44 UTC
Labels: bug, duplicate, synced-folders/smb
