### ISSUE TITLE
vagrant up fails to connect after replacing insecure key

### ISSUE THREAD

**Issue by ahammond** [mitchellh/vagrant#7694] opened 2016-08-09 00:40 UTC
### Vagrant version
Vagrant 1.8.5

### Host operating system
OS 10.10.5

### Guest operating system
itrushenko/CentOS-6.8

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version '>=1.8.1'
require 'yaml'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$homedir = File.expand_path('~')

# Amount of RAM for VMs. For ELK VMs this amount is doubled
$BASERAM = 512

# VirtualBox Naming prefix
$VBPREFIX = ""

# where Vagrantfile is located
$WORKDIR = $homedir

# These control behavior on the salt master.
# If you want to mount the salt or pillar folders, then make these true.
# Otherwise salt will use gitfs for both salt and pillar folders.
# See the env=my_branch_name option for salt gitfs testing.
# If you do mount either the salt or pillar directories,
# they will shadow the gitfs versions of same.
$mount_salt = false
$mount_pillar = false
$mount_vagrant_data = true
$depot_data = false

$repopath = File.join($homedir, 'srv')
$vagrant_data_path = File.join($WORKDIR, 'vagrant_data')
$servers_file = File.join($WORKDIR, 'Vagrant/servers.yaml')
$salt_minion_file = File.join($WORKDIR, 'Vagrant/salt/minion')
$salt_master_config = File.join($WORKDIR, 'Vagrant/salt/master')
$salt_key_dir = File.join($WORKDIR, 'Vagrant/salt/keys' )
$salt_master_bootstrap_directory = File.join($WORKDIR, 'Vagrant')

$salt_general_prepare = <<SCRIPT
#!/bin/bash
service salt-master stop >/dev/null 2>&1 || true
pip -V 2>/dev/null || {
  which apt-get >/dev/null 2>&1 && {
    apt-get -y install python-dev libssl-dev build-essential libffi-dev ipset
    apt-get -y install python-pip
    pip install --upgrade pip
    # replace deb-pip with pip-pip
    mv /usr/bin/pip{,_os}
    mv /usr/bin/pip2{,_os}
    ln -s /usr/local/bin/pip /usr/bin/
    ln -s /usr/local/bin/pip /usr/bin/pip2
  } || {
    yum -y install epel-release
    yum -y install python-pip python-devel openssl-devel libffi-devel gcc
    pip-python install --upgrade pip 2>/dev/null
  }
}
pip install --upgrade pip
pip install --upgrade ipaddress futures setproctitle timelib ujson inotify
rm -rf /etc/salt/*
rm -rf /var/cache/salt
SCRIPT

$salt_master_bootstrap = <<SCRIPT
#!/bin/bash

#install salt with a bootstrapper
pip install --upgrade GitPython
wget --quiet -O /tmp/bootstrap_salt.sh https://bootstrap.saltstack.com
sh /tmp/bootstrap_salt.sh -X -M && \
rm -f /tmp/bootstrap_salt.sh

service salt-master stop
service salt-minion stop

# cleanup any accidental keys
cd /etc/salt/pki
rm -rf */*

mkdir -p /etc/salt/master.d
cd /etc/salt/master.d
tar xzf /tmp/salt_master_d.tar.gz
cd /
tar xzf /tmp/salt_master_bootstrap.tar.gz
rm /tmp/salt_master_bootstrap.tar.gz
SCRIPT

# This is the place to override defaults, if you need to.
if (File.exists?(File.join($WORKDIR, 'vagrant_config.rb')))
  require File.join($WORKDIR, 'vagrant_config')
end

$salt_path = File.join($repopath, 'salt')
$pillar_path = File.join($repopath, 'pillar')
$salt_master_bootstrap_file = $salt_master_bootstrap_directory + '/salt_master_bootstrap.tar.gz'
$salt_master_d_file = $salt_master_bootstrap_directory + '/salt_master_d.tar.gz'

checkable_files = [
  $salt_master_bootstrap_file, $salt_master_config, $salt_key_dir,
  $salt_master_d_file, $salt_minion_file,
]

checkable_files << $salt_path if $mount_salt
checkable_files << $pillar_path if $mount_pillar
checkable_files << $vagrant_data_path if $mount_vagrant_data

# Sanity checks
checkable_files.each { |test_path| raise 'file does not exist: ' + test_path unless File.exists?(test_path) }

if $mount_salt
  raise 'file does not exist: ' + $salt_path unless File.exists?($salt_path)
end

if $mount_pillar
  raise 'file does not exist: ' + $pillar_path unless File.exists?($pillar_path)
end

servers = YAML.load_file($servers_file)
seed_master = Hash.new()

servers.each do |k, v|
  public_key_file = File.join($salt_key_dir, "#{k}.pub")
  raise 'file does not exist: ' + public_key_file unless File.exists?(public_key_file)
  seed_master[k] = public_key_file
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # To enable yum caching please run vagrant plugin install vagrant-cachier.
  # Configure cached packages to be shared between instances of the same base box.
  # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
  config.cache.scope = :box if Vagrant.has_plugin?('vagrant-cachier')

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  config.ssh.forward_agent = true

  config.vm.synced_folder $vagrant_data_path, '/vagrant_data' if $mount_vagrant_data

  config.vm.define 'salt' do |server|
    server.vm.box = 'bento/ubuntu-16.04'
    server.vm.hostname = 'salt'
    server.vm.network :private_network, ip: '192.168.33.2'
    server.vm.provider :virtualbox do |vb|
      vb.name = $VBPREFIX + "salt"
      vb.cpus = 4
      # until memory issues with ipset module are fixed
      vb.memory = 2048
    end # vb
#     server.vm.provision :shell, inline: 'ip route add 199.255.210.0/24 via 192.168.33.128 dev eth1'
    # mount with stashpull uid & gid
    if $mount_salt
      server.vm.synced_folder File.join($salt_path),
        '/srv/salt', :mount_options => ['uid=1050,gid=1050']
    end
    if $mount_pillar
      server.vm.synced_folder File.join($pillar_path),
        '/srv/pillar', :mount_options => ['uid=1050,gid=1050']
    end
    server.vm.provision :shell, inline: $salt_general_prepare
    server.vm.provision :file, source: $salt_master_d_file,
                               destination: '/tmp/salt_master_d.tar.gz'
    server.vm.provision :file, source: $salt_master_bootstrap_file,
                               destination: '/tmp/salt_master_bootstrap.tar.gz'
    server.vm.provision :shell, inline: $salt_master_bootstrap, keep_color: true
    server.vm.provision :salt do |salt|
      salt.install_master = true
      salt.master_config = $salt_master_config
      salt.master_key = File.join($salt_key_dir, 'master.pem')
      salt.master_pub = File.join($salt_key_dir, 'master.pub')
      salt.seed_master = seed_master
      salt.minion_config = $salt_minion_file
      salt.minion_id = 'salt'
      salt.minion_key = File.join($salt_key_dir, 'salt.pem')
      salt.minion_pub = File.join($salt_key_dir, 'salt.pub')
      salt.colorize = true
      salt.log_level = 'warning'
    end # salt
    server.vm.provision :shell, inline: 'echo salt > /etc/salt/minion_id; service salt-minion restart', keep_color: true
    server.vm.provision :shell, inline: 'salt-call --log-level=warning saltutil.sync_all', keep_color: true
    server.vm.provision :shell, inline: 'salt-call --log-level=warning mine.update', keep_color: true
    server.vm.provision :shell, inline: 'salt-call --log-level=warning --state-out=terse state.sls salt.update_inventory', keep_color: true
    server.vm.provision :shell, inline: 'salt-call --log-level=warning --state-out=terse state.sls salt.update_inventory_tvpn', keep_color: true
    server.vm.provision :shell, inline: 'salt-call --log-level=warning --state-out=terse state.sls salt.update_inventory_testcenter', keep_color: true
    server.vm.provision :shell, inline: 'service salt-master restart', keep_color: true
    # for some reason first call of highstate fails with SaltClientError: Connection to master lost
    server.vm.provision :shell, inline: 'salt-call --log-level=warning --state-out=terse state.highstate || true', keep_color: true
    server.vm.provision :shell, inline: 'salt-call --log-level=warning --state-out=terse state.sls af_infra.iptables', keep_color: true
    server.vm.provision :salt do |salt|
      salt.run_highstate = true
      salt.colorize = true
      salt.log_level = 'warning'
    end # salt
  end # server

  servers.each do |k, v|
    next if ['ppr', 'salt'].include? k
    config.vm.define k do |server|
      server.vm.box = v.fetch('box', 'itrushchenko/CentOS-6.8')
      server.vm.hostname = k
      server.vm.network :private_network, ip: v['ip']
      if v.has_key? 'fr_ip'
        server.vm.network :private_network, virtualbox__intnet: "fr", ip: v['fr_ip']
      end
      server.vm.provider :virtualbox do |vb|
        vb.name = $VBPREFIX + k
        vb.memory = String(v.fetch('memory', $BASERAM))
        vb.cpus = v['cpus'] if v.has_key? 'cpus'
      end #vb
      server.vm.provision :shell, inline: $salt_general_prepare
      server.vm.provision :salt do |salt|
        salt.minion_config = $salt_minion_file
        salt.minion_id = k
        salt.minion_key = File.join($salt_key_dir, "#{k}.pem")
        salt.minion_pub = File.join($salt_key_dir, "#{k}.pub")
        salt.run_highstate = true
        salt.colorize = true
        salt.log_level = 'warning'
      end # salt
    end # server
  end # servers
end # config

# Handle user specific VM. If ./local_vms.rb exists, include it.
# Using a name that conflicts or could conflict with a name in the
# shared Vagrantfile is a bad idea. Initials make a nice prefix
# that is unlikely to conflict in the future.
if (File.exists?('./local_vagrantfile.rb'))
  load './local_vagrantfile.rb'
end # local_vagrantfile
```

### Debug output
https://gist.github.com/ahammond/5b4e8c822b22627786207bbb8194bcbc

### Expected behavior
I should be able to run provisioners and then vagrant ssh.

### Actual behavior
Authentication failure immediately after replacing the insecure key.

### Steps to reproduce
```
ahammond@AF6302›~🕔 ⁑ vagrant up shss98                                                                                                                                                                                     [17:28:19]
Bringing machine 'shss98' up with 'virtualbox' provider...
==> shss98: Importing base box 'itrushchenko/CentOS-6.8'...
==> shss98: Matching MAC address for NAT networking...
==> shss98: Checking if box 'itrushchenko/CentOS-6.8' is up to date...
==> shss98: Setting the name of the VM: shss98
==> shss98: Fixed port collision for 22 => 2222. Now on port 2201.
==> shss98: Clearing any previously set network interfaces...
==> shss98: Preparing network interfaces based on configuration...
    shss98: Adapter 1: nat
    shss98: Adapter 2: hostonly
    shss98: Adapter 3: intnet
==> shss98: Forwarding ports...
    shss98: 22 (guest) => 2201 (host) (adapter 1)
==> shss98: Running 'pre-boot' VM customizations...
==> shss98: Booting VM...
==> shss98: Waiting for machine to boot. This may take a few minutes...
    shss98: SSH address: 127.0.0.1:2201
    shss98: SSH username: vagrant
    shss98: SSH auth method: private key
    shss98:
    shss98: Vagrant insecure key detected. Vagrant will automatically replace
    shss98: this with a newly generated keypair for better security.
    shss98:
    shss98: Inserting generated public key within guest...
    shss98: Removing insecure key from the guest if it's present...
    shss98: Key inserted! Disconnecting and reconnecting using new SSH key...
    shss98: Warning: Authentication failure. Retrying...
^C==> shss98: Waiting for cleanup before exiting...
Vagrant exited after cleanup due to external interrupt.
```

### References
None that I know of.

**Comment by ahammond** [comment] 2016-08-09 00:41
This seems to reproduce no matter which box I try to vagrant up. I don't know what changed that lead to this behavior.

**Comment by mvanbaak** [comment] 2016-08-09 10:39
This is a duplicate of #7610 right ?

**Comment by till** [comment] 2016-08-09 14:11
@mvanbaak yeah, it is. Fix is already in master.

@sethvargo any thoughts on nightly builds, or a bugfix release? ;)

**Comment by till** [comment] 2016-08-09 14:13
Btw, `config.ssh.insert_key = false` temporarily fixes this for me.

**Closed** 2016-08-09 14:36 UTC

**Comment by timmah1991** [comment] 2018-03-09 18:24
I am following [This](https://docs.saltstack.com/en/getstarted/fundamentals/index.html) tutorial and can't seem to 'vagrant ssh master' as the instructions suggest. I believe this has something to do with the lines "Vagrant insecure key detected. Vagrant will automatically replace" that I found in the console after doing 'vagrant up'. Does anyone have any ideas for me to move forward with this?

**Comment by briancain** [comment] 2018-03-12 15:49
I recommend emailing the mailing list, you'll get more help on there. @timmah1991 

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/vagrant-up
