### ISSUE TITLE
Create a 'vagrant shell' command

### ISSUE THREAD

**Issue by nspaeth** [mitchellh/vagrant#4903] opened 2014-12-04 23:07 UTC
It might be useful to have a command 'vagrant exec' to enter docker containers without requiring ssh.

It then would be useful to have a 'vagrant shell' command automatically execute the best method of entering a machine. Ie. automatically chooses 'vagrant ssh' for VirtualBox and 'vagrant exec' for docker.

**Comment by sethvargo** [comment] 2016-05-30 17:47
Hi there,

I am going to close this as a duplicate of #6566. Even though this was first, there's more conversation on the other ticket. Thanks! 😄

**Closed by sethvargo** 2016-05-30 17:47 UTC
Labels: enhancement
