### ISSUE TITLE
NFS stopped working in Debian testing (stretch)

### ISSUE THREAD

**Issue by anlutro** [mitchellh/vagrant#6532] opened 2015-11-18 11:59 UTC
```
$ vagrant up dev
Bringing machine 'dev' up with 'virtualbox' provider...
==> dev: Checking if box 'box-cutter/debian79' is up to date...
It appears your machine doesn't support NFS, or there is not an
adapter to enable NFS on this machine for Vagrant. Please verify
that `nfsd` is installed on your machine, and try again. If you're
on Windows, NFS isn't supported. If the problem persists, please
contact Vagrant support.
```

Package upgrades in my apt log that might have caused this:
- upgrading virtualbox from 5.0.8 to 5.0.10
- installing linux kenrel from 4.2.5 to 4.2.6 (tried switching to kernel 4.1, problem persists)
- some ruby packages?

I'll try to manually downgrade some packages and see if I can pinpoint the problem.

Let me know if there's any other information I can give.

**Comment by anlutro** [comment] 2015-11-18 12:23
I had a look in [plugins/synced_folders/nfs/synced_folder.rb](https://github.com/mitchellh/vagrant/blob/master/plugins/synced_folders/nfs/synced_folder.rb) and [plugins/hosts/linux/cap/nfs.rb](https://github.com/mitchellh/vagrant/blob/master/plugins/hosts/linux/cap/nfs.rb) to see how vagrant determines if NFS is installed. My `/proc/filesystems` does not contain anything related to NFS. Maybe this is something that has changed at some point?

**Comment by anlutro** [comment] 2015-11-18 12:36
`sudo modprobe nfs` seems to have put nfs back in `/proc/filesystems`, but vagrant is still insisting that it's not supported.

**Comment by anlutro** [comment] 2015-11-18 12:44
I just noticed that vagrant does `cat /proc/filesystems | grep nfsd > /dev/null 2>&1` - but my `/proc/filesystems` looks like this:

```
nodev	nfs
nodev	nfs4
```

**Comment by anlutro** [comment] 2015-11-18 13:13
I'm stupid - `nfsd` is a separate kernel module from `nfs`. `sudo modprobe nfsd` fixes the problem. Maybe add this as a suggestion to the error message?

**Comment by luatnd** [comment] 2015-11-19 03:18
I met a problem when I run symfony on my Debian vagrant VM.
The /var/www folder (sync by nfs with my OSX host) often automatically disconnect like that:
```
$ ll /var/
ls: cannot access /var/www: Transport endpoint is not connected
total 40
drwxr-xr-x  2 root root  4096 Nov 18 06:25 backups/
drwxr-xr-x  9 root root  4096 Nov 16 07:26 cache/
drwxr-xr-x 36 root root  4096 Nov 18 03:48 lib/
drwxrwsr-x  2 root staff 4096 Dec 24  2014 local/
lrwxrwxrwx  1 root root     9 Jan 30  2015 lock -> /run/lock/
drwxr-xr-x 11 root root  4096 Nov 19 03:01 log/
drwxrwsr-x  2 root mail  4096 Nov 16 07:14 mail/
drwxr-xr-x  4 root root  4096 Nov 16 07:26 nginx/
drwxr-xr-x  2 root root  4096 Jan 30  2015 opt/
lrwxrwxrwx  1 root root     4 Jan 30  2015 run -> /run/
drwxr-xr-x  5 root root  4096 Jan 30  2015 spool/
drwxrwxrwt  2 root root  4096 Jan 30  2015 tmp/
d?????????  ? ?    ?        ?            ? www/
```
Is this a vagrant sync error ?

**Comment by anlutro** [comment] 2015-12-07 08:17
More information. It turns out `nfs-kernel-server` refuses to start if the shared directory is empty, complaining about empty exports.

**Comment by jbzdak** [comment] 2015-12-29 17:23
I had the same problem, it is caused by following circumstances: 

* ``nfs-kernel-server`` service does not start if ``/etc/exports`` do not contain any exports.
* If ``nfs-kernel-server`` is not started ``/etc/filesystems`` does not containg ``nfsd`` which is used by vagrant to detect if nfs kernel server is installed.  In which case vagrant bails out. 

This is a problem only if ``/etc/exports`` is empty, so in practice only if you use vagrant with nfs for first time. When you have any exports everything runs fine. 

A very fast solution would be to link to some documentation in the error message, better solution would be to change method used to check whether nfs is running, and then (maybe?) restart ``nfs-kernel-server`` service.

**Comment by chrisroberts** [comment] 2017-03-01 22:27
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Closed by chrisroberts** 2017-03-01 22:27 UTC
Labels: bug, synced-folders/nfs
