### ISSUE TITLE
Port forwarding issue on OS X

### ISSUE THREAD

**Issue by smebberson** [mitchellh/vagrant#6684] opened 2015-12-18 01:33 UTC
I've come across a port forwarding issue on OS X. Everything seems similar to #5838.

Details of my setup are:

- Vagrant: 1.7.4
- OS X: 10.11.2
- VMWare Fusion: Version 8.1.0 (3272237)

Some slight differences are:

- with the VM halted, I'll go into VMWare Fusion and remove the Network adapters
- I'll restart the VM
- I'll bring up a website inside the VM listening on the correct port
- I'll hit up the VM from my host - It will work
- Two or three requests later, the port forwarding seems to flake out and then dies

This is the attempts to connect to the VM from my host:

```
$ curl 'https://localhost:4000' -v
* Rebuilt URL to: https://localhost:4000/
*   Trying ::1...
* connect to ::1 port 4000 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4000 (#0)
* SSL certificate problem: Invalid certificate chain
* Closing connection 0
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
$ curl 'https://localhost:4000' -v
* Rebuilt URL to: https://localhost:4000/
*   Trying ::1...
* connect to ::1 port 4000 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4000 (#0)
* SSL certificate problem: Invalid certificate chain
* Closing connection 0
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
$ curl 'https://localhost:4000' -v
* Rebuilt URL to: https://localhost:4000/
*   Trying ::1...
* connect to ::1 port 4000 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4000 (#0)
* SSL certificate problem: Invalid certificate chain
* Closing connection 0
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
$ curl 'https://localhost:4000' -v
* Rebuilt URL to: https://localhost:4000/
*   Trying ::1...
* connect to ::1 port 4000 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4000 (#0)
* Server aborted the SSL handshake
* Closing connection 0
curl: (35) Server aborted the SSL handshake
$ curl 'https://localhost:4000' -v
* Rebuilt URL to: https://localhost:4000/
*   Trying ::1...
* connect to ::1 port 4000 failed: Connection refused
*   Trying 127.0.0.1...
* connect to 127.0.0.1 port 4000 failed: Connection refused
* Failed to connect to localhost port 4000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 4000: Connection refused
$ curl 'https://localhost:4000' -v
* Rebuilt URL to: https://localhost:4000/
*   Trying ::1...
* connect to ::1 port 4000 failed: Connection refused
*   Trying 127.0.0.1...
* connect to 127.0.0.1 port 4000 failed: Connection refused
* Failed to connect to localhost port 4000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 4000: Connection refused
$ curl 'https://localhost:4000' -v
* Rebuilt URL to: https://localhost:4000/
*   Trying ::1...
* connect to ::1 port 4000 failed: Connection refused
*   Trying 127.0.0.1...
* connect to 127.0.0.1 port 4000 failed: Connection refused
* Failed to connect to localhost port 4000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 4000: Connection refused
```

Notice that after a few attempts the connection just stops working (the SSL certificate issue is expected).

I'm pretty sure this was all fine before I installed v8 of VMWare Fusion.

**Comment by sethvargo** [comment] 2015-12-18 01:35
Duplicate of https://github.com/mitchellh/vagrant/issues/6678. Please downgrade until VMware can fix the issue. Thanks! :smile:

**Closed by sethvargo** 2015-12-18 01:35 UTC
