### ISSUE TITLE
When repackaging a box multiple times, old-but-generated keys fail to get packaged.

### ISSUE THREAD

**Issue by eldondevcg** [mitchellh/vagrant#5780] opened 2015-06-02 18:41 UTC
I think this is what is happening, not sure.
Steps to reproduce:
* Download a box (in my case, precise64) from hashicorp.
  * The insecure key will be replaced with a newly generated key
* Package the box(box-a).
  * The newly generated key is packaged with the box.
* Start a new box from the package (box-b).
  * Vagrant will detect that the insecure key is not in use, and use the key packaged by box a to log into box b
* Package box b
  * Packaging fails to find the newly generated key, since it is inside the base box from the package of box a.
* Boxes installed from the package of box b can't login via the ssh key generated when box a was brought up.

I have temporarily worked around this by configuring ssh password auth just about everywhere.

**Comment by sethvargo** [comment] 2015-06-02 21:49
Hi @eldondevcg 

This looks like a duplicate of https://github.com/mitchellh/vagrant/issues/5186. Can you please confirm? Thanks! :smile:

**Comment by eldondevcg** [comment] 2015-06-03 19:24
@sethvargo #5186 seems to be about packaging base boxes (which I believe means boxes controlled by Virtualbox but not by vagrant). That isn't a part of this workflow, these boxes initially started with hashicorp's precise64). I used the word "base" generally initially, but have removed it since this has nothing to do with `vagrant package`'s `--base` flag. Have you tried and encountered success or failure with the steps to repro, or is there more information I need to provide? Thanks for looking. :100:

**Comment by eldondevcg** [comment] 2015-06-03 19:35
In looking at the code, I think the logic [here](../blob//518426/lib/vagrant/action/general/package.rb#L115) is naive, and needs to be more like the logic [here](../blob/d28740/lib/vagrant/machine.rb#L438)

**Comment by eldondevcg** [comment] 2015-06-22 19:37
@sethvargo I don't think I have permission to remove the "waiting-reply" label, but I have clearly replied.

**Comment by mitchellh** [comment] 2015-11-20 02:18
Test here: https://github.com/mitchellh/vagrant-spec/commit/6ad6bd51f3b8d09e0adc3f361425fee0a0ea43b8

To verify incoming fix.

**Comment by mitchellh** [comment] 2015-11-20 02:19
Fixed!

**Closed by mitchellh** 2015-11-20 02:19 UTC
Labels: bug, core
