### ISSUE TITLE
Duplicated static ip in private network on multi machine setup

### ISSUE THREAD

**Issue by asm0dey** [mitchellh/vagrant#5293] opened 2015-02-05 09:53 UTC
```
$ vagrant -v
Vagrant 1.7.2
```

Vagrantfile:
```ruby
Vagrant.configure(2) do |config|

  config.vm.define "master" do |master|
    master.vm.hostname = "wf-master"
    master.vm.network "private_network", ip: "192.168.12.13"
  end

  config.vm.define "slave" do |slave|
    slave.vm.hostname = "wf-slave"
    slave.vm.network "private_network", ip: "192.168.12.14"
  end

end
```

ifconfig on master:
```
[vagrant@wf-master ~]$ ifconfig
eth0      Link encap:Ethernet  HWaddr 08:00:27:4F:B8:06  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe4f:b806/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:389 errors:0 dropped:0 overruns:0 frame:0
          TX packets:253 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:43010 (42.0 KiB)  TX bytes:35674 (34.8 KiB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:FC:A3:E9  
          inet addr:192.168.12.13  Bcast:192.168.12.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fefc:a3e9/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:13 errors:0 dropped:0 overruns:0 frame:0
          TX packets:12 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:878 (878.0 b)  TX bytes:932 (932.0 b)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:9 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:508 (508.0 b)  TX bytes:508 (508.0 b)
```

ifconfig on slave:
```
[vagrant@wf-slave ~]$ ifconfig
eth0      Link encap:Ethernet  HWaddr 08:00:27:4F:B8:06  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe4f:b806/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:506 errors:0 dropped:0 overruns:0 frame:0
          TX packets:326 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:55000 (53.7 KiB)  TX bytes:45499 (44.4 KiB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:6E:FE:99  
          inet addr:192.168.12.13  Bcast:192.168.12.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe6e:fe99/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:9 errors:0 dropped:0 overruns:0 frame:0
          TX packets:11 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:710 (710.0 b)  TX bytes:890 (890.0 b)

eth2      Link encap:Ethernet  HWaddr 08:00:27:E0:67:5A  
          inet addr:192.168.12.14  Bcast:192.168.12.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fee0:675a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:14 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:632 (632.0 b)  TX bytes:948 (948.0 b)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:31 errors:0 dropped:0 overruns:0 frame:0
          TX packets:31 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1608 (1.5 KiB)  TX bytes:1608 (1.5 KiB)
```

VirtualBox version: 4.3.18
Host machine is Ubuntu 14.10

I'm using centos 6.5 box from https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box

Here we can see several troubles:
* Why both boxes have default autoconfigured interface with ip 10.0.2.15?
* Why does slave box have both master and slave ips (192.168.12.13, 192.168.12.14)? (SOLVED)

**Comment by matt-richardson** [comment] 2015-02-05 09:59
I *think* that the issue is you are modifying settings at the global level. Inside the define blocks, you need to use the scoped config (see https://docs.vagrantup.com/v2/multi-machine/index.html). Try:

~~~~
Vagrant.configure(2) do |config|

  config.vm.define "master" do |master|
    master.vm.hostname = "wf-master"
    master.vm.network "private_network", ip: "192.168.12.13"
  end

  config.vm.define "slave" do |slave|
    slave.vm.hostname = "wf-slave"
    slave.vm.network "private_network", ip: "192.168.12.14"
  end

end
~~~~

**Comment by asm0dey** [comment] 2015-02-05 10:05
@matt-richardson It  helped with second question, but not with first one. Any ideas?

**Comment by matt-richardson** [comment] 2015-02-05 10:14
Not sure, to be honest. Out of my depth now ;)

**Comment by asm0dey** [comment] 2015-02-05 10:17
Anyway, thanks a lot :)

**Comment by mitchellh** [comment] 2015-02-24 19:05
eth0 is always a NAT, which is auto-assigned IP via DHCP from VirtualBox. The rest should be fixed thanks to @matt-richardson's comment.

**Closed by mitchellh** 2015-02-24 19:05 UTC

**Comment by asm0dey** [comment] 2015-02-24 19:19
Thank you!
