### ISSUE TITLE
exportfs: duplicated export entries while using NFS as mountpoint for vagrant

### ISSUE THREAD

**Issue by Wingie** [mitchellh/vagrant#6047] opened 2015-07-28 10:53 UTC
```
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
cp: cannot create regular file ‘/etc/exports’: Permission denied
nfsd running
exportfs: duplicated export entries:
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: duplicated export entries:
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: duplicated export entries:
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: duplicated export entries:
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: duplicated export entries:
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: duplicated export entries:
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: duplicated export entries:
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: duplicated export entries:
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: duplicated export entries:
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: duplicated export entries:
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: 	10.1.1.33:/home/wingston/bnc
exportfs: duplicated export entries:
exportfs: 	10.1.1.10:/home/wingston/scrap/wingie.github.com
exportfs: 	10.1.1.10:/home/wingston/scrap/wingie.github.com
exportfs: duplicated export entries:
exportfs: 	10.1.1.10:/home/wingston/scrap/wingie.github.com
exportfs: 	10.1.1.10:/home/wingston/scrap/wingie.github.com
exportfs: duplicated export entries:
exportfs: 	10.1.1.10:/home/wingston/scrap/wingie.github.com
exportfs: 	10.1.1.10:/home/wingston/scrap/wingie.github.com
exportfs: duplicated export entries:
exportfs: 	10.1.1.10:/home/wingston/scrap/wingie.github.com
exportfs: 	10.1.1.10:/home/wingston/scrap/wingie.github.com
exportfs: duplicated export entries:
exportfs: 	10.1.1.10:/home/wingston/scrap/wingie.github.com
exportfs: 	10.1.1.10:/home/wingston/scrap/wingie.github.com
```
this keeps happening - its even giving me the errors of my other vagrant boxes.
i.e. its giving 

in my /etc/exports
```
$ cat /etc/exports                                                                                                          [14:50:31]
# /etc/exports: the access control list for filesystems which may be exported
#		to NFS clients.  See exports(5).
#
# Example for NFSv2 and NFSv3:
# /srv/homes       hostname1(rw,sync,no_subtree_check) hostname2(ro,sync,no_subtree_check)
#
# Example for NFSv4:
# /srv/nfs4        gss/krb5i(rw,sync,fsid=0,crossmnt,no_subtree_check)
# /srv/nfs4/homes  gss/krb5i(rw,sync,no_subtree_check)
#
# VAGRANT-BEGIN: 1000 9bdf3c51-4d3a-4044-b869-aebe4a5d2883
"/home/wingston/bnc" 10.1.1.33(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=969191742)
# VAGRANT-END: 1000 9bdf3c51-4d3a-4044-b869-aebe4a5d2883
# VAGRANT-BEGIN: 1000 9bdf3c51-4d3a-4044-b869-aebe4a5d2883
"/home/wingston/bnc" 10.1.1.33(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=969191742)
# VAGRANT-END: 1000 9bdf3c51-4d3a-4044-b869-aebe4a5d2883
# VAGRANT-BEGIN: 1000 9bdf3c51-4d3a-4044-b869-aebe4a5d2883
"/home/wingston/bnc" 10.1.1.33(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=969191742)
# VAGRANT-END: 1000 9bdf3c51-4d3a-4044-b869-aebe4a5d2883
# VAGRANT-BEGIN: 1000 9bdf3c51-4d3a-4044-b869-aebe4a5d2883
"/home/wingston/bnc" 10.1.1.33(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=969191742)
# VAGRANT-END: 1000 9bdf3c51-4d3a-4044-b869-aebe4a5d2883
# VAGRANT-BEGIN: 1000 9bdf3c51-4d3a-4044-b869-aebe4a5d2883
"/home/wingston/bnc" 10.1.1.33(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=969191742)
# VAGRANT-END: 1000 9bdf3c51-4d3a-4044-b869-aebe4a5d2883
# VAGRANT-BEGIN: 1000 9bdf3c51-4d3a-4044-b869-aebe4a5d2883
"/home/wingston/bnc" 10.1.1.33(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=969191742)
# VAGRANT-END: 1000 9bdf3c51-4d3a-4044-b869-aebe4a5d2883
# VAGRANT-BEGIN: 1000 ec69d951-a4e9-445c-987f-92c6c7916626
"/home/wingston/bnc" 10.1.1.33(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=969191742)
# VAGRANT-END: 1000 ec69d951-a4e9-445c-987f-92c6c7916626
# VAGRANT-BEGIN: 1000 ec69d951-a4e9-445c-987f-92c6c7916626
"/home/wingston/bnc" 10.1.1.33(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=969191742)
# VAGRANT-END: 1000 ec69d951-a4e9-445c-987f-92c6c7916626
# VAGRANT-BEGIN: 1000 ec69d951-a4e9-445c-987f-92c6c7916626
"/home/wingston/bnc" 10.1.1.33(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=969191742)
# VAGRANT-END: 1000 ec69d951-a4e9-445c-987f-92c6c7916626
# VAGRANT-BEGIN: 1000 ec69d951-a4e9-445c-987f-92c6c7916626
"/home/wingston/bnc" 10.1.1.33(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=969191742)
# VAGRANT-END: 1000 ec69d951-a4e9-445c-987f-92c6c7916626
# VAGRANT-BEGIN: 1000 ec69d951-a4e9-445c-987f-92c6c7916626
"/home/wingston/bnc" 10.1.1.33(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=969191742)
# VAGRANT-END: 1000 ec69d951-a4e9-445c-987f-92c6c7916626
# VAGRANT-BEGIN: 1000 0330c0f7-ddc8-4efa-9ffc-48f71b7215e4
"/home/wingston/scrap/wingie.github.com" 10.1.1.33(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=3452626601)
# VAGRANT-END: 1000 0330c0f7-ddc8-4efa-9ffc-48f71b7215e4
# VAGRANT-BEGIN: 1000 66385baa-a6ab-4f42-9b46-2750d9fa91bd
"/home/wingston/scrap/wingie.github.com" 10.1.1.10(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=3452626601)
# VAGRANT-END: 1000 66385baa-a6ab-4f42-9b46-2750d9fa91bd
# VAGRANT-BEGIN: 1000 66385baa-a6ab-4f42-9b46-2750d9fa91bd
"/home/wingston/scrap/wingie.github.com" 10.1.1.10(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=3452626601)
# VAGRANT-END: 1000 66385baa-a6ab-4f42-9b46-2750d9fa91bd
# VAGRANT-BEGIN: 1000 66385baa-a6ab-4f42-9b46-2750d9fa91bd
"/home/wingston/scrap/wingie.github.com" 10.1.1.10(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=3452626601)
# VAGRANT-END: 1000 66385baa-a6ab-4f42-9b46-2750d9fa91bd
# VAGRANT-BEGIN: 1000 66385baa-a6ab-4f42-9b46-2750d9fa91bd
"/home/wingston/scrap/wingie.github.com" 10.1.1.10(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=3452626601)
# VAGRANT-END: 1000 66385baa-a6ab-4f42-9b46-2750d9fa91bd
# VAGRANT-BEGIN: 1000 66385baa-a6ab-4f42-9b46-2750d9fa91bd
"/home/wingston/scrap/wingie.github.com" 10.1.1.10(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=3452626601)
# VAGRANT-END: 1000 66385baa-a6ab-4f42-9b46-2750d9fa91bd
# VAGRANT-BEGIN: 1000 66385baa-a6ab-4f42-9b46-2750d9fa91bd
"/home/wingston/scrap/wingie.github.com" 10.1.1.10(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=3452626601)
# VAGRANT-END: 1000 66385baa-a6ab-4f42-9b46-2750d9fa91bd

```

**Comment by michaelherold** [comment] 2015-08-17 14:42
This is a duplicate of #4666.

**Comment by mitchellh** [comment] 2015-11-20 18:54
Agreed on dup. Thanks @michaelherold

**Closed by mitchellh** 2015-11-20 18:54 UTC
Labels: bug, synced-folders/nfs
