### ISSUE TITLE
Previous Rsync Exclude setting caused duplicate rsync on rsync-auto

### ISSUE THREAD

**Issue by bartclarkson** [mitchellh/vagrant#4567] opened 2014-09-26 14:39 UTC
I had a problem with rsync__exclude producing unexpected results.  I noticed in the console log that my rsync_auto was duplicating a previous setting I'd made in VagrantFile.  I did a vagrant destroy and a vagrant up, and the duplication went away.  The issue looked like the following.

Vagrant 1.6.5
VirtualBox 4.3.16
OSX

```
bart-2:vagrant bart$ vagrant rsync-auto
==> default: Doing an initial rsync...
==> default: Rsyncing folder: /local-path/platform/ => /var/www/platform
==> default:   - Exclude: [".vagrant/", ".git/", "app/cache", "app/log", "vendors", "bin/"]
==> default: Rsyncing folder: /local-path/platform/ => /var/www/platform
==> default:   - Exclude: [".vagrant/", ".git/", "app/bootstrap.php.cache", "app/cache/", "vendor/", "build/", "bin/", "web/bundles/", "web/css/", "web/js/", "web/build.js", "app/logs/", ".idea"]
==> default: Watching: /local-path/platform
==> default: Watching: /local-path/platform
```

**Comment by swvjeff** [comment] 2015-01-08 22:58
I'm having the same problem. Any progress on this bug?

**Comment by thePanz** [comment] 2015-02-10 22:27
I can confirm this issue. The solution I found is the following (edit the paths according your configuration):

 ```bash
vagrant halt
rm .vagrant/machines/default/virtualbox/synched_folders
vagrant up
 ```

**Comment by szoper** [comment] 2015-02-11 16:39
@thePanz :+1:

**Comment by philbirnie** [comment] 2015-02-11 19:30
Thanks @thePanz. That works for me too..

**Comment by trompx** [comment] 2015-03-31 22:24
Thanks I had this problem too. That would be in fact a good thing that the cache be cleared on each vagrant up/reload.

**Comment by bartclarkson** [comment] 2015-04-04 21:32
@thePanz solution is spot on.  It was one of those issues that didn't come up again for me once my rsync exclusions stabilized on the symfony2-flavored project I was doing.  But, yeah, seems like that file should be rebuilt on up or reload.

**Comment by mitchellh** [comment] 2015-07-09 17:22
This can be fixed with a `vagrant reload`. And works on master!

**Closed by mitchellh** 2015-07-09 17:22 UTC
Labels: bug, synced-folders/rsync
