### ISSUE TITLE
ipv4_secondaries issue

### ISSUE THREAD

**Issue by trunkatedpig** [mitchellh/vagrant#7462] opened 2016-06-16 15:40 UTC
When I run Vagrant Up, I expect that the Private Network Static IP Address will be used to assign the IP Address for the eth1 Network Interface (as it does on another system I have tested with), but when I run it on my system, the eth1 interface is assigned an intermediate 192.* address, and the static private IP is assigned as a secondary.

### Vagrant version
`Vagrant 1.8.4`

### Host operating system
`ubuntu 14.04`

### Guest operating system
`coreos-stable 1010.5.0`

### Vagrantfile
```
#-*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure(2) do |vagrant|

  # Provider Setup
    vagrant.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end

  # TuxLab Swarm Controller
    vagrant.vm.define "dswarm" do |dswarm|
      dswarm.vm.box = "coreos-stable"
      dswarm.vm.box_url = "https://storage.googleapis.com/stable.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json"

      # Disable Guest Additions Installing on CoreOS
          dswarm.vm.provider :virtualbox do |v|
            # On VirtualBox, we don't have guest additions or a functional vboxsf
            # in CoreOS, so tell Vagrant that so it can be smarter.
            v.check_guest_additions = false
            v.functional_vboxsf     = false
          end
          if Vagrant.has_plugin?("vagrant-vbguest") then
            dswarm.vbguest.auto_update = false
          end

      # Add to Network
      dswarm.vm.network "private_network", ip: "10.100.1.10"
      #dswarm.vm.network "forwarded_port", guest: 53, host: 53 # Local DNS
      dswarm.vm.network "forwarded_port", guest: 2375, host: 2375 # Docker Swarm
      dswarm.vm.network "forwarded_port", guest: 2379, host: 2379 # ETCD Cluster
    end

    # Configure All Hosts via Ansible
    vagrant.vm.provision :ansible do |ansible|
      ansible.playbook = "./setup.yml"
      ansible.limit = 'all'
      ansible.groups = {
        'tuxlab-swarm-manager' => ["dswarm"],
         }
       ansible.extra_vars = {
         swarm_node_ip: "10.100.1.10",
         etcd_interface: "eth1"
       }
    end

end
```

### Debug output
https://github.com/trunkatedpig/ipv4_secondaries_bug/blob/master/README.md

### Expected behavior
In the `eth1` interface,
`ipv4` should contain address, broadcast, and network addresses in the range `10.100.1.0/255`

### Actual behavior
`ipv4` contains address, broadcast, and network addresses in the range `192.168.56.0/255`, and `ipv4_secondaries` contains a single entry containing the addresses `ipv4` _should_ contain

### Steps to reproduce
1. Clone the repo https://github.com/trunkatedpig/ipv4_secondaries_bug
2. Ensure you have the latest version the of coreOS virtual box (1010.5.0)
3. vagrant up

**Comment by sethvargo** [comment] 2016-06-18 18:23
Hi @trunkatedpig 

Thank you for opening an issue. I did some digging and this is not a bug in Vagrant. Box developers can package their own scripts and Vagrantfiles with boxes. When you run a box, their Vagrantfile is merged with your Vagrantfile. You can see the bundled Vagrantfile in ~/.vagrant.d/boxes/coreos-stable/.../Vagrantfile, and you'll notice they are doing a bunch of stuff to mangle the network interfaces. I would recommend opening an upstream issue. Sorry for the inconvenience! 😦

**Closed by sethvargo** 2016-06-18 18:23 UTC
