### ISSUE TITLE
Vagrant doesn't start. At all.

### ISSUE THREAD

**Issue by rdrpenguin04** [mitchellh/vagrant#8757] opened 2017-07-06 22:13 UTC
### Vagrant version
Latest, just downloaded today.

### Host operating system
Windows XP (inside a VM)

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
N/A

### Expected behavior
At least keep a process open, display different stuff with different parameters

### Actual behavior
Says that it's a 32-bit installation and quits

### Steps to reproduce
1. Run "vagrant up" with above conditions

**Comment by chrisroberts** [comment] 2017-07-06 23:57
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by StudioMaX** [comment] 2017-07-08 15:28
I'm not sure that I have the same issue, but the symptoms are the same.
I've just updated Vagrant 1.9.5 to 1.9.7 on Windows 10 1703 x64 (build 15063).
After upgrading and launching `vagrant.exe` there is no output at all - just an empty console window.
This is not related to any guest OS, because I cannot even list the vagrant commands.
I tried to launch the vagrant in debug mode - no luck.
After this I've removed 1.9.7 and installed 1.9.6 - this version is working successfully.
One more try - upgrade from 1.9.6 to 1.9.7 - and there is the same issue, `vagrant.exe` just doesn't executing at all.

**Comment by rdrpenguin04** [comment] 2017-07-08 17:26
Here are the most detailed steps I can give:
1. Create a VirtualBox VM running WinXP Professional, 32-bit, 1024 MB of RAM.
2. Install WinXP Professional and Guest Additions.
3. Create shared folder.
4. Download Vagrant on host, copy to shared folder, install on guest. There were no errors.
5. Download VBox (latest) on guest and install. There were no errors.
6. Open cmd and run 'vagrant' with no arguments, or with any arguments needed. The result is always the same: a timestamp followed by saying that it detected a 32-bit system.

'--debug' also yields no more output.

**Comment by MartinanderssonDotcom** [comment] 2017-07-08 20:09
Same problem here. I'm not using babun. I do have MinGW installed.

**Comment by rdrpenguin04** [comment] 2017-07-08 20:15
Removed current version, installed 1.9.6. Same symptoms. Trying 1.9.7 again now.

**Comment by rdrpenguin04** [comment] 2017-07-08 21:29
1.9.7 still won't work. Exact message (from a while ago):

> C:\Documents and Settings\Rdrpenguin>vagrant --version
2017/07/08 14:26:43 launcher: detected 32bit Windows installation

**Comment by tehmaspc** [comment] 2017-07-09 20:50
1.9.7 is broken on my mac as well; reverting to 1.9.5. :(

**Comment by syntacticvexation** [comment] 2017-07-10 05:10
I can confirm this also occurs on Win10 with GitBash (MingGW).  Reverting to 1.9.6 fixed the issue.

**Comment by chrisroberts** [comment] 2017-07-17 17:25
Closing this as Windows XP is not considered a supported platform as it is a version of Windows that has reached end of life.

The tty issue for Windows platforms is being tracked here: #8764 

Cheers!

**Closed by chrisroberts** 2017-07-17 17:25 UTC
Labels: host/windows, waiting-reply

**Comment by AndyMF** [comment] 2017-09-24 16:36
Why was this closed Chris?

tehmaspc said "1.9.7 is broken on my **mac** as well",
StudioMaX had the same (or similar) issue "on **Windows 10** 1703 x64 (build 15063)", and
syntacticvexation said "I can confirm this also occurs on **Win10** with **GitBash** (MingGW)."

Also, the download page at Vagrant (https://www.vagrantup.com/downloads.html) makes no mention of system requirements (which versions of Windows are supported), nor could I find such information anywhere in the Vagrant website. (I'm not saying it's not there, but I looked more than once and couldn't find such information.) Instead, there are simply links for 32-bit and 64-bit versions.
