### ISSUE TITLE
Vagrant plugin install fails on Arch Linux

### ISSUE THREAD

**Issue by groovytron** [mitchellh/vagrant#8635] opened 2017-05-31 20:59 UTC
### Vagrant version

```console
$ vagrant -v
Vagrant 1.9.5
```

### Host operating system

```console
$ cat /etc/*-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"

$ uname -r
4.11.3-1-ARCH
```

### Debug output

https://gist.github.com/groovytron/332a88c209f8f8a40c6aa29203bc2b8f

### Expected behavior

Except `vagrant-libvirt` which is known to be problematic on Arch but the other plugins are supposed to be installed without problems.

### Actual behavior

Plugin installation is not possible anymore.

### Steps to reproduce

1. Install vagrant with `pacman -S vagrant` or upgrade it wih `pacman -Syu`.
2. Check it *1.9.5* with `vagrant -v`.
3. Reboot.
4. Try to install a plugin with `vagrant plugin install <plugin-name>`.

*I tried to use `downgrader` to downgrade back to the previous version of the vagrant package but the problem persists and vagrant still can't install plugins anymore.*

### References
It looks like some Windows 10 users cannot install plugins anymore.
- GH-8634

I hope it will help you to fix this bug and thanks for your help.

**Comment by groovytron** [comment] 2017-05-31 21:41
Downgrading the `vagrant-substrate` package from 605.0566498-2 to 599.d7cedfe-2 using `downgrader` fixed the problem for me. The solution was found [here](https://serverfault.com/questions/852501/install-vagrant-plugin-on-archlinux).

**Comment by jsteel44** [comment] 2017-06-04 17:29
Looks like the issue is when building (the vagrant substrate layer) with boost-libs 1.64 (a make dependency from the substrate layer needing puppet). Can you (upstream) test against boost/boost-libs 1.64 and confirm if it works for you?

**Comment by groovytron** [comment] 2017-06-05 14:58
I think can do that but how can I run this test? Can you give me a hint on how to run this test? Thanks.

**Comment by jsteel44** [comment] 2017-06-05 16:06
With a system with boost/boost-libs 1.63 (and facter compiled against that) then compile the vagrant substrate layer and vagrant works fine. Update your system to boost/boost-libs 1.64 (and facter compiled against that) then compile the vagrant substrate layer and "vagrant plugin install *plugin*" dies with either a segfault or ruby error (it seems random). I'm hoping someone can test on a non-Arch system to see if their findings are the same.

**Comment by ddnomad** [comment] 2017-06-05 22:37
I can confirm that I also experience the same issue. 

```
$ uname -r
4.10.13-1-ARCH
```

```
$ cat /etc/*release
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

**Comment by dradetsky** [comment] 2017-06-15 22:55
Strictly speaking, this is an arch packaging issue, which HC has nothing to do with. However, I use arch and assuming you're just looking for _some_ vagrant backend that will work, I know that virtualbox works, although the directions on the wiki are a little convoluted. My setup is described [here](https://github.com/mitchellh/vagrant/issues/8668) (might have to also install `virtualbox` pkg; dunno if the modules package depends on it or not)

**Comment by jsteel44** [comment] 2017-06-16 07:18
@dradetsky what do you think the packaging issue is? That Vagrant doesn't work with boost 1.64? I guess you could argue that's a packaging issue (that this issue should have been noticed and boost held back until fixed) but I say Vagrant needs to be tested with that version and fixed to work with it.

**Comment by tonylambiris** [comment] 2017-06-19 18:42
@jsteel44 I don't know if this is relevant or helpful, but when creating an osquery package for the AUR, CMake was expecting the boost libs to end in `-mt` (to signify multi-threading support), but Arch doesn't suffix them with anything special like that.

**Comment by chrisroberts** [comment] 2017-06-20 00:14
Hi there,

This is a duplicate of mitchellh/vagrant-installers#106 so I'm going to close this up. Feel free to continue any conversations around this issue there. 

Cheers!

**Closed by chrisroberts** 2017-06-20 00:14 UTC
Labels: duplicate, host/arch, third-party
