### ISSUE TITLE
`readpartial` error when doing vagrant up

### ISSUE THREAD

**Issue by GhaziTriki** [mitchellh/vagrant#8545] opened 2017-05-01 13:58 UTC
### Vagrant version
`Vagrant 1.9.4`

### Host operating system
Windows 8.1 x64

### Guest operating system
Ubuntu/Xenial64

### Vagrantfile
```ruby

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "private_network", ip: "192.168.33.22"

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
 	vb.name = "bbb"
	vb.memory = "4096"
	vb.cpus = 1
  end
end

```

### Debug output
https://pastebin.com/4ueUJyHf

### Expected behavior
VM should run without any error.

### Actual behavior
The error displays.

### Steps to reproduce
1. Update files in PR https://github.com/mitchellh/vagrant/issues/8520
2. Run `vagrant up`

**Comment by iguyking** [comment] 2017-05-02 17:03
I've encountered the same thing.  I reverted back to vagrant 1.9.0 and it works as expected.  
My system is Windows 10 x64 Anniversary Update.

**Comment by chrisroberts** [comment] 2017-05-02 20:42
Duplicate of #8520 and fixed via #8526

**Closed by chrisroberts** 2017-05-02 20:42 UTC
Labels: bug, communicator/ssh, duplicate

**Comment by GhaziTriki** [comment] 2017-05-03 09:31
Dowgraded to vagrant 1.9.0

**Comment by iguyking** [comment] 2017-05-03 15:43
Further testing found that 1.9.3 worked also.   I have not had a chance to test 1.9.5 yet, though likely the issue has been solved.
