### ISSUE TITLE
Custom Manifest Settings not working

### ISSUE THREAD

**Issue by AlexanderAllen** [mitchellh/vagrant#2935] opened 2014-02-04 23:56 UTC
According to http://docs.vagrantup.com/v2/provisioning/puppet_apply.html:

> "You can also specify a manifests path that is on the remote machine already, perhaps put in place by a shell provisioner. In this case, Vagrant won't attempt to upload the manifests directory."

I have tried the following in my Vagrantfile:

```ruby
config.vm.provision :puppet do |puppet| 
      puppet.manifests_path = ["vm", "/etc/puppet/manifests"]
      puppet.module_path = ["vm", "/etc/puppet/modules"]
      puppet.manifest_file = ["vm", "default.pp"]
      puppet.options = "--verbose --debug"
end
```

Where `/etc/puppet/manifests` is a valid directory inside the VM (not the packaged box, but the virtual "remote" OS itself), however, Vagrant/puppet do not seem to look in this location. This is what I get instead:

```
alex$ vagrant init vagrant-centos-x64-6.5
alex$ vagrant up --provider vmware_fusion
Bringing machine 'default' up with 'vmware_fusion' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

puppet provisioner:
* The configured module path doesn't exist: /Users/alex/Documents/test4/vm
* The configured module path doesn't exist: /etc/puppet/modules
```

So far the only way I have been able to `vagrant up` my machine is by copying the files into each project, which is not ideal. I do not know if this is my mistake or a bug. In the meantime I will follow the suggestions given on #344.

```
alex$ vagrant -v
Vagrant 1.4.3
```

**Comment by sethvargo** [comment] 2015-05-31 04:18
Closing as a duplicate of 2902. Let's track that one! :smile:

**Closed by sethvargo** 2015-05-31 04:18 UTC
Labels: enhancement, provisioner/puppet
