### ISSUE TITLE
Cygwin rsync path translation fails after upgrade to Vagrant 1.8.1. 

### ISSUE THREAD

**Issue by rct** [mitchellh/vagrant#6989] opened 2016-02-05 20:54 UTC
After upgrading from Vagrant 1.7.4 to 1.8.1, rsync under Cygwin (Cygwin Terminal: bash + MinTTY) fails due to using Windows paths instead of Cygwin paths.  The cygwin environment was being properly detected in 1.7.4

```
==> default: Rsyncing folder: /cygdrive/c/Users/rct/Downloads/cdk/components/rhel/rhel-ose/ => /vagrant
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /cygdrive/c/Users/rct/Downloads/cdk/components/rhel/rhel-ose/
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o ControlMaster=auto -o ControlPath=C:/cygwin/tmp/ssh.954 -o ControlPersist=10m -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'C:/Users/rct/Downloads/cdk/components/rhel/rhel-ose/.vagrant/machines/default/virtualbox/private_key' --exclude .vagrant/ /cygdrive/c/Users/rct/Downloads/cdk/components/rhel/rhel-ose/ vagrant@127.0.0.1:/vagrant
Error: cygwin warning:
  MS-DOS style path detected: C:/Users/rct/Downloads/cdk/components/rhel/rhel-ose/.vagrant/machines/default/virtualbox/private_key
  Preferred POSIX equivalent is: /cygdrive/c/Users/rct/Downloads/cdk/components/rhel/rhel-ose/.vagrant/machines/default/virtualbox/private_key
  CYGWIN environment variable option "nodosfilewarning" turns off this warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
mm_receive_fd: no message header
process_mux_new_session: failed to receive fd 0 from slave
mux_client_request_session: read from master failed: Connection reset by peer
Failed to connect to new control master
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.0]
```

**Comment by sethvargo** [comment] 2016-02-05 20:58
Dupe of https://github.com/mitchellh/vagrant/issues/6702. Let's track that issue please. Thanks! :smile:

**Closed by sethvargo** 2016-02-05 20:58 UTC

**Comment by rct** [comment] 2016-02-05 22:36
Ok, but at first glance that doesn't look like the same bug about not properly detecting the cygwin environment.
