### ISSUE TITLE
1.9.6 Failed to present a shell prompt

### ISSUE THREAD

**Issue by fyi2** [mitchellh/vagrant#8739] opened 2017-06-29 21:42 UTC
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
1.9.6

### Host operating system
Windows 10

### Guest operating system
Ubuntu

### Vagrantfile

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", host_ip: "127.0.0.1", guest: 8080, host: 8080

  config.vm.provision "shell", inline: <<-SHELL
    # Update and upgrade the server packages.
    sudo apt-get update
    sudo apt-get -y upgrade
    # Set Ubuntu Language
    sudo locale-gen en_GB.UTF-8
    # Install Python, SQLite and pip
    sudo apt-get install -y python3-dev sqlite python-pip
    # Upgrade pip to the latest version.
    sudo pip install --upgrade pip
    # Install and configure python virtualenvwrapper.
    sudo pip install virtualenvwrapper
    if ! grep -q VIRTUALENV_ALREADY_ADDED /home/ubuntu/.bashrc; then
        echo "# VIRTUALENV_ALREADY_ADDED" >> /home/ubuntu/.bashrc
        echo "WORKON_HOME=~/.virtualenvs" >> /home/ubuntu/.bashrc
        echo "PROJECT_HOME=/vagrant" >> /home/ubuntu/.bashrc
        echo "source /usr/local/bin/virtualenvwrapper.sh" >> /home/ubuntu/.bashrc
    fi
  SHELL

end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Expected behavior
File should have run and a shell prompt should have appeared in the guest OS

### Actual behavior
No shell prompt

### Steps to reproduce
1. Run Vagrent file on 1.9.6
2. run it on 1.9.5 NO ISSUES
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by mark1282** [comment] 2017-06-30 08:41
I'm having the same issue in Windows 7, with homestead and virtualbox. I updated my osx machine to 1.9.6 also and didn't get the issue.

**Comment by megwill4268** [comment] 2017-06-30 14:21
Same issue on windows 7 with virtual box 5.1.22 with both babun and git bash to ssh.

**Comment by voytass** [comment] 2017-07-01 17:06
Same issue on Windows 7 x64 with VirtualBox 5.1.22. Box ubuntu/xenial64.

**Comment by eruixma** [comment] 2017-07-03 08:12
Same issue on Windows 7 x64 with VirtualBox 5.1.22 and from git bash, Guest operating system is CentOS

**Comment by neeesn** [comment] 2017-07-05 06:48
Same issue on windows 10 x64 with VirtualBox 5.1.22 and from git bash. Vagrant ssh works in windows CMD

**Comment by stemau98** [comment] 2017-07-06 11:47
Same problem with win 10 and Git Bash (Git version 2.23.2)
no shell promt affter `vagrant ssh`

**Comment by dbelanger** [comment] 2017-07-06 19:09
Same problem with Win 10 x64, Virtual Box 5.1.22 and Git Bash (Git version 2.13.0)

**Comment by chrisroberts** [comment] 2017-07-08 00:16
Fixed in latest release

**Closed by chrisroberts** 2017-07-08 00:16 UTC
Labels: host/windows, installer

**Comment by smitelli** [comment] 2017-09-17 04:03
I think I'm seeing this problem, or something with very similar symptoms, again in version 2.0.0. Am I the only one?

**Comment by mark1282** [comment] 2017-11-03 09:49
I have just upgraded to version 2.0.1 and the issue is occurring again.

**Comment by chbach** [comment] 2017-11-03 09:52
Yes, still happens with 2.0.1 on Windows 10 with git bash.

**Comment by javinievas** [comment] 2017-11-03 09:53
Yep. Latest version and same problem.

**Comment by jk3us** [comment] 2017-11-06 19:03
I'm getting this with cygwin and version 2.0.1, too.  Currently working around with: (your command maybe be somewhat different)

    ssh ubuntu@127.0.0.1 -p2222 -i .vagrant/machines/web/virtualbox/private_key -o 'StrictHostKeyChecking no'

Should a new issue be opened about this?

**Comment by briancain** [comment] 2017-11-06 22:39
@jk3us - if you are experiencing this with vagrant 2.0.1, please open a new issue so we can triage it. Thanks!

**Comment by Brocklobsta** [comment] 2017-11-10 22:50
A workaround that works for me is to use winpty in Git Bash (this package is pre-installed). For example instead of calling "vagrant ssh" you can prepend winpty and call "winpty vagrant ssh". To make this seamless you can create an alias where vagrant="winpty vagrant".

**Comment by jk3us** [comment] 2017-11-13 15:42
The solution I found is [here](https://github.com/hashicorp/vagrant/issues/9143#issuecomment-343311263). Basically, set the `VAGRANT_PREFER_SYSTEM_BIN` environment variable to get vagrant to use your normal ssh executable instead of the msys one that it ships with.
