### ISSUE TITLE
runtime: bsdthread_register error with 1.7.4 on OSX 10.10.5

### ISSUE THREAD

**Issue by JamesByers** [mitchellh/vagrant#6293] opened 2015-09-22 00:30 UTC
I downloaded and installed Virtual box 5.0.4 on OSX 10.10.5.   This is the first time I have installed or run vagrant on this Mac.  When I run vagrant in a terminal window I get a fatal error.  For example when I run "vagrant -v" I get this error message back:

```
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x194415)
	/Users/mitchellh/code/3rdparty/go/src/runtime/panic.go:491 +0xad fp=0x7fff5fbffb40 sp=0x7fff5fbffb10
runtime.goenvs()
	/Users/mitchellh/code/3rdparty/go/src/runtime/os_darwin.c:104 +0x70 fp=0x7fff5fbffb58 sp=0x7fff5fbffb40
runtime.schedinit()
	/Users/mitchellh/code/3rdparty/go/src/runtime/proc.c:141 +0x5f fp=0x7fff5fbffb80 sp=0x7fff5fbffb58
runtime.rt0_go(0x7fff5fbffbb8, 0x2, 0x7fff5fbffbb8, 0x0, 0x0, 0x2, 0x7fff5fbffcc0, 0x7fff5fbffcc8, 0x0, 0x7fff5fbffd03, ...)
	/Users/mitchellh/code/3rdparty/go/src/runtime/asm_amd64.s:95 +0x116 fp=0x7fff5fbffb88 sp=0x7fff5fbffb80
```

**Comment by deanchin** [comment] 2015-10-10 12:58
I am also receiving the same error after installing vagrant 1.7.4 on OSX 10.9.5

**Comment by mitchellh** [comment] 2015-11-19 19:25
This should be fixed in the next release, this is a Go issue.

**Closed by mitchellh** 2015-11-19 19:25 UTC
Labels: bug, installer

**Comment by SmilentRhino** [comment] 2015-12-08 02:05
osx10.10.5  and vagrant 1.7.4 here, I encounter the same problem. 
And it's caused by a Trend Micro Data Loss Prevention plugin, after I removed the plugin, my vagrant works well now. So I think this problem might has something to do with anti-virus software, maybe you can take a look at it first. 
Hope it might help.

**Comment by cosmin-marginean** [comment] 2016-01-08 16:22
Hi, I couldn't find version information on this patch. Is it already released?

**Comment by kenorb** [comment] 2016-01-21 14:03
The same here, how do you actually fix it?

> VBox 5.0.14, vagrant 1.8.1

	fatal error: runtime: bsdthread_register error

	runtime stack:
	runtime.throw(0x162640, 0x21)
		/Users/mitchellh/code/3rdparty/go/src/runtime/panic.go:527 +0x90 fp=0x7fff5fbffbb0 sp=0x7fff5fbffb98
	runtime.goenvs()
		/Users/mitchellh/code/3rdparty/go/src/runtime/os1_darwin.go:73 +0x8d fp=0x7fff5fbffbd8 sp=0x7fff5fbffbb0
	runtime.schedinit()
		/Users/mitchellh/code/3rdparty/go/src/runtime/proc1.go:60 +0x83 fp=0x7fff5fbffc20 sp=0x7fff5fbffbd8
	runtime.rt0_go(0x7fff5fbffc58, 0x1, 0x7fff5fbffc58, 0x0, 0x0, 0x1, 0x7fff5fbffd48, 0x0, 0x7fff5fbffd50, 0x7fff5fbffd6c, ...)
		/Users/mitchellh/code/3rdparty/go/src/runtime/asm_amd64.s:109 +0x132 fp=0x7fff5fbffc28 sp=0x7fff5fbffc20
