### ISSUE TITLE
Windows: \\VBOXSVR\v-csn-1 does not get recreated on vagrant up following a vagrant halt

### ISSUE THREAD

**Issue by vinyar** [mitchellh/vagrant#5267] opened 2015-01-30 14:40 UTC
Once Windows box turns off, it has to be destroyed in order for chef-client run to succeed.
What's actually happening is the \\VBOXSVR\v-csn-1 doesn't get recreated, so chef-client fail to find cookbooks. 

This is particularly annoying because like many others I am using box cutter images, which use Evaluation edition of Windows 2k8 which auto-turns off after one hour. 

Note which may help with debugging: 
If provisioner is chef-zero and chef.nodes_path & chef.node_name are defined, the \\VBOXSVR\v-csn-1 folder gets mapped to the value of chef.nodes_path which also causes a failure (or this may be an entirely separate bug).

Guest OS: Windows 2008r2

$ vagrant plugin list
vagrant-berkshelf (4.0.2)
vagrant-omnibus (1.4.1)
vagrant-share (1.1.3, system)

$ vagrant -v
Vagrant 1.7.2

$ chef -v
Chef Development Kit Version: 0.3.6

$ knife -v
Chef: 11.18.0

Vagrant file:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 config.vm.define 'wsus_server' do |config|

    config.berkshelf.enabled = true
    config.berkshelf.berksfile_path = "cookbooks/wsus_wrapper/Berksfile"
    config.vm.box = 'windows2008r2'
    config.vm.communicator = "winrm"

    config.vm.provider :virtualbox do |p|
        p.gui = true
        p.name = "wsus_server"
        p.customize ["modifyvm", :id, "--memory", "1024", "--clipboard", "bidirectional"]#, "--natdnshostresolver1", "on"]
    end

    config.vm.provision :chef_solo do |chef|
      chef.run_list  = ["recipe[wsus_wrapper]"]
    end
  end
```

**Comment by vinyar** [comment] 2015-02-06 14:31
This seems to work fine with Vagrant 1.7.1

**Comment by sethvargo** [comment] 2015-07-10 19:16
Duplicate of https://github.com/mitchellh/vagrant/issues/5199?

**Comment by vinyar** [comment] 2015-07-12 20:53
Appears to be same or very closely related

**Comment by Naveen2015** [comment] 2015-10-27 01:35
I am hitting the same issue with windows 10 host spinning up windows 2012 r2 vm-hyperv

**Comment by mwrock** [comment] 2015-11-13 23:48
Just to add some data here, I was unable to reproduce this bug. I tried on both a VirtualBox 5.0.4 and a Hyper-V host.

Both Environments: 
Windows 10
Vagrant 1.7.4
Guest: Windows 2012 R2 mwrock/Windows2012R2

Vagrantfile:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "mwrock/Windows2012R2"
  config.vm.communicator = "winrm"

  config.vm.provider "hyperv" do |hv|
    hv.ip_address_timeout = 240
  end

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = ['../../dev/cookbooks']
    chef.run_list  = ["recipe[chocolatey::default]"]
  end

end
```

Steps taken:
* manually removed the `depends windows` from the chocolatey `metadata.rb` to avoid messing with the berkshelf plugin
* vagrant up
* Installed Guest Additions (only on the virtualbox environment)
* Installed latest Chef client (12.5.1)
* vagrant reload
* vagrant provision
* manually rebooted box
* vagrant provision

Both provisions succeeded

**Comment by mitchellh** [comment] 2015-11-19 04:29
Agreed with @mwrock, we tried some weeks back and couldn't repro this as well. I'm going to close without a repro case. Thanks!

**Closed by mitchellh** 2015-11-19 04:29 UTC
Labels: bug, windows
