### ISSUE TITLE
Vagrant does not connect to docker container when using ssh passwords

### ISSUE THREAD

**Issue by jonasv** [mitchellh/vagrant#8220] opened 2017-01-20 10:08 UTC
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 1.8.1

### Host operating system
RHEL

### Guest operating system
RHEL

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.hostname = "test-docker-dev"
  config.ssh.username = "root"
  config.ssh.password = "secret"
 # config.hostmanager.enabled = true
 # config.hostmanager.manage_guest = true
#  config.ssh.host = "172.0.0.2"
#  config.ssh.port = "22"
  config.vm.provider :docker do |d|
     d.image = 'test:image'
     d.remains_running = true
     d.has_ssh = true
     d.privileged = true
#     d.volumes = ["/tmp/:/tmp"]
     d.cmd = ["/bootstrap.sh"]
  end
end
```
And this is dockerfile:
FROM base
MAINTAINER test
COPY entrypoint.sh /entrypoint.sh
CMD ["/usr/sbin/sshd", "-D"]
ENTRYPOINT ["/entrypoint.sh"]
EXPOSE 22
COPY bootstrap.sh /bootstrap.sh

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://pastebin.mozilla.org/8966328

### Expected behavior
Vagrant started docker test:image and ran /bootstrap.sh file

### Actual behavior
vagrant up --provider=docker
Bringing machine 'default' up with 'docker' provider...
==> default: Vagrant has noticed that the synced folder definitions have changed.
==> default: With Docker, these synced folder changes won't take effect until you
==> default: destroy the container and recreate it.
==> default: Starting container...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 172.17.0.2:22
    default: SSH username: root
    default: SSH auth method: password
    default: Warning: Connection refused. Retrying...

### Steps to reproduce
Just use vagrant file provided.

### References
None afaik.

**Comment by kikitux** [comment] 2017-01-31 22:35
Hello.

This is not a Vagrant issue, its more a combination of factors on your repo. Happy to assist over the mailing list.

You need to have ssh inside docker working. spin up the container without vagrant and confirm you can ssh.

This is what I did just now.

Dockerfile:
```
FROM ubuntu:16.04
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:screencast' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile
EXPOSE 22

```

build as `docker build -t docker_ssh .`

Then Vagrantfile:
```
Vagrant.configure("2") do |config|
  config.ssh.insert_key = true
  config.vm.hostname = "test-docker-dev"
  config.ssh.username = "root"
  config.ssh.password = "screencast"
  config.vm.provider :docker do |d|
     d.image = 'docker_ssh'
     d.remains_running = true
     d.has_ssh = true
  end
end
```

Note I have insert_key = true since I want to run commands there.

Now up and ssh
```
[root@desktop docker_ssh]# vagrant up
Bringing machine 'default' up with 'docker' provider...
==> default: Creating the container...
    default:   Name: docker_ssh_default_1485902073
    default:  Image: docker_ssh
    default: Volume: /root/docker_ssh:/vagrant
    default:   Port: 127.0.0.1:2222:22
    default:
    default: Container created: c9258aae6475c445
==> default: Starting container...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 172.17.0.2:22
    default: SSH username: root
    default: SSH auth method: password
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
[root@desktop docker_ssh]# vagrant ssh -c 'which apt'
/usr/bin/apt
Connection to 172.17.0.2 closed.
```

my host is rpm based, so no apthere
```
[root@desktop docker_ssh]# which apt
/usr/bin/which: no apt in (/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
[root@desktop docker_ssh]#
```

So closing as not a bug.

**Closed by kikitux** 2017-01-31 22:35 UTC
