### ISSUE TITLE
Ansible dynamic inventory missing the variable 'ansible_user'

### ISSUE THREAD

**Issue by craneworks** [mitchellh/vagrant#6672] opened 2015-12-15 21:08 UTC
The dynamic inventory is missing the variable which user Ansible should use to connect to the VM.
This might break in some conditions the deployment of the VM. ~~For example if Ansible has to reconnect to the box during the run it fails because a reconnect is not possible.~~
Also I think the dynamic inventory was designed to let Ansible work out of the box. So  I would say this is more a bug than a feature request.

Currently:
```
default ansible_ssh_host=127.0.0.1 ansible_ssh_port=2222 ansible_ssh_private_key_file=/Users/craneworks/ansible-role-dev/.vagrant/machines/default/virtualbox/private_key
```

How it should be:
```
default ansible_ssh_host=127.0.0.1 ansible_ssh_port=2222 ansible_ssh_private_key_file=/Users/craneworks/ansible-role-dev/.vagrant/machines/default/virtualbox/private_key ansible_user=vagrant
```

EDIT: Reconnect error I stumble into is caused by Ansible

**Comment by gildegoma** [comment] 2015-12-16 09:35
@craneworks I'm going to close this as duplicate of #6348 and #6210. Vagrant 1.8 will by default add `ansible_ssh_user` parameter to the generated inventory.

For the support of the new _transport layer agnostic_ parameters names (`ansible_host` instead of `ansible_ssh_host`, please refer to #6570 (not planned for 1.8.0 at the moment).

**Closed by gildegoma** 2015-12-16 09:35 UTC
