### ISSUE TITLE
Setting the hostname using Vagrant 1.7.2 boxes

### ISSUE THREAD

**Issue by codeATbusiness** [mitchellh/vagrant#5694] opened 2015-05-08 00:29 UTC
I'm using the multi-machine options from Vagrant but I cannot set the hostname for each machine.

```ruby
    # -*- mode: ruby -*-
    # vi: set ft=ruby :

    VAGRANT_API_VERSION = "2"

    # Boxes Configuration
    Vagrant.configure(VAGRANT_API_VERSION) do |config|
        # WebServer Machine 1
        config.vm.define "web1" do |web|
            web.vm.box = "ubuntu/vivid64"
            web.vm.hostname = "webserver1.dev"
            web.vm.network "private_network", ip: 192.168.50.5
            web.vm.provider "virtualbox" do |v|
                v.name = "WebServer 1"
                v.cpus = 1
                v.memory = 1024
            end
            web.vm.network "forwarded_port", guest: 80, host: 8080
        end
    end
```

This results with the following error:

```
     ==> ansible: Setting hostname...
    The following SSH command responded with a non-zero exit status.
    Vagrant assumes that this means the command failed!

    service hostname start

    Stdout from the command:

    Stderr from the command:

    stdin: is not a tty
    Failed to start hostname.service: Unit hostname.service is masked.
```

**Comment by devjatkin** [comment] 2015-05-13 12:01
IMHO this issue is duplicate of #5673

**Comment by sethvargo** [comment] 2015-05-13 13:57
Closing as a dupe, thanks!

**Closed by sethvargo** 2015-05-13 13:57 UTC
