### ISSUE TITLE
/usr/bin is not writeable on Mac OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by mathie** [mitchellh/vagrant#5816] opened 2015-06-10 09:17 UTC
I wondered why vagrant had disappeared from my path this morning. In the end, I discovered that `/usr/bin` isn't writeable on Mac OS X 10.11 El Capitan -- even by root! I've worked around it by sticking a symlink in `/usr/local/bin/vagrant` pointing to `/opt/vagrant/bin/vagrant`. Perhaps the installer could be tweaked to do this automatically?

**Comment by sethvargo** [comment] 2015-06-10 13:13
Duplicate of https://github.com/mitchellh/vagrant/issues/5807

**Closed by sethvargo** 2015-06-10 13:13 UTC

**Comment by elikem** [comment] 2015-06-19 18:57
@mathie Thanks a lot for your comment. It was most useful :+1:
