### ISSUE TITLE
Interrupting vagrant during operation doesn't trap signal correctly

### ISSUE THREAD

**Issue by madAndroid** [mitchellh/vagrant#6248] opened 2015-09-08 13:40 UTC
Prior to upgrading to `1.7.4`, when I `ctrl-c` to interrupt a vagrant operation, the process would catch the signal correctly, issue a message stating:
```
Waiting for cleanup before exiting...
```
and then allow me to stop the process by hitting `ctrl-c` again, after which the following is shown:
```
Exiting immediately, without cleanup!
```

After upgrading to `1.7.4`, I can no longer do this cleanly - after hitting `ctrl-c`, I get returned to my shell prompt, and the command is sent to the background, and continues to execute, with the output entering the current shell session when it continues. After some time, the expected message of:
```
Vagrant exited after cleanup due to external interrupt.
```
... is shown, and the process list shows that vagrant is no longer running.

I have no idea why this is happening - I've tried without any luck to track it down. It's happening to another colleague as well, I'm just not sure how many other users this is affecting, and whether it's possibly my shell environment that's responsible; when I downgrade to `1.7.2`, the problem goes away.

**Comment by madAndroid** [comment] 2015-09-08 13:42
Environment details:
```
Mac OSX 10.10.5
Shell: zsh 5.1 (x86_64-apple-darwin14.5.0)
```

**Comment by Tyrael** [comment] 2015-09-28 11:53
for the record I experienced similar issues, same Mac OSX version and also using zsh.

**Comment by tuminoid** [comment] 2015-10-20 05:16
Another one here, OSX 10.11 and iTerm2.

**Comment by tuminoid** [comment] 2015-10-20 07:11
Also confirming it on Ubuntu 14.04 with vagrant 1.7.4. Not just a OSX issue. I have also new verified it using `vmware-fusion`, `virtualbox` and `lxc` providers, so it is not provider dependant issue.

1.7.2 is the first downgrade that works, so there is something in 1.7.3 that has changed the functionality.

1.7.3 introduced bundler env jailbreaks, configurable sudo and ssh for machine etc which could do something like this as a side-effect, but I couldn't pinpoint it either.

**Comment by madAndroid** [comment] 2015-10-20 08:27
> 1.7.3 introduced bundler env jailbreaks, configurable sudo and ssh for machine etc which could do something like this as a side-effect, but I couldn't pinpoint it either.

Yep, there were quite a few changes that could have caused this. BTW @tuminoid - are you also using zsh?

I have a feeling it may be down to this commit: https://github.com/mitchellh/vagrant/commit/3b8bc2a433c14a1c8ce159f034a457180683b788 but I've not been able to prove this conclusively

**Comment by tuminoid** [comment] 2015-10-20 08:49
@madAndroid No, I'm using bash 4.x on both machines.

I'm kind of lucky not having to use Virtualbox as a VM backend in most cases (vmware on Mac, lxc on Linux as defaults), since dropping down to 1.7.2 kills Virtualbox 5.0 support.

**Comment by mitchellh** [comment] 2015-11-19 17:27
I believe this is caused by our launcher we introduced in 1.7.4 to lower the Vagrant start times.

I've been able to repro then fix it locally: https://github.com/mitchellh/vagrant-installers/commit/318bf4074e435674966e627dda426ff86f32f717

This will be part of the next Vagrant release. Thanks!

**Closed by mitchellh** 2015-11-19 17:27 UTC
Labels: bug, core

**Comment by madAndroid** [comment] 2015-11-19 17:30
@mitchellh - that's awesome, thanks so much!
