### ISSUE TITLE
GuestAdditions seems to be installed correctly, but not running - VirtualBox Guest Additions (4.3.30), Vagrant (1.7.4), guest CentOS (6.3), host Mac 10.9

### ISSUE THREAD

**Issue by jakirkham** [mitchellh/vagrant#6018] opened 2015-07-21 13:13 UTC
Log here ( https://gist.github.com/jakirkham/df3fb2f99431da0cb211 ). This problem also occurs with Vagrant (1.7.3). When using VirtualBox Guest Additions (4.3.12), Vagrant (1.7.3), and everything else the same, this problem does not surface. The image is built with packer. Details for how the machine is built can be found here ( http://github.com/jakirkham/ilastik-centos_6_3-test-vm ).

**Comment by jakirkham** [comment] 2015-08-12 06:42
Potentially related to this issue ( https://github.com/mitchellh/vagrant/issues/5503 ). However, the stackoverflow solution also does not work for me.

**Comment by jakirkham** [comment] 2015-09-04 00:21
This problem persists when switching to VirtualBox 5.0.0 and using a matching version of Guest Additions.

**Comment by tompscanlan** [comment] 2015-09-17 13:16
From the log, it looks like your sudo doesn't support the '-E' argument.  Look at setting  `config.ssh.sudo_command = sudo -H %c`

**Comment by jakirkham** [comment] 2015-09-21 11:25
Thanks for the advice @tompscanlan.

I tried setting `sudo_command` based on your advice. However, it appears that I get basically the same error message except regarding `-H`. So, I tried dropping the option altogether making the command `config.ssh.sudo_command = sudo %c`. That actually appears to work.

Is there some reason these options are required? Are them some environment variables that are needed within the `sudo` session like `$HOME`? If so, why is this?

**Comment by tompscanlan** [comment] 2015-09-22 01:36
@jakirkham those options aren't required, just pretty common.  You should be just fine switching the sudo_command to something that works.  I believe the feature to change this was due to off-brand Linux distros that will work with the shorter sudo command.

**Comment by sethvargo** [comment] 2016-06-01 02:15
Hi all,

I just tried, and I'm unable to reproduce this on Vagrant 1.8.2.dev (master). I'm sorry this issue sat for so long, but it should be fixed in the next release. If, for some reason, it is not, please **open a new issue** and follow our supplied issue template. This will help us get a reproducible test case to fix the issue and avoid future regressions. Thanks!

**Closed by sethvargo** 2016-06-01 02:15 UTC
Labels: bug
