### ISSUE TITLE
timeout during server version negotiating

### ISSUE THREAD

**Issue by laura-kraus-nexient** [mitchellh/vagrant#8412] opened 2017-03-26 18:51 UTC
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 1.9.3

### Host operating system
OSX Yosemite
Version 10.10.5

### Guest operating system
Ubuntu (64 bit)

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/laura-kraus-nexient/b9bdda25781917fa5e1560ced8551baf

### Expected behavior
What should have happened?
To allow variant up to run without an error

### Actual behavior
What actually happened?
I get this error:
An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout during server version negotiating

I do not believe I am using homestead, as i do not know what that is.
### Steps to reproduce
1.I was following these steps: https://www.mediawiki.org/wiki/MediaWiki-Vagrant
2.when i got to 'vagrant up', i get the error
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
https://github.com/mitchellh/vagrant/issues/6854

**Comment by chrisroberts** [comment] 2017-03-27 15:01
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Items of particular importance to help identify the source cause:

* Minimal Vagrantfile to reproduce the error
* Debug output of command causing the error (currently provided debug output does not show error)

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by laura-kraus-nexient** [comment] 2017-03-27 15:35
-How do i get the vagrant file, it is not clear to me. 
-when i search the file (https://gist.github.com/laura-kraus-nexient/b9bdda25781917fa5e1560ced8551baf) for 'error', i am able to see some results. I ran  vagrant up --debug and then copied that information into a file. What other way can I get it for you?

**Comment by chrisroberts** [comment] 2017-03-27 16:17
The `Vagrantfile` should be located in the directory you are executing the `vagrant` command. The errors in the debug output provided are not errors related to the SSH connection failure. You should be able to reproduce the original error by fully destroying the existing VM and creating it again. First:

```
$ vagrant destroy --force
```

This will destroy the current VM instance (erasing it completely). Then you can run:

```
$ vagrant up --debug
```

and that debug output should (hopefully) include the original error you encountered.

**Comment by chrisroberts** [comment] 2017-04-12 23:45
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2017-04-12 23:45 UTC
Labels: question, waiting-reply

**Comment by leiluspocus** [comment] 2018-04-04 08:25
I had the same error. I solved it by restarting the machine using the following commands 

`vagrant halt`

`vagrant up`

In case it helps someone ...

Thank you for the great work ! :)
