### ISSUE TITLE
Failure during salt provision since upgrade to 1.7.4

### ISSUE THREAD

**Issue by rasathus** [mitchellh/vagrant#6103] opened 2015-08-06 18:03 UTC
I have just upgraded from 1.7.2 to 1.7.4, and at the same time upgraded to version 5.0 of Virtualbox.

Since doing so an 'up' requiring a provision will fail at the salt provisioning stage ...

```
Copying salt minion config to vm.
Checking if salt-minion is installed
salt-minion found
Checking if salt-call is installed
salt-call found
Salt binaries found. Configuring only.
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/tmp/bootstrap_salt.sh  -C

Stdout from the command:



Stderr from the command:

stdin: is not a tty
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 * ERROR: In order to run the script in configuration only mode you also need to provide the configuration directory.
 23  204k   23 48522    0     0   610k      0 --:--:-- --:--:-- --:--:--  615k
curl: (23) Failed writing body (630 != 16384)
```

I have a gist showing the debug output from 1.7.4 around the failure, and the same area from an older version of vagrant...

https://gist.github.com/rasathus/e8bbf6c48c7f89f2b4d2

The /tmp/bootstrap_salt.sh scripts look to be the the same, but the execution parameters vary.

Working:
INFO ssh: Execute: /tmp/bootstrap_salt.sh  -F -c /tmp -C (sudo=true)

Non-Working:
INFO ssh: Execute: /tmp/bootstrap_salt.sh  -C (sudo=true)

Running the bootstrap script is the '-C' parameter results in the 'ERROR: In order to run the script in configuration only mode you also need to provide the configuration directory.' output.

**Comment by sethvargo** [comment] 2015-08-06 20:38
Looks like a duplicate of https://github.com/mitchellh/vagrant/issues/6029. Let's track that issue please :smile:

**Closed by sethvargo** 2015-08-06 20:38 UTC

**Comment by darkn3rd** [comment] 2015-08-11 23:06
And #6011
