### ISSUE TITLE
Self-hosted versioning with .json file over scp

### ISSUE THREAD

**Issue by ibizaman** [mitchellh/vagrant#5413] opened 2015-03-01 21:32 UTC
I know this isn't officially supported but my problem will maybe shed light on a bug in vagrant, so I ask anyway.

I followed a [recipe to make my own instance of vagrant cloud](https://github.com/hollodotme/Helpers/blob/master/Tutorials/vagrant/self-hosted-vagrant-boxes-with-versioning.md). Basically, I simply need to set the `config.vm.box_url` to point to my own server in the `Vagrantfile` and on the server's side I need to create a .json file following a certain structure.

The problem is that depending on the url scheme in the `config.vm.box_url`, the .json is recognized incorrectly as a VM itself instead of being correctly identified as a .json file containing versions.

First, this is how it is supposed to work:
The Vagrantfile points to myHost:
``` ruby
config.vm.box_url = "scp://vagrant@myHost:/vagrant/archlinux-x86_64/archlinux-x86_64.json"
```
And the following .json file is on the server:
``` json
{
    "description": "Base archlinux box",
    "name": "archlinux-x86_64",
    "versions": [
        {
            "providers": [
                {
                    "checksum": "5493156f8a09bacc01f7312abc921cdf838620ef",
                    "checksum_type": "sha1",
                    "name": "virtualbox",
                    "url": "scp://vagrant@myHost:/vagrant/archlinux-x86_64/boxes/archlinux-x86_64_0.1.0.box"
                }
            ],
            "version": "0.1.0"
        }
    ]
}
```
It, however, doesn't work. Vagrant fails to identify the .json file and thinks it's a VM box and tries to unzip it. [See debug log for more details](https://gist.github.com/ibizaman/54f4aa421e1aa2968910#file-failing-log-remote-json-file).

The thing is it works if I download the .json file locally and change the Vagrantfile to:
``` ruby
box.vm.box_url = "file://archlinux-x86_64.json"
```
There, the box is correctly being downloaded. [See debug log](https://gist.github.com/ibizaman/54f4aa421e1aa2968910#file-succeding-log-local-json-file).
So I suppose my setup correct and it seems the problem is due to the `scp://` scheme I'm trying to use.

Any advice? (if needed I can try to patch the code myself and provide a pull request, I'm just asking for a head start then)

**Comment by ibizaman** [comment] 2015-03-04 19:39
I'm working on a PR for this.

For now, a check is made by [metadata_url?](https://github.com/mitchellh/vagrant/blob/master/lib/vagrant/action/builtin/box_add.rb#L448). If the file's url is a local one, it is opened and parsed as json. If it's a http protocol, the file header is downloaded and checked is it is a json file (it is not parsed).

Obviously this check fails for scp and sftp (and other curl supported protocols) since there's no "header" in those cases.

I thought about overcoming this by changing a bit the `metadata_url?` function:
1/ If the url is not local, download the file by specifying the max download file size with the [cURL --range option](http://curl.haxx.se/docs/manpage.html)
2/ Open the file (or temporary downloaded one) and parse it.
3/ If everything went well, return the already parsed metadata, else return False

Now, in the `box_add.add_from_metadata` method, no need to re-download the metadata and re-parse it.

Any comments or warnings about this? Anyway, I'll try to make an as perfect as possible PR tonight.

**Comment by sethvargo** [comment] 2015-05-30 18:26
Hi @ibizaman  

Do you think this is the same issue as https://github.com/mitchellh/vagrant/issues/5635?

**Comment by sethvargo** [comment] 2015-05-31 00:57
After more thought, I am going to close this as a duplicate of #5635. Thank you for reporting. Hopefully we can get this fixed soon!

**Closed by sethvargo** 2015-05-31 00:57 UTC

**Comment by ibizaman** [comment] 2015-05-31 20:05
Hello @sethvargo, it seems the same indeed. The related PR though fixes both issues IMO. Did you have time to check it?
