### ISSUE TITLE
CentOS 7.0 + VMware Provider + Vagrant 1.6.5 = Failure

### ISSUE THREAD

**Issue by skyzyx** [mitchellh/vagrant#4558] opened 2014-09-25 05:01 UTC
I've already seen #4195 and #4171, and the issue persists.

> $ vagrant up
> Bringing machine 'dev' up with 'vmware_fusion' provider...
> ==> dev: Cloning VMware VM: 'dev/centos-7.0'. This can take some time...
> ==> dev: Verifying vmnet devices are healthy...
> ==> dev: Preparing network adapters...
> ==> dev: Starting the VMware VM...
> ==> dev: Waiting for the VM to finish booting...
> ==> dev: The machine is booted and ready!
> ==> dev: Forwarding ports...
>     dev: -- 80 => 80
>     dev: -- 443 => 443
>     dev: -- 22 => 2222
> ==> dev: Configuring network adapters within the VM...
> The following SSH command responded with a non-zero exit status.
> Vagrant assumes that this means the command failed!
> 
> /sbin/ifup eth1
> 
> Stdout from the command:
> 
> ERROR    : [/etc/sysconfig/network-scripts/ifup-eth] Device eth1 does not seem to be present, delaying initialization.
> 
> 
> Stderr from the command:

I happen to know that, for whatever reason, the default name of the ethernet interface is `eno16777728` instead of `eth0`.

**Comment by mattstep** [comment] 2015-03-26 00:22
@mitchellh point me to the part of the vagrant codebase where you think this needs to be fix, i'll fix it myself, it doesn't seem like anyone else is going to address this.

**Comment by mattstep** [comment] 2015-03-26 00:36
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown ens33

Stdout from the command:

ERROR    : [/etc/sysconfig/network-scripts/ifdown-eth] Device ens33 has MAC address 00:0C:29:3E:2D:9C, instead of configured address 00:0C:29:59:C4:97. Ignoring.

**Comment by mattstep** [comment] 2015-03-26 00:40
it seems vagrant 1.7.2 appends to the right ifcfg file now for centos7, but it's appending the config 3 times and not removing the default config, it should probably just open the file for write

**Comment by phinze** [comment] 2015-04-27 18:15
Hey folks,

Just did a bunch of research into this issue, and I have some updates for you.

Using the latest Vagrant and VMware plugins, the error message as reported by @mattstep is still reproducible on `chef/centos-7.0`.

I managed to track it down to a file leaked from the bootstrapping process. Even with no additional network interfaces, it shows up at `/etc/sysconfig/network-scripts/ifcfg-ens33` with these contents:

```
# Generated by dracut initrd
DEVICE="ens33"
ONBOOT=yes
NETBOOT=yes
UUID="2c063a06-a598-4d3a-9c70-9f5cc6e1f994"
IPV6INIT=yes
BOOTPROTO=dhcp
HWADDR="00:0c:29:59:c4:97"
TYPE=Ethernet
NAME="ens33"
```

The hard-coded MAC address in there is the problem - it was generated based on the interface present during bootstrapping, but each new VM is going to boot with its own set of devices with their own hardware addresses.

I've confirmed that removing that file and rebooting the VM causes the MAC address error to go away and everything to behave as expected. It looks like this issue was fixed recently for chef's boxes: https://github.com/chef/bento/pull/321 - it can be fixed in a similar way for other boxes.

So given all this, I'm going to close this as a box-specific issue - feel free to lobby for reopening if you believe there's still a Vagrant-level problem here.

> it's appending the config 3 times and not removing the default config,

This is true - it happens in the error case thanks to the fact that there's a `>>` in a retry block. These blocks get cleaned up on subsequent boots, so it's not a behavioral problem, just a cosmetic one. We should still fix it, but it's a pretty minor thing so I still think the best move is to close this issue.

**Closed by phinze** 2015-04-27 18:15 UTC
Labels: bug, guests/rhel
