### ISSUE TITLE
unknown nfs problem on El Capitan

### ISSUE THREAD

**Issue by boneskull** [mitchellh/vagrant#6809] opened 2016-01-05 23:10 UTC
Hi,

I'm getting a *ton* of the following in my logs:

```
1/5/16 15:03:37.000 kernel[0]: LS(4352) m3b121173:24935 :<ptr> error:2
```

After trying to decipher what this meant, I figured out that 24935 was the PID of the process.  That process is `nfsd`.

It seems on every write on my host (which ends up in the guest vagrant machine), this error occurs.  It's causing pretty significant system slowdown.

My `/etc/exports` is not doing anything special:

```
# VAGRANT-BEGIN: 505 7edbbbdf-3975-404e-9ff4-4735e3ed6317
"/Volumes/alien/projects/decipher/beacon" 10.20.1.6 -alldirs -mapall=505:20
# VAGRANT-END: 505 7edbbbdf-3975-404e-9ff4-4735e3ed6317
```

Of note is that this mount is formatted "Case-sensitive, Journaled".

Contents of `Vagrantfile`:

```
Vagrant.configure(2) do |config|

  # Ubuntu Server
  config.vm.define "headless", primary: true do |headless|
    headless.vm.box = "some/box"
  end

  ## FOLDER ##

  config.vm.synced_folder ".", "/vagrant"

  ## NETWORK ##

  # pgsql forwarding
  config.vm.network :forwarded_port, guest: 5432, host: 5432, auto_correct: true

  # hermes forwarding
  config.vm.network :forwarded_port, guest: 5000, host: 5000, auto_correct: true

  # your host OS type
  host = RbConfig::CONFIG['host_os']

  ## VIRTUALBOX ##

  config.vm.provider "virtualbox" do |v|
    # Give VM 1/4 system memory & access to all cpu cores on the host
    if host =~ /darwin/
      cpus = `sysctl -n hw.ncpu`.to_i
      # sysctl returns Bytes and we need to convert to MB
      mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 4
    elsif host =~ /linux/
      cpus = `nproc`.to_i
      # meminfo shows KB and we need to convert to MB
      mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 4
    end

    v.memory = mem
    v.cpus = cpus
  end

  ## HOST-SPECIFIC ##

  if host =~ /darwin/
    # macs require NFS for sharing because of performance issues.
    # NFS comes preinstalled on Macs, so no extra steps are necessary here.
    config.vm.synced_folder ".", "/vagrant", type: "nfs"

    # NFS requires a private network.  by default, a private network requires a static IP,
    # but this is a bitch to manage if you have many machines up.  the auto_network plugin
    # will automatically assign a static IP to your box.  to install this plugin, execute
    # `./scripts/vagrant/setup-host.sh` or `vagrant plugin install vagrant-auto_network`
    config.vm.network :private_network, :auto_network => true
  end

  ## PROVISIONING ##

  config.vm.provision "shell", path: "./scripts/vagrant/provision.sh"

  ## SSH ##
  
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
  
end

```

Is there anything I should try to modify that you can think of, or can I supply more information?  Any red flags in the above?

I'm using Vagrant v1.8.1and VirtualBox v5.0.12r104815.

**Comment by sethvargo** [comment] 2016-01-12 18:56
Hi @boneskull 

Unfortunately I am not an expert on NFS. Perhaps someone from the community may be able to offer additional insight. Tagging for now.

**Comment by paulschreiber** [comment] 2016-07-07 13:15
I am seeing this as well. I'm using Vagrant + Virtualbox + Ubuntu via https://github.com/Automattic/vip-quickstart/

**Comment by osopolar** [comment] 2016-07-07 17:14
I have this issue too. But I am currently not using vagrant (actually I uninstalled it to check if this issue still persists). I use VM-Ware Fusion with a Ubuntu 15.10 guest system and MacOS El Capitan (10.11.5). So it does not seem to be a vagrant issue, but anyway would be nice to get this resolved.

It seems that these messages could be caused by **L**ittle **S**nitch, just search in internet for part of the message: "kernel[0]: LS(", in most cases the issues are related to Little Snitch: see for example [here](http://www.tonymacx86.com/threads/new-mavericks-10-9-install-giving-me-ls-4050-m66deaaf0-messages-in-verbose-during-boot.116395/#post-718152) and [here](https://forums.obdev.at/viewtopic.php?t=8976).

I just contacted LS support. 

Who get's these errors and is not using Little Snitch?

**Comment by paulschreiber** [comment] 2016-07-07 17:33
LS could also be LaunchServices.

FWIW, I am also using Little Snitch.

**Comment by osopolar** [comment] 2016-07-07 17:42
Uninstalling Little Snitch fixed this for me, the message didn't appear again.

I tested it by calling `fgrep -rl 'test' .` in a nfs share which before gave me hundreds of messages per second.

**Comment by osopolar** [comment] 2016-07-19 21:37
The Little Snitch support answered me, that this issue would be fixed in the next release (_the current release is 3.6.3 (Build 4362, from January 2016)_).

**Comment by chrisroberts** [comment] 2016-10-03 16:56
With the above update (https://github.com/mitchellh/vagrant/issues/6809#issuecomment-233774176) is this still causing problems?

**Comment by boneskull** [comment] 2016-10-03 21:36
I haven't experienced this since, but I no longer use Little Snitch.

**Comment by chrisroberts** [comment] 2016-10-04 00:08
Okay, great. Thanks for the update!

**Closed by chrisroberts** 2016-10-04 00:08 UTC
Labels: bug, synced-folders/nfs, waiting-reply
