### ISSUE TITLE
Vagrant doesn't sync chef cookbook folders on second run

### ISSUE THREAD

**Issue by etki** [mitchellh/vagrant#5344] opened 2015-02-17 04:55 UTC
Hi.
I'm newbie with chef, so constantly i rewrite my recipes and run commands like `vagrant up --provision` on already provisioned machine. However, cookbook folders are not synced on second run until i manually delete synced_folders file. Is this correct behavior? If yes, how do i force cookbooks folder sync to re-provision machine?

p.s. Forgot to mention my version, i'm using latest 1.7.2 version downloaded from vagrantup.com with triggers, omnibus and librarian-chef plugins.

**Comment by sethvargo** [comment] 2015-02-17 05:49
Hi there. This is a duplicate of #5140. Please track that issue. Thanks! :smile:

**Closed by sethvargo** 2015-02-17 05:49 UTC

**Comment by etki** [comment] 2015-02-17 06:59
@sethvargo sorry, couldn't narrow issue search enough to find itby myself. Thank you!
