### ISSUE TITLE
Error Mounting Shared Folders with default and NFS synced folders after yum update

### ISSUE THREAD

**Issue by NathanKleekamp** [mitchellh/vagrant#8123] opened 2016-12-14 20:28 UTC
Thanks for all your hard work on Vagrant! 

### Vagrant version
Version: Vagrant 1.9.1
Vagrant + VMWARE plugin (4.0.15)

### Host operating system
Mac OS 10.11.6 (15G1108)
VMWARE Fusion Pro 8.5.3 (4696910)

### Guest operating system
CentOS 7.2
config.vm.box = "bento/centos-7.2"

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don"t change it unless you know what
# you"re doing.
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.

  # config.vm.network "public_network"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.

  config.vm.network "private_network", ip: "192.168.33.2"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.

  # config.vm.synced_folder "./www", "/var/www/html", type: "nfs"
  # config.vm.synced_folder ".", "/vagrant", type: "nfs"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.

  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "4"
  end


  config.ssh.insert_key = false
  config.ssh.forward_agent = true
end
```

### Debug output
https://gist.github.com/NathanKleekamp/451b8bdb015ce47ebd8cbd10620bd761

### Expected behavior
The synced folders should have mounted with either the basic or NFS methods

### Actual behavior
For the basic sync folder method, I received:

```
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["enableSharedFolders", "/Users/nathankleekamp/Projects/DevBox/VMWARE_TEST/Test/.vagrant/machines/default/vmware_fusion/4aadd314-3252-4b20-97c4-6f369d4e4500/centos-7.2-x86_64.vmx", {:notify=>[:stdout, :stderr]}]

Stdout: Error: There was an error mounting the Shared Folders file system inside the guest operating system

Stderr:
```
Using the NFS synced folders, I received this: 

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp 172.16.228.1:/Users/nathankleekamp/Projects/DevBox/VMWARE_TEST/Test/www /var/www/html
result=$?
if test $result -eq 0; then
if test -x /sbin/initctl && command -v /sbin/init && /sbin/init 2>/dev/null --version | grep upstart; then
/sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/var/www/html
fi
else
exit $result
fi

Stdout from the command:

Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported
```

### Steps to reproduce
1. `vagrant up`
2. After it finishes provisioning, run `vagrant reload`. Synced folders should mount fine.
3. `vagrant ssh`
4. `yum update -y`
5. `exit` out of vm
6. `vagrant reload`
7. After it reloads, the synced folder(s) will throw an error

This issue might be related to issue [#7763](https://github.com/mitchellh/vagrant/issues/7763)

**Comment by apquinn** [comment] 2017-01-12 21:07
I have the same issue

**Comment by chrisroberts** [comment] 2017-03-02 18:30
I believe that this issue should be resolved with the latest Vagrant release. Can you confirm if you are still experiencing this issue? Thanks!

**Comment by chrisroberts** [comment] 2017-04-12 23:46
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2017-04-12 23:46 UTC
Labels: guest/redhat, synced-folders/nfs, waiting-reply

**Comment by mphare** [comment] 2017-05-18 19:54
Well, too bad for me you closed this. I just purchased the VMWare provider for Fusion and I am having this same issue running Vagrant 1.9.5 on OS X 10.12.4 with VMWare Fusion 8.5.6 . Should I open a new issue?

**Comment by chrisroberts** [comment] 2017-05-18 23:45
@mphare Yes, please create a new issue and provide the information requested in the template.
