### ISSUE TITLE
The following SSH command responded with a non-zero exit status.

### ISSUE THREAD

**Issue by Andreych1500** [mitchellh/vagrant#8450] opened 2017-04-05 20:17 UTC
Hi,
When you run Vagrant -> Up error occurs in the system connect to SSH I understand. Do not Know Where to watch. Help please

### Vagrant version

Vagrant 1.9.3

### Host operating system

Centos 7

### Guest operating system

Windows 10

### Vagrantfile
```
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder "./public", "/home/bitrix/www/bitrix-demo.com"

end
```
```
{
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.3.28
    default: VirtualBox Version: 5.1
==> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ip -o -0 addr | grep -v LOOPBACK | awk '{print $2}' | sed 's/://'

Stdout from the command:

Stderr from the command:

}
```

**Comment by chrisroberts** [comment] 2017-04-05 20:20
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, the Vagrantfile, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by jeanbilal** [comment] 2017-06-06 16:01
Same problem happened today after i had to manually close VirtualBox:

==> homestead-7: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ip -o -0 addr | grep -v LOOPBACK | awk '{print $2}' | sed 's/://'

Stdout from the command:



Stderr from the command:

**Comment by chrisroberts** [comment] 2017-07-26 17:23
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Closed by chrisroberts** 2017-07-26 17:23 UTC
Labels: guest/redhat, networking

**Comment by shiretu** [comment] 2017-12-23 12:39
Still happens on Vagrant 2.0.1

Manually executed that command on the box with the indicated user, no sudo and with sudo, both worked. Vagrant fails to execute it tho

**Comment by Dsantacruz** [comment] 2017-12-28 02:48
i have vagrant v: 2.0.1 and not able run "vagrant up", show message "The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong."

**Comment by vojtagrec** [comment] 2018-01-18 12:03
This too is happening to me with Vagrant 2.0.1 on a Mac. I've already spent a lot of time debugging this, and so far have come to one interesting conclusion: it probably won't be an error in Vagrant. When I comment out all provisioning, this error doesn't occur. I'll update you if I find the cause so that others who google this bug can possibly know how to fix it.

**Comment by vojtagrec** [comment] 2018-01-18 14:56
OK, so I have it solved for my use case. I was overwriting `/home/vagrant/.bashrc` by mistake (by just one line containing `sudo -i` – don't ask for reasoning, not my decision) and it obviously broke some of Vagrant's SSH calls. 🤦‍♂️ 🤦‍♂️ 🤦‍♂️  FYI my guest OS was not even CentOS, it was Debian 8.

**Comment by greister** [comment] 2018-02-01 02:50
I have the same problem on generic/gentoo.
`.rb:308:in `cli'                                                                 
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/bin/vagrant:138:in `<ma    
in>'                                                                             
 INFO interface: error: The following SSH command responded with a non-zero e    
xit status.                                                                      
Vagrant assumes that this means the command failed!                              
                                                                                 
sed -i'' -e '/^#VAGRANT-BEGIN/,/^#VAGRANT-END/ d' /etc/conf.d/net                
  ln -sf /etc/init.d/net.lo /etc/init.d/net.eth1                                 
  /etc/init.d/net.eth1 stop || true                                              
                                                                                 
  cat '/tmp/vagrant-network-eth1-1517451117-0' >> /etc/conf.d/net                
  rm -f '/tmp/vagrant-network-eth1-1517451117-0'                                 
                                                                                 
  /etc/init.d/net.eth1 start                                                     
                                                                                 
  ln -sf /etc/init.d/net.lo /etc/init.d/net.eth2                                 
  /etc/init.d/net.eth2 stop || true                                              
                                                                                 
  cat '/tmp/vagrant-network-eth2-1517451117-1' >> /etc/conf.d/net                
  rm -f '/tmp/vagrant-network-eth2-1517451117-1'                                 
                                                                                 
  /etc/init.d/net.eth2 start                                                     
                                                                                 
                                                                                 
Stdout from the command:                                                         
                                                                                 
 * Bringing up interface eth1                                                    
 *   Starting ifplugd on eth1 ... [ ok ]                                         
 *     Backgrounding ...                                                         
 * Caching service dependencies ... [ ok ]                                       
 * Bringing up interface eth2                                                    
 *   Starting ifplugd on eth2 ... [ ok ]                                         
 *     Backgrounding ...                                                         
                                                                                 
                                                                                 
Stderr from the command:                                                         
                                                                                 
 * WARNING: net.eth1 is already stopped                                          
 * WARNING: net.eth1 has started, but is inactive                                
 * WARNING: net.eth2 is already stopped                                          
 * WARNING: net.eth2 has started, but is inactive                                
                                                                                 
The following SSH command responded with a non-zero exit status.                 
Vagrant assumes that this means the command failed!                              
                                                                                 
sed -i'' -e '/^#VAGRANT-BEGIN/,/^#VAGRANT-END/ d' /etc/conf.d/net                
  ln -sf /etc/init.d/net.lo /etc/init.d/net.eth1                                 
  /etc/init.d/net.eth1 stop || true                                              
                                                                                 
  cat '/tmp/vagrant-network-eth1-1517451117-0' >> /etc/conf.d/net                
  rm -f '/tmp/vagrant-network-eth1-1517451117-0'                                 
                                                                                 
  /etc/init.d/net.eth1 start                                                     
                                                                                 
  ln -sf /etc/init.d/net.lo /etc/init.d/net.eth2                                 
  /etc/init.d/net.eth2 stop || true                                              
                                                                                 
  cat '/tmp/vagrant-network-eth2-1517451117-1' >> /etc/conf.d/net                
  rm -f '/tmp/vagrant-network-eth2-1517451117-1'                                 
                                                                                 
  /etc/init.d/net.eth2 start                                                     
                                                                                 
                                                                                 
Stdout from the command:                                                         
                                                                                 
 * Bringing up interface eth1                                                    
 *   Starting ifplugd on eth1 ... [ ok ]                                         
 *     Backgrounding ...                                                         
 * Caching service dependencies ... [ ok ]                                       
 * Bringing up interface eth2                                                    
 *   Starting ifplugd on eth2 ... [ ok ]                                         
 *     Backgrounding ...                                                         
                                                                                 
                                                                                 
Stderr from the command:                                                         
                                                                                 
 * WARNING: net.eth1 is already stopped                                          
 * WARNING: net.eth1 has started, but is inactive                                
 * WARNING: net.eth2 is already stopped                                          
 * WARNING: net.eth2 has started, but is inactive                                
                                                                                 
 INFO interface: Machine: error-exit ["Vagrant::Errors::VagrantError", "The f    
ollowing SSH command responded with a non-zero exit status.\nVagrant assumes     
that this means the command failed!\n\nsed -i'' -e '/^#VAGRANT-BEGIN/,/^#VAGR    
ANT-END/ d' /etc/conf.d/net\n  ln -sf /etc/init.d/net.lo /etc/init.d/net.eth1    
\n  /etc/init.d/net.eth1 stop || true\n\n  cat '/tmp/vagrant-network-eth1-151    
7451117-0' >> /etc/conf.d/net\n  rm -f '/tmp/vagrant-network-eth1-1517451117-    
0'\n\n  /etc/init.d/net.eth1 start\n\n  ln -sf /etc/init.d/net.lo /etc/init.d    
/net.eth2\n  /etc/init.d/net.eth2 stop || true\n\n  cat '/tmp/vagrant-network    
-eth2-1517451117-1' >> /etc/conf.d/net\n  rm -f '/tmp/vagrant-network-eth2-15    
17451117-1'\n\n  /etc/init.d/net.eth2 start\n\n\nStdout from the command:\n\n    
 * Bringing up interface eth1\n *   Starting ifplugd on eth1 ... [ ok ]\n *      
   Backgrounding ...\n * Caching service dependencies ... [ ok ]\n * Bringing    
 up interface eth2\n *   Starting ifplugd on eth2 ... [ ok ]\n *     Backgrou    
nding ...\n\n\nStderr from the command:\n\n * WARNING: net.eth1 is already st    
opped\n * WARNING: net.eth1 has started, but is inactive\n * WARNING: net.eth    
2 is already stopped\n * WARNING: net.eth2 has started, but is inactive\n"]      
                                                                                 
`

**Comment by briancain** [comment] 2018-02-01 17:06
@greister I recommend opening a new issue and filling out the relevant information from the issue template. Thanks!

**Comment by leoswaldo** [comment] 2019-03-05 22:40
So I had this issue as well, I found the answer on [ray's response]( https://github.com/hashicorp/vagrant/issues/1659#issuecomment-17046154)
