### ISSUE TITLE
The box '*.box' could not be found.

### ISSUE THREAD

**Issue by slamonega** [mitchellh/vagrant#7596] opened 2016-07-17 17:50 UTC
I follow all the steps, but when I want to Vagrant Up, it show that could not found the Box

**Comment by sethvargo** [comment] 2016-07-17 18:22
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by chrisroberts** [comment] 2016-10-03 16:03
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2016-10-03 16:03 UTC
Labels: waiting-reply
