### ISSUE TITLE
Is it a curl issue?

### ISSUE THREAD

**Issue by rakibtg** [mitchellh/vagrant#7060] opened 2016-02-20 06:55 UTC
I am on windows 10 and has VirtualBox 5.0.14 and vagrant 1.8.1 installed in it.

While i try to add a box it gives me this error:

**Command:** $ vagrant box add ubuntu/trusty64
**Error:**

> The box 'ubuntu/trusty64' could not be found or could not be accessed in the remote catalog. If this is a private box on HashiCorp's Atlas, please verify you're logged in via  vagrant login. Also, please double-check the name. The expanded URL and error message are shown below:
> 
> URL: ["https://atlas.hashicorp.com/ubuntu/trusty64"] Error:

I badly need vagrant to work on my system, sadly i had no idea whats going wrong! i tested virtualbox with a ubuntu 64 server and it installed fine.. please any idea? and do you think the curl.exe file in windows is corrupted or misplaced?

**Comment by sethvargo** [comment] 2016-02-20 17:21
Duplicate of https://github.com/mitchellh/vagrant/issues/6754

**Closed by sethvargo** 2016-02-20 17:21 UTC
