### ISSUE TITLE
Rsync default behaviour

### ISSUE THREAD

**Issue by stepanzarubin** [mitchellh/vagrant#6480] opened 2015-11-04 11:49 UTC
I think default behaviour should be:

When we run `rsync` it should do full rsync
When we run `rsync-auto` it should first do full rsync and then watch for modified only.

This should affect all the plugins that are using Vagrant rsync internals.

Thanks.

**Comment by nuncanada** [comment] 2015-11-04 14:12
For big directory structures that are common for a lot of projects, even more for development workbenchs, this is the difference between a usable vs non-usable rsync solution.

**Comment by sethvargo** [comment] 2015-11-08 13:07
Oops - looks like a duplicate of https://github.com/mitchellh/vagrant/issues/6399 actually. Thanks!

**Closed by sethvargo** 2015-11-08 13:07 UTC
Labels: enhancement, synced-folders/rsync
