### ISSUE TITLE
ansible_local passes extra_vars as hash instead of string.

### ISSUE THREAD

**Issue by Ohadbasan** [mitchellh/vagrant#7322] opened 2016-05-17 13:49 UTC
### Vagrant version
1.8.1

### Host operating system
Mac Os x El capitan

### Guest operating system
ubuntu

### Vagrantfile
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.insert_key = false

 config.vm.provision :shell, inline: <<SCRIPT
GALAXY=/usr/local/bin/ansible-galaxy
echo '#!/usr/bin/env python2
import sys
import os

args = sys.argv
if args[1:] == ["--help"]:
  args.insert(1, "info")

os.execv("/usr/bin/ansible-galaxy", args)
' | sudo tee $GALAXY
sudo chmod 0755 $GALAXY
SCRIPT

config.vm.provision :shell, inline: <<EOF
ansible-galaxy install savagegus.consul
EOF

  config.vm.provision "ansible_local" do |ansible|
    ansible.install=true
    ansible.verbose = "vvv"
    ansible.playbook = "consul_local.yml"
    ansible.inventory_path = "ansible_hosts"
    ansible.limit = "all"
    ansible.extra_vars =  {
      consul_service_name: "foo",
      consul_service_port: 80
    }
  end

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

What should have happened?
ansible-playbook --limit='all' --inventory-file=ansible_hosts --extra-vars="{"consul_service_name":"crap","consul_service_port":80}" -vvv consul_local.yml

### Actual behavior
What actually happened?

ansible-playbook --limit='all' --inventory-file=ansible_hosts --extra-vars={"consul_service_name":"crap","consul_service_port":80} -vvv consul_local.yml

### Steps to reproduce
1.pass extra-vars as hash to ansible using ansible_local. vagrant passes them as hash. should be passed as a string as written in the ansible docs
--extra-vars '{"pacman":"mrs","ghosts":["inky","pinky","clyde","sue"]}'

**Comment by gildegoma** [comment] 2016-05-20 21:38
Closing as a duplicate of #6726 

This bug will be fixed (#7103) in the next Vagrant release (1.8.2).

**Closed by gildegoma** 2016-05-20 21:38 UTC
Labels: provisioner/ansible
