### ISSUE TITLE
IPv6 address error - `hostonly_config': undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by zaius** [mitchellh/vagrant#7058] opened 2016-02-19 21:32 UTC
Hi vagrant team - I'm running into an issue when adding an ipv6 address to my machine.

The traceback and error message are quite similar to #5608, but I wanted to post a new issue to make sure it gets seen.

I have only tested this on vmware, but let know if confirming on vbox would help.

### Vagrant version
1.8.1

### Host operating system
Mac 10.11.3

### Guest operating system
Ubuntu 14.04

### Vagrantfile
```ruby
Vagrant.configure('2') do |config|
  config.vm.box = 'hashicorp/precise64'
  config.vm.provider 'vmware_workstation'
  config.vm.network :private_network, ip: '172.16.172.1'
  config.vm.network :private_network, ip: 'fd00::1'
end
```

### Debug output
https://gist.github.com/zaius/8f6e158f8f335b956603

### Expected behavior
Guest should start.

### Actual behavior
Guest does not start.

### Steps to reproduce
1. Add the above Vagrantfile
2. Run `vagrant up`

### References
- GH-5608

**Comment by dbishop** [comment] 2016-03-04 23:25
We're hitting this as well.  Our Vagrantfile is pretty complicated, but the problem reproduces fine with the given minimal Vagrantfile here.

I'm attaching a `--debug` log.  Note that we're running some IPv6-related patches on top of Vagrant `1.8.1` that we've packaged as `1.8.1.1`, so don't be too surprised by that reported version in the output.  The delta from 1.8.1 isn't large, and isn't related to the bug in this ticket.


[debug.log.zip](https://github.com/mitchellh/vagrant/files/159539/debug.log.zip)

**Comment by dbishop** [comment] 2016-04-26 18:33
@sethvargo any update on this?  This is still blocking us from rolling out Vagrant + VMware to the rest of our developers and CI infrastructure...

**Comment by dbishop** [comment] 2016-06-10 03:58
@sethvargo Have you been able to reproduce the problem?  Is there anything we can do to help speed up a fix?

**Comment by sethvargo** [comment] 2016-06-10 11:23
Hi there,

I just tried to reproduce this using Vagrant master (which will be released very soon) and I was unable to do so:

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: You assigned a static IP ending in ".1" to this machine.
==> default: This is very often used by the router and can cause the
==> default: network to not work properly. If the network doesn't work
==> default: properly, try changing this IP.
==> default: Importing base box 'hashicorp/precise64'...
==> default: Matching MAC address for NAT networking...
==> default: You assigned a static IP ending in ".1" to this machine.
==> default: This is very often used by the router and can cause the
==> default: network to not work properly. If the network doesn't work
==> default: properly, try changing this IP.
==> default: Checking if box 'hashicorp/precise64' is up to date...
==> default: Setting the name of the VM: vagrant-vmware-desktop_default_1465557325305_51497
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
    default: Adapter 3: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.2.0
    default: VirtualBox Version: 5.0
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/sethvargo/Development/vagrant-vmware-desktop
```

```
Welcome to Ubuntu 12.04 LTS (GNU/Linux 3.2.0-23-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
New release '14.04.4 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Welcome to your Vagrant-built virtual machine.
Last login: Fri Sep 14 06:23:18 2012 from 10.0.2.2
vagrant@precise64:~$ ifconfig
eth0      Link encap:Ethernet  HWaddr 08:00:27:88:0c:a6
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe88:ca6/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:820 errors:0 dropped:0 overruns:0 frame:0
          TX packets:639 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:94316 (94.3 KB)  TX bytes:73511 (73.5 KB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:2f:3b:3b
          inet addr:172.16.172.1  Bcast:172.16.172.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe2f:3b3b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:16 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:3880 (3.8 KB)  TX bytes:468 (468.0 B)

eth2      Link encap:Ethernet  HWaddr 08:00:27:4f:65:3b
          inet6 addr: fe80::a00:27ff:fe4f:653b/64 Scope:Link
          inet6 addr: fd00::1/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:17 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:3966 (3.9 KB)  TX bytes:586 (586.0 B)
```

I also tried `ubuntu/xenial64` and it worked as well. This is likely fixed in either the latest release of the vagrant-vmware plugin and/or Vagrant master. Thanks!

**Comment by dbishop** [comment] 2016-06-10 15:03
@sethvargo odd, your box name was `vagrant-vmware-desktop` but appears to have been using the virtualbox provider.  Our issue is somewhere within the vmware code, which is closed-source (otherwise we would have fixed it ourselves already).

Can you be sure to test using vmware fusion?

Also, was your test using IPv6 addresses?  It looks like the ones in the `ifconfig` output are just link addresses?

**Comment by sethvargo** [comment] 2016-06-10 16:51
Hi @dbishop 

I did some research on this. Unfortunately VMware IPv6 simply does not work. Our Vagrant team spent hours investigating and also talked to VMware about this. They simply don't support IPv6 in a robust way like VirtualBox. They support getting a NAT IPv6 address but its not routeable.

The next version of the VMware plugin will make this lack of support clearer (and not raise an error). Sorry!

**Closed by sethvargo** 2016-06-10 16:51 UTC
Labels: bug, provider/vmware

**Comment by dbishop** [comment] 2016-06-13 15:56
@sethvargo I've been able to do enough, manually in the Vagrantfile, to support our use-case of IPv6 host-only networks on VMware Fusion (untested on VMware Workstation).

AFAICT, the only missing piece in VMware Fusion is the ability for VMware Fusion to manage IPv6 addresses on the host OS (OS X 10.11.5 in my case) vmnetX interfaces.  **If you manually put IPv6 addresses on the network interfaces (e.g. `eth1` in the guest OS and `vmnet2` in the host OS), then IPv6 packets flow/route just fine.**

If you manually add the host-only interfaces to the vmx data in the Vagrantfile, and assign the IPv6 address and "up" the interface with `ip` directly inside the guest VM using two shell provisioning lines in the Vagrantfile, and use vagrant-triggers to run a command like  `sudo ifconfig vmnet2 inet6 fd22:d006:1028:2060::1 prefixlen 64` in the host OS after `:up` and `:destroy`, then everything we need works.

If the vagrant VMware plugin could still create the host-only interfaces in the vmx, and perform the correct guest OS IPv6 configuration (which I know it can, because Vagrant can set up guest OS IPv6 networking for VirtualBox), then all we would need to add is a secure setuid binary on the host OS to repair the manually-assigned IPv6 address on the host OS `vmnetX` interfaces.

**I'll open another GitHub Issue for this feature request, when I have a working minimal Vagrantfile and instructions that illustrate our workaround and outlines more specifically what the vagrant VMware plugin could do to add support for IPv6 + VMware Fusion.**

Thanks!
Darrell
