### ISSUE TITLE
Script provisioner never terminates

### ISSUE THREAD

**Issue by rfkrocktk** [mitchellh/vagrant#6051] opened 2015-07-28 23:01 UTC
I have a multi-machine Vagrant setup. My Vagrantfile looks like this:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Use Phusion's Ubuntu 14.04 box with support for Docker
    config.vm.box = "phusion-open-ubuntu-14.04-amd64"
    config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box"
    # tty stuff
    config.ssh.pty = true

    # Configure the VirtualBox Provider
    config.vm.provider :virtualbox do |vb|
        # Give the VM 1GB of RAM
        vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    # per-machine changes
    config.vm.define "kibana" do |kibana|
        kibana.vm.hostname = "kibana1"

        kibana.vm.provision "shell", path: "conf/scripts/upgrade-latest-puppet.sh", run: "once"

        kibana.vm.provision :puppet do |puppet|
            puppet.hiera_config_path = "conf/hiera.yaml"
            puppet.manifests_path = "manifests"
            puppet.module_path = "modules"
            puppet.manifest_file = "kibana1.pp"

            puppet.facter = {
                "is_vagrant" => true,
            }
        end
    end
end
```

I have defined two provisioners, one is a shell script and the other is Puppet, in that order.

My `conf/scripts/upgrade-latest-puppet.sh` looks like this:

```
#!/bin/bash

DEBIAN_FRONTEND=noninteractive apt-get update |& tee -a /tmp/apt.log && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes puppet |& tee -a /tmp/apt.log

echo "process exited..." |& tee -a /tmp/apt.log

exit 0
```

I have everything logged to `/tmp/apt.log` in the machine. While doing `vagrant up`, I `vagrant ssh` into the machine and tail the file. I see "process exited" from the echo statement, but the shell provisioner never terminates:

```
Bringing machine 'kibana' up with 'virtualbox' provider...
==> kibana: Importing base box 'phusion-open-ubuntu-14.04-amd64'...
==> kibana: Matching MAC address for NAT networking...
==> kibana: Setting the name of the VM: puppet_kibana_1438123500249_3721
==> kibana: Clearing any previously set forwarded ports...
==> kibana: Clearing any previously set network interfaces...
==> kibana: Preparing network interfaces based on configuration...
    kibana: Adapter 1: nat
==> kibana: Forwarding ports...
    kibana: 22 => 2222 (adapter 1)
==> kibana: Running 'pre-boot' VM customizations...
==> kibana: Booting VM...
==> kibana: Waiting for machine to boot. This may take a few minutes...
    kibana: SSH address: 127.0.0.1:2222
    kibana: SSH username: vagrant
    kibana: SSH auth method: private key
    kibana: Warning: Connection timeout. Retrying...
    kibana: 
    kibana: Vagrant insecure key detected. Vagrant will automatically replace
    kibana: this with a newly generated keypair for better security.
    kibana: 
    kibana: Inserting generated public key within guest...
    kibana: Removing insecure key from the guest if its present...
    kibana: Key inserted! Disconnecting and reconnecting using new SSH key...
==> kibana: Machine booted and ready!
==> kibana: Checking for guest additions in VM...
==> kibana: Setting hostname...
==> kibana: Mounting shared folders...
    kibana: /vagrant => /home/tkocheran/Documents/Development/chromeriver-elk/puppet
    kibana: /tmp/vagrant-puppet/modules-c105fde19be8ba0d62cee003ed9aa016 => /home/tkocheran/Documents/Development/chromeriver-elk/puppet/modules
    kibana: /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513 => /home/tkocheran/Documents/Development/chromeriver-elk/puppet/manifests
==> kibana: Running provisioner: shell...
    kibana: Running: /tmp/vagrant-shell20150728-27168-1ennj6c.sh
```

I'm on Vagrant 1.7.4 and VirtualBox 4.3.30. My host operating system is elementary Freya, which is Ubuntu 14.04, kernel 3.19.0-25-generic.

**Comment by rfkrocktk** [comment] 2015-07-28 23:24
If I run `vagrant --debug up`, I see the command output as it comes, and then my script exits and nothing happens after that:

```
DEBUG ssh: stdout:  * Starting puppet agent

puppet not configured to start, please edit /etc/default/puppet to enable
   ...done.

DEBUG ssh: stdout: Processing triggers for ureadahead (0.100.0-16) ...

DEBUG ssh: stdout: process exited...

DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
```

**Comment by sethvargo** [comment] 2015-08-06 20:08
Hi @rfkrocktk 

What happens if you remove puppet from the mix? I just tried using the same base box with no provisioning and I can't get this error to reproduce, so it's possible there is something in your provisioning scripts that is causing the script to not exit.

**Comment by rfkrocktk** [comment] 2015-08-06 20:40
I'm certain that my Puppet code terminates just fine, as I run it in production all the time without issues. What's more is that I've examined that there's no network activity, so it isn't waiting for a long download.

Additionally, there seems to be a bug with the latest Vagrant that I don't get output from Puppet until the Puppet process has terminated.This means that I'll wait at a blank screen until Puppet finishes running. This wasn't the case before. I'll probably have to submit this as a separate bug report.

**Comment by sethvargo** [comment] 2015-08-06 20:43
@rfkrocktk okay, but are you able to reproduce this issue without the puppet code?

**Comment by b-long** [comment] 2015-08-10 18:44
I'm debugging a similar issue.  Is there a command-line flag to skip a specific provisioner?  Something that's the opposite of [`--provision-with`](http://docs.vagrantup.com/v2/cli/up.html) ?

**Comment by b-long** [comment] 2015-08-10 18:55
**Edit**: Sorry, I think I figured out the workflow for isolating provision steps:
```shell
vagrant up --no-provision
vagrant up --provision a, b, c
vagrant up --provision d
```

In my case `d` (above) is puppet, and it seems to cause issues when run all at once, but not when run in this manner.

**Comment by rfkrocktk** [comment] 2015-08-10 20:07
@b-long So you're confirming that there's an issue with the Puppet provisioner itself? My experience was that I could run the script fine by itself, Puppet fine by itself, but never both in order. The script provisioner would never exit and go onto do Puppet.

**Comment by b-long** [comment] 2015-08-10 20:11
@rfkrocktk Sorry, no, I'm not confirming that it's an error with the puppet provisioner necessarily.  I'm trying to build a new mult-node Vagrant setup and have had no trouble at all when using Puppet + Virtualbox as a provider.  However, when using Puppet + [vagrant-cloudstack](https://github.com/schubergphilis/vagrant-cloudstack) provider, I did run into a scenario where it seemed the puppet provisioner wouldn't exit after Puppet was applied.

**Comment by rfkrocktk** [comment] 2015-08-24 22:22
Here's a demonstration of the problem in the form of a full Vagrant project: https://dl.dropboxusercontent.com/u/439089/provisioner-hang.zip

**Comment by rfkrocktk** [comment] 2015-09-01 19:09
@sethvargo Please see a working demonstration of this at [rfkrocktk/rfkrocktk.github.io](https://github.com/rfkrocktk/rfkrocktk.github.io) at commit [32e4d49b2a49f48c09b27fd3dfe689f74bdbd771](https://github.com/rfkrocktk/rfkrocktk.github.io/tree/32e4d49b2a49f48c09b27fd3dfe689f74bdbd771).

I have a shell provisioner and a Puppet provisioner. This demonstrates the issue perfectly.

**Comment by sethvargo** [comment] 2015-09-01 22:02
Hi @rfkrocktk 

You are definitely correct that that script hangs. After some debugging, I have determined that the issue is a result of asking Vagrant to allocate a PTY. By default, Vagrant does not allocate a PTY for you, and the error message "stdin is not a tty" is not actually a bug but rather a warning. The easiest fix is to simply remove the `config.ssh.pty = true` line from your Vagrantfile.

The problem is that programs such as apt detect the presence of a PTY and can ask for input (i.e. do you want to install these packages), even with `-y` and noninteractive mode set. It's bizarre, but the other way around this is to wrap the shell provisioner in its own shell (which won't have a PTY):

```ruby
  config.vm.provision :shell,
    inline: <<-EOH
/bin/bash <<EOB
apt-get update -qq && apt-get install -y puppet
EOB
EOH
```

It's not pretty, but it works. Note that `bash -c "..."` **won't** work and I have absolutely no idea why - you need the multi-line statement. Interestingly, we were only able to reproduce this issue with `apt`. We tried a number of other shell commands and they all succeeded without error.

I do not think this is a bug in Vagrant, but rather our misunderstanding of PTYs and/or apt's strange behavior. 

I'm going to close this issue since there are two concrete workarounds for solving this. Please let me know if you have any questions.

**Closed by sethvargo** 2015-09-01 22:02 UTC
Labels: waiting-reply

**Comment by rfkrocktk** [comment] 2015-09-01 22:12
Thanks for looking into this!

**Comment by alkemann** [comment] 2016-01-26 14:58
@sethvargo i did not have the pty=true in my vagrant file and setting it to false did not have any effect

**Comment by Chocofede** [comment] 2016-08-11 22:20
@alkemann: If you had an IP defined as 
`config.vm.network :private_network, ip: "198.10.10.201"`
You may have a problem with the DNS. If you flush them (http://askubuntu.com/questions/414826/how-to-flush-dns-in-ubuntu-12-04) you'll get out of the issue. Taken from https://github.com/mitchellh/vagrant/issues/5232
