### ISSUE TITLE
Vagrant-1.9.4: "vagrant list-commands" throws exception

### ISSUE THREAD

**Issue by sayotte** [mitchellh/vagrant#8546] opened 2017-05-01 15:49 UTC
### Vagrant version
```
$ vagrant -v
Vagrant 1.9.4
```

### Host operating system
```
$ lsb_release -ri
Distributor ID: Ubuntu
Release:        14.04
```

### Guest operating system
N/A

### Expected behavior
Expected to see a list of subcommands when running `vagrant list-commands`

### Actual behavior
```
$ vagrant list-commands
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- vagrant-share/helper/api (LoadError)
```

### Steps to reproduce
1. Install vagrant-1.9.4
2. Run `vagrant list-commands`

**Comment by chrisroberts** [comment] 2017-05-01 21:17
Duplicate of #8519

**Closed by chrisroberts** 2017-05-01 21:17 UTC
Labels: bug, duplicate, share
