### ISSUE TITLE
Vagrant not able to create shared folders in virtual box 5.1.20

### ISSUE THREAD

**Issue by dave00galloway** [mitchellh/vagrant#8536] opened 2017-04-28 13:21 UTC
Hi Team, 

I get this error when trying to start a vbox with vagrant:- 

{{{
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=999,gid=999 rsr /rsr

}}}

this was working fine in vbox 5.1.18, but does not work in any version of vagrant (tried 1.9.1 -> 1.9.4). Here's the vagrant file (relevant bits only...)

{{{
Vagrant.configure(2) do |config|

  config.vm.define :capture do |node|
    name = 'myvm'
    bootstrap_vm(name, node)
    node.vm.synced_folder Dir.pwd + '/..', "/operations", :create => true

    if Dir.exists? (Dir.pwd + '/../../rsr')
      node.vm.synced_folder Dir.pwd + '/../../rsr', "/rsr", :create => true
    end

}}}
and

{{{
def bootstrap_linux(name, node)
  node.vm.box = '<url>'
  node.ssh.username = 'vagrant'
  node.ssh.private_key_path = '.vagrant-ssh/vagrant'
  node.ssh.forward_agent = true
  node.vm.hostname = name
  node.vm.provider 'virtualbox' do |vb|
    vb.customize ['modifyvm', :id, '--cpus', 2]
    vb.customize ['modifyvm', :id, '--memory', 4096]
    vb.customize ['modifyvm', :id, '--audio', 'none']
    vb.gui = false
    # Linux workarounds for vbox network problems
    (1..8).each do |i|
      vb.customize ['modifyvm', :id, "--nictype#{i}", 'virtio']
      vb.customize ['modifyvm', :id, "--natdnshostresolver#{i}", 'off']
      vb.customize ['modifyvm', :id, "--natdnsproxy#{i}", 'off']
      vb.customize ['modifyvm', :id, "--nicpromisc#{i}", 'allow-all']
    end
  end
end

}}}

please find a way to make the shared folders work (again...)

**Comment by dave00galloway** [comment] 2017-04-28 13:25
I've raised a corresponding bug with vbox since it looks like a breaking change in vbox guest additions, but I somehow think vagrant might be able to get a fix out quicker! https://www.virtualbox.org/ticket/16709

**Comment by chrisroberts** [comment] 2017-04-28 21:48
Closing as a duplicate of #8502. Thanks for the report.

**Closed by chrisroberts** 2017-04-28 21:48 UTC
Labels: bug, duplicate, provider/virtualbox, upstream
