### ISSUE TITLE
Vagrant doesn't work on Mac OS X 10.11

### ISSUE THREAD

**Issue by aleksandra-tarkowska** [mitchellh/vagrant#6517] opened 2015-11-13 15:50 UTC
After upgrade from 10.8 to 10.11, for unknown reason vagrant is pointing to the old version of ruby.
```
$ vagrant -v
Vagrant 1.7.4 installed by ``brew cask install vagrant`` and/or from .dmg
$ vagrant
/opt/vagrant/embedded/lib/ruby/2.0.0/openssl.rb:17:in `require': dlopen(/opt/vagrant/embedded/lib/ruby/2.0.0/universal-darwin12.6.0/openssl.bundle, 9): Symbol not found: _SSLv2_client_method (LoadError)
  Referenced from: /opt/vagrant/embedded/lib/ruby/2.0.0/universal-darwin12.6.0/openssl.bundle
  Expected in: /usr/local/Cellar/openssl/1.0.2d_1/lib/libssl.1.0.0.dylib
 - /opt/vagrant/embedded/lib/ruby/2.0.0/universal-darwin12.6.0/openssl.bundle
	from /opt/vagrant/embedded/lib/ruby/2.0.0/openssl.rb:17:in `<top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant.rb:64:in `require'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant.rb:64:in `<top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:105:in `require'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:105:in `<main>'
```
 I reinstalled openssl, vagrant, even installed ruby and still the same error.

```
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
```
```
$ otool -L /usr/local/Cellar/openssl/1.0.2d_1/lib/libssl.1.0.0.dylib
/usr/local/Cellar/openssl/1.0.2d_1/lib/libssl.1.0.0.dylib:
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/Cellar/openssl/1.0.2d_1/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
```

I do not understand why is looking for old ``ruby/2.0.0/universal-darwin12.6.0/openssl.bundle``

any thoughts on how to embed right lib?

**Comment by sethvargo** [comment] 2015-11-13 17:00
Hi @aleksandra-tarkowska 

Vagrant contains its own Ruby and everything it needs to run. Can you please uninstall the homebrew cask version and install via the official package installer at https://www.vagrantup.com/downloads.html? Thanks!

**Comment by aleksandra-tarkowska** [comment] 2015-11-13 19:29
I also tried that but I am getting the same error.

**Comment by sethvargo** [comment] 2015-11-13 19:30
Hi @aleksandra-tarkowska 

What is the output of `vagrant -v` with the version from the website? Do you have openssl installed via homebrew too?

**Comment by aleksandra-tarkowska** [comment] 2015-11-16 09:51
@sethvarg, yes I did install openssl via homebrew, see otool output above, it points to `` /usr/local/Cellar/openssl/1.0.2d_1/lib/libcrypto.1.0.0.dylib``

```
Mac-Book-Pro:~ ola$  brew cask uninstall vagrant
Error: vagrant is not installed
Mac-Book-Pro:~ ola$ vagrant -v
Vagrant 1.7.4
```

**Comment by aleksandra-tarkowska** [comment] 2015-11-16 09:52
Hi @sethvargo, yes I did install openssl via homebrew, see otool output above, it points to `` /usr/local/Cellar/openssl/1.0.2d_1/lib/libcrypto.1.0.0.dylib``

```
Mac-Book-Pro:~ ola$  brew cask uninstall vagrant
Error: vagrant is not installed
Mac-Book-Pro:~ ola$ vagrant -v
Vagrant 1.7.4
```

**Comment by aleksandra-tarkowska** [comment] 2015-11-16 09:57
I tried update built in path like stated here http://apple.stackexchange.com/questions/126830/how-to-upgrade-openssl-in-os-x, but is not possible to move that file even as root

**Comment by sethvargo** [comment] 2015-11-16 14:36
Hi @aleksandra-tarkowska 

Did you link the openssl you installed via homebrew? I think something is linked incorrectly on your local system.

**Comment by aleksandra-tarkowska** [comment] 2015-11-16 16:08
It is linked correctly

```
which openssl
/usr/local/bin/openssl
```

**Comment by sethvargo** [comment] 2015-11-16 16:26
@aleksandra-tarkowska right, but that looks like homebrew's openssl, not OSX's openssl

**Comment by aleksandra-tarkowska** [comment] 2015-11-16 16:33
Apple deprecated openssl, you shouldn't relay on it, is outdated!

**Comment by sethvargo** [comment] 2015-11-16 17:32
@aleksandra-tarkowska we don't - Vagrant packages its own openssl, curl, and a bunch of other libraries with it's package. But I think your local system is still preferring the wrong version for some reason. I don't quite understand why, but I think this is a local environment issue. I am unable to reproduce the issue (even with homebrew's openssl). Is there any additional information you can share to help diagnose this?

**Comment by aleksandra-tarkowska** [comment] 2015-11-16 18:58
I am afraid I don't know what else I could check.

**Comment by sethvargo** [comment] 2015-11-16 19:00
Hi @aleksandra-tarkowska 

Can you please try the following:

1. Completely uninstall vagrant: https://docs.vagrantup.com/v2/installation/uninstallation.html
2. Make sure there's nothing in `/opt/vagrant` and `$HOME/vagrant.d`
3. Re-install vagrant 1.7.4 from the official installer

I suspect there's something strange with the homebrew version that might have persisted even after uninstall

**Comment by aleksandra-tarkowska** [comment] 2015-11-16 19:27
I am afraid I tried that:
```
$ /Volumes/Vagrant/uninstall.tool ; exit;
The following files and directories will be removed:
    /opt/vagrant
    /usr/local/bin/vagrant
Do you wish to uninstall Vagrant (Yes/No)?
Yes
The uninstallation process requires administrative privileges
because some of the installed files cannot be removed by a
normal user. You may now be prompted for a password...
Successfully uninstalled Vagrant.
Done.
```
then:
```
$ ls /Applications/Vagrant
ls: /Applications/Vagrant: No such file or directory
$ ls /usr/bin/vagrant
ls: /usr/bin/vagrant: No such file or directory
$ sudo pkgutil --forget com.vagrant.vagrant
Forgot package 'com.vagrant.vagrant' on '/'.
$ ls /opt/vagrant/
ls: /opt/vagrant/: No such file or directory
$ rm -rf .vagrant.d/
```
reinstalled the same error. I presume you are right there must be something on my local paths. I installed vagrant as fresh new user. All works. It is really hard to guess.

**Comment by sethvargo** [comment] 2015-11-16 19:32
Hi @aleksandra-tarkowska 

> I installed vagrant as fresh new user.

You mean you created another user on the same machine and it's working fine?

That certainly is a bit strange. Unfortunately I do not think this is a bug in Vagrant, but rather a local environment issue.

I am going to go ahead and close this issue for triage purposes, but if you find something that we could do in Vagrant to make this better, please do let me know!

**Closed by sethvargo** 2015-11-16 19:32 UTC
