### ISSUE TITLE
Setting to always start a VM

### ISSUE THREAD

**Issue by ryanneufeld** [mitchellh/vagrant#5554] opened 2015-04-02 21:21 UTC
I have a use case where I have one specific VM that needs to be always uped before any other box can start. This box is cf-engine policy hub (due to our configuration using the provisioner won't work for us).

As a result, it would be handy to designate one or more vms as 'always_start' so no matter what you `vagrant up` they start as well. The 'autostart' is handy, but still requires a separate 'up' command to be executed.

**Comment by sethvargo** [comment] 2016-05-30 20:20
Hi there,

I am going to close this as a duplicate of https://github.com/mitchellh/vagrant/issues/4026, which discusses the much broader topic of "vm dependencies". Thanks! 😄

**Closed by sethvargo** 2016-05-30 20:20 UTC
Labels: thinking
