### ISSUE TITLE
"timeout during server version negotiating" during vagrant up

### ISSUE THREAD

**Issue by dictcp** [mitchellh/vagrant#7013] opened 2016-02-11 04:25 UTC
got error when `vagrant up`

```
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::NetSSHException: An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout during server version negotiating>
ERROR vagrant: An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout during server version negotiating
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:429:in `rescue in connect'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:349:in `connect'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:628:in `scp_connect'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:265:in `upload'
```

**Comment by dictcp** [comment] 2016-02-11 04:26
the following PR fix this issue for myself
https://github.com/mitchellh/vagrant/pull/7014

**Comment by chrisroberts** [comment] 2016-10-03 17:17
Closing as PR fixing this issue has been merged.

**Closed by chrisroberts** 2016-10-03 17:17 UTC
Labels: core, enhancement, has-pr

**Comment by PMunch** [comment] 2018-01-10 09:02
@chrisroberts, that PR was closed, not merged.. I'm still experiencing this error, although I'm not sure it's caused by just a bad timeout.
