### ISSUE TITLE
vagrant up fails after aborted download

### ISSUE THREAD

**Issue by shaicoleman** [mitchellh/vagrant#4479] opened 2014-09-08 22:11 UTC
If a download is interrupted during "vagrant up", and the server doesn't support HTTP byte ranges, subsequent invocations of vagrant up will return the curl error "HTTP server doesn't seem to support byte ranges. Cannot resume.", exception: Vagrant::Errors::DownloaderError

Expected behavior:
If the server does not support byte ranges, the incomplete file should be deleted and retried.

Vagrant 1.6.5
Ubuntu 14.04 LTS
curl 7.35.0

**Comment by cgood92** [comment] 2015-01-14 00:41
All you need to do is simply delete the temporary download file, which is located (in the Windows world) at: C:\Users\<<username>>\.vagrant.d\tmp\*
After you delete it, you can re-run vagrant up and everything should work fine.

**Comment by anandjainjk** [comment] 2015-01-17 00:17
That worked for me. Thanks

**Comment by sergiotapia** [comment] 2015-02-05 14:25
Still an issue for me.

* Vagrant 1.7.2
* Mac OSX Yosemite

---

The download timed out, and then when I ran the `vagrant up` command again to download it says: 

> HTTP server doesn't seem to support byte ranges. Cannot resume

I think Vagrant should be smart enough to toss the tmp data for that image, if the response server does not support byte ranges. Thanks!

**Comment by atommyb** [comment] 2015-03-18 16:42
For any Mac users: 
Remove `~/.vagrant.d/tmp/' directory. 
Then try 'vagrant up' again.

**Comment by Dlimaun** [comment] 2015-03-21 03:14
This keeps ocurring. 
On linux we must remove files using that command 
`rm ~/.vagrant.d/tmp/*`.

**Comment by vtool** [comment] 2015-03-21 03:14
I will be out of the office on March 23 an 24.

Please contact Simi Dhillon simi@toolofna.com or Chris Kaliszewski chris@toolofna.com for your respective job.

Best,
Vincent V. Toscano

**Comment by levlaz** [comment] 2015-06-16 04:07
This is still an issue for me on Debian Testing (Stretch) with the latest Vagrant package installed 1.7.2+dfsg-4, removing from .vagrant.d/tmp resolves the issue for me.

**Comment by brendantwhite** [comment] 2015-06-25 09:22
Same problem, same fix, when Updating 'laravel/homestead' with provider 'virtualbox' from version '0.2.6' to '0.2.7' under Yosemite 10.10.3.

**Comment by mitulgolakiya** [comment] 2015-07-03 06:24
getting same problem with 'laravel/homestead' virtualbox for version 0.2.7 with Yosemite 10.10.4.

**Comment by brendantwhite** [comment] 2015-07-03 06:37
@mitulgolakiya did you try `rm ~/.vagrant.d/tmp/*` and then `vagrant up` again? That fixed it for me when I had this issue.

**Comment by kazemisoroush** [comment] 2015-07-06 13:02
👍 +1

**Comment by cesarcruzc** [comment] 2015-07-15 22:06
Thanks!

**Comment by timozattol** [comment] 2015-07-16 20:46
Happened to me after "ctrl+c"ing the process during a vagrant box update, since it was taking too long for my connection. Removing all temp files in vagrant.d resolved the problem :+1: 
Thanks!

**Comment by Createstandard** [comment] 2015-07-23 14:31
+1

**Comment by danieljimenez** [comment] 2015-07-23 21:40
+1 👍

**Comment by Achimh3011** [comment] 2015-07-26 19:09
Still a problem, workaround works:
````
> rpm -qi vagrant
Name        : vagrant
Epoch       : 1
Version     : 1.7.4
Release     : 1
Architecture: x86_64
Install Date: So 26 Jul 2015 21:00:07 CEST
Group       : default
Size        : 187219096
License     : MIT
Signature   : (none)
Source RPM  : vagrant-1.7.4-1.src.rpm
Build Date  : Sa 18 Jul 2015 02:42:43 CEST
Build Host  : vagrant-package-centos-64
Relocations : / 
Packager    : HashiCorp <support@hashicorp.com>
Vendor      : root@vagrant-package-centos-64
URL         : https://www.vagrantup.com
Summary     : Vagrant is a tool for building and distributing development environments.
Description :
Vagrant is a tool for building and distributing development environments.
Distribution: (none)
````

on openSUSE 13.2 x64

**Comment by gerob** [comment] 2015-08-01 22:01
Like @mitulgolakiya I get this with 'laravel/homestead' version 0.2.7 with Yosemite 10.10.4.

**Comment by tashinyima** [comment] 2015-08-04 07:21
worked for me after deleting the files in C:\Users\your user name \.vagrant.d\tmp\
i m using window...  :-)

**Comment by cooper-22** [comment] 2015-08-10 12:13
I'm also having this problem.
@tashinyima thanks for the Windows path.

**Comment by joshbrw** [comment] 2015-08-17 19:18
+1

**Comment by dx9** [comment] 2015-08-20 02:10
+1

**Comment by ArwedSchmidt** [comment] 2015-09-12 13:16
+1 (OS X 10.10, resuming partial download fails, clearing ~/.vagrant.d/tmp/ helped)

**Comment by pablobablo** [comment] 2015-09-13 21:00
jschiessl thanks!

**Comment by umbarger** [comment] 2015-09-16 15:31
+1  Win 7 - Workaround `del C:/Users/<username>/.vagrant.d/tmp/` worked.
```
C:\>vagrant version
Installed Version: 1.7.4
```

**Comment by beedaan** [comment] 2015-09-25 19:30
+1

**Comment by seyfer** [comment] 2015-09-29 05:34
+1

**Comment by Achimh3011** [comment] 2015-09-29 05:41
I guess the fact is now well established for all major platforms and does not need further plussing...

**Comment by flycoop** [comment] 2015-10-01 13:16
Awesome, many thanks!

**Comment by pliniotheodoro** [comment] 2015-10-11 03:52
Delete .vangran.d/tmp/* works for me! Thank you friend :+1:

**Comment by iamvitali** [comment] 2015-10-13 21:57
Just happened to me on the OS X 10.11.

Deleting the file from home/%username%/.vagrant.d/tmp/ did the trick!

**Comment by ascsoftware** [comment] 2015-10-21 10:40
On Ubuntu 12.04 check for tmp files with: ls -al ~/.vagrant.d/tmp/
Then delete the image rm -rf .vagrant.d/tmp/boxf6d5788a461c7fff8e60ab85ed9732f64a77fa0f
And restart download process with vagrant up.
Worked on vagrant 1.7.3 and Virtualbox 5.0

**Comment by tedstein** [comment] 2015-10-29 02:01
+1

**Comment by RossBarnie** [comment] 2015-10-29 11:54
+1 Vagrant 1.7.4, OS X 10.10, deleting the tmp box "fixed" the issue but given the number of plusses above since the issue was closed it should perhaps be re-opened.

**Comment by robmarano** [comment] 2015-10-30 16:30
+1 on deleting tmp files on mac. Find it in /Users/$USER/.vagrant.d/tmp. Thanks!

**Comment by ericrini** [comment] 2015-11-02 19:53
This doesn't seem to be fixed.

**Comment by kentaguilar** [comment] 2015-11-03 13:43
Still occurs on my end on OSX. Ran the following code.

rm ~/.vagrant.d/tmp/*
Then run the vagrant command again.

**Comment by livemixlove** [comment] 2015-11-04 21:58
+1

**Comment by bijanvakili** [comment] 2015-11-06 01:31
+1

**Comment by anthonygreen** [comment] 2015-11-06 08:06
"Still occurs on my end on OSX."
+ 1

**Comment by Gandem** [comment] 2015-11-07 10:48
Delete .vangran.d/tmp/* worked for me. The error still occurs on Windows 10

**Comment by JBusch** [comment] 2015-11-09 12:17
+1 on Windows 10

**Comment by chrisgame** [comment] 2015-11-11 17:45
Have you guys tried `vagrant box add <box name> --clean`. The fix would be better but at least this way you don't have to go digging around for files.

**Comment by nprokopic** [comment] 2015-11-11 20:05
+1 Vagrant 1.7.4, OS X 10.10.4

**Comment by davidyell** [comment] 2015-11-12 12:22
I just found this issue by googling for the error. I can see I'm not alone. I'm using `1.7.4` on OSX.

**Comment by olleman42** [comment] 2015-11-12 14:18
+1 OS X 10.10.2

**Comment by ludo237** [comment] 2015-11-16 11:16
+1 the patch works for OSX `10.11.2 Beta (15C40a)` with Vagrant `1.7.4`

**Comment by pfuhrmann** [comment] 2015-11-16 23:15
Same issue with the `1.7.4` on `Linux Mint 17.2`

**Comment by mitchellh** [comment] 2015-11-20 00:11
Reproduced, taking a look.

**Comment by VincentVToscano** [comment] 2015-11-20 00:12
I’m out of the office until November 24.

Please contact the appropriate producer regarding your job.

Job#1 - *bar
Tara Conlin: tara.conlin@toolofna.com

Job#2 - IDR2
Chris Kaliszewski: chris@toolofna.com

Best,
Vincent

**Comment by mitchellh** [comment] 2015-11-20 00:14
Fixed

**Closed by mitchellh** 2015-11-20 00:14 UTC
Labels: bug, core

**Comment by davidrichied** [comment] 2015-11-26 03:19
Same issue on Mac OSX 10.9. Deleting the files in .vagrant.d/tmp/ fixed the issue.

**Comment by gonciarz** [comment] 2015-12-03 00:16
+1

**Comment by pfuhrmann** [comment] 2015-12-03 00:20
@davidrichied @gonciarz do you have 1.8 version because this is scheduled for that release I believe.

**Comment by davidrichied** [comment] 2015-12-03 01:02
@pfuhrmann I do not believe I do. I downloaded Vagrant, version 1.7.4, from https://www.vagrantup.com/downloads.html

**Comment by omurphy27** [comment] 2016-01-07 10:18
+1

This just happened to me and I solved it by doing `rm ~/.vagrant.d/tmp/*`

On `Mac OS X El Capitan 10.11.2 (15C50)` and `Vagrant 1.7.4`

**Comment by nirajbothra** [comment] 2016-02-01 09:25
+1

**Comment by RossBarnie** [comment] 2016-02-01 09:59
@nirajbothra This has been fixed in Vagrant 1.8.1, you should upgrade to resolve the problem.

**Comment by juanjoc333** [comment] 2016-02-22 14:18
+1

**Comment by VincentVToscano** [comment] 2016-02-22 14:18
Hi,

I am currently at an offsite meeting and will be checking my e-mail periodically. 

For scheduling, inquiries, and emergencies, please reach out to Jean Chang at jean@toolofna.com or at (310) 453-9244.

Thank you!

**Comment by fujiiface** [comment] 2016-03-07 17:55
This just happened for me on Windows using 1.7.4.  [cgood92's comment](https://github.com/mitchellh/vagrant/issues/4479#issuecomment-69850252) worked for me.

**Comment by joshmccall221** [comment] 2016-04-07 16:54
:+1:

**Comment by VincentVToscano** [comment] 2016-04-07 16:55
Hello,

I am currently out of the office from 04/02 - 04/11.

If you are contacting me about a new project, please reach out to either Chris Neff (chris.neff@toolofna.com) or Adam Baskin (adam.baskin@toolofna.com) in my absence.

For scheduling, inquiries, and emergencies, please reach out to Jean Chang (jean@toolofna.com) or call (310) 453-9244.

Thank you!


Dustin Callif
