### ISSUE TITLE
change file permesions

### ISSUE THREAD

**Issue by CodeCare** [mitchellh/vagrant#7555] opened 2016-07-08 11:01 UTC
Hello,
I'm working on a project with Ansible and Vagrant together.
I have a problem! the problem message is:
"ERROR! Problem running vault password script / v a g r a n t / p r o v i s i o n i n g / c o d e c a r e . k e y ([Errno 8] Exec format error). If this is not a script, remove the
executable bit from the file. "
I cann't modify the permesion as executable file with the comand chmod.
I tried with different ways to modify that but I couldn't.
maybe because of vboxsf.
thank you
I am waiting for your Answer.

**Comment by sethvargo** [comment] 2016-07-08 14:11
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by 123iq** [comment] 2016-07-21 22:28
Sex

**Closed** 2016-07-21 22:39 UTC
Labels: waiting-reply

**Comment by 123iq** [comment] 2016-07-21 22:41
#7555

**Comment by sethvargo** [comment] 2016-07-21 22:59
Hi there,

There is still not enough information to diagnose this issue. Do you have a Vagrantfile or debug output to share?

**Comment by 123iq** [comment] 2016-07-21 23:02
#7555

**Comment by 123iq** [comment] 2016-07-21 23:03
Hi

**Comment by sethvargo** [comment] 2016-07-21 23:09
Okay, I'm going to close this because of failure to provide adequate information. If this is still occurring, please open a new issue and supply the information in the template that pops up. Thanks! 😄
