### ISSUE TITLE
Composer freezes vagrant machine with installed 1.8.5.

### ISSUE THREAD

**Issue by bitfroster** [mitchellh/vagrant#7799] opened 2016-09-15 08:59 UTC
Vagrant machine with usage of the latest version (1.8.5) freezes during `composer install` and `composer update`. I've downgraded version to 1.8.4 and everything works fine.
### Vagrant version

1.8.5
### Host operating system

OSX 10.11.6
### Guest operating system

Debian 8
### Virtualbox version

5.0.26 
### Expected behavior

`composer install` and `composer update` should work
### Actual behavior

`composer install` and `composer update` commands are freezing during execution

**Comment by chrisroberts** [comment] 2016-09-16 18:00
Hi. Thanks for opening an issue, but some more information is required to be able to reproduce the error you are describing. Please include the Vagrantfile that you are using, and anything being done to the guest instance to configure it before running the command that hang. Thanks!

**Comment by bitfroster** [comment] 2016-09-19 15:42
Hi Chris.

Thank you for a response! Below my Vagrantfile. 

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "jessie64"

  config.vm.hostname = "api"

  config.vm.network :private_network, ip: "10.0.8.78"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 35729, host: 35729

  config.ssh.forward_agent = true

  config.vm.synced_folder "../api", "/home/vagrant/api", mount_options: ['rw', 'vers=3', 'fsc' ,'actimeo=2', 'async'], nfs: true
  config.vm.synced_folder "../frontend", "/home/vagrant/frontend", mount_options: ['rw', 'vers=3', 'fsc' ,'actimeo=2', 'async'], nfs: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider :virtualbox do |vb|
    # Use VBoxManage to customize the VM. For example to change memory:
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
        vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
        vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
        vb.name = "edited-api"
  end

  config.vm.provision :ansible do |ansible|
      ansible.playbook = "seenex.yml"
      ansible.verbose = "v"
      ansible.inventory_path = "development"
      ansible.limit = "all"
  end

end
```

Also I used different configurations for composer. With the same configuration it works good in Vagrant v1.8.4.

**Comment by mpragliola** [comment] 2016-09-21 07:31
I had the same problem with Vagrant 1.8.5 and VBox 5.1, had to downgrade all because composer is freezing.

**Comment by bitfroster** [comment] 2016-10-25 09:54
@chrisroberts I've updated Vagrant to version 1.8.6 and I can't reproduce this issue anymore. @mpragliola could you try with 1.8.6 please?

**Comment by bitfroster** [comment] 2016-10-25 09:56
I thought that the issue was resolved with 1.8.6, but its not. I'm going to create a configuration to reproduce it.

**Comment by chrisroberts** [comment] 2017-03-02 16:42
Hi there. If this is still an issue please provide me a simple Vagrantfile with instructions to reproduce using the latest Vagrant release. I'm going to be working through a large number of NFS related issues so if this is still a problem I would like to make sure it's addressed. Thanks!

**Comment by bitfroster** [comment] 2017-03-06 08:19
Hi Chris,

I'll try to provide Vagrantfile today. Thank you!

**Comment by briancain** [comment] 2017-07-17 23:01
Hey @bitfroster ,

After doing some investigation, it looks like the issue here is that NFS over UDP (which is vagrants default configuration for NFS) just cannot handle the amount of information attempting to be transferred and the guest ends up timing out when trying to talk to the NFS server during the `composer install`. I was getting a time out error in the guests syslog when attempting to run a `composer install`. I found a previous `composer` issue that seems to match the description of this issue, https://github.com/composer/composer/issues/1787. Not only that, but it looks like the `nfs_udp` option was introduced because of a similar issue. There's some good discussion as to why UDP times out https://github.com/mitchellh/vagrant/issues/2304. 

I recommend just using `:nfs_udp: false` when syncing your folder to store composer vendor libraries. When doing so, it worked just fine for me without any timeouts. You can just append this option to your existing `synced_folder` config options.

```ruby
# vagrantfile stuff....
config.vm.synced_folder "../api", "/home/vagrant/api", mount_options: ['rw', 'vers=3', 'fsc' ,'actimeo=2', 'async'], nfs: true, nfs_udp: false
config.vm.synced_folder "../frontend", "/home/vagrant/frontend", mount_options: ['rw', 'vers=3', 'fsc' ,'actimeo=2', 'async'], nfs: true, nfs_udp: false
# more vagrantfile stuff...
```

I hope this helps, thank you for reporting the issue!

**Closed by briancain** 2017-07-17 23:01 UTC
Labels: guest/debian, needs-repro, synced-folders/nfs, waiting-reply

**Comment by jelrikvh** [comment] 2018-11-21 14:36
Not trying to be a necromancer for this issue, but I wanted to thank @briancain for his research and wanted to let people know this is still a viable workaround. Switching to TCP for the write-heavy operations made sure I could get my vagrant machine up and running, instead of it freezing and doing nothing.
