### ISSUE TITLE
'chef_install' capability  not working and aws windows

### ISSUE THREAD

**Issue by psimonovsk** [mitchellh/vagrant#6417] opened 2015-10-20 09:11 UTC
Hi.
I have quite simple Vagrantfile, that actually do almost nothing - but run chef-solo test recipe.
Provider is aws. Those vagrant job have to launch aws windows machine 9from standard aws win2012 ami) and run chef-solo recipe that actually creates file. That is all
Vagrant file:

```ruby
require File.expand_path('aws\\aws_credentials.rb')

Vagrant.configure("2") do |config|
	config.vm.guest = :windows
	config.vm.communicator = :winrm
	config.vm.synced_folder ".", "/vagrant", type: "winrm", :disabled => true
	config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
	config.vm.box = "dummy"
	# Admin user name and password
    config.winrm.username = "vagrant"
    config.winrm.password = "Pass@123" 
	#config.winrm.password = "vagrant" 
 	config.nfs.functional = false
	
	
	config.vm.provider :aws do |aws, override|
		aws.user_data = File.read("aws\\Setup.txt")
		aws.tags = {
		  'Name' => @aws_machine_name,
		}
		aws.access_key_id=@access_key_id
		aws.secret_access_key=@secret_access_key
		aws.keypair_name=@keypair_name
		aws.ami=@ami
		aws.region=@region
		aws.instance_type=@instance_type
		aws.security_groups= [ @security_groups ]
	end
	
	config.vm.provision :chef_solo do |chef| 
		chef.synced_folder_type = "winrm" 
		chef.add_recipe("Control-M::touch_file")
		#chef.add_recipe("vim-windows")
	end	
end
```

What I get is:

```
==> default: Running provisioner: chef_solo...
    default: Installing Chef (latest)...
Vagrant attempted to execute the capability 'chef_install'
on the detect guest OS 'windows', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
```

That means - when creating windows aws machine, internal vagrant function "chef_install" do not work...
I have to mention - exactly same Vagrantfile but launching aws redhat image (after appropriate fix of file pathes syntax to UNIX convention - works like a charm... Installs chef client and runs cookbook with no any problems...

**Comment by sethvargo** [comment] 2015-11-08 02:37
Duplicate of https://github.com/mitchellh/vagrant/issues/6306

**Closed by sethvargo** 2015-11-08 02:37 UTC
