### ISSUE TITLE
Vagrant 1.8.6 hung at Configuring and enabling network interfaces

### ISSUE THREAD

**Issue by f-w** [mitchellh/vagrant#7909] opened 2016-10-18 20:54 UTC
Vagrant 1.8.6 appears to be incompatible with 1.8.1. The following commands work in 1.8.1 but hung in 1.8.6. All other software in the stack remains unchanged.

```
vagrant init openshift/origin-all-in-one
vagrant up
```
### Vagrant version

1.8.6
### Host operating system

Windows 10/7
### Guest operating system

Linux
### Vagrantfile

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "openshift/origin-all-in-one"

end

```
### Expected behavior

`vagrant up` should not hung
### Actual behavior

hung in the last output

```
x@laptop MINGW64 ~/vagrants/os
$ vagrant up --provider=virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'openshift/origin-all-in-one'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'openshift/origin-all-in-one' is up to date...
==> default: Setting the name of the VM: openshift-origin
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 8443 (guest) => 8443 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default:
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Configuring and enabling network interfaces...

```

**Comment by madoke** [comment] 2016-10-26 15:02
able to reproduce this issue using vagrant 1.8.6, on a mac osx el capitan host/centos7 guest

**Comment by bezhermoso** [comment] 2016-10-26 21:54
I had this, but upgrading to `1.8.7.dev` (https://www.vagrantup.com/docs/installation/source.html) fixed it for me.

**Comment by chrisroberts** [comment] 2016-12-09 15:56
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Closed by chrisroberts** 2016-12-09 15:56 UTC
