### ISSUE TITLE
Commands using machine ID fail

### ISSUE THREAD

**Issue by noplanman** [mitchellh/vagrant#6834] opened 2016-01-09 00:04 UTC
Since I updated to Vagrant 1.8.1, using the machine ID with Vagrant commands has stopped working properly.
It seems as if the `vagrant` command gets executed twice.

If I start up the machine from the project directory with `vagrant up`, it starts up perfectly and `vagrant halt` shuts it down properly.

Yet if I use the same commands using the machine ID from `vagrant global-status`, I get an error.

`vagrant up 1a2b3c4d` now gives me:
```
Vagrant can't use the requested machine because it is locked! This
means that another Vagrant process is currently reading or modifying
the machine. Please wait for that Vagrant process to end and try
again. Details about the machine are shown below:

Name: default
Provider: virtualbox
```

and `vagrant halt 1a2b3c4d` gives me:
```
/project-dir/Vagrantfile:50: warning: already initialized constant CONF
/project-dir/Vagrantfile:50: warning: previous definition of CONF was here
```

The last version I was using was 1.7.4, where it worked perfectly.

**Comment by kamigerami** [comment] 2016-01-21 00:45
Initially it looks like it will hold a lock to the index so it can be read/updated
 then it reloads the data (does not lock the index since it is already locked from outside of the call)
 then locking the machine exclusively and never releasing the entry (unlocking it).

so if the entry is released by running the unlocked_release method everything works fine.

Will investigate further during the weekend. 

@sethvargo  initial thoughts?

**Comment by noplanman** [comment] 2016-01-23 02:24
@kamigerami Any news on this? Is this a general problem or just some configuration issue?
Thanks for checking it out :blush:

**Comment by kamigerami** [comment] 2016-01-23 23:44
looks general to me! I'll update when I have something useful.

**Comment by tdebatty** [comment] 2016-02-20 16:43
+1
`vagrant halt, suspend and resume <id>` are working properly
`cd <directory> && vagrant up` works too
`but vagrant up <id>` gives
`Vagrant can't use the requested machine because it is locked!`

**Comment by kamigerami** [comment] 2016-02-25 14:28
@tdebatty you are right! Did not notice that the first time around! I have a new fix for it! Will update soon

**Comment by kamigerami** [comment] 2016-02-26 23:48
I am running Version: 1.8.2.dev and all these commands (halt, suspend, up and resume) are working fine for me with the machine id.

Please confirm this on your end as well @noplanman @tdebatty so we can close this ticket.

**Comment by noplanman** [comment] 2016-02-26 23:51
Where can I get 1.8.2.dev from? Do I need to build from source or is there an installer around?
Thanks for your efforts on fixing this :+1:

**Comment by kamigerami** [comment] 2016-02-26 23:53
pull the master branch

**Comment by noplanman** [comment] 2016-02-27 00:26
Ok, with 1.8.2.dev it's a lot better, nothing fails, just some warnings.
*(the CONF constant is an example, in other Vangrantfiles it could be something else)*

**up**
I do still get a warning when using `vagrant up [id]`:
```
/project-dir/Vagrantfile:50: warning: already initialized constant CONF
/project-dir/Vagrantfile:50: warning: previous definition of CONF was here
```

**reload**
When I use `vagrant reload [id]` on a halted machine, no warning pops up. Using `vagrant up [id]` on a started machine displays the warning again.

**global-status**, **status**
With the command `vagrant global-status --prune`, I get alternating warnings for all my machines:
```
/project-dir-1/Vagrantfile:50: warning: already initialized constant CONF
/project-dir-2/Vagrantfile:50: warning: previous definition of CONF was here
/project-dir-3/Vagrantfile:50: warning: already initialized constant CONF
/project-dir-4/Vagrantfile:50: warning: previous definition of CONF was here
```
Without `--prune` I get no warnings.
Just `vagrant status [id]` gives me the same warnings as `vagrant up [id]`.

**resume**
Resuming a suspended machine runs a provision, is this normal?!

**suspend**, **ssh**
Works :+1: 

The other commands I haven't really used so I haven't tested them.

**Comment by kamigerami** [comment] 2016-02-27 00:29
@noplanman  thanks for testing this out! The warnings you are getting are most likely related to your Vagrantfile and not Vagrant.

try the same thing with a default Vagrantfile (vagrant init) and It most likely won't show you the warnings again.

**Comment by noplanman** [comment] 2016-02-27 00:35
You're right, but the default Vagrantfile has no constants defined, so of course it wouldn't happen.

Regarding the warnings I'm getting (on different Vagrantfiles and projects) they indicate that the file is being loaded twice, issuing the warning that the constant is already loaded.

Does this make sense?

**Comment by kamigerami** [comment] 2016-02-27 00:38
sure does :) It would help if you paste your Vagrantfile as well :)

**Comment by noplanman** [comment] 2016-02-27 00:44
Here is the one from the [ZeroNet](https://github.com/HelloZeroNet/ZeroNet/blob/master/Vagrantfile) project, the warning here pops up for `VAGRANTFILE_API_VERSION`:
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  #Set box
  config.vm.box = "ubuntu/trusty64"

  #Do not check fo updates
  config.vm.box_check_update = false

  #Add private network
  config.vm.network "private_network", type: "dhcp"

  #Redirect ports
  config.vm.network "forwarded_port", guest: 43110, host: 43110
  config.vm.network "forwarded_port", guest: 15441, host: 15441

  #Sync folder using NFS if not windows
  config.vm.synced_folder ".", "/vagrant",
      :nfs => !Vagrant::Util::Platform.windows?

  #Virtal Box settings
  config.vm.provider "virtualbox" do |vb|
    # Don't boot with headless mode
    #vb.gui = true

    # Set VM settings
    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ["modifyvm", :id, "--cpus", 1]
  end

  #Update system
  config.vm.provision "shell",
      inline: "sudo apt-get update -y && sudo apt-get upgrade -y"

  #Install deps
  config.vm.provision "shell",
      inline: "sudo apt-get install msgpack-python python-gevent python-pip python-dev -y"
  config.vm.provision "shell",
      inline: "sudo pip install msgpack-python --upgrade"

end
```

**Comment by kamigerami** [comment] 2016-02-27 02:41
Ok thanks! I was able to confirm that.

I noticed that you have multiple project dirs

have a look here https://github.com/mitchellh/vagrant/issues/5253


A few thoughts thought.

What happens when you run

`vagrant` global-status --prune` ? Will you still have the "constant" issues with the commands?


`VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|`

can just be changed to 
`Vagrant.configure(2) do |config|`

or if you want to use constans you could do

`VAGRANTFILE_API_VERSION ||= "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|`

which will help as well.

**Comment by noplanman** [comment] 2016-02-27 08:28
Regarding the project directories, you're right, the warnings that pop up when running `vagrant global-status --prune` come from projects which use the same Vagrantfile, so it kind of makes sense that it thinks the constants are defined already. Yet, the warnings state that the duplicate it finds is "the same" one, not the one from the other project folder. So there is still a bug in there somewhere.

Since these are projects that I don't maintain, changing the Vagrantfile is not so desirable as you can imagine.

Running `vagrant global-status --prune` changes nothing, warnings still pop up.

Reading through [this comment](https://github.com/mitchellh/vagrant/issues/5253#issuecomment-130024764) got me wondering if that could solve the problem.
How would I identify a corrupted vagrant box?

**Comment by kamigerami** [comment] 2016-02-27 09:57
If your box is starting up properly and working fine (apart from the warning messages) I doubt the actual box is corrupted. maybe @sethvargo can give his opinion as well :)

**Comment by noplanman** [comment] 2016-02-27 10:18
Ok.
For me, if the boxes start up properly and the only "problem" is the warnings and not an exception, that's fine by me for my use cases.
If the warnings do indicate some bug somewhere, having it fixed is obviously better.

Looking forward to 1.8.2, thanks again! :tada:

**Comment by sethvargo** [comment] 2016-06-01 01:44
Hi all,

I just checked and this appears to be working on master now. Sorry about the regression. Machine IDs as values will work in the next release of Vagrant again!

**Closed by sethvargo** 2016-06-01 01:44 UTC
Labels: bug, core, has-pr
