### ISSUE TITLE
Error when running vagrant up for the base box

### ISSUE THREAD

**Issue by behrangsa** [mitchellh/vagrant#7261] opened 2016-04-26 02:01 UTC
Vagrant version: `1.8.1`
VirtualBox version: `5.0.18 r106667`
Ruby versions tried: `2.2`, `2.1`, and `1.9.3`.

Error:

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
/opt/vagrant/embedded/lib/ruby/2.2.0/uri/rfc3986_parser.rb:66:in `split': bad URI(is not URI?): file:///Users/foo.bar/Vagrant/My Deployer/base (URI::InvalidURIError)
    from /opt/vagrant/embedded/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
    from /opt/vagrant/embedded/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/box_add.rb:467:in `metadata_url?'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/box_add.rb:77:in `block in call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/box_add.rb:75:in `map'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/box_add.rb:75:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/handle_box.rb:82:in `handle_box'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/handle_box.rb:42:in `block in call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/handle_box.rb:36:in `synchronize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/handle_box.rb:36:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:224:in `action_raw'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:199:in `block in action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/batch_action.rb:82:in `bloc
```

**Comment by sethvargo** [comment] 2016-04-26 06:45
Hi @behrangsa 

Thank you for opening an issue. In the future, please complete the [full issue template](https://raw.githubusercontent.com/mitchellh/vagrant/master/.github/ISSUE_TEMPLATE.md) that appears when opening a new issue.

- The locally installed version of Ruby is irrelevant to Vagrant, since Vagrant bundles it's own Ruby environment independent on the system version.
- Could you please share your complete Vagrantfile?

I do not think this is a bug in Vagrant. The URL you've provided is not a valid URI:

```
[1] pry(main)> require "uri"
=> true
[2] pry(main)> URI.parse("file:///Users/foo.bar/Vagrant/My Deployer/base")
URI::InvalidURIError: bad URI(is not URI?): file:///Users/foo.bar/Vagrant/My Deployer/base
from /Users/sethvargo/.rubies/ruby-2.1.6/lib/ruby/2.1.0/uri/common.rb:176:in `split'
```

Notice this is just a regular irb session with Ruby, no Vagrant. I believe the issue is due to the space in your URI. If you replace the space with the URI encoded value (%20), the parsing works:

```
[3] pry(main)> URI.parse("file:///Users/foo.bar/Vagrant/My%20Deployer/base")
=> #<URI::Generic:0x007fd893827710 URL:file:/Users/foo.bar/Vagrant/My%20Deployer/base>
```

It is the user's responsibility to properly URL-encode the box URL, since it's not safe for Vagrant to just encode for you (since it can change the URL's format). Does that make sense?

**Comment by behrangsa** [comment] 2016-04-28 06:20
The box name is just `base`:

This is where I run `vagrant init`:

{code}
$ pwd
/Users/behrang.saeedzadeh/Vagrant/Foo Bar
{code}

And this is the generated `Vagrantfile`:

{code}
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "base"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
end
{code}

So as far as I can see, it's Vagrant that creates the URI and it doesn't encode it properly.

Cheers,
Behrang

**Comment by sethvargo** [comment] 2016-04-28 06:22
Hi @behrangsa 

Do you have a box named "base" installed? What is the output of `vagrant box list`?

**Comment by behrangsa** [comment] 2016-04-28 06:29
No,

```
boxcutter/ubuntu1510 (virtualbox, 2.0.16)
centos/7             (virtualbox, 1603.01)
ubuntu/trusty64      (virtualbox, 20160406.0.0)
```

My only suspicion is that Docker creates a VM named `default`:

![screen shot 2016-04-28 at 4 26 18 pm](https://cloud.githubusercontent.com/assets/18451/14877147/1b173c02-0d5e-11e6-9643-a2fd6d52501a.png)

And when you run `vagrant up`, it shows this message:

```
$ vagrant up
Bringing machine **'default'** up with 'virtualbox' provider...
...
```

**Comment by sethvargo** [comment] 2016-04-28 07:27
Hi @behrangsa 

The "default" is the name of the machine, not the name of the box. What is your end goal here?

**Comment by Daemoen** [comment] 2016-05-29 21:49
@behrangsa 
Given your vagrantfile, it would be nearly impossible for your vagrant up to succeed.

There is no source uri being provided for the base box to download (when it doesnt exist in the local storage, it will attempt to download 'base' from the specified location).

You have neither a base box in storage, nor a src uri for it in the Vagrantfile.

Additionally, there is no configuration being done of your machines, *everything* is commented out.  My assumption is that you copied a Vagrantfile believing that it was just 'good to go', but really, its not even a template vagrantfile, its just a Vagrantfile with everything commented out that you still need to configure yourself.

@sethvargo assuming no response from @behrangsa and the amount of time, might want to close this one out :)

**Comment by sethvargo** [comment] 2016-05-30 22:14
@gildegoma you can go ahead and close it out at your convenience.

**Comment by gildegoma** [comment] 2016-05-31 05:31
Hey @behrangsa 

> There is no source uri being provided for the base box to download (when it doesnt exist in the local storage, it will attempt to download 'base' from the specified location).

I am closing per @sethvargo and @Daemoen's comments above. Your `vagrant box list` showed no local `base` box, and the the expected behaviour is the following: 

```shell
⇒  vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'base' (v0) for provider: virtualbox
    default: Downloading: base
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
```

Somehow this (missing) `file:///Users/foo.bar/Vagrant/My Deployer/base` path (to a custom base box?) was configured in your original `Vagrantfile`.

**Closed by gildegoma** 2016-05-31 05:31 UTC
Labels: waiting-reply
