### ISSUE TITLE
GemfileNotFound error

### ISSUE THREAD

**Issue by fnordfish** [mitchellh/vagrant#7495] opened 2016-06-20 07:52 UTC
After upgrading to vagrant 1.8.4 (from 1.8.1) I'm not able to start/reload one of my vmware-fusion boxes.

It fails with a `Bundler::GemfileNotFound` error pointing to a temp `vagrant-gemfile` (which does not exist, but other probably older ones do. See comment on the linked gist).

I've tried to `rm -rf  ~/.vagrant.d/{gems,plugins.json}` and re-install vagrant and plugins, with no success.
### Vagrant version

Vagrant 1.8.4
### vagrant plugin list
- vagrant-auto_network (1.0.2)
- vagrant-bindfs (0.4.7)
- vagrant-cachier (1.2.1)
- vagrant-dns (1.0.0)
- vagrant-share (1.1.5, system)
- vagrant-triggers (0.5.3)
- vagrant-vmware-fusion (4.0.9)
### Host operating system

Max OS 10.11.5
### Guest operating system

"box-cutter/ubuntu1404-docker" v2.0.10
### Debug output

https://gist.github.com/fnordfish/5f57327659ce8b361f0917b00669ae91
### Expected behavior

Does not fail ;)
### Actual behavior

fails with error `/var/folders/xl/1qcjng6x11b0h2fbqsvxt5ym0000gn/T/vagrant-gemfile20160620-5534-1c1pwv5 not found (Bundler::GemfileNotFound)`
### Steps to reproduce

~~Unknown. For me it is:~~
- ~~start a vmware fusion box~~
- install vagrant-dns plugin (maybe any other plugin that has gem dependencies defined?)
- start the box
- `vagrant reload` the box

**Comment by fnordfish** [comment] 2016-06-20 08:32
Downgrading to vagrant v1.8.1 (and vagrant-vmware-fusion v4.0.8 b/c of #7381) works for me. 
I've also tested vagrant v1.8.4 and vagrant-vmware-fusion v4.0.8 with no success.

**Comment by sethvargo** [comment] 2016-06-20 20:10
Hi @fnordfish 

I tried a few different things, but I'm unable to reproduce this issue. Can you share more information about your environment? In particular, does this issue reproduce when you have no plugins installed?

**Comment by fnordfish** [comment] 2016-06-23 09:16
Hi,

no, without plugins and dead-simple Vagrantfile it works:

- `rm -fr  ~/.vagrant.d/{gems,plugins.json}`
- install Vagrant 1.8.4
- `vagrant plugin install vagrant-vmware-fusion --plugin-version 4.0.8`

Vagrantfile:
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "box-cutter/ubuntu1404-docker"
  config.vm.box_version = "2.0.10"
end
```

I'm now trying to install plugins one by one and see when the error re-accrues.

**Comment by fnordfish** [comment] 2016-06-23 14:03
I've tracked it down to the vagrant-dns plugin (ironically I'm a maintainer of it).
In my local plugin-dev environment (using VirtualBox), everything works like a charm. It fails as soon as it runs with the vmware_fusion provider.

Also it seems only be happening on `vagrant reload` (sorry, I really didn't notice before) - running `vagrant halt; vagrant up` also works.

The only thing that obviously distinguishes vagrant-dns from the other plugins I have installed is, that it has dependencies on other gems defined in the gemspec.

**Comment by sethvargo** [comment] 2016-06-23 17:38
Hi @fnordfish 

What does the gemspec look like? I'm willing to bet its a version conflict that's just bubbling up as a different error.

**Comment by fnordfish** [comment] 2016-06-23 17:47
Hi,

that's the current v1.0.0 one: https://github.com/BerlinVagrant/vagrant-dns/blob/master/vagrant-dns.gemspec
here is the one I've experimented with for a v1.0.1: https://github.com/BerlinVagrant/vagrant-dns/blob/fix/vagrant_1-8-4/vagrant-dns.gemspec

**Comment by sethvargo** [comment] 2016-06-23 17:54
Oh boy. You're gonna have problems already looking at that dependency tree 😦 . rubydns depends on celluloid 😫

**Comment by sethvargo** [comment] 2016-06-23 17:55
As a _guess_, I'm willing to bet that Vagrant's use of bundler isn't threadsafe, but that's also not a promise we've ever made. It might be more apparent in this new version of Bundler, but I don't think this is a "bug" per-sae.

**Comment by fnordfish** [comment] 2016-06-23 17:55
Yah, And even that pretty buggy 0.16 version. But hey, it worked so far.

**Comment by fnordfish** [comment] 2016-06-23 17:57
What makes me wonder is why it works on virtualbox (even with fusion plugin installed - probably not loaded) but breaks with fusion.

**Comment by sethvargo** [comment] 2016-06-23 17:59
Honestly... it could just be because vbox is slower

**Comment by fnordfish** [comment] 2016-06-23 18:19
Is there a way to get the bundle (like Gemfile.lock) a vagrant run uses? I would try to compare vagrant 1.8.1 vs. 1.8.4

**Comment by sethvargo** [comment] 2016-06-23 18:23
Not without hacking the source - it's a tempfile

**Comment by fnordfish** [comment] 2016-06-23 18:42
Maybe as a plugin?

--  
Robert Schulze

**Comment by sethvargo** [comment] 2016-06-27 14:39
@fnordfish 

You could jump into `/opt/vagrant/embedded` and throw some `puts` statements in the `lib/bundler.rb` file to print the lockfile.

**Comment by chrisroberts** [comment] 2016-12-09 14:42
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Closed by chrisroberts** 2016-12-09 14:42 UTC
Labels: waiting-reply
