### ISSUE TITLE
The option box_check_update is not working

### ISSUE THREAD

**Issue by iyouruby** [mitchellh/vagrant#7790] opened 2016-09-13 05:54 UTC
### Vagrant version
Vagrant 1.8.5

### Host operating system
Mac OS X El Capitan 10.11.6

### Guest operating system
ubuntu-14.04

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "sandbox"
  config.vm.box_check_update = false
end
```

### Output
```
default] No installation found.
stdin: is not a tty
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  debhelper
The following NEW packages will be installed:
  dkms
The following packages will be upgraded:
  linux-headers-3.13.0-24-generic
1 upgraded, 1 newly installed, 0 to remove and 151 not upgraded.
Need to get 772 kB of archives.
After this operation, 349 kB of additional disk space will be used.
Err http://archive.ubuntu.com/ubuntu/ trusty-updates/main dkms all 2.2.0.3-1.1ubuntu5.14.04.1
  404  Not Found [IP: 91.189.88.152 80]
```

**Comment by chrisroberts** [comment] 2016-10-04 17:13
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by chrisroberts** [comment] 2016-10-25 20:14
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2016-10-25 20:14 UTC
Labels: waiting-reply
