### ISSUE TITLE
Windows 7 guest, Virtualbox, Cygwin-ssh, unable to mount shared folder

### ISSUE THREAD

**Issue by NeroBurner** [mitchellh/vagrant#7200] opened 2016-04-04 12:55 UTC
Vagrant cannot mount virtualbox shared folder using a windows 7 guest connecting with ssh (from cygwin openSSH)

When using the cygwin bash (used when connecting with ssh) the command 

```
net use x: \\VBOXSVR\vagrant
```

the network share cannot be found.
The backslashes need to be escaped resulting in

```
net use x: '\\VBOXSVR\vagrant'
```

or

```
net use x: \\\\VBOXSVR\\vagrant
```

I was not able to use WinRM, so I tried ssh. Unfortunately this led me to write this issue
### Vagrant version

```
$ vagrant --version
Vagrant 1.8.1
```
### Host operating system

Ubuntu 14.04

```
$ uname -r
3.19.0-56-generic
```
### Guest operating system

Windows 7 Professional 64bit
### Vagrantfile

``` ruby

Vagrant.configure(2) do |config|
  config.vm.box = "windows7_64_base"
  config.vm.guest = :windows
  config.ssh.insert_key = false

  #config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     vb.linked_clone = true if Vagrant::VERSION =~ /^1.8/
     vb.name = "windows_test"
  end
end
```
### Debug output

gist containing the debug messages when mounting
https://gist.github.com/NeroBurner/bb853b4643056b40ae53e15dead13f00
### Expected behavior

mount shared folder and finish `vagrant up`
### Actual behavior

Hanging at `==> default: Mounting shared folders...` forever
### Steps to reproduce
1. Setup Windows 7 Virtualbox and install Cygwin openSSH
   A windows iso for testing is available at https://az792536.vo.msecnd.net/vms/VMBuild_20150916/Vagrant/IE10/IE10.Win7.Vagrant.zip
2. setup vagrantfile
3. run `vagrant up`

**Comment by chrisroberts** [comment] 2016-10-03 20:35
I believe that this is likely fixed now, but need to repro and confirm.

**Comment by while0pass** [comment] 2016-12-22 13:42
Just a quick piece of info if it helps somehow. I don't use vagrant, but I have a similar problem with Virtualbox 5.1.12, Windows 7 and Cygwin. The shared folder opens well within Windows, but Cygwin doesn't see it. There was no problem with previous versions of Virtualbox. In my case the problem is only observed when cygwin is run as Administrator (as I'm used to doing). There is no problem when run as a common user, cygwin sees the disk and the folder.

**Comment by chrisroberts** [comment] 2017-03-02 00:08
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Closed by chrisroberts** 2017-03-02 00:08 UTC
Labels: bug, core, needs-repro, synced-folders/general
