### ISSUE TITLE
Please support bundler 1.9.4

### ISSUE THREAD

**Issue by roroco** [mitchellh/vagrant#5611] opened 2015-04-20 14:09 UTC
I use latest ruby 2.2, when i run 'gem install bundler', it default install bundler 1.9.4

**Comment by sethvargo** [comment] 2015-04-20 14:13
Hi @roroco 

This is a duplicate of https://github.com/mitchellh/vagrant/issues/5581. Please note, unless you are doing Vagrant plugin development, the recommended way to use Vagrant is via the [official Vagrant installers](http://www.vagrantup.com/downloads.html) which include a well-tested Ruby version and all the supporting/required libraries for using Vagrant as a tool.

If you are a plugin developer, the reason for the bundler restriction is because Vagrant relies on some internal APIs in Bundler core that are not guaranteed to be backwards-compatible between minor version bumps (because they are internal APIs). Plugins in the Vagrant eco-system also leverage those APIs. In order to ensure we do not break other's plugins, we impose a tight restriction on the allowed versions of bundler. 

Please let me know if you have any questions.

**Closed by sethvargo** 2015-04-20 14:13 UTC

**Comment by gildas** [comment] 2015-04-20 15:36
You should use gem install bundler:1.7.9.
Also, you should use rvm or rbenv (with the excellent rbenv-gemset plugin).
Doing development on Mac or Linux with the plain ruby is at best suicidal.
