### ISSUE TITLE
vagrant-vmware-workstation 4.0.9 fails for shared directory 4.0.8 works

### ISSUE THREAD

**Issue by newtonianb** [mitchellh/vagrant#7381] opened 2016-06-01 21:11 UTC
**Vagrant**: 1.8.1
**OS**: Windows 10 Pro
**Homestead**: 2.2.1

When I run homestead up (proxy to vagrant up) one of my folders fail below. NOTE this works just fine in vagrant-vmware-workstation (4.0.8) but fails in vagrant-vmware-workstation (4.0.9)

```
vmhgfs-fuse -o uid=`id -u vagrant`,gid=900,allow_other, '.host:/-home-vagrant-Code-my-folder' /home/vagrant/Code/my/folder
```

```
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: vmware_workstation

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: C:\my\other\folder
      to: /home/vagrant/Code/my/other/folder
	  
    - map: C:\my\folder
      to: /home/vagrant/Code/my/folder
            
sites:
    - map: myother.app
      to: /home/vagrant/Code/my/other/folder/public
    - map: my.app
      to: /home/vagrant/Code/my/folder/public

```

**Comment by mitchellh** [comment] 2016-06-01 21:21
Hi, can you please share the error message you receive when running Vagrant?

**Comment by newtonianb** [comment] 2016-06-01 21:41
![2016-06-01_17-39-32](https://cloud.githubusercontent.com/assets/2313644/15726643/ff1dbc74-281f-11e6-89a6-aaf1b13aa12a.png)

Sorry had to block out some content but this is after running homestead up.

**Comment by mitchellh** [comment] 2016-06-01 21:48
What is the error that shows up below that? (likely from "Stderr from command")

**Comment by yhuang** [comment] 2016-06-10 20:56
I am running into the same issue with Mac OS X 10.11.5, vagrant 1.8.1, ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15], and VMware Fusion 8.1.1.  I cannot upgrade to vagrant 1.8.3 due to a known vagrant-bundler issue.  Here is the error:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

vmhgfs-fuse -o uid=`id -u vagrant`,gid=1000,allow_other '.host:/-vagrant' /vagrant

Stdout from the command:



Stderr from the command:
```

There are no stdout and stderr given.

**Comment by yhuang** [comment] 2016-06-10 21:47
Here are some output from the vagrant's more detailed logging:

https://gist.github.com/yhuang/004d6a39b92343a676e735aadb4f1b47

I tried upgrading to vagrant 1.8.3.  When I realized I could not due to that known bundler issue, I downgraded to 1.8.1, which is what I had before.  I am not sure why vagrant up now fails for me, when I did not run into such issue before on 1.8.1.

**Comment by yhuang** [comment] 2016-06-10 21:56
More information for you, Seth.  I downgraded my vagrant-vmware-fusion to 4.0.8 and the problem went away!

```
vagrant plugin install vagrant-vmware-fusion --plugin-version 4.0.8
```

**Comment by mightyoj** [comment] 2016-06-15 17:58
Same issue with the plugin version 4.0.9 on using the fusion provider, OSX 10.11.5, tried both on 1.8.1 and 1.8.4. Downgrade back to 4.0.8 is only working solution so far.

**Comment by mitchellh** [comment] 2016-06-22 16:47
Note we have a fix staged and a release should come soon.

**Comment by geerlingguy** [comment] 2016-06-24 22:19
Another +1 — just ran into this when testing my centos6 and centos7 boxes. Switching them to NFS bypasses the problem for now.

**Comment by chrisroberts** [comment] 2016-10-06 19:57
This should be fixed within the latest plugin. If the problem is not resolve, please let me know. Otherwise I'll close this up. Thanks!

**Comment by chrisroberts** [comment] 2016-10-17 16:19
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2016-10-17 16:19 UTC
Labels: bug, provider/vmware, waiting-reply
