### ISSUE TITLE
"vagrant share --name ..." fails

### ISSUE THREAD

**Issue by ndarilek** [mitchellh/vagrant#5400] opened 2015-02-27 13:58 UTC
```text
bash-3.1$ vagrant share --http 8080 --https 8443
==> core-01: Detecting network information for machine...
    core-01: Local machine address: 172.16.8.101
    core-01: Local HTTP port: 8080
    core-01: Local HTTPS port: 8443
==> core-01: Checking authentication and authorization...
==> core-01: Creating Vagrant Share session...
    core-01: Share will be at: menacing-otter-2463
==> core-01: Your Vagrant Share is running! Name: menacing-otter-2463
==> core-01: URL: http://menacing-otter-2463.vagrantshare.com
```

```text
bash-3.1$ vagrant share --http 8080 --https 8443Exiting due to interrupt.
 --name perceptron
==> core-01: Detecting network information for machine...
    core-01: Local machine address: 172.16.8.101
    core-01: Local HTTP port: 8080
    core-01: Local HTTPS port: 8443
==> core-01: Checking authentication and authorization...
==> core-01: Creating Vagrant Share session...
There was an error returned by the Vagrant Cloud server. The
error message is shown below:
```

(No error is shown.)

Interestingly enough, naming it "perceptron2" works. I did get this working yesterday, perhaps the share didn't get cleaned up on Atlas' end? I suppose someone else may have grabbed it, but if so then I'd expect an error to that effect.

**Comment by sethvargo** [comment] 2015-02-27 14:59
Hi @ndarilek 

Thank you for reporting the issue. Are you able to reproduce this issue reliably? It would be helpful to have a reproduction case. What version of Vagrant are you using please?

**Comment by ndarilek** [comment] 2015-02-27 16:07
Yes, this reproduces every time. Vagrant 1.7.2.

Are names not intended to be reused? I just tried this with "vagrant
share ... -name perceptron2" and it worked, but when I killed the
session and tried again, it failed. It seems like Atlas may not be
cleaning up dead shares, or that maybe names can't be reused, which I
hope isn't the case as it'd make testing web hooks a pain.

Thanks.

**Comment by fredsted** [comment] 2015-03-24 08:40
I have problems re-using my share names, too. I worked around this by manually logging in to the "atlas.hashicorp.com" page and deleting my share.

But now, I get the "There was an error returned..." error even though I can't see any of my shares on the "atlas.hashicorp.com" page. 

I'm testing an application where I manually have to enter a new URL 50+ places, it's very time consuming to change, so that's my use case for wanting to re-use the URL.

**Comment by muya** [comment] 2015-04-10 11:01
I couldn't reach the link shared above, however I found my shares here: https://atlas.hashicorp.com/vagrant (after login and was able to recycle there
It would be good if `vagrant share` showed the error message.

**Comment by mitchellh** [comment] 2015-07-06 17:58
@sethvargo I assigned this to you since you have more context on Atlas, is that okay?

**Comment by sethvargo** [comment] 2015-07-10 20:56
Hi all,

Share names are not intended to be used. Once you use a share name, you will need to "recycle" it in Atlas so it can be re-used with other shares: https://atlas.hashicorp.com/shares. Thanks!

**Closed by sethvargo** 2015-07-10 20:56 UTC
Labels: bug, core

**Comment by ndarilek** [comment] 2015-07-10 21:13
Not trying to nitpick, but do you mean reused? Or should we genuinely
not be *using* share names for some reason?

Also, out of curiosity, why not? If I'm developing something that needs
to expose an external endpoint, say for oauth callbacks, it seems
legitimate that I'd need a static endpoint to register and reuse
throughout development. Of course don't permit using named shares for
deployment or anything beyond casual development, but I can't help but
think that there are better ways to discourage this than not permitting
shares to be reused unless I recycle them.

Thanks.

**Comment by sethvargo** [comment] 2015-07-10 21:24
@ndarilek for that use case, you can register a domain with Atlas and then persist named shares using the `--name` flag on your custom domin.

**Comment by ndarilek** [comment] 2015-07-10 21:26
Gotcha, sounds good. Thanks, glad that use case is covered. :)

**Comment by cascornelissen** [comment] 2016-07-26 19:49
For anyone running into this, reusing share names is - at the time of writing - officially supported as stated on https://atlas.hashicorp.com/help/vagrant/shares/custom-names

> Share names are recycled when they expire automatically, meaning they can be used again (by any user, if not on a custom domain)
