### ISSUE TITLE
Insecure by default - sharing project directory that has Vagrantfile

### ISSUE THREAD

**Issue by ilyash** [mitchellh/vagrant#8153] opened 2016-12-24 20:05 UTC
As mentioned at https://www.vagrantup.com/docs/synced-folders/

> By default, Vagrant will share your project directory (the directory with the Vagrantfile) to /vagrant.

Since virtualization is involved, people are likely to feel safe to run untrusted boxes they find on the Internet. It should be trivial for any malicious box to edit `Vagrantfie`, "escaping" the virtualization by placing arbitrary ruby code there. (Don't have working VirtualBox to test this at the moment.)

(Sorry if it's a duplicate, too many results for "insecure" search in issues)

**Comment by chrisroberts** [comment] 2017-01-04 00:04
Closing this as a dup of #8018.

@ilyash Thanks for the report. This configuration is by design and documented here: https://www.vagrantup.com/docs/synced-folders/

As vagrant is a development tool first, defaults configurations may not always be viewed as secure. However, the configuration of the Vagrantfile can disable or modify these configurations.

Cheers!

**Closed by chrisroberts** 2017-01-04 00:04 UTC
