### ISSUE TITLE
The following SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed! vagrant In windows

### ISSUE THREAD

**Issue by saurabhjd** [mitchellh/vagrant#7702] opened 2016-08-11 11:00 UTC
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
[default] GuestAdditions versions on your host (5.0.24) and guest (5.0.10) do no                                                                                                                t match.
Setting up Install Process
Package kernel-uek-devel-2.6.39-400.277.1.el5uek.x86_64 already installed and la                                                                                                                test version
Package gcc-4.1.2-55.el5.x86_64 already installed and latest version
Package 1:make-3.81-3.el5.x86_64 already installed and latest version
Package bzip2-1.0.3-6.el5_5.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package perl.x86_64 4:5.8.8-43.el5_11 set to be updated
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package      Arch           Version                   Repository          Size
================================================================================
Installing:
 perl         x86_64         4:5.8.8-43.el5_11         el5_latest          12 M

Transaction Summary
================================================================================
Install       1 Package(s)
Upgrade       0 Package(s)

Total download size: 12 M
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Finished Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing     : perl                                                     1/1

Installed:
  perl.x86_64 4:5.8.8-43.el5_11

Complete!
Copy iso file C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso into the                                                                                                                 box /tmp/VBoxGuestAdditions.iso
Installing Virtualbox Guest Additions 5.0.24 - guest version is 5.0.10
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.0.24 Guest Additions for Linux............
VirtualBox Guest Additions installer
Removing installed version 5.0.10 of VirtualBox Guest Additions...
Stopping VirtualBox Additions [FAILED]
(Cannot unload module vboxguest)
Removing existing VirtualBox non-DKMS kernel modules[  OK  ]
[  OK  ] VirtualBox Guest Addition service [  OK  ]
Copying additional installer modules ...
Installing additional modules ...
Removing existing VirtualBox non-DKMS kernel modules[  OK  ]
Building the VirtualBox Guest Additions kernel modules
The headers for the current running kernel were not found. If the following
module compilation fails then this could be the reason.
The missing package can be probably installed with
yum install kernel-uek-devel-2.6.39-400.277.1.el5uek

Building the main Guest Additions module[  OK  ]
Building the shared folder support module[  OK  ]
Building the graphics driver module[  OK  ]
Doing non-kernel setup of the Guest Additions[  OK  ]
You should restart your guest to make sure the new modules are actually used

==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

# Down the interface before munging the config file. This might
# fail if the interface is not actually set up yet so ignore
# errors.
/sbin/ifdown '' || true

# Move new config into place
mv '/tmp/vagrant-network-entry--1470858193-0' '/etc/sysconfig/network-scripts/if                                                                                                                cfg-'

# Bring the interface up
ARPCHECK=no /sbin/ifup ''

Stdout from the command:

Stderr from the command:

usage: ifdown <device name>
Usage: ifup <device name>

**Comment by chrisroberts** [comment] 2016-10-03 22:20
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by chrisroberts** [comment] 2016-10-25 20:21
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2016-10-25 20:21 UTC
Labels: waiting-reply
