### ISSUE TITLE
vagrant ssh keeps freezing

### ISSUE THREAD

**Issue by ccapndave** [mitchellh/vagrant#6845] opened 2016-01-11 10:29 UTC
I have build an Ubuntu Trusty 14.04 LTS x64 box via puphpet.  However, when I access the box via `vagrant ssh`, the terminal completely freezes for about 20 seconds every 2 minutes or so, making is essentially unusable.  Once it unfreezes any keys I pressed whilst it was frozen all appear at once.

Note that the behaviour also occurs even when I do not provision the box (i.e. no PHP/MySQL/Apache/etc).  Further I have noticed that if I use the straight ssh command `ssh -i ~/.vagrant/insecure_private_key vagrant@myhost` the freezing does *not* occur and everything works normally.

**Comment by sethvargo** [comment] 2016-01-11 15:46
Hi @ccapndave 

Thank you for opening an issue. Could you please share your complete Vagrantfile as well as the output of the commands in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)?

Are you able to try a different box (like `hashicorp/precise64`) to see if the issue is reproducible there? This will help us narrow down if the issue is with Vagrant or with that particular box :smile:

**Comment by jtreminio** [comment] 2016-01-22 01:22
I believe fixed by https://github.com/puphpet/puphpet/issues/2086

**Closed** 2016-03-17 22:36 UTC
Labels: waiting-reply
