### ISSUE TITLE
couldn't build from source!

### ISSUE THREAD

**Issue by rahsd** [mitchellh/vagrant#5684] opened 2015-05-06 12:18 UTC
~~~
bundle install
Updating https://github.com/mitchellh/vagrant-spec.git
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    vagrant (>= 0) ruby depends on
      bundler (< 1.8.0, >= 1.5.2) ruby

  Current Bundler version:
    bundler (1.9.6)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
Could not find gem 'bundler (< 1.8.0, >= 1.5.2) ruby', which is required by gem
'vagrant (>= 0) ruby', in any of the sources.
~~~

**Comment by karlnp** [comment] 2015-05-14 00:28
I just went through a torturous pipeline of fixing this... So here's the workaround I used on this Windows 7 box:

* Install Ruby <2.2 (most recent RubyInstaller is 2.1.6) [this is necessary because a dependency of vagrant relies on native libraries built with the development kit (see below) and one of its dependencies relies on wdm, [which uses a method deprecated in Ruby and taken out completely in 2.2](http://stackoverflow.com/questions/29123339/error-installed-wdm-gem-on-windows-system)]
* install the [Ruby Devkit ] (https://github.com/oneclick/rubyinstaller/wiki/Development-Kit)
* install bundler @ 1.7.9
* bundle install (if you have multiple versions of bundler installed, bundle _1.7.9_ install)
* rake (this fails for me with not really any feedback, but it's something to be aware of)
* rake install (succeeds with the message that it's 1.7.2 because the version number hasn't been bumped)

Let me know if this helped!

**Comment by sethvargo** [comment] 2015-05-14 13:56
Hi @rahsd 

This is actually a duplicate of https://github.com/mitchellh/vagrant/issues/5581. Let's track this there please. Thanks!

**Closed by sethvargo** 2015-05-14 13:56 UTC
