### ISSUE TITLE
Cannot install remote boxes

### ISSUE THREAD

**Issue by swashcap** [mitchellh/vagrant#8034] opened 2016-11-24 23:25 UTC
### Vagrant version

Vagrant 1.8.7

### Host operating system

OS X 10.12.1

### Guest operating system

n/a

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "hashicorp/precise64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

### Debug output

https://gist.github.com/swashcap/db4d262b37c896bb6645e440c9a5e0a8

### Expected behavior

Ran these commands from the [Getting Started guide](https://www.vagrantup.com/docs/getting-started/):

```shell
$ vagrant init hashicorp/precise64
$ vagrant up
```

I expected this would start up a machine using VirtualBox as the provider.

### Actual behavior

Vagrant couldn’t retrieve the box (see debugging output) and dumps this error:

```shell
The box 'hashicorp/precise64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/hashicorp/precise64"]
Error: 
```

This behavior is observed with every other box. This error seems to swallow a Vagrant bundled dependency problem (libcurl), observable in the debug log:

```shell
DEBUG subprocess: stderr: dyld: Library not loaded: @rpath/libcurl.4.dylib
  Referenced from: /opt/vagrant/embedded/bin/curl
  Reason: Incompatible library version: curl requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 6
```

### Steps to reproduce

1. Install latest Vagrant (Vagrant 1.8.7)
2. Run instructions from the Getting Started guide:

    ```shell
    $ vagrant init hashicorp/precise64
    $ vagrant up
    ```

**Comment by bigautomata** [comment] 2016-11-25 06:03
Check the workaround available on the related issue #7969 . Also I'd similar issue as you stated. I have done as @jenhsun stated on issue #7969.

Below are the steps executed as follows:
1. sudo rm -rf /opt/vagrant/embedded/bin/curl
2. vagrant box add centos/7

Add box will print out the following stand message as:

==> box: Loading metadata for box 'centos/7'
    box: URL: https://atlas.hashicorp.com/centos/7
This box can work with multiple providers! The providers that it
can work with are listed below. Please review the list and choose
the provider you will be working with.

1) libvirt
2) virtualbox
3) vmware_desktop
4) vmware_fusion

Enter your choice: 2
==> box: Adding box 'centos/7' (v1610.01) for provider: virtualbox
    box: Downloading: https://atlas.hashicorp.com/centos/boxes/7/versions/1610.01/providers/virtualbox.box
==> box: Successfully added box 'centos/7' (v1610.01) for 'virtualbox'!

**Comment by kikitux** [comment] 2016-11-25 20:32
Hello.

Seems duplicate of https://github.com/mitchellh/vagrant/issues/7969

**Closed by kikitux** 2016-11-25 20:32 UTC
Labels: bug, host/darwin, installer

**Comment by swashcap** [comment] 2016-11-26 21:07
Ah, great! Running:

```shell
sudo rm -rf /opt/vagrant/embedded/bin/curl
```

…seems to remove the conflicted version of cURL. I can run `vagrant up` successfully. Thanks! 🙌
