### ISSUE TITLE
Regular expression for machine names are not working

### ISSUE THREAD

**Issue by berendt** [mitchellh/vagrant#6994] opened 2016-02-06 18:55 UTC
I am following https://www.vagrantup.com/docs/multi-machine/ to bring up only a subset of all defined machines:

```
# vagrant up '/dev-de-1-container-[1-3]/'
The machine with the name '/dev-de-1-container-[1-3]/' was not found configured for
this Vagrant environment.
```

Also I think the documentation makes no sense, because when using zsh I get the following issue when not using ``'``.

```
# vagrant up /dev-de-1-container-[1-3]/                                                                                 :(
zsh: no matches found: /dev-de-1-container-[1-3]/
```

With bash and without ``'`` it is also not working:

```
# vagrant up /dev-de-1-container-[1-3]/     
The machine with the name '/dev-de-1-container-[1-3]/' was not found configured for
this Vagrant environment.
```

```
# vagrant --version                                                                                                     :(
Vagrant 1.8.1
```

**Comment by sethvargo** [comment] 2016-02-07 18:04
Dupe of https://github.com/mitchellh/vagrant/issues/6828

**Closed by sethvargo** 2016-02-07 18:04 UTC
