### ISSUE TITLE
New command: vagrant box remove-old-versions (with tests)

### ISSUE THREAD

**Issue by bbrala** [mitchellh/vagrant#7213] opened 2016-04-06 19:26 UTC
See PR #6863 

Added a command ``vagrant box remove-old-versions`` to remove all but the newest version of a box in vagrant. It builds a list of  boxes that are installed and finds the newest versions. It then removes every box that had a newer version installed.

Since it uses the internal `box remove` command, all safeguards vagrant has for removing boxes that are in use are in place.

```
Usage: vagrant box remove-old-versions [options]

Options:

    -p, --provider PROVIDER          The specific provider type for the boxes to destroy.
    -n, --dry-run                    Only print the boxes that would be removed.
        --name NAME                  The specific box name to destroy.
    -f, --force                      Destroy without confirmation even when box is in use.
    -h, --help                       Print this help

```

The PR has tests for everything except the `--force` flag which i feel should be covered in the `vagrant box remove` command.

**Comment by sethvargo** [comment] 2016-04-06 20:15
This is a duplicate of https://github.com/mitchellh/vagrant/issues/4412. Let's just keep everything in one issue please. Thanks! :smile:

**Closed by sethvargo** 2016-04-06 20:15 UTC

**Comment by bbrala** [comment] 2016-04-06 20:20
Sorry, thought it might just need a specific issue for the PR. :smile:
