### ISSUE TITLE
config.ssh.private_key_path seems to be ignored

### ISSUE THREAD

**Issue by acesuares** [mitchellh/vagrant#5533] opened 2015-03-30 01:07 UTC
In my Vargantfile, I have 

``` config.ssh.private_key_path = "/root/.ssh/vagrant/id_rsa" ```

via a require directive.

This worked fine in previous installations, but now it doesn't work.

Vagrant keep looking in

``` /PATH TO DEFAULT MACHINE/virtualbox/private_key ```

How to fix this?

**Comment by sethvargo** [comment] 2015-03-30 14:18
Hi @acesuares. I am sorry you are having issues. This is actually a duplicate of https://github.com/mitchellh/vagrant/issues/5090. Please track that issue instead. Thank you for reporting! :smile:

**Closed by sethvargo** 2015-03-30 14:18 UTC
