### ISSUE TITLE
Shared folder of chef works only on vagrant destroy (1.7.2)

### ISSUE THREAD

**Issue by manea-eugen** [mitchellh/vagrant#5200] opened 2015-01-16 15:36 UTC
After successful vagrant destroy -f && vagrant up  if i run reload chef doesn't remount 

```text
$ vagrant reload --provision
==> default: Loading Berkshelf datafile...
==> default: Sharing cookbooks with VM
==> default: Unmounting NFS shared folders from guest...
==> default: Attempting graceful shutdown of VM...
==> default: Checking if box 'hashicorp/precise64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Updating Vagrant's Berkshelf...
==> default: Resolving cookbook dependencies...
==> default: Fetching 'pimcore' from source at .
==> default: Using apache2 (2.0.0)
==> default: Using apt (2.6.1)
==> default: Using build-essential (2.0.6)
==> default: Using aws (2.5.0)
==> default: Using chef-sugar (2.5.0)
==> default: Using chef_handler (1.1.6)
==> default: Using cron (1.6.1) from https://github.com/manea-eugen/cron.git (at master)
==> default: Using composer (1.0.6)
==> default: Using database (2.3.1)
==> default: Using dmg (2.2.2)
==> default: Using hostsfile (2.4.5)
==> default: Using git (4.0.2)
==> default: Using iis (2.1.6)
==> default: Using iptables (0.14.1)
==> default: Using locale (1.0.2)
==> default: Using line (0.5.3) from https://github.com/manea-eugen/line-cookbook.git (at 0.5.3)
==> default: Using logrotate (1.7.0)
==> default: Using mailcatcher (0.1.4) from https://github.com/manea-eugen/chef-mailcatcher.git (at master)
==> default: Using mongodb (0.16.2)
==> default: Using mysql (5.5.4)
==> default: Using mysql-chef_gem (0.0.5)
==> default: Using now (0.3.0)
==> default: Using ntp (1.6.8)
==> default: Using pacman (1.1.1)
==> default: Using openssl (2.0.2)
==> default: Using php (1.5.0)
==> default: Using pimcore (0.1.0) from source at .
==> default: Using python (1.4.6)
==> default: Using postgresql (3.4.14)
==> default: Using runit (1.5.14)
==> default: Using simple_iptables (0.6.0)
==> default: Using vim (1.1.2)
==> default: Using sudo (2.7.1)
==> default: Using windows (1.36.1)
==> default: Using xdebug (1.0.0)
==> default: Using xfs (1.1.0)
==> default: Using xml (1.2.9)
==> default: Using yum (3.5.2)
==> default: Using yum-epel (0.6.0)
==> default: Using yum-mysql-community (0.1.11)
==> default: Vendoring apache2 (2.0.0) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/apache2
==> default: Vendoring apt (2.6.1) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/apt
==> default: Vendoring aws (2.5.0) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/aws
==> default: Vendoring build-essential (2.0.6) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/build-essential
==> default: Vendoring chef-sugar (2.5.0) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/chef-sugar
==> default: Vendoring chef_handler (1.1.6) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/chef_handler
==> default: Vendoring composer (1.0.6) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/composer
==> default: Vendoring cron (1.6.1) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/cron
==> default: Vendoring database (2.3.1) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/database
==> default: Vendoring dmg (2.2.2) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/dmg
==> default: Vendoring git (4.0.2) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/git
==> default: Vendoring hostsfile (2.4.5) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/hostsfile
==> default: Vendoring iis (2.1.6) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/iis
==> default: Vendoring iptables (0.14.1) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/iptables
==> default: Vendoring line (0.5.3) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/line
==> default: Vendoring locale (1.0.2) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/locale
==> default: Vendoring logrotate (1.7.0) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/logrotate
==> default: Vendoring mailcatcher (0.1.4) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/mailcatcher
==> default: Vendoring mongodb (0.16.2) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/mongodb
==> default: Vendoring mysql (5.5.4) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/mysql
==> default: Vendoring mysql-chef_gem (0.0.5) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/mysql-chef_gem
==> default: Vendoring now (0.3.0) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/now
==> default: Vendoring ntp (1.6.8) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/ntp
==> default: Vendoring openssl (2.0.2) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/openssl
==> default: Vendoring pacman (1.1.1) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/pacman
==> default: Vendoring php (1.5.0) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/php
==> default: Vendoring pimcore (0.1.0) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/pimcore
==> default: Vendoring postgresql (3.4.14) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/postgresql
==> default: Vendoring python (1.4.6) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/python
==> default: Vendoring runit (1.5.14) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/runit
==> default: Vendoring simple_iptables (0.6.0) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/simple_iptables
==> default: Vendoring sudo (2.7.1) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/sudo
==> default: Vendoring vim (1.1.2) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/vim
==> default: Vendoring windows (1.36.1) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/windows
==> default: Vendoring xdebug (1.0.0) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/xdebug
==> default: Vendoring xfs (1.1.0) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/xfs
==> default: Vendoring xml (1.2.9) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/xml
==> default: Vendoring yum (3.5.2) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/yum
==> default: Vendoring yum-epel (0.6.0) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/yum-epel
==> default: Vendoring yum-mysql-community (0.1.11) to /Users/burycel/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150116-11730-qj3v18-default/yum-mysql-community
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.2.0
    default: VirtualBox Version: 4.3
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
==> default: Mounting NFS shared folders...
==> default: Chef 12.0.3 Omnibus package is already installed.
==> default: Configuring cache buckets...
==> default: Running provisioner: chef_solo...
==> default: Detected Chef (latest) is already installed
Shared folders that Chef requires are missing on the virtual machine.
This is usually due to configuration changing after already booting the
machine. The fix is to run a `vagrant reload` so that the proper shared
folders will be prepared and mounted on the VM.
```

PS. I think this relates to this issue https://github.com/mitchellh/vagrant/issues/5199

**Comment by Fantus** [comment] 2015-01-17 18:47
same problem for me "vagrant up" and "vagrant reload --provision" results in the reported missing shared folders.

works fine again after downgrading to 1.7.1

iam using ubuntu 14

**Comment by manea-eugen** [comment] 2015-01-18 09:26
For me it's  still not working 1.7.1 on mac, i will continue downgrade and keep you guys updated

**Comment by phillipsnick** [comment] 2015-01-21 22:40
Also having the same issue after upgrading to 1.7.2 from 1.7.1.

I first thought this was a berkshelf issue as seen here https://github.com/berkshelf/vagrant-berkshelf/issues/258

Seems to have come from this commit
https://github.com/mitchellh/vagrant/commit/155516fb6c8a4025b38d5b709b886f5d02a33a27

Specifically this block of code

```ruby
            if existing_set.include?(remote_path)
              @logger.debug("Not sharing #{local_path}, exists as #{remote_path}")
              next
```

Basing this on the debug messages

```
DEBUG chef_solo: Not sharing /Users/x1nick/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150121-14677-1ddtg4i-web, exists as /tmp/vagrant-chef/502ce27a6c8e59a74d01392ffa38f706/cookbooks
DEBUG chef_solo: Not sharing /Users/x1nick/Development/vagrant-vmware/roles, exists as /tmp/vagrant-chef/0cbbaf0e09888042d68677cf81e7d0a4/roles
DEBUG chef_solo: Not sharing /Users/x1nick/Development/vagrant-vmware/environments, exists as /tmp/vagrant-chef/027c3605c92b2cddeb8d333c7718e3a2/environments
```

**Comment by hugofonseca** [comment] 2015-01-23 11:31
+1

**Comment by methyl** [comment] 2015-01-23 15:48
+1, workaround for me was to resign from vagrant-berkshelf plugin and use berks vendor instead.

**Comment by cognoscibilis** [comment] 2015-01-23 19:47
+1

**Comment by MikeSchuette** [comment] 2015-01-28 22:22
"Me too", on OSX 10.10.1 and 10.10.2.  Downgrade to 1.6.5 worked.

**Comment by ernie58** [comment] 2015-01-29 07:25
I'm using 1.7.1 on a mac and I don't have this problem. My colleagues on Windows had the problem on 1.7.2 but solved it by downgrading to 1.7.1

**Comment by joelhandwell** [comment] 2015-02-06 04:54
Getting same error with 1.7.2 on windows 7 with chef_zero provisioner and vagrant-berkshelf plugin.

**Comment by jeqo** [comment] 2015-02-06 08:57
+1 Me too on Ubuntu 14.04 with chef_zero and chef_solo. Cookbooks and Roles are not mapped. Other directories like "nodes" work.

**Comment by sethvargo** [comment] 2015-02-06 13:45
Hey there,

I just realized this is actually a dupe of #5199. Let's track that one instead please.

**Closed by sethvargo** 2015-02-06 13:45 UTC
Labels: bug, provisioners/chef, synced_folders

**Comment by ManFromEast** [comment] 2015-07-03 05:21
after install chef by hand, I execute command vagrant up -> vagrant provision, get shared folders are missing.
