### ISSUE TITLE
chef-zero provisioner spends a long time synchronizing cookbooks 

### ISSUE THREAD

**Issue by fishnix** [mitchellh/vagrant#5972] opened 2015-07-15 18:42 UTC
This was an issue introduced in 1.7.3 and is worked around by downgrading to 1.7.2.  

Chef spends a long time doing this:

```
DEBUG ssh: stdout: [2015-07-15T14:40:53-04:00] INFO: Storing updated cookbooks/np-pr/recipes/_platform.rb in the cache.

 INFO interface: info: [2015-07-15T14:40:53-04:00] INFO: Storing updated cookbooks/np-pr/recipes/_platform.rb in the cache.
 INFO interface: info: ==> default: [2015-07-15T14:40:53-04:00] INFO: Storing updated cookbooks/np-pr/recipes/_platform.rb in the cache.
==> default: [2015-07-15T14:40:53-04:00] INFO: Storing updated cookbooks/np-pr/recipes/_platform.rb in the cache.
DEBUG ssh: stdout: [2015-07-15T14:40:53-04:00] INFO: Storing updated cookbooks/np-pr/recipes/docker.rb in the cache.

 INFO interface: info: [2015-07-15T14:40:53-04:00] INFO: Storing updated cookbooks/np-pr/recipes/docker.rb in the cache.
 INFO interface: info: ==> default: [2015-07-15T14:40:53-04:00] INFO: Storing updated cookbooks/np-pr/recipes/docker.rb in the cache.
==> default: [2015-07-15T14:40:53-04:00] INFO: Storing updated cookbooks/np-pr/recipes/docker.rb in the cache.
DEBUG ssh: stdout: [2015-07-15T14:40:53-04:00] INFO: Storing updated cookbooks/np-pr/recipes/prview_app.rb in the cache.

 INFO interface: info: [2015-07-15T14:40:53-04:00] INFO: Storing updated cookbooks/np-pr/recipes/prview_app.rb in the cache.
 INFO interface: info: ==> default: [2015-07-15T14:40:53-04:00] INFO: Storing updated cookbooks/np-pr/recipes/prview_app.rb in the cache.
```

Thanks!

**Comment by sethvargo** [comment] 2015-07-15 19:26
Hi @fishnix 

This is working as intended. The Chef Zero provisioner in Vagrant 1.7.2 was not functioning properly and ran Chef Solo, not Chef Client (#5619). Unfortunately this is just a side-effect of using the Chef Zero provisioner as it needs to upload cookbooks to "itself" on each run.

You might also be experiencing [poor synced folder performance](http://mitchellh.com/comparing-filesystem-performance-in-virtual-machines), which can also affect upload speeds.

Sorry about the confusion! I am going to close this issue, but if I have misunderstood your issue, please @mention me and I will take another look. :smile:

**Closed by sethvargo** 2015-07-15 19:26 UTC

**Comment by jperville** [comment] 2015-08-16 17:47
If this behavior is intended, any chance to get back the old chef-zero provisioner, maybe under a different name such as 'chef-solo-zero'?

On my application (a multi-VM Vagrantfile that installs a whole platform; 83 cookbooks according to `berks list` in total), vagrant provision timeouts while synchronising cookbooks (even after raising the webrick timeout #138). If I run `chef-client -z` manually inside the VM, it takes 22 minutes just for cookbook resolution, as shown below:

```sh
root@admin-vm:~# time chef-client -z -c /tmp/vagrant-chef/client.rb -o xx-environment::default
[2015-08-16T17:23:46+00:00] INFO: Started chef-zero at chefzero://localhost:8889 with repository at /tmp/vagrant-chef/1dd0c304936f9b6857952baf4cf57488
  One version per cookbook
  data_bags at /tmp/vagrant-chef/9a39ae1709b67de965614799360d8c2d/data_bags
  environments at /tmp/vagrant-chef/3cda2f44c6bf2c2209ac4d140ed54d79/environments
  nodes at /tmp/vagrant-chef/ec566cee687ea593b54c7dd68a089c87/nodes
  roles at /tmp/vagrant-chef/5a4a9c5201b4ba0512652c19f884c59c/roles

[2015-08-16T17:23:46+00:00] INFO: Forking chef instance to converge...
Starting Chef Client, version 12.4.1
[2015-08-16T17:23:46+00:00] INFO: *** Chef 12.4.1 ***
[2015-08-16T17:23:46+00:00] INFO: Chef-client pid: 3699
[2015-08-16T17:23:47+00:00] WARN: Run List override has been provided.
[2015-08-16T17:23:47+00:00] WARN: Original Run List: []
[2015-08-16T17:23:47+00:00] WARN: Overridden Run List: [recipe[xx-environment::default]]
[2015-08-16T17:23:47+00:00] INFO: Run List is [recipe[xx-environment::default]]
[2015-08-16T17:23:47+00:00] INFO: Run List expands to [xx-environment::default]
[2015-08-16T17:23:47+00:00] INFO: Starting Chef Run for admin-vm
[2015-08-16T17:23:47+00:00] INFO: Running start handlers
[2015-08-16T17:23:47+00:00] INFO: Start handlers complete.
resolving cookbooks for run list: ["xx-environment::default"]
# <----- this step takes 22 minutes, and cookbooks have not even been downloaded yet.
[2015-08-16T17:39:14+00:00] INFO: Loading cookbooks [xx-environment@0.1.0, xx-base@0.1.0, xx-backup@0.1.0, xx-networking@0.1.0, xx-monitoring@0.2.1, xx-load-balancer@0.1.9, xx-apache2@0.1.0, xx-proxy@0.1.0, xx-samba@0.1.0, xx-postfix@0.1.0, xx-postgresql@0.1.0, xx-owncloud@0.1.0, xx-odoo@0.1.0, xx-alfresco@0.1.0, xx-openvpn@0.1.0, apt@2.7.0, cron@1.6.1, sudo@2.7.2, user@0.3.0, resolvconf@0.2.9, chef-client@4.3.1, nfs@2.2.5, backup@1.3.0, brightbox-ruby@1.2.1, network_interfaces@1.0.0, dhcp@2.2.2, sysctl@0.6.2, simple_iptables@0.7.2, build-essential@2.2.3, partial_search@1.0.8, sensu@2.10.0, uchiwa@1.1.0, influxdb@2.6.0, grafana@2.0.0, newrelic@2.12.5, newrelic_meetme_plugin@0.2.1, certificate@0.6.3, nginx@2.7.4, apache2@3.0.1, logrotate@1.9.2, squid@0.5.4, dnsmasq@0.2.0, ntp@1.8.6, postfix@3.7.0, postgresql@3.4.20, database@4.0.8, ark@0.9.0, line@0.6.2, openoffice@0.2.3, python@1.4.6, ulimit@0.3.3, java@1.31.0, tomcat@0.16.1, imagemagick@0.2.3, openvpn@2.1.1, windows@1.38.1, gem_specific_install@0.2.4, modules@0.2.0, ruby-helper@0.0.1, helpers-databags@1.0.0, ohai@2.0.1, yum@3.6.3, rabbitmq@4.1.2, redisio@2.3.0, chef_handler@1.2.0, curl@2.0.1, bluepill@2.3.1, runit@1.7.2, yum-epel@0.6.2, iptables@1.0.0, hosts_file@0.2.0, openssl@4.0.0, 7-zip@1.0.2, tar@0.7.0, git@4.3.3, erlang@1.5.8, yum-erlang_solutions@0.2.0, rsyslog@2.1.0, packagecloud@0.0.19, chef-sugar@3.1.1, dmg@2.2.2]
[2015-08-16T17:39:14+00:00] INFO: Skipping removal of obsoleted cookbooks from the cache
Synchronizing Cookbooks:
```

For information, just running `knife cookbook list -z -c /tmp/vagrant-chef/client.rb` takes 3 minutes.

**Comment by joelhandwell** [comment] 2015-08-25 19:48
A question can be asked. Is it considered as better practice to use chef-client over chef-zero when if one's priority in development is less time spent on provisioning? 

And if it's yes, I think it's ironical as one of the purpose of chef-zero is to provision with less time...

**Comment by glenjamin** [comment] 2015-09-01 17:18
Would there be a performance improvement if the cookbooks were uploaded from the host to the zero server, instead of going through the guest FS?

This takes forever, but I guess the problem is also with chef-zero uploading being slow?

**Comment by jperville** [comment] 2015-09-19 21:57
Have posted a patch and workaround in #6285; to sum it up: chef-zero provisioner + local_mode (in a custom_config_path) + shared folder for nodes_path = behavior of old chef_zero provisioner.

**Comment by glenjamin** [comment] 2015-10-01 21:20
@jperville should that comment read as this?
> chef-**solo** provisioner + local_mode (in a custom_config_path) + shared folder for nodes_path 

As I understand it, your PR makes chef-solo work with multiple nodes, it doesn't make chef-zero any faster?

**Comment by jperville** [comment] 2015-10-01 21:22
Yes, it makes chef solo work with multiple nodes, which is required to emulate the former chef zero provisioner (which was actually chef solo with the "local mode" option and working support for multiple nodes, required to use "search" feature).
