### ISSUE TITLE
vagrant plugin install conflicting dependencies builder (= 3.2.2) and builder (= 3.2.3)

### ISSUE THREAD

**Issue by HareRee** [mitchellh/vagrant#8870] opened 2017-08-09 21:22 UTC
### Vagrant version
1.9.7

### Host operating system
OSX 10.12.6

### Debug output
DEBUG bundler: Dependency list for installation:
 - vagrant-share > 0
 - vagrant-hosts > 0
 - akami = 1.2.2
 - bigdecimal = 1.2.8
 - builder = 3.2.3
 - builder = 3.2.2
 - bundler = 1.7.11
 - celluloid = 0.16.0
 - childprocess = 0.6.3
 - childprocess = 0.5.5
 - domain_name = 0.5.20170404
 - erubis = 2.7.0
 - ffi = 1.9.18
 - ffi = 1.9.6
 - gssapi = 1.2.0
 - gssapi = 1.0.3
 - gyoku = 1.3.1
 - gyoku = 1.2.2
 - hashicorp-checkpoint = 0.1.4
 - hitimes = 1.2.2
 - http-cookie = 1.0.3
 - httpclient = 2.8.3
 - httpclient = 2.6.0.1
 - httpi = 0.9.7
 - i18n = 0.8.0
 - i18n = 0.6.11
 - io-console = 0.4.5
 - json = 1.8.3
 - listen = 3.1.5
 - listen = 2.8.4
 - little-plugger = 1.1.4
 - little-plugger = 1.1.3
 - log4r = 1.1.10
 - logging = 2.2.2
 - logging = 1.8.2
 - mime-types = 3.1
 - mime-types = 2.4.3
 - mime-types = 1.25.1
 - mime-types-data = 3.2016.0521
 - mini_portile = 0.6.0
 - multi_json = 1.12.1
 - multi_json = 1.10.1
 - net-scp = 1.2.1
 - net-scp = 1.1.2
 - net-sftp = 2.1.2
 - net-ssh = 4.1.0
 - net-ssh = 2.9.1
 - netrc = 0.11.0
 - netrc = 0.10.2
 - nokogiri = 1.6.3.1
 - nori = 2.6.0
 - nori = 1.1.5
 - pkg-config = 1.1.9
 - psych = 2.1.0
 - rack = 1.6.0
 - rb-fsevent = 0.10.2
 - rb-fsevent = 0.9.4
 - rb-inotify = 0.9.10
 - rb-inotify = 0.9.5
 - rb-kqueue = 0.2.5
 - rb-kqueue = 0.2.3
 - rdoc = 4.2.1
 - rest-client = 2.0.2
 - rest-client = 1.7.2
 - rest-client = 1.6.8
 - ruby_dep = 1.3.1
 - rubyntlm = 0.6.2
 - rubyntlm = 0.1.1
 - rubyzip = 1.2.1
 - savon = 0.9.5
 - timers = 4.0.1
 - unf = 0.1.4
 - unf_ext = 0.0.7.4
 - uuidtools = 2.1.5
 - vagrant = 1.9.7
 - vagrant = 1.7.2
 - wasabi = 1.0.0
 - wdm = 0.1.1
 - wdm = 0.1.0
 - winrm = 2.2.3
 - winrm = 1.1.3
 - winrm-elevated = 1.1.0
 - winrm-fs = 1.0.1

The error from Bundler is:

conflicting dependencies builder (= 3.2.2) and builder (= 3.2.3)
  Activated builder-3.2.3
  which does not match conflicting dependency (= 3.2.2)

  Conflicting dependency chains:
    builder (= 3.2.3), 3.2.3 activated

  versus:
    builder (= 3.2.2)

  Gems matching builder (= 3.2.2):
    builder-3.2.2

### Expected behavior
plugin should install

### Actual behavior
two versions of the builder are listed in the dependency list.

### Steps to reproduce
1. uninstall vagrant
2. delete .vagrant folder
3. download vagrant 1.9.7
4. $vagrant plugin install vagrant-hosts

I also tried $vagrant plugin expunge.  Seems to work when I downgrade to vagrant 1.9.5

**Comment by chrisroberts** [comment] 2017-08-10 16:01
Hi there,

This looks to be a duplicate of #8785 so I'm going to close this issue. If the comments in that issue do not apply to the error you are receiving, please let me know and I will re-open this issue. Cheers!

**Closed by chrisroberts** 2017-08-10 16:01 UTC
Labels: installer
