### ISSUE TITLE
agrant-wrapper.rb:134:in `match': invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by jstortz** [mitchellh/vagrant#6056] opened 2015-07-29 17:52 UTC
I just installed 1.7.4. I also rebooted.  When I try to execute any vagrant command I get the following output:

```
/Users/jstortz/.rvm/gems/ruby-2.1.4/gems/vagrant-wrapper-1.2.1.1/lib/vagrant-wrapper.rb:134:in `match': invalid byte sequence in UTF-8 (ArgumentError)
	from /Users/jstortz/.rvm/gems/ruby-2.1.4/gems/vagrant-wrapper-1.2.1.1/lib/vagrant-wrapper.rb:134:in `match'
	from /Users/jstortz/.rvm/gems/ruby-2.1.4/gems/vagrant-wrapper-1.2.1.1/lib/vagrant-wrapper.rb:134:in `block in find_vagrant'
	from /Users/jstortz/.rvm/gems/ruby-2.1.4/gems/vagrant-wrapper-1.2.1.1/lib/vagrant-wrapper.rb:131:in `each'
	from /Users/jstortz/.rvm/gems/ruby-2.1.4/gems/vagrant-wrapper-1.2.1.1/lib/vagrant-wrapper.rb:131:in `find_vagrant'
	from /Users/jstortz/.rvm/gems/ruby-2.1.4/gems/vagrant-wrapper-1.2.1.1/lib/vagrant-wrapper.rb:153:in `exec_vagrant'
	from /Users/jstortz/.rvm/gems/ruby-2.1.4/gems/vagrant-wrapper-1.2.1.1/lib/vagrant-wrapper.rb:67:in `execute'
	from /Users/jstortz/.rvm/gems/ruby-2.1.4/gems/vagrant-wrapper-1.2.1.1/bin/vagrant:12:in `<top (required)>'
	from /Users/jstortz/.rvm/gems/ruby-2.1.4/bin/vagrant:23:in `load'
	from /Users/jstortz/.rvm/gems/ruby-2.1.4/bin/vagrant:23:in `<main>'
	from /Users/jstortz/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jstortz/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by sethvargo** [comment] 2015-07-29 17:53
Merged in https://github.com/mitchellh/vagrant/issues/5896 - we are going to track all the encoding issues in one place. Thanks for opening this and we hope to get these all fixed soon!

**Closed by sethvargo** 2015-07-29 17:53 UTC

**Comment by jamessetaro** [comment] 2015-08-10 18:07
Is there a work around for now?

**Comment by jstortz** [comment] 2015-08-11 12:39
Or any kind of update on plans y'all are making?  For anyone else with this issue I was able to just uninstall 1.7.4 and reinstall 1.7.2 and things worked normally again.  So you CAN rollback if needed.

**Comment by jamessetaro** [comment] 2015-08-11 13:34
I was caught by this because I had upgraded to Virtualbox 5 and vagrant 1.7.2 doesn't work with it.  I just upgraded it per instructions here and now 1.7.2 works with 5.0.

https://github.com/mitchellh/vagrant/issues/5572

**Comment by samphippen** [comment] 2015-09-08 13:29
@jstortz Hi. I'm looking in to some vagrant encoding issues. If you're still around and still able to reproduce this I'd really appreciate it if you could give me the output of this snippet

```
ruby -e "p ENV['PATH'].bytes; p '--------'; p ENV['PATH'].encoding"
```

so that I can debug what's causing this issue.

Thanks ^_^

**Comment by jstortz** [comment] 2015-09-08 17:16
Hello @samphippen! I WILL make some time this afternoon to get you more data as needed, just let me know what else you want me to try.

## Current Status
Everything is "working" for me right now. I don't have an issue until I try to upgrade to Vagrant 1.7.4.

## Software
Vagrant 1.7.2
VMWare Fusion 1.7.2
OSX 10.10.5

## Plugins
```
$ vagrant plugin list
vagrant-aws (0.6.0)
vagrant-aws-route53 (0.3.2)
vagrant-multiprovider-snap (0.0.14)
vagrant-share (1.1.4, system)
vagrant-vmware-fusion (3.2.11)
```

## Ruby Version
```
ruby -v
ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-darwin14.0]
```

## Command Output
```
$ ruby -e "p ENV['PATH'].bytes; p '--------'; p ENV['PATH'].encoding"
[47, 117, 115, 114, 47, 108, 111, 99, 97, 108, 47, 115, 98, 105, 110, 58, 47, 85, 115, 101, 114, 115, 47, 106, 115, 116, 111, 114, 116, 122, 47, 46, 114, 118, 109, 47, 103, 101, 109, 115, 47, 114, 117, 98, 121, 45, 50, 46, 49, 46, 52, 47, 98, 105, 110, 58, 47, 85, 115, 101, 114, 115, 47, 106, 115, 116, 111, 114, 116, 122, 47, 46, 114, 118, 109, 47, 103, 101, 109, 115, 47, 114, 117, 98, 121, 45, 50, 46, 49, 46, 52, 64, 103, 108, 111, 98, 97, 108, 47, 98, 105, 110, 58, 47, 85, 115, 101, 114, 115, 47, 106, 115, 116, 111, 114, 116, 122, 47, 46, 114, 118, 109, 47, 114, 117, 98, 105, 101, 115, 47, 114, 117, 98, 121, 45, 50, 46, 49, 46, 52, 47, 98, 105, 110, 58, 47, 85, 115, 101, 114, 115, 47, 106, 115, 116, 111, 114, 116, 122, 47, 46, 103, 118, 109, 47, 118, 101, 114, 116, 120, 47, 99, 117, 114, 114, 101, 110, 116, 47, 98, 105, 110, 58, 47, 85, 115, 101, 114, 115, 47, 106, 115, 116, 111, 114, 116, 122, 47, 46, 103, 118, 109, 47, 115, 112, 114, 105, 110, 103, 98, 111, 111, 116, 47, 99, 117, 114, 114, 101, 110, 116, 47, 98, 105, 110, 58, 47, 85, 115, 101, 114, 115, 47, 106, 115, 116, 111, 114, 116, 122, 47, 46, 103, 118, 109, 47, 108, 97, 122, 121, 98, 111, 110, 101, 115, 47, 99, 117, 114, 114, 101, 110, 116, 47, 98, 105, 110, 58, 47, 85, 115, 101, 114, 115, 47, 106, 115, 116, 111, 114, 116, 122, 47, 46, 103, 118, 109, 47, 106, 98, 97, 107, 101, 47, 99, 117, 114, 114, 101, 110, 116, 47, 98, 105, 110, 58, 47, 85, 115, 101, 114, 115, 47, 106, 115, 116, 111, 114, 116, 122, 47, 46, 103, 118, 109, 47, 103, 114, 111, 111, 118, 121, 115, 101, 114, 118, 47, 99, 117, 114, 114, 101, 110, 116, 47, 98, 105, 110, 58, 47, 85, 115, 101, 114, 115, 47, 106, 115, 116, 111, 114, 116, 122, 47, 46, 103, 118, 109, 47, 103, 114, 111, 111, 118, 121, 47, 99, 117, 114, 114, 101, 110, 116, 47, 98, 105, 110, 58, 47, 85, 115, 101, 114, 115, 47, 106, 115, 116, 111, 114, 116, 122, 47, 46, 103, 118, 109, 47, 103, 114, 105, 102, 102, 111, 110, 47, 99, 117, 114, 114, 101, 110, 116, 47, 98, 105, 110, 58, 47, 85, 115, 101, 114, 115, 47, 106, 115, 116, 111, 114, 116, 122, 47, 46, 103, 118, 109, 47, 103, 114, 97, 105, 108, 115, 47, 99, 117, 114, 114, 101, 110, 116, 47, 98, 105, 110, 58, 47, 85, 115, 101, 114, 115, 47, 106, 115, 116, 111, 114, 116, 122, 47, 46, 103, 118, 109, 47, 103, 114, 97, 100, 108, 101, 47, 99, 117, 114, 114, 101, 110, 116, 47, 98, 105, 110, 58, 47, 85, 115, 101, 114, 115, 47, 106, 115, 116, 111, 114, 116, 122, 47, 46, 103, 118, 109, 47, 103, 108, 105, 100, 101, 47, 99, 117, 114, 114, 101, 110, 116, 47, 98, 105, 110, 58, 47, 85, 115, 101, 114, 115, 47, 106, 115, 116, 111, 114, 116, 122, 47, 46, 103, 118, 109, 47, 103, 97, 105, 100, 101, 110, 47, 99, 117, 114, 114, 101, 110, 116, 47, 98, 105, 110, 58, 47, 85, 115, 101, 114, 115, 47, 106, 115, 116, 111, 114, 116, 122, 47, 46, 103, 118, 109, 47, 99, 114, 97, 115, 104, 47, 99, 117, 114, 114, 101, 110, 116, 47, 98, 105, 110, 58, 47, 85, 115, 101, 114, 115, 47, 106, 115, 116, 111, 114, 116, 122, 47, 46, 103, 118, 109, 47, 97, 115, 99, 105, 105, 100, 111, 99, 116, 111, 114, 106, 47, 99, 117, 114, 114, 101, 110, 116, 47, 98, 105, 110, 58, 47, 117, 115, 114, 47, 108, 111, 99, 97, 108, 47, 98, 105, 110, 58, 47, 117, 115, 114, 47, 98, 105, 110, 58, 47, 98, 105, 110, 58, 47, 117, 115, 114, 47, 115, 98, 105, 110, 58, 47, 115, 98, 105, 110, 58, 47, 111, 112, 116, 47, 88, 49, 49, 47, 98, 105, 110, 58, 47, 76, 105, 98, 114, 97, 114, 121, 47, 74, 97, 118, 97, 47, 74, 97, 118, 97, 86, 105, 114, 116, 117, 97, 108, 77, 97, 99, 104, 105, 110, 101, 115, 47, 106, 100, 107, 49, 46, 56, 46, 48, 95, 53, 49, 46, 106, 100, 107, 47, 67, 111, 110, 116, 101, 110, 116, 115, 47, 72, 111, 109, 101, 47, 98, 105, 110, 58, 47, 117, 115, 114, 47, 108, 111, 99, 97, 108, 47, 115, 104, 97, 114, 101, 47, 112, 97, 99, 107, 101, 114, 58, 47, 85, 115, 101, 114, 115, 47, 106, 115, 116, 111, 114, 116, 122, 47, 46, 114, 118, 109, 47, 98, 105, 110]
"--------"
#<Encoding:UTF-8>
```

**Comment by samphippen** [comment] 2015-09-09 17:03
Hi @jstortz,

I've created a patch for this on [this branch](https://github.com/samphippen/gem-vagrant-wrapper/tree/samphippen/bugfix/mitchellh/vagrant/6056). I'm going to try and get it merged back into vagrant-wrapper, but in the mean time, it should fix your problem.

**Comment by samphippen** [comment] 2015-10-07 13:34
@mitchellh we can close this one out now. @jstortz if you need support for the old version of this gem, you can use my patch branch, otherwise the authors of vagrant wrapper [recommend you update](https://github.com/org-binbab/gem-vagrant-wrapper/issues/12).

**Comment by jstortz** [comment] 2015-10-19 14:46
@samphippen works for me now, thank you!

**Comment by samphippen** [comment] 2015-10-20 11:53
@mitchellh can we close this?
