### ISSUE TITLE
Possible regression with vagrant ssh in Vagrant 1.9.5 with Windows 10 paths

### ISSUE THREAD

**Issue by lordgordon** [mitchellh/vagrant#8711] opened 2017-06-23 17:21 UTC
### Vagrant version
``1.9.5``

### Host operating system
``Windows 10 Home 1703 64bit``

### Guest operating system
``FreeBSD 11.0``

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# make sure we have a recent Vagrant version
Vagrant.require_version ">= 1.9"

Vagrant.configure(2) do |config|
  ################################################
  # MULTI MACHINE
  ################################################

  # DEV
  config.vm.define "dev", primary: true do |dev|
    dev.vm.box = "company/DEV"
    dev.vm.box_url = "./provisioning/DEV/packer_images/DEV_machine.json"
    dev.vm.box_check_update = true

    # specific for FreeBSD
    dev.vm.guest = :freebsd
    dev.vm.base_mac = "080027D14C66" # we need this to avoid errors at vagrant up
    dev.vm.hostname = "devmachine"
  end

  ################################################
  # COMMON CONFIG
  ################################################

  # SSH config
  config.ssh.shell = "sh"
  config.ssh.private_key_path = "./provisioning/DEV/keys/custom.key"
  config.ssh.keep_alive = true

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine.
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 8888, host: 8888

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.1.42"

  # Shared Folders
  # RSYNC
  config.vm.synced_folder ".", "/vagrant", type: "rsync", id:"vagrant-rsync"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
  end
end
```

### Debug log
```
INFO ssh: Invoking SSH: ssh ["vagrant@127.0.0.1", "-p", "2222", "-o", "Compression=yes", "-o", "DSAAuthentication=yes", "-o", "LogLevel=FATAL", "-o", "IdentitiesOnly=yes", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null", "-i", "E:/Drive Company/J. Doe - COMPANY/_Repository/company-backend-stable/provisioning/DEV/keys/custom.key"]
DEBUG safe_exec: Converting command and arguments to single string for exec
DEBUG safe_exec: Command: `"ssh"` Args: `["vagrant@127.0.0.1", "-p", "2222", "-o", "Compression=yes", "-o", "DSAAuthentication=yes", "-o", "LogLevel=FATAL", "-o", "IdentitiesOnly=yes", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null", "-i", "E:/Drive Company/J. Doe - COMPANY/_Repository/company-backend-stable/provisioning/DEV/keys/custom.key"]`
DEBUG safe_exec: Converted command: ssh vagrant@127.0.0.1 -p 2222 -o Compression=yes -o DSAAuthentication=yes -o LogLevel=FATAL -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i E:/Drive Drive Company/J. Doe - COMPANY/_Repository/company-backend-stable/provisioning/DEV/keys/custom.key
Warning: Identity file E:/Drive not accessible: No such file or directory.
Permission denied (publickey).
```

### Expected behavior
``vagrant ssh`` should open the usual ssh without errors, as it did with the previous version of Vagrant I was using (``1.9.1``). Vagranfile was not changed.

### Actual behavior
``vagrant ssh`` fails with the following error:

```
Warning: Identity file E:/Drive not accessible: No such file or directory.
Permission denied (publickey).
```

The manual ``ssh`` command works fine: ``ssh.exe -i ./provisioning/DEV/keys/custom.key -p 2222 vagrant@127.0.0.1``.

It seems that Vagrant is unable to properly recognize Windows paths with spaces.

### Steps to reproduce
1. ``vagrant up``;
2. ``vagrant ssh``.

**Comment by Kellman3000** [comment] 2017-06-24 21:10
Same issue here.  The identity file path is not quoted/escaped correctly:
DEBUG safe_exec: Converted command: ssh vagrant@127.0.0.1 -p 2222 -o Compression=yes -o DSAAuthentication=yes -o LogLevel=FATAL -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i C:/users/somebloke/Documents/All Work/.vagrant/machines/dubuntu/virtualbox/private_key
Warning: Identity file C:/users/somebloke/Documents/All not accessible: No such file or directory.

If you take the full ssh command, wrapping the string in quotes, ssh works just fine as it used to:
ssh vagrant@127.0.0.1 -p 2222 -o Compression=yes -o DSAAuthentication=yes -o LogLevel=FATAL -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i "C:/users/somebloke/Documents/All Work/.vagrant/machines/dubuntu/virtualbox/private_key"

**Comment by Kellman3000** [comment] 2017-07-04 04:04
Just tested 1.9.6, and confirmed that this is resolved and working correctly now.

**Comment by chrisroberts** [comment] 2017-07-04 14:09
Hi there,

It looks like this has been resolved within the last shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Closed by chrisroberts** 2017-07-04 14:09 UTC
Labels: host/windows
