### ISSUE TITLE
Question: can 'vagrant destroy' run shell or puppet

### ISSUE THREAD

**Issue by jeff1evesque** [mitchellh/vagrant#7064] opened 2016-02-23 03:20 UTC
I was wondering if it was possible to run some kind of provisioner, upon `vagrant destroy` (i.e. shell, or puppet).  One trivial use case:

>assume we are building a content management system (cms) within a linux stack.  Suppose this cms is drupal, and my apache server repoints the document root, to the shared `/vagrant/webroot` directory.

Upon building an adequate linux stack via `vagrant up`, the drupal instance will create a corresponding `/vagrant/webroot/sites/default/settings.php`, during installation.  This file will contain database information, required to run the website.  However, if later I need to `vagrant destroy`, the shared `/vagrant` directory, will persist on the host.  So, after a successive `vagrant up`, a drupal installation will not work, because `settings.php` will already exists, without its corresponding database.

**Note:** drupal installation will not remove `settings.php`, if the corresponding sql database does not exist.

Is there a better way, than doing `vagrant destroy && ./cleanup`, where i would need to define a `cleanup` shell script?  Can I expand, and implement some kind of vagrant hook?

**Comment by sethvargo** [comment] 2016-02-23 03:27
Duplicate of https://github.com/mitchellh/vagrant/issues/2538

**Closed by sethvargo** 2016-02-23 03:27 UTC
