### ISSUE TITLE
vagrant CLI missing after upgrade to OS X 10.11 (El Capitan)

### ISSUE THREAD

**Issue by johnjamesjacoby** [mitchellh/vagrant#5809] opened 2015-06-09 12:15 UTC
After upgrading to OS X 10.11, I was greeted with:
```
me: vagrant up
bash: vagrant: command not found
```
...because `vagrant` gets moved to here:
```
/Previous System/usr/bin/vagrant
```

I attempted `sudo ln -s alias /opt/vagrant/bin/vagrant /usr/bin/vagrant` but received this failure:
```
ln: failed to create symbolic link ‘/usr/bin/vagrant’: Operation not permitted
```

My quick fix (as the only user on my machine) is an alias in `~/.bash_profile`:
```
alias vagrant=/opt/vagrant/bin/vagrant
```
A few more thoughts:
* I tried reinstalling Vagrant 1.7.2, but that didn't reinstate the original symlink either
* The alias works fine enough for my needs, but obviously isn't a long term solution
* I'm unsure exactly what permissions or directory structure changes there are, but am happy to help troubleshoot so no one else needs to install the OS X beta that doesn't want/need to already

**Comment by yveslaroche** [comment] 2015-06-09 12:21
See https://github.com/mitchellh/vagrant/issues/5807

**Comment by sethvargo** [comment] 2015-06-09 13:55
Duplicate of https://github.com/mitchellh/vagrant/issues/5807.

Please note that we will support 10.11 after the final release.

**Closed by sethvargo** 2015-06-09 13:55 UTC

**Comment by johnjamesjacoby** [comment] 2015-06-09 18:52
3 closed duplicates in less than 24 hours.

Might be worth keeping one open to avoid more work on your end from people that think they are being helpful?

**Comment by johnjamesjacoby** [comment] 2015-06-10 21:16
2 more closed duplicates.

**Comment by sethvargo** [comment] 2015-06-10 21:43
Hi @johnjamesjacoby 

In our experience, no one checks open issues either, so it's best to keep the signal-to-noise ratio at a minimum :smile:.
