### ISSUE TITLE
vagrant cannot find Ansible

### ISSUE THREAD

**Issue by mwagg** [mitchellh/vagrant#6868] opened 2016-01-13 10:47 UTC
Seeing this error this morning when trying to bring up a new box which uses the ansible_local provisioner.

I tried manually installing ansible via apt and provisioning again but get the same error.

This exact env was working fine yesterday. 

Is this possibly caused by the V2 release of ansible?

```
The Ansible software could not be found! Please verify that Ansible is correctly installed on your guest system.  If you haven't installed Ansible yet, please install Ansible on your Vagrant basebox, or enable the automated setup with the `install` option of this provisioner. Please check https://docs.vagrantup.com/v2/provisioning/ansible_local.html for more information.
```

**Comment by JamesSmaldon** [comment] 2016-01-13 11:03
I have the same problem. I think it's because the ansible-galaxy (which is called with the ansible_local provisioner to detect ansible) now exits with a non-zero code when passed the --help option.

As a workaround, I'm going to try using the shell provisioner to install an older version of ansible and set ansible.install to false (not tested yet tho).

**Comment by JamesSmaldon** [comment] 2016-01-13 11:09
If I comment out the following line in: <vagrant install dir>\embedded\gems\gems\vagrant-1.8.1\plugins\provisioners\guest.rb:54

```ruby
          @machine.communicate.execute(
            "ansible-galaxy --help && ansible-playbook --help",
            :error_class => Ansible::Errors::AnsibleNotFoundOnGuest,
            :error_key => :ansible_not_found_on_guest)
```

then it works

**Comment by mwagg** [comment] 2016-01-13 11:10
Yeah I see the same thing. `ansible-galaxy --help` exits with code 5 on ansible v2, but 0 if I manually install 1.9.4

**Comment by JamesSmaldon** [comment] 2016-01-13 11:16
I think this is really an ansible bug so I've raised https://github.com/ansible/ansible/issues/13833.

**Comment by gildegoma** [comment] 2016-01-13 11:54
Closing as it duplicate of #6793.

**Closed by gildegoma** 2016-01-13 11:54 UTC
