### ISSUE TITLE
vagrant 1.8.0 error with vmware fusion, An unexpected error occurred while loading the Vagrant VMware provider.

### ISSUE THREAD

**Issue by biemond** [mitchellh/vagrant#6699] opened 2015-12-21 23:12 UTC
I got this error right away.

    DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/synced_folders/smb/plugin.rb
     INFO manager: Registered plugin: SMB synced folders
     INFO global: Loading plugins!
     INFO manager: Registered plugin: vagrant-share
    An unexpected error occurred while loading the Vagrant VMware
    provider. Please contact support with the following
    error code: '7'.
    ERROR vagrant: Vagrant experienced an error! Details:
    ERROR vagrant: #<Vagrant::Errors::PluginLoadError: The plugins failed to load properly. The error message given is
    shown below.

    exit>
    ERROR vagrant: The plugins failed to load properly. The error message given is
    shown below.

    exit
    ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant.rb:293:in `rescue in <top (required)>'
    /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant.rb:289:in `<top (required)>'
    /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/bin/vagrant:105:in `require'
    /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/bin/vagrant:105:in `<main>'
    Vagrant failed to initialize at a very early stage:

    The plugins failed to load properly. The error message given is
    shown below.

    exit

with vagrant 1.7.4 everything works fine

Thanks

**Comment by mitchellh** [comment] 2015-12-22 00:31
This is a dupe of #6697

**Closed by mitchellh** 2015-12-22 00:31 UTC
Labels: bug, provider/vmware

**Comment by biemond** [comment] 2015-12-22 11:35
But not fixed for mac osx

**Comment by stedwick** [comment] 2015-12-22 16:05
Doesn't work for me on Mac OS X

# vagrant up
up
An unexpected error occurred while loading the Vagrant VMware
provider. Please contact support with the following
error code: '7'.
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

exit

**Comment by dominikzogg** [comment] 2015-12-22 20:35
same here on ubuntu host

**Comment by geerlingguy** [comment] 2015-12-23 04:16
Note to anyone else running into this; you can try running `vagrant plugin update` to see if that fixes things. Also, if you use the VMware plugin, you may need to [reinstall the VMware plugin](https://docs.vagrantup.com/v2/vmware/installation.html).

**Comment by dominikzogg** [comment] 2015-12-23 05:42
@geerlingguy weird, on update it meant everything is up 2 date, but uninstall and install get a new plugin version.

```{.sh}
xps13 ~ schreiner $ vagrant plugin list
vagrant-bindfs (0.4.3)
vagrant-hostmanager (1.6.1)
vagrant-share (1.1.5, system)
vagrant-vmware-workstation (4.0.1)
```
```{.sh}
xps13 ~ schreiner $ vagrant plugin uninstall vagrant-vmware-workstation
Uninstalling the 'vagrant-vmware-workstation' plugin...
```

```{.sh}
xps13 ~ schreiner $ vagrant plugin install vagrant-vmware-workstation
Installing the 'vagrant-vmware-workstation' plugin. This can take a few minutes...
Installed the plugin 'vagrant-vmware-workstation (4.0.5)'!
```

**Comment by dominikzogg** [comment] 2015-12-23 05:57
@geerlingguy both, virtualbox and vmware are usable again after the update. thank you

**Comment by biemond** [comment] 2015-12-23 09:47
they released a new vmware plugin 4.0.5 which solved for me the linked run startup error on vmware fusion (not pro)

**Comment by aleksijohansson** [comment] 2016-03-18 11:22
@dominikzogg Thanks for the info! Uninstalling and reinstalling the vagrant-vmware-fusion plugin fixed the issue for me.

**Comment by hogepodge** [comment] 2016-04-27 14:30
This may be closed, but there's still a bug in the vagrant code for updating both vagrant and the provider.
