### ISSUE TITLE
puppet provisioner executes powershell script

### ISSUE THREAD

**Issue by frusswur** [mitchellh/vagrant#7461] opened 2016-06-16 14:46 UTC
I suffer from a very strange bug of the puppet provisioner. I try to execute the puppet provisioner on windows server 2012. But vagrant executes the powershell script RunBoxStarterGist.ps1 instead of puppet provision. 
I tested the same vagrantfile with windows server 2012r2 and 2008r2. With this operating system the puppet provisioner worked correctly.

### Vagrant version
I run version 1.8.4
### Host operating system
Windows 10

### Guest operating system
Windows Server 2012

### Vagrantfile
```ruby
machine_id.vm.provision 'shell' do |s|
        s.path = 'shell/initial-setup.ps1'
      end
      machine_id.vm.provision 'shell' do |s|
        s.path = 'shell/windows/InstallBoxStarter.bat'
      end
      machine_id.vm.provision 'shell' do |s|
        s.path = 'shell/RunBoxStarterGist.ps1'
      end
    end

      machine_id.vm.provision :puppet do |puppet|
            puppet.facter = {
             'domain' => 'local',
             'kernel' => 'windows',
             'operatingsystem' => 'windows',
	     'osfamily' => 'windows',
             'provisioner_type' => 'local'
	    }
	end
        puppet.manifests_path = "puppet/manifests"
        puppet.module_path    = "puppet/modules"
      end
```
Output:
```
DEBUG puppet: Checking for shared folder: /tmp/vagrant-puppet/manifests-75f35e3bc7e32744860c4bb229c888
DEBUG winrmshell: Output: {:data=>[], :exitcode=>0}
DEBUG puppet: Checking for shared folder: /tmp/vagrant-puppet/modules-9f9ad523a881530c64fb64015e9d33fb
DEBUG winrmshell: Output: {:data=>[], :exitcode=>0}
DEBUG winrmshell: Output: {:data=>[{:stdout=>"C:\\Program Files (x86)\\Puppet Labs\\Puppet\\bin\\puppe
 INFO interface: info: Running Puppet with ...
 INFO interface: info: ==> 6f927e20: Running Puppet with ...
==> 6f927e20: Running Puppet with ...
 INFO winrm: Uploading: C:/Users/Fabian/AppData/Local/Temp/vagrant-elevated-shell20160616-7676-ovpt7vp
DEBUG winrmshell: [WinRM] opening remote shell on http://127.0.0.1:5985/wsman
DEBUG winrmshell: [WinRM] remote shell 0D275989-8CE2-4B49-B0B2-D9D3B0637E6B is open on http://127.0.0.
DEBUG winrmshell: creating hash for file c:/tmp/vagrant-elevated-shell.ps1
DEBUG winrmshell: Running check_files.ps1
DEBUG winrmshell: @{
DEBUG winrmshell:   "c:/tmp/vagrant-elevated-shell.ps1" = "bd6aa37961025954c1b30978922cde2a"
DEBUG winrmshell: }
DEBUG winrmshell: File c:/tmp/vagrant-elevated-shell.ps1 is up to date, skipping
DEBUG winrmshell: No remote files to decode, skipping
DEBUG winrmshell: Uploaded 1 items dirty_check: (0m0.47s) stream_files: (0m0.00s) decode: (0m0.00s)
DEBUG winrmshell: [WinRM] closing remote shell 0D275989-8CE2-4B49-B0B2-D9D3B0637E6B on http://127.0.0.
DEBUG winrmshell: [WinRM] remote shell 0D275989-8CE2-4B49-B0B2-D9D3B0637E6B closed
DEBUG winrm: powershell executing:
powershell -executionpolicy bypass -file 'c:/tmp/vagrant-elevated-shell.ps1' -username 'vagrant' -pass
QBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAnADsAIAAkAGUAbgB2ADoARgBBAEMAVABFAFIAXwBkAG8AbQBhAGkAbgA9ACcAbABvAGM
QBuAHYAOgBGAEEAQwBUAEUAUgBfAG8AcABlAHIAYQB0AGkAbgBnAHMAeQBzAHQAZQBtAD0AJwB3AGkAbgBkAG8AdwBzACcAOwAgACQ
gBBAEMAVABFAFIAXwBmAHEAZABuAD0AJwA2AGYAOQAyADcAZQAyADAAJwA7ACAAJABlAG4AdgA6AEYAQQBDAFQARQBSAF8AcAByAG8
AAtAC0AZABlAGIAdQBnACAALQAtAHYAZQByAGIAbwBzAGUAIAAtAC0AbQBvAGQAdQBsAGUAcABhAHQAaAAgACcALwB0AG0AcAAvAHY
ABjADYANABmAGIANgA0ADAAMQA1AGUAOQBkADMAMwBmAGIAOwAvAFAAcgBvAGcAcgBhAG0ARABhAHQAYQAvAFAAdQBwAHAAZQB0AEw
ABpAHQAYwBvAGQAZQBzACAALwB0AG0AcAAvAHYAYQBnAHIAYQBuAHQALQBwAHUAcABwAGUAdAAvAG0AYQBuAGkAZgBlAHMAdABzAC0
ABpAHQAIAAkAEwAQQBTAFQARQBYAEkAVABDAE8ARABFAA==' -execution_time_limit 'PT2H'
```

### Steps to reproduce

1. Build windows server 2012 boxcutter https://github.com/boxcutter/windows
2. Try to provision with puppet

### Expected behavior
The puppet provisioner should be executed

### Actual behavior
A powershell script will be executed

I guess there happened something strange in the tmp folder.

**Comment by sethvargo** [comment] 2016-06-16 19:25
Hi @frusswur 

I see two provisioners defined in your Vagrantfile - shell and puppet. By default, all provisioners run, and they are run in order (meaning "shell" would run before "puppet"). Does that make sense?

**Comment by frusswur** [comment] 2016-06-16 19:49
Yes, that makes sense. But puppet is never executed. Vagrant instead executes the last powershell script again.

**Comment by sethvargo** [comment] 2016-06-16 20:00
Hi @frusswur 

Can you please share your complete Vagrantfile?

```ruby
  machine_id.vm.provision 'shell' do |s|
    s.path = 'shell/initial-setup.ps1'
  end

  machine_id.vm.provision 'shell' do |s|
    s.path = 'shell/windows/InstallBoxStarter.bat'
  end

  machine_id.vm.provision 'shell' do |s|
    s.path = 'shell/RunBoxStarterGist.ps1'
  end
end

machine_id.vm.provision :puppet do |puppet|
  puppet.facter = {
  'domain' => 'local',
  'kernel' => 'windows',
  'operatingsystem' => 'windows',
  'osfamily' => 'windows',
  'provisioner_type' => 'local'
  }
  end
  puppet.manifests_path = "puppet/manifests"
  puppet.module_path    = "puppet/modules"
end
```

It looks like your Vagrantfile might have the wrong nesting, but I need to see the whole thing to confirm.

**Comment by frusswur** [comment] 2016-06-16 21:11
The vagrantfile is very large. Therefore I sent it to you via Gitter.

**Comment by sethvargo** [comment] 2016-06-16 22:16
Gitter? Please just make a gist and paste the link on this issue? I have a feeling this is an issue with your Vagrantfile, so it would be helpful if you can provide a minimum setup that reproduces the issue with just a puppet and shell provisioner.

**Comment by frusswur** [comment] 2016-06-18 06:52
I build a new base-Box with packer from scratch and now it worked with the same Vagrantfile. Apparently the problem was caused of the packer build.
Thank you for your help.

**Comment by frusswur** [comment] 2016-06-19 09:06
I have reproduced this error with this minimal Vagrantfile: https://gist.github.com/frusswur/300aa0a5a4ca3bc128c84b5d2e6eab62

I get the following error message:
```
==> default: Running provisioner: puppet...
==> default: Running Puppet with ...
==> default: Ausnahme beim Aufrufen von "Run" mit 1 Argument(en):  "Die Datei oder Assembly
==> default: "Microsoft.PowerShell.Commands.Utility" oder eine Abhängigkeit davon wurde
==> default: nicht gefunden. Das System kann die angegebene Datei nicht finden."
==> default: In C:\tmp\vagrant-elevated-shell.ps1:73 Zeichen:1
==> default: + $registered_task.Run($null) | Out-Null
==> default: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> default:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> default:     + FullyQualifiedErrorId : ComMethodTargetInvocation
```

**Comment by sethvargo** [comment] 2016-06-19 13:59
Hi @frusswur 

Thank you for that, but unfortunately I can't reproduce the issue without your puppet scripts and box. I noticed you are provisioning a Windows machine - are you sure Puppet isn't running Powershell as part of your regular provisioning?

**Comment by frusswur** [comment] 2016-06-19 14:17
The puppet script only adds users without executing a powershell script. I think it is a problem with the box or the operating system, because the same files work correctly with windows 2012r2, windows 2008r2 and windows 7.

**Comment by sethvargo** [comment] 2016-06-19 15:59
Okay - I'm going to close this as a box issue then. If you can reproduce this consistently, please let me know.

**Closed by sethvargo** 2016-06-19 15:59 UTC
Labels: waiting-reply
