### ISSUE TITLE
vagrant takes a long time to mount default share

### ISSUE THREAD

**Issue by iamjsed** [mitchellh/vagrant#8251] opened 2017-02-02 23:34 UTC
Vagrant 1.9
VirtualBox 5.1.12
BaseBox:  https://github.com/CommanderK5/packer-centos-template/releases/download/0.7.2/vagrant-centos-7.2.box
OS: Windows 7

I noticed that when I spinup a vagrant box on a partition with bitlocket enabled, it takes a long time for vagrant to mount the default share.

**Comment by chrisroberts** [comment] 2017-02-03 20:51
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by chrisroberts** [comment] 2017-03-02 19:34
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2017-03-02 19:34 UTC
Labels: waiting-reply

**Comment by iamjsed** [comment] 2017-03-21 22:28
Sorry for not responding sooner.  Yes this is not vagrant issue it turned out that the company firewall is messing with vagrant.
