### ISSUE TITLE
setting node.vm.hostname fails after using an ipv6 link-local address

### ISSUE THREAD

**Issue by ggascoigne** [mitchellh/vagrant#7561] opened 2016-07-08 19:10 UTC
Vagrant 1.8.4 running on OSX 10.11.5

When trying to set the hostname of a Windows 7 VM (running on vsphere), I get:

    te-console-win7: WinRM address: 10.248.93.60:5985
    te-console-win7: WinRM username: vagrant
    te-console-win7: WinRM execution_time_limit: PT2H
    te-console-win7: WinRM transport: negotiate

bad URI(is not URI?): http://fe80::8c73:5289:4d4:7fae:5985/wsman

The relevant part of the vagrantfile is:

```ruby
  config.vm.define 'te-console-win7' do |node|
    node.vm.box = 'tw-win7-64-ssh'
    node.vm.provider :vsphere do |v, override|
      v.template_name = 'Templates/Perf/Windows/win7pro-x64'
      v.memory_mb = 4096
      v.cpu_count = 2
      node.vm.communicator = :winrm
      node.vm.guest = :windows
    end
    node.vm.hostname = 'te-console-win7' # <-- this one!!
  end
```
Commenting out the hostname causes the VM to come up reliably.

There seem to be several issues.

1. The ipv4 address has already been detected and used so why isn't this using the same ipv4 address?
1. Why is it using the link-local address (fe80::*) at all in this context, it will always be wrong.
1. And finally, if it's going to use an ipv6 address in a url, then it should be formatted as: http://[fe80::8c73:5289:4d4:7fae]:5985/wsman

--

As a work around, it looks like disabling ipv6 support on the VM template dodges this issue, but we'd rather not do this on all of our templates.

**Comment by sethvargo** [comment] 2016-07-19 01:10
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by chrisroberts** [comment] 2016-10-03 16:05
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2016-10-03 16:05 UTC
Labels: waiting-reply
