### ISSUE TITLE
Destination path issue on windows with vagrant push

### ISSUE THREAD

**Issue by kyleweishaupt** [mitchellh/vagrant#5570] opened 2015-04-09 14:58 UTC
I'm attempting to use 'vagrant push' to copy code in the project directory to a VPS for staging. I am on a Windows 7 machine and the VPS is running Centos 6.5, as well as the Vagrant box. 

The connection appears to go through, but there is a problem with `push.destination` getting `c:\` added onto the beginning of the path at the remote side. 

Here is a copy of my Vagrantfile config for push:
```ruby
config.push.define "ftp" do |push|
    push.host = "vps.mydomain.com"
    push.username = "user"
    push.password = "password"
    push.secure = true
    push.destination = "/var/www/html/vagrant/"
    push.dir = "./public"
end
```

And here is the output of `vagrant push`:
```shell
C:\dev\myproject>vagrant push
Uploading C:/dev/myproject to user@vps.mydomain.com:/var/www/html/vagrant/
C:/HashiCorp/Vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:321:in `on_open': Net::SFTP::StatusExcept
ion open C:/var/www/html/vagrant/Vagrantfile (2, "no such file") (Net::SFTP::StatusException)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/request.rb:87:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/request.rb:87:in `respond_to'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:948:in `dispatch_request'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:911:in `when_channel_polled'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:311:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:311:in `process'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:222:in `block in preprocess'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:222:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:222:in `preprocess'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:802:in `loop'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:203:in `wait'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:103:in `upload!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/ftp/adapter.rb:114:in `upload'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/ftp/push.rb:33:in `block (2 levels) in push'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/ftp/push.rb:31:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/ftp/push.rb:31:in `block in push'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/ftp/adapter.rb:109:in `block in connect'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `block in do_version'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `do_version'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:909:in `when_channel_polled'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:311:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:311:in `process'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:222:in `block in preprocess'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:222:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:222:in `preprocess'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:802:in `loop'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:787:in `connect!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp.rb:32:in `start'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/ftp/adapter.rb:107:in `connect'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/ftp/push.rb:44:in `connect'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/ftp/push.rb:30:in `push'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:567:in `push'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/push/command.rb:28:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'
```

As you can see, there is an error `Net::SFTP::StatusException open C:/var/www/html/vagrant/Vagrantfile (2, "no such file")` where it looks like `C:/` is added on to the remote destination, even though it is a Linux server.

**Comment by smotti** [comment] 2015-04-21 08:35
Have the same issue under Linux but it seems to only effect certain files. The Vagrantfile and a README.md file that are in the default dir are being copied without any problems but for other directories within push.dir it doesn't seem to work.

If the directory exists in push.destination it works. So it looks like that directories won't be created automatically :/, if they don't exist yet.

```
  config.push.define "ftp" do |push|
    push.host = "192.168.11.230:22"
    push.username = "sysadmin"
    push.password = "password"
    push.passive = false
    push.secure = true
    push.destination = "/home/sysadmin/SensableCareHost"
    push.dir = "./"
    push.exclude = "Vagrantfile"
    push.exclude = "README.md"
  end
```

```
Uploading /home/smotti/Work/unkown/office_tw/pigeon/vivo to sysadmin@192.168.11.230:22:/home/sysadmin/SensableCareHost
/opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:321:in `on_open': Net::SFTP::StatusException open /home/sysadmin/SensableCareHost/cfengine/masterfiles/cfe_internal/CFE_cfengine.cf (2, "no such file") (Net::SFTP::StatusException)
        from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/request.rb:87:in `call'
        from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/request.rb:87:in `respond_to'
        from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:948:in `dispatch_request'
        from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:911:in `when_channel_polled'
        from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:311:in `call'
        from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:311:in `process'
        from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:223:in `block in preprocess'
        from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:223:in `each'
        from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:223:in `preprocess'
        from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:206:in `process'
        from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
        from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
        from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
        from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:802:in `loop'
        from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:203:in `wait'
        from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:103:in `upload!'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/ftp/adapter.rb:114:in `upload'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/ftp/push.rb:33:in `block (2 levels) in push'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/ftp/push.rb:31:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/ftp/push.rb:31:in `block in push'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/ftp/adapter.rb:109:in `block in connect'
        from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `call'
        from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `block in do_version'
        from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `each'
        from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `do_version'
        from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:909:in `when_channel_polled'
        from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:311:in `call'
        from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:311:in `process'
        from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:223:in `block in preprocess'
        from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:223:in `each'
        from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:223:in `preprocess'
        from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:206:in `process'
        from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
        from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
        from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
        from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:802:in `loop'
        from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:787:in `connect!'
        from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp.rb:32:in `start'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/ftp/adapter.rb:107:in `connect'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/ftp/push.rb:44:in `connect'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/ftp/push.rb:30:in `push'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:567:in `push'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/push/command.rb:28:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
        from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'
```

**Comment by sethvargo** [comment] 2015-04-21 12:42
I think the directory bug was fixed with https://github.com/mitchellh/vagrant/pull/5549, but this is still really strange. I'm going through the code and I cannot see why it would be prefixing like this. We do some magic to try and calculate the final destination on the ftp server, and I wonder if there's some expanded_path nonsense happening.

**Comment by kyleweishaupt** [comment] 2015-04-21 14:01
Just tried excluding the Vagrantfile, and the same issue happens but with an .htaccess file. 
Creating one of the subdirectories on the remote server did not help either, no files were copied.

**Comment by pichillilorenzo** [comment] 2015-05-25 15:50
I have the same issue. I'm on windows 8.1 and this is my Vagrantfile : 
```
Vagrant.configure("2") do |config|

  config.vm.box = "scotch/box"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.hostname = "scotchbox"
  config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]

  config.push.define "ftp" do |push|
    push.host = "ftp.mydomain.altervista.org:21"
    push.username = "myusername"
    push.password = "mypassword"
    push.destination = "/"
    push.dir = "./public"
  end

end
```
The output of ```vagrant push``` give me no errors, but only this:
```
Uploading C:/Users/lorenzo/Desktop/vagrant to myusername@ftp.mydomain.altervista.org
:21:/
```
The problem is that on my server it creates a folder named 'C:' and it puts in there the file of my public folder.

**Comment by InfinityWebMe** [comment] 2015-06-10 15:42
:+1

I have the same issue than pichillilorenzo " The problem is that on my server it creates a folder named 'C:' and it puts in there the file of my public folder. "

I use vagrant 1.7.2 on virtualbox 4.3.16

**Comment by oskarp** [comment] 2015-08-10 13:56
Same problem here. It creates a C: on the remote host, which it is not supposed to do. Both on Windows 8 and 10 using Vagrant 1.7.4.

**Comment by ccondrup** [comment] 2015-08-26 10:29
Same here, Win 8.1 host with Vagrant 1.7.4, trying to push from a Magestead.com box to a shared Linux webhost.

	push.dir = "magento/"
	push.destination = "/home/myuser/public_html/testmage/"
	
	Output:
	Net::SFTP::StatusException open C:/home/myuser/public_html/testmage/.gitignore (2, "no such file") (Net::SFTP::StatusException)

**Comment by apsolut** [comment] 2015-09-05 07:20
Same here.. Win8.1, Vagrant 1.7.4... was thinkin i missed something..

**Comment by ctammes** [comment] 2015-09-21 11:10
Same problem when copying from Windows 7 to Linux. The destination dir (on Linux) is added to the source dir (on Windows), creating a non-existing file.

```
  config.push.define "docker", strategy: "ftp" do |push|
      # FTP vs SFTP
      push.secure = "true"

      # Login Credentials
      push.host = "localhost:2222"
      push.username = "<user>"
      push.password = "<psw>"

      # Where are the files
      push.dir = "testscp"

      # Where to copy the files on the server
      push.destination = "/vagrant/testscp"

      # Which files to copy
      push.include = "chris.txt"
  end
```

result:
```
Uploading C:/Users/chris.tammes/PhpProjects/docker to vagrant@localhost:2222:/vagrant/testscp
C:/HashiCorp/Vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:321:in `on_open': Net::SFTP::StatusException open C:/vagrant/testscp/C:
/Users/chris.tammes/PhpProjects/docker/testscp/chris.txt (2, "no such file") (Net::SFTP::StatusException)
```

**Comment by stphivos** [comment] 2015-09-25 00:59
Not sure why C:\ is appended to the target file path in the exception message but I think the message is misleading. I was facing this issue on a mac, but only with sftp (secure = true). The implementation of FTPAdapter and SFTPAdapter is a little bit different, so try secure = false to see if it works. If it does my patch may resolve the issue for you too. See PR [#6316](https://github.com/mitchellh/vagrant/pull/6316). If it doesn't then maybe it's some File.expand_path nonsense happening as sethvargo has mentioned. I don't have a windows env to replicate but the magic happens [here](https://github.com/mitchellh/vagrant/blob/master/plugins/pushes/ftp/push.rb#L22).

**Comment by ctammes** [comment] 2015-10-06 07:34
I followed your suggestion and started to debug push.rb (C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.2\plugins\pushes\ftp\ on my disk).

First, in class Push, def push, I removed File.expand_path() from the destination line. Now, the destination path is correct. 
This copied the first file from my local testscp directory to the host, but I got an error on the second file, chris.txt. Strange, because I intended to only copy this file and not the rest (push.include in Vagrantfile).
```
Uploading C:/Users/chris.tammes/PhpProjects/docker/testscp/Vagrantfile => /vagrant/testscp/Vagrantfile
Uploading C:/Users/chris.tammes/PhpProjects/docker/testscp/chris.txt => /vagrant/testscp/C:/Users/chris.tammes/PhpProjects/docker/testscp/chris.txt
C:/HashiCorp/Vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:321:in `on_open': Net::SFTP::StatusException open /vagrant/testscp/C:/U
sers/chris.tammes/PhpProjects/docker/testscp/chris.txt (2, "no such file") (Net::SFTP::StatusException)
```

So then I removed the push.include in the Vagrantfile and now all files were copied as expected.

Apparently, there is an issue with File.expand_path() when copying from Windows to Linux.

There is also a problem with push.include. When I use push.include and print the files array it looks like this, which is correct:
```
{"C:/Users/chris.tammes/PhpProjects/docker/testscp/Vagrantfile"=>"/vagrant/testscp/Vagrantfile", "C:/Users/chris.tammes/PhpProjects/docker/testscp/chris.txt"=>"
/vagrant/testscp/C:/Users/chris.tammes/PhpProjects/docker/testscp/chris.txt", "C:/Users/chris.tammes/PhpProjects/docker/testscp/install-docker.sh"=>"/vagrant/te
stscp/install-docker.sh", "C:/Users/chris.tammes/PhpProjects/docker/testscp/test_loggedin.sh"=>"/vagrant/testscp/test_loggedin.sh"}
```

However, when I walk through this array, the result is different for the second file:
```
files.each do |local, remote|
  env.ui.info "Uploading #{local} => #{remote}"
end

Uploading C:/Users/chris.tammes/PhpProjects/docker/testscp/Vagrantfile => /vagrant/testscp/Vagrantfile
Uploading C:/Users/chris.tammes/PhpProjects/docker/testscp/chris.txt => /vagrant/testscp/C:/Users/chris.tammes/PhpProjects/docker/testscp/chris.txt
Uploading C:/Users/chris.tammes/PhpProjects/docker/testscp/install-docker.sh => /vagrant/testscp/install-docker.sh
Uploading C:/Users/chris.tammes/PhpProjects/docker/testscp/test_loggedin.sh => /vagrant/testscp/test_loggedin.sh
```

**Comment by ctammes** [comment] 2015-10-06 11:59
I made changes to two files, which makes the push work for me (Windows -> Linux via SFTP).

push.rb
```
22: 
destination = File.join(config.destination, relative_path)
```

adapter.rb:
```
122:
      def upload(local, remote)
        parent = File.dirname(remote)
        fullpath = Pathname.new(parent)
        fullpath.descend do |path|
          unless check_dir_exists? path.to_s  
            @server.mkdir(path.to_s)
          end  
        end
        
        @server.upload!(local, remote, mkdir: true)
      end
      
      def check_dir_exists?(path)
        begin
          @server.opendir!(path) do |response|
            return false unless response.ok?
            @server.close(response[:handle])
            return true
          end
        end
      end

```

**Comment by ctammes** [comment] 2015-10-06 12:33
PR 6365 seems to solve the same problem as PR 6316 (stphivos). Sorry ...

**Comment by stphivos** [comment] 2015-10-11 19:45
@ctammes you are right, "File.expand_path" does not seem to be necessary when calculating the destination file path, whether someone is using a linux/mac or windows environment. I also changed it from
```ruby
destination = File.expand_path(File.join(config.destination, relative_path))
```
to
```ruby
destination = File.join(config.destination, relative_path)
```
and it works as expected.

Also about the other issue, the reason I rewrote the logic that checks whether a destination directory exists was to reduce the number of ftp queries and make it a bit faster. But merging either patch serves the purpose well!

**Comment by ctammes** [comment] 2015-10-12 05:38
Your patch is better, so I withdrew my pull request. I had entered it before checking your code properly.

**Comment by blsn** [comment] 2015-11-14 14:59
Trying to copy code in the project directory to a VPS. 
I am on a Windows 7 VirtualBox machine and the VPS is running Ubuntu 14.04
I have the same problem and I get the same result with localhost:
```    
config.push.define "ftp" do |push|
  push.host = "localhost:2222"
  push.username = "vagrant"
  push.password = "vagrant"
  push.dir = "/home/vagrant/sites/test"
  push.destination = "/var/www/test"
  push.secure = true
end
```
**Nothing happens** and here is the output of ```vagrant push```:
Uploading C:/Users/Mike/web/Homestead to vagrant@localhost:2222:/var/www/test

**Comment by mitchellh** [comment] 2015-11-18 22:01
Fixed by #6364

**Closed by mitchellh** 2015-11-18 22:01 UTC
Labels: bug, pushes/ftp

**Comment by yckart** [comment] 2016-03-08 23:33
Why is it closed?

```
/opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:321:in `on_open': Net::SFTP::StatusException open /var/www/somefoldername (2, "no such file") (Net::SFTP::StatusException)
```

- OS X 10.11.3
- Vagrant 1.8.1
- Ruby 2.2.3

**Comment by mitchiru** [comment] 2016-04-25 08:11
Same Issue here with V 1.81

`/opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:321:in `on_open': Net::SFTP::StatusException open /var/www/virtual/online/libs/typo3_src-7.6.5/CONTRIBUTING.md (2, "no such file") (Net::SFTP::StatusException)
	from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/request.rb:87:in `call'
	from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/request.rb:87:in `respond_to'
	from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:948:in `dispatch_request'
	from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:911:in `when_channel_polled'
	from /opt/vagrant/embedded/gems/gems/net-ssh-3.0.1/lib/net/ssh/connection/channel.rb:311:in `call'
	from /opt/vagrant/embedded/gems/gems/net-ssh-3.0.1/lib/net/ssh/connection/channel.rb:311:in `process'
	from /opt/vagrant/embedded/gems/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:223:in `block in preprocess'
	from /opt/vagrant/embedded/gems/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:223:in `each'
	from /opt/vagrant/embedded/gems/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:223:in `preprocess'
	from /opt/vagrant/embedded/gems/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:206:in `process'
	from /opt/vagrant/embedded/gems/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:170:in `block in loop'
	from /opt/vagrant/embedded/gems/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:170:in `loop'
	from /opt/vagrant/embedded/gems/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:170:in `loop'
	from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:802:in `loop'
	from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:203:in `wait'
	from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:103:in `upload!'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/pushes/ftp/adapter.rb:123:in `upload'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/pushes/ftp/push.rb:33:in `block (2 levels) in push'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/pushes/ftp/push.rb:31:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/pushes/ftp/push.rb:31:in `block in push'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/pushes/ftp/adapter.rb:118:in `block in connect'
	from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `call'
	from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `block in do_version'
	from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `each'
	from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `do_version'
	from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:909:in `when_channel_polled'
	from /opt/vagrant/embedded/gems/gems/net-ssh-3.0.1/lib/net/ssh/connection/channel.rb:311:in `call'
	from /opt/vagrant/embedded/gems/gems/net-ssh-3.0.1/lib/net/ssh/connection/channel.rb:311:in `process'
	from /opt/vagrant/embedded/gems/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:223:in `block in preprocess'
	from /opt/vagrant/embedded/gems/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:223:in `each'
	from /opt/vagrant/embedded/gems/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:223:in `preprocess'
	from /opt/vagrant/embedded/gems/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:206:in `process'
	from /opt/vagrant/embedded/gems/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:170:in `block in loop'
	from /opt/vagrant/embedded/gems/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:170:in `loop'
	from /opt/vagrant/embedded/gems/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:170:in `loop'
	from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:802:in `loop'
	from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:787:in `connect!'
	from /opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp.rb:32:in `start'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/pushes/ftp/adapter.rb:116:in `connect'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/pushes/ftp/push.rb:44:in `connect'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/pushes/ftp/push.rb:30:in `push'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:618:in `push'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/push/command.rb:28:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:302:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:174:in `<main>'
`

**Comment by sergeymorkovkin** [comment] 2016-05-29 13:16
Confirm. Reproduces with 1.8.1. Uploading from OS X to Ubuntu.

**Comment by stphivos** [comment] 2016-05-29 16:58
Guys, the fix is only in master still: https://github.com/mitchellh/vagrant/blob/master/plugins/pushes/ftp/adapter.rb#L128
