### ISSUE TITLE
Rsync Issue

### ISSUE THREAD

**Issue by pete-hodgman** [mitchellh/vagrant#5547] opened 2015-04-01 12:49 UTC
I am not sure what is causing this. Its not clear if it is something I have configured incorrectly in Vagrant or something else. I intermittently get an rsync error when using Vagrant to rsync files to an AWS EC2 host. Please see the error below. It does not happen always but it does happen from time to time.

```text
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /Users/pete/dev/inv/ba/XOSPassport/scripts/
Guest path: /bimassure/XOSPassport/scripts
Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group --rsync-path sudo rsync -e ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '/Users/pete/dev/devops/vagrant/awstest/vagkey.pem' --exclude .vagrant/ /Users/pete/dev/inv/ba/XOSPassport/scripts/ ubuntu@54.227.251.229:/bimassure/XOSPassport/scripts
Error: Connection closed by 54.227.251.229
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /SourceCache/rsync/rsync-45/rsync/io.c(453) [sender=2.6.9]
```

**Comment by sethvargo** [comment] 2015-04-01 13:54
Hi @pete-hodgman 

Could you please run the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html) and Gist the output? Thank you!

**Comment by pete-hodgman** [comment] 2015-04-01 14:35
Hi,

The gist can be found here... 

https://gist.github.com/pete-hodgman/742032ae015bb497dcfb

**Comment by sethvargo** [comment] 2015-04-01 14:49
Hi @pete-hodgman 

Are you using Windows by chance? I have seen this issue with certain windows terminal programs. Additionally, error code 12 sometimes means incompatible versions of rsync - can you check the version of rsync installed on your local machine versus the one installed on the guest?

**Comment by pete-hodgman** [comment] 2015-04-01 14:52
Thanks. Here is my environment

Mac - Yosemite
RSync on Mac 3.1.1
RSync on AWS  box 3.0.9

Any thoughts.. ?

**Comment by sethvargo** [comment] 2015-04-01 15:06
Hrm. What happens if you upgrade rsync to a version in the 3.1 series on the AWS box?

**Comment by pete-hodgman** [comment] 2015-04-01 19:58
The same issue occurs. I do not believe its a protocol issue. Thoughts?

**Comment by mitchellh** [comment] 2015-07-09 17:03
If you run the command manually, does this still occur? 

Closing since we cant' reproduce on our end, but if we can get a reliable reproduction case, we'll fix.

**Closed by mitchellh** 2015-07-09 17:03 UTC
Labels: bug, synced-folders/rsync
