### ISSUE TITLE
undefined variable in vagrant/plugins/guests/linux/cap/mount_smb_shared_folder.rb

### ISSUE THREAD

**Issue by jean-kiepura-consultant** [mitchellh/vagrant#8411] opened 2017-03-25 20:54 UTC
### Vagrant version
1.9.3

### Host operating system
Windows 10

### Guest operating system
Ubuntu Trusty 14.04 LTS x64

### Vagrantfile
```ruby
# -*- mode: ruby -*-

dir = File.dirname(File.expand_path(__FILE__))

require 'yaml'
require "#{dir}/puphpet/ruby/deep_merge.rb"
require "#{dir}/puphpet/ruby/to_bool.rb"
require "#{dir}/puphpet/ruby/puppet.rb"

configValues = YAML.load_file("#{dir}/puphpet/config.yaml")

provider = ENV['VAGRANT_DEFAULT_PROVIDER'] ? ENV['VAGRANT_DEFAULT_PROVIDER'] : 'local'
if File.file?("#{dir}/puphpet/config-#{provider}.yaml")
  custom = YAML.load_file("#{dir}/puphpet/config-#{provider}.yaml")
  configValues.deep_merge!(custom)
end

if File.file?("#{dir}/puphpet/config-custom.yaml")
  custom = YAML.load_file("#{dir}/puphpet/config-custom.yaml")
  configValues.deep_merge!(custom)
end

data = configValues['vagrantfile']

Vagrant.require_version '>= 1.8.1'

Vagrant.configure('2') do |config|
  eval File.read("#{dir}/puphpet/vagrant/Vagrantfile-#{data['target']}")
end

```
### Expected behavior
mouting smb share on the VM using settings in the phphpet config file

### Actual behavior
an error occurs:
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/guests/linux/cap/mount_smb_shared_folder.rb:18:in `mount_smb_shared_folder': undefined local variable or method `guest_path' for VagrantPlugins::GuestLinux::Cap::MountSMBSharedFolder:Class (NameError)

The error seems to be caused by a typo in the file mount_smb_shared_folder.rb at line 18, a local variable guest_path should probably be typed "expanded_guest_path"

**Comment by chrisroberts** [comment] 2017-03-26 00:06
Duplicate of #8404

**Closed by chrisroberts** 2017-03-26 00:06 UTC
Labels: bug, duplicate, synced-folders/smb
