### ISSUE TITLE
Bootstrapping Salt Fails Due to Salt-Boostrap Update

### ISSUE THREAD

**Issue by JoePortlandME** [mitchellh/vagrant#6029] opened 2015-07-23 12:21 UTC
See the below commit / comment - recent update to salt-bootstrap.sh causes boostrapping of salt to fail.

The "-P" flag is needed to allow PIP-based install - I have submitted comment to see if Tornado can be installed via apt-get instead of PIP to avoid needing this flag...

https://github.com/saltstack/salt-bootstrap/commit/0b5524317258a715f2ceb4c69e89530f15bfe05f

**Comment by JoePortlandME** [comment] 2015-07-23 20:42
This issue is resolved with the following configuration change to the Vagrantfile:
```
 config.vm.provision :salt do |salt|
	
       salt.bootstrap_options = "-P"
       salt.minion_config = "salt/minion"
       salt.run_highstate = true

   end
```

Not sure if the "-P" flag should be called by default from Vagrant to prevent this error from occurring when a PIP-Install based dependency is needed for salt-bootstrap...

**Comment by dkerkow** [comment] 2015-07-28 09:56
@JoePortlandME the "-P" flag fix does not work for me with the precise box.

**Comment by jrosskopf** [comment] 2015-07-28 10:05
Does not work for me neither.

2015-07-28 11:56 GMT+02:00 Daniel Kerkow <notifications@github.com>:

**Comment by GregMeno** [comment] 2015-07-29 22:00
@dkerkow One thing you can do is 
curl -o install_salt.sh -L https://bootstrap.saltstack.com/develop
then add
salt.bootstrap_script = "install_salt.sh"
to your Vagrantfile

**Comment by Phlip** [comment] 2015-08-03 22:59
Trouble magnet, here. The "-P" doesn't work, and the "install_salt.sh" seems to be worknig. Vivid Vervet on amd64.

(and can we turn "man-db" off? who reads documentation inside a virtual device?)

**Comment by clintberry** [comment] 2015-08-06 21:20
I am using a box with salt already installed, and I see in the logs that it detects salt is there, then it tries to run bootstrap anyway. I just updated from 1.7.2 to 1.7.4 as well. 1.7.2 behaves correctly. I'm assuming this is related?

**Comment by darkn3rd** [comment] 2015-08-11 23:09
#6011 looks similar to #6103, and #6103 was closed as a duplicate of this bug, thus is #6011 the same as this issue?  They look different.

**Comment by darkn3rd** [comment] 2015-08-12 01:22
Note.  I  could **NOT** reproduce this issue, with the `-P` message on the following using the configuration below:
  - Cent OS 6.6 (`chef/centos-6.6`)
  - Debian Wheezy (`puppetlabs/debian-7.8-64-puppet`)

I only have to add the `-F -c /tmp`, and it seems to work.

My configuration snippet that works fine with Cent OS 6.6 and Debian Wheezy:

```Ruby
  config.vm.provision :salt do |salt|
    salt.run_highstate = true
    salt.minion_config = "../../provisioning/minion"
    salt.bootstrap_options = "-F -c /tmp"
    salt.verbose = true
  end
```

Now with Ubuntu Precise (`puppetlabs/ubuntu-12.04-64-puppet`), I have been having weird behavior.  At first it would error out saying I needed `-C`, so then I commented out the line with the `-F -c /tmp`, then I would get:

`* ERROR: You need to allow pip based installations (-P) in order to install the python package 'tornado >= 4.0'`

**Comment by darkn3rd** [comment] 2015-08-12 01:34
Alright, due to bug #6011, with Ubuntu Precise 12.04, you need to do the following to work around this issue:
```ruby
  config.vm.provision :salt do |salt|
    # ... 
    salt.bootstrap_options = "-F -c /tmp -P"      # Vagrant Issues #6011, #6029
    # ...
  end
```

**Comment by mafrosis** [comment] 2015-08-27 12:27
There's a whole lot of noise around this issue.

Another data point for anyone looking into a solution:

Since 1.7.4, when using a box with Salt already installed, I need:
- `-F` in order to overwrite the existing minion config
- `-c /tmp` or the salt bootstrap script fails entirely

**Comment by mitchellh** [comment] 2015-11-20 17:41
I believe a fix is in with the latest PR merges. Please verify with Vagrant 1.8 and if the issue persist please reopen. Thanks!

**Closed by mitchellh** 2015-11-20 17:41 UTC
Labels: bug, provisioner/salt
