### ISSUE TITLE
Plugin winrm-fs is out of date and contains bugs (currently 0.3.2, latest version is 0.4.3)

### ISSUE THREAD

**Issue by TheFrogDaddy** [mitchellh/vagrant#7526] opened 2016-06-27 21:02 UTC
### Vagrant version

1.8.4
### Host operating system

OSX El Capitan
### Guest operating system

Windows 10
### Expected behavior

winrm-fs plugin be a recent version >= 4.0
### Actual behavior

winrm-fs plugin is out of date and contains bugs which preventing provisioning of a windows box after installing chocolatey
### References

This was my original issue, the devs of winrm-fs have informed me that the latest versions resolves my issue.

https://github.com/chocolatey/choco/issues/834

**Comment by StefanScherer** [comment] 2016-07-01 08:35
I manually updated winrm-fs 0.4.3 in vagrant 1.8.4 with [these steps](https://github.com/mitchellh/vagrant/issues/7476#issuecomment-229887350) and I can work with it for a while. Only a minor issue is that some parts of the WinRM output is now visisble:

<img width="622" alt="bildschirmfoto 2016-07-01 um 10 33 31" src="https://cloud.githubusercontent.com/assets/207759/16516257/5d81cd3c-3f77-11e6-9155-8c9e31d1f23a.png">

**Comment by TheFrogDaddy** [comment] 2016-07-07 07:20
Thanks @StefanScherer , I'll give those steps a go.

**Comment by StefanScherer** [comment] 2016-07-07 07:26
@TheFrogDaddy but be warned as Seth mentioned in #7476 there may be new issues.
Yesterday I got a reproducible error creating a Windows Domain Controller with a PowerShell provision script that the WinRM login failed.

I now have switched back to Vagrant 1.8.1 without any patches to it and using the embedded winrm-1.3.6 and winrm-fs 0.2.3.

Ping me if someone needs this scenario and provision scripts to test against newer winrm/winrm-fs versions.

**Comment by dragon788** [comment] 2016-07-18 17:40
@StefanScherer @TheFrogDaddy This may be an issue in the underlying WinRb/WinRM gem, not sure if it is patched in the version you mention above as there is still an open issue, https://github.com/WinRb/winrm-fs/issues/18.

**Comment by chrisroberts** [comment] 2017-03-02 00:54
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Closed by chrisroberts** 2017-03-02 00:54 UTC
Labels: bug, communicator/winrm, core, has-pr
