### ISSUE TITLE
ansible is failing to provision docker provider in vagrant

### ISSUE THREAD

**Issue by jcheung0** [mitchellh/vagrant#5724] opened 2015-05-16 17:16 UTC
Hi I'm trying to provision my docker container with ansible but when I run a vagrant provision ansible is unable to reach the docker container. Below is last command it tries to run before it fails.

```
EXEC ssh -C -tt -vvv -o ProxyCommand=ssh  -p 2222 -i /Users/jcheung/.vagrant.d/insecure_private_key -o Compression=yes -o ConnectTimeout=5 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ForwardAgent=yes exec nc %h %p 2>/dev/null -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/jcheung/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o IdentityFile="/Users/jcheung/Dev/VMS/vm-build/phusion.key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 10.1.0.4 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1431795795.19-163874062635763 && echo $HOME/.ansible/tmp/ansible-tmp-1431795795.19-163874062635763
```
```
fatal: [default] => SSH Error: ssh_exchange_identification: Connection closed by remote host
```

**Comment by gildegoma** [comment] 2015-05-18 14:46
@jcheung0 Could you please provide following information:

* Your Host Operating System *(it seems to be OS X)*
* Your Vagrant Version
* a `Vagrantfile` able to reproduce the problem
* The `ansible-playbook` command executed by Vagrant (This command is displayed just after the `Running provisioner: ansible...` line when the `ansible.verbose` option is enabled).

Note that [Version 1.7.1 or above](https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#171-december-11-2014) is required for a seamless Docker integration when running Vagrant from a non-Linux host, see #4906.

**Comment by jcheung0** [comment] 2015-05-19 17:53
Hi I'm currently using OSX Yosemite (10.10.3) and my Vagrant version is 1.7.2 below is the repo to the provisioner

https://github.com/jcheung0/Vagrant-Docker-CoreOS

**Comment by gildegoma** [comment] 2015-05-27 06:22
Thanks @jcheung0! I can reproduce the problem with the debugging repository you provided.

Please note that there is no issue when I integrate with an other Docker host (e.g. default `mitchellh/boot2docker`), but so far I have no idea about the difference in [`coreos-vagrant`](https://github.com/coreos/coreos-vagrant) that leads to the SSH tunnel failure.

Personally, I don't have time to further investigate. Maybe some other Vagrant users can help, and it might be worth to ask via google mailing list or IRC channel.

**Comment by gildegoma** [comment] 2016-05-26 16:57
Closing as this issue was specific to the `coreos-vagrant` intermediate Docker host (things working fine with other docker host). Please bring more information if you want to keep working on this problem.

**Closed by gildegoma** 2016-05-26 16:57 UTC
Labels: bug, needs info, provider/docker, provisioner/ansible
