### ISSUE TITLE
Ansible provision via ansible-pull

### ISSUE THREAD

**Issue by certifiedloud** [mitchellh/vagrant#6511] opened 2015-11-11 21:37 UTC
Would it be possible to change the way the Ansible provisioner works to use `ansible-pull` so that the guest machine can provision itself even when the host machine is running Windows?

It would involve getting Ansible installed within the guest machine, which might be a deal-breaker.

**Comment by sethvargo** [comment] 2015-11-11 21:59
@gildegoma

**Comment by gildegoma** [comment] 2015-11-12 07:58
@certifiedloud this feature is planned to be introduced in Vagrant 1.8.0, with the introduction of an alternative provisioner: `ansible_local`, see #6500. 
This new provisioner provides already some capabilities to auto-install Ansible on the guest (and this will certainly be improved in the future). It is of course also possible to prepare a vagrant base box preinstalled with the desired Ansible version (e.g. with packer).

Please have a look at the upcoming [documentation](https://github.com/mitchellh/vagrant/blob/9bfdaf7e75d710aac42c65f68d9999c4f7c92798/website/docs/source/v2/provisioning/ansible_local.html.md) (or [code](https://github.com/mitchellh/vagrant/commit/9bfdaf7e75d710aac42c65f68d9999c4f7c92798)), and tell us if it can satisfy your needs.

Note that this new provisioner doesn't rely on `ansible-pull` tool (which behaviour cannot fit with the Vagrant workflow), but uses `ansible-playbook` tool with [local connection mode](http://docs.ansible.com/ansible/glossary.html#local-connection).

Closing as duplicate of #2103.

**Closed by gildegoma** 2015-11-12 07:58 UTC

**Comment by certifiedloud** [comment] 2015-11-13 15:03
This is fantastic @gildegoma! This opens ansible up as a provisioner for my windows users. I can't wait for 1.8. Thank you for making me aware.

**Comment by gildegoma** [comment] 2015-11-13 20:41
@certifiedloud :+1:
