### ISSUE TITLE
Can't connect to Virtualbox using vagrant up 

### ISSUE THREAD

**Issue by arashabtahi** [mitchellh/vagrant#8662] opened 2017-06-09 00:06 UTC
I keep getting this error message when trying to connect to virtualbox.

> $ vagrant up
> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Importing base box 'bento/ubuntu-16.04-i386'...
> ==> default: Matching MAC address for NAT networking...
> ==> default: Checking if box 'bento/ubuntu-16.04-i386' is up to date...
> ==> default: Setting the name of the VM: vagrant_default_1496966266239_11678
> ==> default: Clearing any previously set network interfaces...
> ==> default: Preparing network interfaces based on configuration...
>     default: Adapter 1: nat
> ==> default: Forwarding ports...
>     default: 8000 (guest) => 8000 (host) (adapter 1)
>     default: 8080 (guest) => 8080 (host) (adapter 1)
>     default: 5000 (guest) => 5000 (host) (adapter 1)
>     default: 22 (guest) => 2222 (host) (adapter 1)
> ==> default: Running 'pre-boot' VM customizations...
> ==> default: Booting VM...
> ==> default: Waiting for machine to boot. This may take a few minutes...
>     default: SSH address: 127.0.0.1:2222
>     default: SSH username: vagrant
>     default: SSH auth method: private key
> Timed out while waiting for the machine to boot. This means that
> Vagrant was unable to communicate with the guest machine within
> the configured ("config.vm.boot_timeout" value) time period.
> 
> If you look above, you should be able to see the error(s) that
> Vagrant had when attempting to connect to the machine. These errors
> are usually good hints as to what may be wrong.
> 
> If you're using a custom box, make sure that networking is properly
> working and you're able to connect to the machine. It is a common
> problem that networking isn't setup properly in these boxes.
> Verify that authentication configurations are also setup properly,
> as well.
> 
> If the box appears to be booting properly, you may want to increase
> the timeout ("config.vm.boot_timeout") value.

I've tried

-removing antivirus
- reinstalling both vagrant and VB
-changing guest and host port
-connecting to the internet with cable instead of wifi

**Comment by arashabtahi** [comment] 2017-06-09 00:26
I went to VirtualBox property and marked "run as administrator" 

I got this message 

> $ vagrant up
> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Checking if box 'bento/ubuntu-16.04-i386' is up to date...
> ==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
> ==> default: flag to force provisioning. Provisioners marked to run always will still run.

**Comment by dradetsky** [comment] 2017-06-11 22:09
@arashabtahi this looks like the issues I solved in #8668. I'm guessing you're on windows, but that shouldn't matter. Please do me a favor and check the output of `vagrant status` from the directory after `vagrant up` fails via timeout before trying the fix.

**Comment by arashabtahi** [comment] 2017-06-11 23:05
Problem solved. Thank you.

**Comment by dradetsky** [comment] 2017-06-12 08:38
_sighs_ next time i'm going to ask for the data first...

**Comment by chrisroberts** [comment] 2017-06-13 00:15
Closing as the issue is resolved.

**Closed by chrisroberts** 2017-06-13 00:15 UTC

**Comment by Cankopy** [comment] 2017-11-30 04:10
Hi @arashabtahi, I am with the same issue.
How do you fixed that?

**Comment by arashabtahi** [comment] 2017-11-30 05:13
My problem was that my laptop had virtualization disabled. You have to enable it if it's already not

________________________________

**Comment by Cankopy** [comment] 2017-11-30 14:46
@arashabtahi thank you.
Now is working here.

This is the steps I did to solved that:

1. Enable virtualization 
https://stackoverflow.com/questions/46723611/vagrant-timed-out-while-waiting-for-the-machine-to-boot-in-windows-10

2. Uninstall the VM  
https://it.nmu.edu/docs/uninstalling-oracle-vm-virtualbox-resolve-connection-problems

3. Reinstall the VM again

**Comment by ZondaHTR** [comment] 2018-06-02 12:00
Hello @arashabtahi. I had the same issue and what i did to fix it was just a repairment of Vagrant at Control Panel->Programs->Program and feature, select vagrant and then repair. 
I'm using windows 7. I hope that its gonna solve your and others issue too.

**Comment by ZondaHTR** [comment] 2018-06-02 12:02
Hello @arashabtahi. I had the same issue and what i did to fix it was just a repairment of Vagrant at Control Panel->Programs->Program and feature, select vagrant and then repair.
I'm using windows 7. I hope that this is going to be a solution for  most of you.

**Comment by idreesandroid** [comment] 2019-05-21 05:37
my virtualization is enable
i reinstall the virtual box yet i face again this error

E:\vagrant>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'chrislentz/trusty64-lamp' version '3.0.0' is up to date...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

**Comment by anaskhalid98** [comment] 2019-07-17 12:21
> my virtualization is enable
> i reinstall the virtual box yet i face again this error
> 
> E:\vagrant>vagrant up
> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Checking if box 'chrislentz/trusty64-lamp' version '3.0.0' is up to date...
> ==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
> ==> default: flag to force provisioning. Provisioners marked to run always will still run.

me too i have the same probleme ????

**Comment by xacaxulu** [comment] 2019-07-30 14:27
+1

**Comment by rluiseugenio** [comment] 2019-09-04 16:46
+1
