### ISSUE TITLE
Run provisioner regardless of errors in previous provisioners

### ISSUE THREAD

**Issue by TomyLobo** [mitchellh/vagrant#7260] opened 2016-04-25 15:18 UTC
Please add a way to always run a certain provisioner regardless of errors in previous provisioners in the same Vagrantfile.

For example, say I have the following Vagrantfile:
````ruby
Vagrant.configure(2) do |config|
  config.vm.box = "bar"

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "default.pp"
  end

  config.vm.provision "shell", inline: "echo Thank you for using foo, red text means blah, please report to bleh@example.com"
end
````

If the puppet provisioner fails, the user never gets to see the text telling them where to send error reports.
I wanted to run an error analysis script on the box that tells the user what may be wrong and how to solve it.

**Comment by sethvargo** [comment] 2016-04-25 21:55
Hi @TomyLobo 

This is actually a duplicate of https://github.com/mitchellh/vagrant/pull/4765. Please see the comments and reasons there. Thanks! 😄

**Closed by sethvargo** 2016-04-25 21:55 UTC

**Comment by TomyLobo** [comment] 2016-04-26 06:58
That issue is about printing a message. Granted my example is about that as well, but my proposal goes far beyond that, in that it allows executing arbitrary commands.
Also, I'd need to output/execute things on failure, too, not just on success.

**Comment by TomyLobo** [comment] 2016-04-26 07:40
I tried the vagrant-triggers plugin, and you can config.trigger.after :provision, but there are two major problems and one minor problem with that approach:

1. It doesn't trigger on "vagrant up" with no box created
2. Like a provisioner at the end, it doesn't trigger if a previous provisioner failed
3. I'd have to recode half of the shell provisioner logic

I can certainly solve point 3 and point 2 may be solvable by using config.trigger.instead_of :provision, but point 1 means that plugin isn't useful for me.

**Comment by TomyLobo** [comment] 2016-04-26 08:21
I went through the code and it seems that failed provisioners throw an exception which is caught only very late.
That makes implementing this feature in a patched version not at all trivial.
It also means I can't just write a plugin to implement this feature and it explains why the vagrant-triggers plugin doesn't trigger after a provisioner failure.

**Comment by TomyLobo** [comment] 2016-05-13 08:27
@sethvargo I think you did not properly read my original post. Two weeks ago, I posted comments explaining what you missed. Can you please re-evaluate your decision to close this issue after reading my additional comments?
