### ISSUE TITLE
Vagrant push error on Windows 7

### ISSUE THREAD

**Issue by CruzanCaramele** [mitchellh/vagrant#6262] opened 2015-09-12 16:29 UTC
#### When I try to push my application to Atlas I get the following error:

```
c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/safe_exec
.rb:22:in `fork': fork() function is unimplemented on this machine (NotImplement
edError)
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/u
til/safe_exec.rb:22:in `exec'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/pushe
s/atlas/push.rb:35:in `execute'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/pushe
s/atlas/push.rb:17:in `push'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/e
nvironment.rb:567:in `push'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/comma
nds/push/command.rb:28:in `execute'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/c
li.rb:42:in `execute'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/e
nvironment.rb:301:in `cli'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:1
74:in `<main> ```

**Comment by volcomism** [comment] 2015-10-30 10:03
Pretty sure your issue is duped here: 
https://github.com/mitchellh/vagrant/issues/5307

**Comment by sethvargo** [comment] 2015-11-08 00:41
Duplicate of #5307 - please track that issue :smile:

**Closed by sethvargo** 2015-11-08 00:41 UTC
