### ISSUE TITLE
Docker provision not working correctly?

### ISSUE THREAD

**Issue by saitheexplorer** [mitchellh/vagrant#5245] opened 2015-01-24 23:13 UTC
When provisioning a box (using VB for provider) with Docker using this code: 

```
config.vm.provision "docker",
    images: ["debian:7.8"]
```

and running `vagrant up`, I'm getting this error: 

```
==> default: Running provisioner: docker...
    default: Installing Docker (latest) onto machine...
    default: Configuring Docker to autostart containers...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

stop docker

Stdout from the command:



Stderr from the command:

stdin: is not a tty
bash: line 2: stop: command not found
```

Running `vagrant reload --provision` then fixes the issue, but not sure why it doesn't work the first time.

**Comment by ngommenginger** [comment] 2015-02-13 14:41
Same problem here.
Did you find any solution?

**Comment by brentnk** [comment] 2015-02-26 02:52
Which config.vm.box are you guys running?  I ran into this as well but switching from "puphpet/debian75-x64" to "ubuntu/trusty64" got rid of the issue. 
I haven't yet tried it with other images but Debian could be the issue here.

```
Vagrant.configure(2) do |config|
  # config.vm.box = "puphpet/debian75-x64" <--- stop docker error
  config.vm.box = "ubuntu/trusty64" # <--- no stop docker error

  config.vm.synced_folder "./", "/workspace"

  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provision "docker"

end
```

**Comment by brentnk** [comment] 2015-02-26 04:15
Ok so, I think this is due to Debian not supporting Upstart out of the box which Ubuntu does.  [docker_configure_auto_start.rb](https://github.com/mitchellh/vagrant/blob/efd1d5e11bfc5a72c7a1d1eae294b4751d841544/plugins/provisioners/docker/cap/debian/docker_configure_auto_start.rb) checks to see if the docker options have been set and if they haven't it tries to add them then restart Docker with
```Ruby
if !comm.test('grep -q \'\-r=true\' /etc/default/docker')
                comm.sudo("echo 'DOCKER_OPTS=\"-r=true ${DOCKER_OPTS}\"' >> /etc/default/docker")
                comm.sudo("stop docker")
                comm.sudo("start docker")
                ...
end
```
You can see that the first time that the commands aren't found they are added before `stop docker` is called.  When you `vagrant reload --provision` the options are already set so the command is not called. 
Could this be fixed by replacing the
```
comm.sudo("stop docker")
comm.sudo("start docker")
```
with `comm.sudo("service docker restart")` ?

**Comment by ngommenginger** [comment] 2015-02-26 08:24
You're right, the issue is due to Debian. I also switched to ubuntu (phusion/ubuntu-14.04-amd64) and it is working well since.
I will try to test your fix when I'll have the chance.
Thanks.

**Comment by arnlen** [comment] 2015-04-08 17:26
Same problem here on [chef/debian-7.4](https://atlas.hashicorp.com/chef/boxes/debian-7.4).
Switched to [ubuntu/trusty64](https://atlas.hashicorp.com/ubuntu/boxes/trusty64) solved it.

@brentnk: I would like to test your fix but I don't know how...

**Closed** 2015-06-01 03:44 UTC
Labels: bug, provisioner/docker

**Comment by kardasz** [comment] 2015-07-24 15:40
*Solution* just add before provision docker

`config.vm.provision :shell, inline: "/usr/bin/apt-get -y install apt-transport-https upstart", privileged: true`
