### ISSUE TITLE
config.vm.provider not overriding VMWare Fusion plugin

### ISSUE THREAD

**Issue by sjmh** [mitchellh/vagrant#7226] opened 2016-04-12 02:59 UTC
### Vagrant version
Vagrant 1.8.1

### Host operating system
OSX 10.11.3 (15D21)

### Guest operating system
Centos 7 (centos/7)

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox"
  config.vm.hostname = "example"
  config.vm.box = "centos/7"
  config.vm.network "private_network", type: "dhcp"
end
```

### Debug output

https://gist.github.com/sjmh/a0e6e9e197b042a4a18f453e2fed2096

### Expected behavior

According to the documentation ( https://www.vagrantup.com/docs/providers/basic_usage.html ), provider priority goes '--provider', then 'VAGRANT_DEFAULT_PROVIDER', then the provider option in the config file, then prefers VMWare over VirtualBox.  Box should start up with VirtualBox.  No environment for default provider is defined.

### Actual behavior

Box starts tries to start up with VMWare Fusion instead.  Giving the --provider or setting VAGRANT_DEFAULT_PROVIDER works.

Installed plugins:

```
vagrant-hostmanager (1.8.1)
vagrant-omnibus (1.4.1)
vagrant-share (1.1.5, system)
vagrant-triggers (0.5.2)
vagrant-vmware-fusion (4.0.8)
```

No default provider defined in environment:

```
vgtest|⇒ env | grep VAGRANT
vgtest|⇒
```

### Steps to reproduce
1.  Install Vagrant VMWare Fusion Plugin
2.  Create a Vagrantfile and define the provider as virtualbox
3.  vagrant up

**Comment by sethvargo** [comment] 2016-04-12 06:42
Hi @sjmh 

Thank you for opening an issue. This is actually a duplicate of https://github.com/mitchellh/vagrant/issues/4654. Let's track that issue please. Thanks!

**Closed by sethvargo** 2016-04-12 06:42 UTC

**Comment by sjmh** [comment] 2016-04-12 08:05
Oops! Sorry @sethvargo - I took a look through old issues before opening but must have missed it.  Apologies!
