### ISSUE TITLE
Is it bug or some trouble with permissions after creating new files by nginx ?

### ISSUE THREAD

**Issue by niknickolas** [mitchellh/vagrant#7666] opened 2016-08-01 16:20 UTC
After creating file from php script , it immediately loses permissions to write.
Permission for new files created  by nginx (php) are :
User -  rw
Group - r
Other - r
In working folder all files belong to user vagrant.
I need modify  old project, but don't change root files, but logs write some of root files, it causes very many warnings even fatal error if can not get access to files.

What do i have to do ?

I did not find information how to set umask for nginx or php-fpm  in their settings.

I use php5.5-fpm and nginx 1.11.2 also vagrant 1.8.4

**Comment by dragon788** [comment] 2016-08-09 18:14
You best bet is to move the project files out of the shared folder or use a different mount type like NFS to correctly handle permissions. The default SMB/shared folder tends to lock permissions and be exceedingly complex to work around.

**Comment by chrisroberts** [comment] 2016-10-03 22:53
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by chrisroberts** [comment] 2016-10-25 20:22
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2016-10-25 20:22 UTC
Labels: waiting-reply
