### ISSUE TITLE
chef.delete_node and chef.delete_client does not work (1.7.2)

### ISSUE THREAD

**Issue by jfbibeau** [mitchellh/vagrant#5154] opened 2015-01-09 15:43 UTC
Looks like #5021 was fixed in Vagrant 1.7.2. However Vagrant still fails to clean up the node and client off the Chef Server.

The two lines in my Vagrantfile:
```
chef.delete_node = true
chef.delete_client = true
```

Log from trying to destroy a VM:
```
vagrant destroy

    latest: Are you sure you want to destroy the 'latest' VM? [y/N] y
==> latest: Forcing shutdown of VM...
==> latest: Destroying VM and associated drives...
==> latest: Pruning invalid NFS exports. Administrator privileges will be required...
==> latest: Running cleanup tasks for 'chef_client' provisioner...
==> latest: Deleting client "latest" from Chef server...
==> latest: Cleaning up the 'client' for Chef failed. The stdout and
==> latest: stderr are shown below. Vagrant will continue destroying the machine,
==> latest: so please clean up these resources manually.
==> latest: 
==> latest: stdout: Check your configuration file and ensure that your private key is readable
==> latest: 
==> latest: 
==> latest: stderr: WARNING: No knife configuration file found
==> latest: ERROR: Your private key could not be loaded from /etc/chef/client.pem
==> latest: Deleting node "latest" from Chef server...
==> latest: Cleaning up the 'node' for Chef failed. The stdout and
==> latest: stderr are shown below. Vagrant will continue destroying the machine,
==> latest: so please clean up these resources manually.
==> latest: 
==> latest: stdout: Check your configuration file and ensure that your private key is readable
==> latest: 
==> latest: 
==> latest: stderr: WARNING: No knife configuration file found
==> latest: ERROR: Your private key could not be loaded from /etc/chef/client.pem
```
/etc/chef/client.pem definitely does exist before the VM gets destroyed. 

```
[vagrant@latest ~]$ ls -la /etc/chef/client.pem 
-rw-------. 1 root root 1675 Dec 22 15:49 /etc/chef/client.pem
```

- Is it a permissions issue? Presumably the chef cleanup is being run as the root user?
- Is it an order thing, is the VM being destroyed or cleaned up before running the chef cleanup, and that file no longer exists? 

Maybe some more insight as to how the cleanup works can help figure out why this doesn't work. I'd really like to stop using the vagrant-butcher plugin to achieve this functionality. Thanks!

**Comment by sethvargo** [comment] 2015-01-09 18:39
Hi @jfbibeau,

Could you please run that command in debug mode and gist the output? How is Chef installed on your local system?

**Comment by jfbibeau** [comment] 2015-01-09 18:48
Here's the relevant part at debug level: https://gist.github.com/jfbibeau/0aea9448bda47f780828

Looking at it quickly.... Is the "knife" command being run on the vagrant VM, or is it being run on the host machine? It's looking to me like it's trying to run on the host machine?

Is it a requirement to have chef installed on the host system for this clean up to work? I was under the impression the chef provisioner only had to exist on the guest VM, and perform it's own cleanup... Otherwise anyone who runs vagrant with a chef-provisioned VM would have to install Chef also on the host machine? Am I making sense?

**Comment by sethvargo** [comment] 2015-01-09 19:26
@jfbibeau ah yes :smile:.

You must have Chef (either the Chef Client or ChefDK) installed on your host operating system to process the cleanup tasks in the current Chef implementation.

Leaving this open to see if we can potentially move that operation onto the guest.

**Comment by jfbibeau** [comment] 2015-01-09 19:29
@sethvargo Thanks for the prompt reply! It would indeed be a nice enhancement, otherwise vagrant-butcher plugin does a good job of it. Cheers.

**Comment by Daveawb** [comment] 2015-04-23 10:40
I get this exact same error with the Chef DK installed on my host.

**Comment by sethvargo** [comment] 2015-05-31 04:55
This is actually a duplicate of https://github.com/mitchellh/vagrant/issues/2476. Let's track that issue since it's older and has more history :smile:

**Closed by sethvargo** 2015-05-31 04:55 UTC
Labels: bug, provisioner/chef
