### ISSUE TITLE
Unable to run vagrant commands without tty in 1.9.7

### ISSUE THREAD

**Issue by chui101** [mitchellh/vagrant#8780] opened 2017-07-13 17:17 UTC
### Vagrant version
Vagrant 1.9.7

### Host operating system
Windows 10 + Cygwin

### Guest operating system
Ubuntu 16.04 LTS

### Debug output
    $ ssh user@windows-test vagrant box list --debug
    stdin is not a tty

### Expected behavior
The issued command should be performed

### Actual behavior
Vagrant exists with code 1 and the message 

    stdin is not a tty

### Steps to reproduce
1. Open a cygwin shell
2. Run any vagrant command in a way that does not allocate a tty, in my case with maven (maven-exec-plugin):

        $ mvn clean install
        ...
        [INFO] --- exec-maven-plugin:1.4.0:exec (run-vagrant-destroy) @ integration-tests ---
        stdin is not a tty
        ...
        [INFO] BUILD FAILURE
    or over ssh

        $ ssh user@windows-test vagrant --version
        stdin is not a tty

    or with setsid 

        $ setsid -w vagrant --help < /dev/null
        stdin is not a tty

This does not happen with Vagrant running on a Linux host.

**Comment by chrisroberts** [comment] 2017-07-13 17:27
Hi there. Is the sshd process being provided by cygwin? Would you run the command with `VAGRANT_DEBUG_LAUNCHER=1` and provide the output. Thanks!

**Comment by chui101** [comment] 2017-07-13 17:56
Yes, it is Cygwin SSHD. Specifying the environment variable actually makes it work with no complaints...

    $ ssh user@windows-test vagrant --version
    stdin is not a tty
    $ ssh user@windows-test VAGRANT_DEBUG_LAUNCHER=1;vagrant --version
    Vagrant 1.9.7
    $ ssh user@windows-test VAGRANT_DEBUG_LAUNCHER=1;vagrant box list
    u16-test-box (virtualbox, 20170626)
    $ ssh user@windows-test VAGRANT_DEBUG_LAUNCHER=1;cd workspace/path/to/vagrantfile;vagrant destroy -f
    ==> default: VM not created. Moving on...

But this is because apparently it allocates a TTY when you add an environment variable to the ssh command...? 

    $ ssh user@windows-test tty
    not a tty
    $ ssh user@windows-test VAGRANT_DEBUG_LAUNCHER=1;tty
    /dev/pty0
    $ ssh user@windows-test WHAT_THE_FOO=1;tty
    /dev/pty0

**Comment by chrisroberts** [comment] 2017-07-17 17:22
Related to #8764. Installer fix needs to be tested with ssh connection to cygwin provided sshd.

**Comment by chrisroberts** [comment] 2017-07-31 22:25
Closing as duplicate of #8764. Thanks!

**Closed by chrisroberts** 2017-07-31 22:25 UTC
Labels: host/windows, installer
