### ISSUE TITLE
Regression - Vagrant 1.9.7 rsync-auto error

### ISSUE THREAD

**Issue by Darkless012** [mitchellh/vagrant#8887] opened 2017-08-14 08:08 UTC
`vagrant rsync-auto` command is working perfectly fine in 1.9.5 where I've used it to monitor shared folders.
Example output:

```
$ vagrant rsync-auto
==> default: Doing an initial rsync...
==> default: Rsyncing folder: /home/someprojectfolder/ => /opt/someprojectfolder
==> default: Rsyncing folder: /home/someprojectfolder2/ => /opt/someprojectfolder2
==> default: Watching: /home/someprojectfolder
==> default: Watching: /home/someprojectfolder2
```

But on version 1.9.7 it is refusing to work ending with error:

```
$ vagrant rsync-auto
==> default: Not syncing /home/someprojectfolder as it is not part of the current working directory.
==> default: Not syncing /home/someprojectfolder2 as it is not part of the current working directory.
==> default: Doing an initial rsync...
There are no paths to watch! This is either because you have no
synced folders using rsync, or any rsync synced folders you have
have specified `rsync_auto` to be false.
```

in the Vagrantfile i have this configuration:
```
config.vm.synced_folder "../someprojectfolder/", "/opt/someprojectfolder", id: "project_root",  type: "rsync"
config.vm.synced_folder "../someprojectfolder2/", "/opt/someprojectfolder2", id: "source_root",  type: "rsync"
```

I've not tested this on 1.9.6.

**Comment by briancain** [comment] 2017-08-14 15:57
Hello @Darkless012 , apologies for this regression. This bug was introduced in Vagrant 1.9.7 and has already been fixed via https://github.com/mitchellh/vagrant/pull/8781 for the next release. For now, using Vagrant 1.9.6 should work as intended until the next release is out. Thank you!

**Closed by briancain** 2017-08-14 15:57 UTC

**Comment by cmcintosh** [comment] 2019-02-17 18:39
This is still a issue :/ 2019

**Comment by briancain** [comment] 2019-02-19 17:59
@cmcintosh - if you are experiencing what you think is a bug please open a new issue.

**Comment by cmcintosh** [comment] 2019-02-19 18:05
Think I resolved it, may have been a local thing.  Sorry, just a bit of in the moment desperation on trying to fix something.
