### ISSUE TITLE
Ansible with Windows Guest, fact gathering tries to execute /bin/sh

### ISSUE THREAD

**Issue by jb11211** [mitchellh/vagrant#7083] opened 2016-02-26 21:20 UTC
### Vagrant version
Vagrant 1.8.1

### Host operating system
Mac
$ uname -a
Darwin brookerj-mac1.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64

### Guest operating system
Windows 2012r2 sourced from "mwrock/Windows2012R2"
```
### Vagrantfile
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define :vagrantwin12 do |cfg|
    cfg.vm.box = "mwrock/Windows2012R2"
    cfg.vm.communicator = "winrm"
    cfg.vm.guest = :windows
    cfg.vm.network :private_network, :ip => "192.168.33.41"

    cfg.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--hardwareuuid", "02f110e7-369a-4bbc-bbe6-6f0b6864ccb6"]
      vb.gui = true
      vb.memory = "1024"
    end
  end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "manage.yml"
    ansible.inventory_path = "hosts"
    ansible.sudo = true
  end

end
```

#### hosts
```
vagrantwin12 ansible_user=vagrant ansible_password=vagrant ansible_host=192.168.33.41 ansible_port=5985 ansible_connection=winrm ansible_winrm_server_cert_validation=ignore
```
#### manage.py
```
---
- hosts: all
  gather_facts: yes

  tasks:
    - debug: msg="You'll need ansible >= 2 to update all packages (https://goo.gl/4J8NXy) {{ ansible_version }}"
      when: ansible_version.major >= "2"
```

### Debug output
https://gist.github.com/jb11211/3d37593c6ce1ca332130

### Expected behavior
Should be able to run ansible provisioner within vagrant the same way I can by running ansible-playbook directly. ansible provisioning should complete without error

### Actual behavior
The vagrant ansible provisioner comes back with an error from the windows guest saying it cant run "/bin/sh".

### Steps to reproduce
execute "vagrant up" and watch.
execute "ansible-playbook manage.yml -i hosts --limit=vagrantwin12" to see what SHOULD happen

### References
example code is published in this git repo:
https://github.com/jb11211/vagrant_ansible_windows_guest_facts_error

**Comment by jb11211** [comment] 2016-02-26 21:24
Editted for clarity

**Comment by jb11211** [comment] 2016-02-28 05:16
Discovered that having this variable configured for my windows hosts was causing this:
ansible.sudo = true

it's an ansible bug with the --sudo flag. but it's far from well handled by vagrant

**Comment by gildegoma** [comment] 2016-05-28 06:04
Thank you John for reporting this, and taking time to bring the additional details. I am going to close it though, as it is (was?) an Ansible issue. See more arguments and tips below...

> it's an ansible bug with the --sudo flag. but it's far from well handled by vagrant

@jb11211 if you directly executed 

`ansible-playbook manage.yml -i hosts --limit=vagrantwin12 --sudo` (or with --become), I am pretty sure that you'd observed exactly the same Ansible bug.

More generally, it is a good practice to enable `ansible.verbose = true` while comparing `ansible-playbook` behaviours (Vagrant will print out the `ansible-playbook` commands used under the cover so you can manually run them). This way you can quickly identify whether the Issue is in Vagrant provisioner, or in Ansible itself.

**Closed by gildegoma** 2016-05-28 06:04 UTC
Labels: bug, provisioner/ansible
