### ISSUE TITLE
NFS synced_folder is broken under 1.9.1

### ISSUE THREAD

**Issue by andronat** [mitchellh/vagrant#8138] opened 2016-12-19 22:45 UTC
### Vagrant version
1.9.1

### Host operating system
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1212

### Guest operating system
Centos 7

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"

  config.vm.network "private_network", ip: "10.11.12.13"

  config.vm.synced_folder "/Users/tasos", "/Users/tasos", :nfs => true
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
NFS should had mounted

### Actual behavior
Get an error:
```
$ vagrant up
...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
Password:
==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp 10.11.12.1:/Users/tasos /Users/tasos
result=$?
if test $result -eq 0; then
if test -x /sbin/initctl && command -v /sbin/init && /sbin/init 2>/dev/null --version | grep upstart; then
/sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/Users/tasos
fi
else
exit $result
fi


Stdout from the command:



Stderr from the command:

mount.nfs: access denied by server while mounting 10.11.12.1:/Users/tasos
```

### Steps to reproduce
1. vagrant up

### Extra

I found that if I do `vagrant ssh` to the VM after the error and I do a `sudo service network restart` everything works. I noticed that before the network restart the routes are broken:
```
# before network restart
# ip route
default via 10.0.2.2 dev enp0s3  proto static  metric 100
10.0.2.0/24 dev enp0s3  proto kernel  scope link  src 10.0.2.15  metric 100

# after network restart
# ip route
default via 10.0.2.2 dev enp0s3  proto static  metric 100
10.0.2.0/24 dev enp0s3  proto kernel  scope link  src 10.0.2.15  metric 100
10.11.12.0/24 dev enp0s8  proto kernel  scope link  src 10.11.12.13
169.254.0.0/16 dev enp0s8  scope link  metric 1003

**Comment by andronat** [comment] 2016-12-19 22:50
I downgraded to `1.8.7` and the above Vagrant config works normally

**Comment by smelchior** [comment] 2016-12-21 14:09
I also have this issue. 
I dug a bit deeper and it happens due to this change in 1.9.1:
https://github.com/mitchellh/vagrant/commit/166d10d4e16836e908be0bd94c2f671cac2b38b4
NetworkManager is running for centos7 but it is not managing the private network interface due to the ``` NM_CONTROLLED=no``` that is used [here](https://github.com/mitchellh/vagrant/blob/master/templates/guests/redhat/network_static.erb)

**Comment by wwek** [comment] 2016-12-25 16:45
Official version is still a problem, not updated

**Comment by andronat** [comment] 2017-01-01 14:27
Any news on this? I'm completely blocked...

**Comment by Artistan** [comment] 2017-01-03 16:46
blocked here also...
reference that may be relevant to network issues... 
https://github.com/mitchellh/vagrant/pull/8052

**Comment by ilmarioranen** [comment] 2017-01-10 10:10
I've lost too much time trying to get NFS mounts working on my new setup, which was:
Mac OS Sierra, Virtualbox 5.1, Vagrant 1.9.1, Ansible 2.2.0. 
I also happen to use [WunderTools](https://github.com/wunderkraut/WunderTools).

As the WunderTools readme advises, downgrading to Vagrant 1.9.0 solves the mounting issue. Phew! 

I hope Vagrant 1.9.2 will bring the proper solution to this issue.

**Comment by nilsga** [comment] 2017-01-10 10:37
Same here. Had to downgrade to 1.9.0 to get it working.

**Comment by ekka21** [comment] 2017-01-10 18:07
Downgrade to v1.9.0 worked for me as well.
Here what I did:
- Bring a VM down with `vagrant halt`
- Download and install [v1.9.0](https://releases.hashicorp.com/vagrant/1.9.0/) (no need to uninstall v1.9.1)
- Bring it back up with `vagrant up`

Link to [Vagrant Archives](https://releases.hashicorp.com/vagrant/).

**Comment by astephensen** [comment] 2017-01-11 01:39
Experienced the same issue here. If anyone is using `brew cask` to install vagrant you can easily rollback by installing the 1.9.0 commit.

```
brew cask uninstall vagrant
brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/b99d5280a3fae60bc18bf16ab314d9cc84e7af87/Casks/vagrant.rb
```

**Comment by andronat** [comment] 2017-01-11 16:50
Is this #8148 fixing our issue here? Is it going to be released in `1.9.2`?

**Comment by alexivkin** [comment] 2017-01-17 19:37
This did not fix it for me in 1.9.1. To fix I had to add
              /sbin/ifup '#{network[:device]}'
right after 
              nmcli c reload || true
in 
/plugins/guests/redhat/cap/configure_networks.rb

**Comment by ascotan** [comment] 2017-01-18 20:24
@astephensen you just saved me hours of debugging this. 
I've been trying to figure out why this wasn't working for almost an entire day.  Confirmed that 1.9.0 works and 1.9.1 doesn't.
Vagrant 1.9.1, macOS Sierra, Centos 7 guest

**Comment by ascotan** [comment] 2017-01-18 20:40
BTW there were not too many commits to 1.9.1. This is the suspicious one:
https://github.com/mitchellh/vagrant/commit/166d10d4e16836e908be0bd94c2f671cac2b38b4

Is this i subtle bug with NetworkManager and NFS mounts?

**Comment by federivo** [comment] 2017-01-24 16:16
OSX El Capitan / vagrant 1.9.1

Same issue. Solved by downgrading to 1.9.0.
@ekka21 I had to uninstall before installing 1.9.0. I didn't work otherwise.

**Comment by Kotpes** [comment] 2017-01-27 08:51
@alexivkin Thanks a lot you'r fix worked for me

**Comment by geerlingguy** [comment] 2017-02-28 15:29
Note that Vagrant 1.9.2 will be released sometime today (hopefully!). I'll test and see if it works with NFS + CentOS 7.

**Comment by jordimolesblanco** [comment] 2017-02-28 17:52
Just tried with 1.9.2 and ubuntu 16.04 host. I'm getting the same issue.
Going back to 1.9.0 for now.

**Comment by geerlingguy** [comment] 2017-02-28 18:00
Testing on CentOS 7 as well...

**Comment by andronat** [comment] 2017-02-28 18:57
@jordimolesblanco it is not expected to be fixed on ubuntu. This is a CentOS/Redhat explicit issue. I'm waiting for @geerlingguy's outcome patiently 👂

**Comment by geerlingguy** [comment] 2017-02-28 19:17
@andronat - It's working for me in all cases on macOS, at least.

Though, now that S3 is down, just about everything else I try is breaking today :P

**Closed** 2017-02-28 21:45 UTC
Labels: bug, synced-folders/nfs

**Comment by rncain** [comment] 2017-03-20 18:52
This is still breaking for me on Ubuntu guest.
```
app.vm.box = 'bento/ubuntu-16.04'
```

```
Installed Version: 1.9.2
Latest Version: 1.9.2
```

mount.nfs: access denied by server while mounting 10.10.10.1

**Comment by giancarloandroid** [comment] 2017-04-29 14:32
The problem persists for me with version 1.9.4

**Comment by kiyanwang** [comment] 2017-05-24 07:20
I'm having the same problem   i'm running Vagrant 1.9.3 on OSX 10.12.4
