### ISSUE TITLE
Can't remount NFS with vagrant reload

### ISSUE THREAD

**Issue by georeith** [mitchellh/vagrant#6477] opened 2015-11-03 12:34 UTC
Host OS: OSX 10.10
Guest box: http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.6-x86_64-v20150426.box

`vagrant up` works fine. But a subsequent `vagrant reload` give me the following NFS error:
```
==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 192.168.55.1:'/Users/georgereith/Documents/repos/base-api' /opt/base-api

Stdout from the command:



Stderr from the command:

mount.nfs: rpc.statd is not running but is required for remote locking.
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
mount.nfs: an incorrect mount option was specified
```

Based on the following configuration:

```
config.vm.synced_folder "../base-api", "/opt/base-api", type: :nfs
config.vm.synced_folder "../application", "/opt/application", type: :nfs
```

It seems it successfully starts `rpc.statd` on up but not on reload. I don't want to use NFS without locking.

**Comment by Premke** [comment] 2016-06-30 21:42
I can also confirm this issue.

Host OS: Ubuntu 15.10
Guest box: CentOS 6.7 (no link since its tested on customized box)

Although in my case neither does `vagrant up` work. 
These 2 commands solved it for me:

```
/etc/init.d/rpcbind start
chkconfig rpcbind on
```

**Comment by sethvargo** [comment] 2016-07-19 01:36
Hi all,

Thank you for opening an issue. I spent some time thinking about this, and I'm not sure if it's Vagrant's responsibility to perform these actions. rpc.statd (and statd in general) is a service that should be installed and configured by the box author itself, not Vagrant. What do you think?

**Comment by georeith** [comment] 2016-07-19 12:24
@sethvargo If you've specified an NFS share you probably want that to work. If Vagrant needs a specific service to be running why wouldn't it run it unless there are harmful side effects? I don't know enough about `statd` to know if there are?

At the very least clear documentation of what to do with it, but really I think the most important thing here is that the synced folder works as it says. What percentage of people given the same situation and the fix wouldn't apply it? I would presume extremely slim, if thats the case then surely we should cater to them instead of throw errors at them.

**Comment by chrisroberts** [comment] 2016-08-10 21:33
Started digging around to see why the mount was successful on the initial `up` but then failed on subsequent `reload`s and found:

https://github.com/mitchellh/vagrant/blob/master/plugins/guests/redhat/cap/nfs_client.rb

When the nfs client is installed, the services are started via the restart. After a `reload` though, the nfs client is installed so the above is not executed, thus the services aren't started. Tossing in enables after the restarts would likely get the desired behavior on reload. Since the restarts are already happening, enabling them as well seems reasonable.

**Comment by chrisroberts** [comment] 2016-08-11 16:41
@georeith  I was unable to reproduce this locally using bento based centos 6/7 boxes, or the current 6.6 version of the nrel box linked above. Digging through some ticket information I've found there were issues with systemd setups from the packages (not applicable specifically here but still related) as well as tickets referencing the need to restart the rpcbind service after a restart to allow successful mounts. 

Being unable to successfully reproduce, I'm wondering if this was a problem that was resolved in updated nfs packages. Is this behavior something that can still be reproduced? If so, can you provide the box so I can reproduce it locally?

Thanks!

**Comment by chrisroberts** [comment] 2016-09-28 12:59
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2016-09-28 12:59 UTC
Labels: bug, synced-folders/nfs, waiting-reply
