### ISSUE TITLE
Configuring and enabling network interfaces... Error in vagrant up

### ISSUE THREAD

**Issue by ngobi1** [mitchellh/vagrant#8427] opened 2017-03-30 16:12 UTC
when i run vagrant up i get this error after passing the setting hostname part

app1: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ip -o -0 addr | grep -v LOOPBACK | awk '{print $2}' | sed 's/://'

Stdout from the command:

Stderr from the command:

am using a debian box on my local machine with virtualbox

part of my vagrant file
"config.vm.define "app1" do |app|      
        app.vm.hostname = "app1"
	app.vm.box = "Debian.box"
	app.vm.network :private_network, ip: "192.168.60.4"
  end "

vagrant version 1.9.3

link for the debug log is below created with gedit text editor
https://drive.google.com/file/d/0B7isTi7BGRCYOUVxVTY5YUtuWjQ/view?usp=sharing
 
someone know what the issue could be

**Comment by chrisroberts** [comment] 2017-04-01 15:31
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by ngobi1** [comment] 2017-04-03 11:59
i have update the issue and put a link for the debug report since the refused posting them on the platform.... Thank you Chris

**Comment by chrisroberts** [comment] 2017-04-03 18:11
Hi there. It looks like the base box you are using is not properly configured. This error message:

> DEBUG ssh: stderr: sudo: no tty present and no askpass program specified

indicates that the sudo rules within the guest machine are incorrect. Fixing the base box or using a different box (like a bento or boxcutter box) should resolve your issue. Cheers!

**Closed by chrisroberts** 2017-04-03 18:11 UTC
Labels: waiting-reply

**Comment by ngobi1** [comment] 2017-04-03 18:16
how can i change the sudo rules and what about the ssh command that returns a non zero exit status

**Comment by chrisroberts** [comment] 2017-04-03 19:11
The documentation for building base boxes will walk you through all the requirements: https://www.vagrantup.com/docs/boxes/base.html
