### ISSUE TITLE
Don't deprecate docker provision version

### ISSUE THREAD

**Issue by carc1n0gen** [mitchellh/vagrant#8579] opened 2017-05-11 20:44 UTC
### Guest operating system Ubuntu 14.04

Please don't deprecate adding the version number to the docker provisioner.  At my job we lost 3 days to docker network issues in our local dev environments because most of us had recently rebuild our vagrant boxes and automatically got the latest docker version since we didn't specify a version number in the Vagrantfile. 

 Docker 17.x seems to have made changes to networking that severely slowed down things like a simple `npm install`, and broke our environments in other ways where we would get `ENETUNREACH` for all http requests from the vm to certain containers.

Specifying the docker version was our next step to prevent this from happening to others at the office, but we were met with a lovely red deprecation notice about doing that.

**Comment by kikitux** [comment] 2017-07-20 20:41
@carc1n0gen 

Vagrant will try to install docker if not installed, so the best use case here is to create a base box with the version you require.

I will close this as not a bug, however, I welcome you to email either the packer mailing list if you need help building a box.

Thanks

**Closed by kikitux** 2017-07-20 20:41 UTC
