### ISSUE TITLE
chef-solo launched by vagrant on Windows guest throws Chef::Exceptions::MissingRole

### ISSUE THREAD

**Issue by lonniev** [mitchellh/vagrant#4974] opened 2014-12-15 04:32 UTC
Similiar to (closed) https://github.com/mitchellh/vagrant/issues/2818

```bash
==> vb-tt-sync: [2014-12-14T18:49:44-08:00] INFO: Setting the run_list to ["role[tasktop-sync-server]"] from CLI options
==> vb-tt-sync: [2014-12-14T18:49:44-08:00] DEBUG: Applying attributes from json file
==> vb-tt-sync: [2014-12-14T18:49:44-08:00] DEBUG: Platform is windows version 6.1.7601
==> vb-tt-sync: [2014-12-14T18:49:50-08:00] ERROR: Role tasktop-sync-server (included by 'top level') is in the runlist but does not exist. Skipping expand.
==> vb-tt-sync: 
==> vb-tt-sync: 
==> vb-tt-sync: ================================================================================
==> vb-tt-sync: Error expanding the run_list:
==> vb-tt-sync: ================================================================================
==> vb-tt-sync: 
==> vb-tt-sync: Missing Role(s) in Run List:
==> vb-tt-sync: ----------------------------
==> vb-tt-sync: * tasktop-sync-server included by 'top level'
==> vb-tt-sync: 
==> vb-tt-sync: Original Run List
==> vb-tt-sync: -----------------
==> vb-tt-sync: * role[tasktop-sync-server]
==> vb-tt-sync: 
==> vb-tt-sync: [2014-12-14T18:49:50-08:00] DEBUG: Re-raising exception: Chef::Exceptions::MissingRole - The expanded run list includes nonexistent roles: tasktop-sync-server
```

The Vagrantfile includes:

```ruby
    vmh.vm.provision "chef_solo" do |chef|

      chef.log_level = :debug
      
      chef.cookbooks_path = "./cookbooks"
      chef.roles_path = "./roles"
      chef.data_bags_path = "./bags"

      chef.add_role "tasktop-sync-server"
    end
```

The entire configuration works fine for Ubuntu guest boxes. The provider is virtualbox. All the proper files are in the right directories on the host, all the right mounts of shared folders are in place, all the remapped files are available on the guest Windows, all the files can be opened from the Windows guest file explorer, and the solo.rb file has the proper, mapped paths for cookbooks, roles, and bags. If chef.add_role is replaced with chef.add_recipe for a recipe that is in the cookbooks folder, then that works fine. It is just the role access that is failing.

So, what could be the problem?

(Is there a unix-dos CRLF issue at the root of this?)

**Comment by sethvargo** [comment] 2015-01-06 00:16
Ohai! I'm going to close this as we have determined this is a regression in Chef 12. If Chef determines this is "not a bug", we can revisit potential ways to fix this in Vagrant, but this is really an upstream bug.

**Closed by sethvargo** 2015-01-06 00:16 UTC
Labels: bug, provisioners/chef, windows

**Comment by sidcool1234** [comment] 2015-03-19 16:06
I am getting the exact same issue on Mac OSX.  Any solution?

**Comment by yeungs** [comment] 2015-04-09 21:47
FYI. I am hitting this issue as well @lonniev . My setup is Vagrant 1.7.2 on Windows 2012r2 using Microsoft Hyper-V as provider to create Windows 2012r2 VM with Chef-solo 12.2.1 (apparently I was being silly to think latest is greatest) in that VM.

I was happy with Vagrant 1.7.1 with chef-solo 11.14.2 . The only reason I moved is because the "sql_server" cookbook reveal a bug in the older version of chef-solo. :( That was my day.

I am just glad someone knows about this.

**Comment by yeungs** [comment] 2015-04-09 22:01
I just downgraded to Chef client version 11.18.6 and the role problem went away. :+1: 

Hopefully this helps others.

**Comment by NickMRamirez** [comment] 2015-06-24 19:42
This doesn't look like a bug in Chef to me. Rather, it's a bug in the default value Vagrant assigns to the `provisioning_path` config property.

By default, this property is set to `/tmp/chef-vagrant`, even on Windows guests.

[Shared Chef Options](http://docs.vagrantup.com/v2/provisioning/chef_common.html):
> provisioning_path (string) - The path on the remote machine where Vagrant will store all necessary 
> files for provisioning such as cookbooks, configurations, etc. This path must be world writable. By 
> default this is /tmp/vagrant-chef-# where "#" is replaced by a unique counter.

`/tmp/vagrant-chef` sounds pretty Linux-y. I don't get the error if I set that config property to something more Windows-y:

```ruby
config.vm.provision 'chef_zero' do |chef|
    chef.provisioning_path = 'C:\vagrant-chef'

    chef.roles_path = 'roles'
    chef.add_role 'windowsnode'
end
```

Maybe something along the lines of updating the default value of provisioning_path in `vagrant/plugins/provisioners/chef/config/base_runner.rb` if the guest is Windows? I can open a new issue for this.

**Comment by lonniev** [comment] 2015-06-24 19:52
The path is fine. This works in chef 12.4.0.rc.1

Generally, the issues all arise with dealing with Windows pathname drive letters and backslashes that get interpreted by Ruby regex as escaping codes.

(I need to turn off a Chef Config monkey patch to assure that 12.4.0.rc.1 gets it right but I haven’t had the role issue myself for a week or so with 12.4.0.rc.1 — but the patch may still be doing its workaround. Your conversation here is a good kick to me to go see if I still need it.)

-- 
Lonnie VanZandt
303-900-3048

On 24 June 2015 at 13:42:25, NickMRamirez (notifications@github.com) wrote:

This doesn't look like a bug in Chef to me. Rather, it's a bug in the default value Vagrant assigns to the provisioning_path config property.

By default, this property is set to /tmp/chef-vagrant, even on Windows guests.

Shared Chef Options:

provisioning_path (string) - The path on the remote machine where Vagrant will store all necessary
files for provisioning such as cookbooks, configurations, etc. This path must be world writable. By
default this is /tmp/vagrant-chef-# where "#" is replaced by a unique counter.

/tmp/vagrant-chef sounds pretty Linux-y. I don't get the error if I set that config property to something more Windows-y:

config.vm.provision 'chef_zero' do |chef|
    chef.provisioning_path = 'C:\vagrant-chef'

    chef.roles_path = 'roles'
    chef.add_role 'windowsnode'
end
Maybe something along the lines of updating the default value of provisioning_path in vagrant/plugins/provisioners/chef/config/base_runner.rb if the guest is Windows? I can open a new issue for this.

**Comment by NickMRamirez** [comment] 2015-06-24 20:01
Hmm...I wonder what they're doing in the release candidate. Because even escaped,

\\tmp\\vagrant-chef

doesn't get interpreted right by Windows. Really, /tmp isn't a normal Windows directory. Putting a drive letter at the front makes the problem go away, via File.absolute_path or File.expand_path, but the feedback I got when I submitted a pull request in Chef that does that was that there might be unintended consequences if the user changes the running process' current working directory.

**Comment by lonniev** [comment] 2015-06-24 20:11
The vagrant base box I built for SoftLayer does create a c:\tmp directory. I need to check my state of affairs with what I have working with 12.4.0.rc.1. I may just be lucky.

-- 
Lonnie VanZandt
303-900-3048

On 24 June 2015 at 14:01:28, NickMRamirez (notifications@github.com) wrote:

Hmm...I wonder what they're doing in the release candidate. Because even escaped,

\tmp\vagrant-chef

doesn't get interpreted right by Windows. Really, /tmp isn't a normal Windows directory. Putting a drive letter at the front makes the problem go away, via File.absolute_path or File.expand_path, but the feedback I got when I submitted a pull request in Chef that does that was that there might be unintended consequences if the user changes the running process' current working directory.

**Comment by NickMRamirez** [comment] 2015-06-24 20:20
I opened another issue for the Vagrant default paths, just to see what the consensus is:

[https://github.com/mitchellh/vagrant/issues/5862](https://github.com/mitchellh/vagrant/issues/5862)

**Comment by lonniev** [comment] 2015-06-25 04:18
I was just lucky. If I remove the line:

```ruby
        chef.custom_config_path = "ChefConfig.WindowsMonkeyPatch"
```

where the following is set on the guest:

```ruby
role_path "c:/vagrant/roles"
```

Then chef role-specified provisioning is busted because the roles path can't be resolved.

I apologize for being optimistic; I thought I had removed this bandaid.

**Comment by lonniev** [comment] 2015-06-25 04:26
Darn fragile code:

```ruby
rsync: mkdir "/cygdrive/c/Users/vagrant/C:vagrant-chef/5e5b4497aa57800c3fe732202ad0e04e/cookbooks" failed: No such...
```

That's what I get when I use the provisioning_path fix you suggest. It looks like for now I am stuck with my little monkey patch. (We can see that the rsync handling code doesn't know how to cygwin-ize a ruby path for Windows that already has drive letters within it.)

**Comment by NickMRamirez** [comment] 2015-06-25 11:33
@lonniev For cygwin, what's the setup? I'd like to try some things out with it.

**Comment by lonniev** [comment] 2015-06-25 13:14
It isn’t the case that a guest VM happens to have cygwin installed onto but rather than the rsync executable most usable for Windows was built with Cygwin’s libraries for dealing with Windows pathnames and other OS-specific details. Therefore, the vagrant and chef modules that call rsync are responsible for transforming Ruby paths to Windows paths to Cygwin paths.

-- 
Lonnie VanZandt
303-900-3048

On 25 June 2015 at 05:33:51, NickMRamirez (notifications@github.com) wrote:

@lonniev For cygwin, what's the setup? I'd like to try some things out with it.

**Comment by NickMRamirez** [comment] 2015-06-25 18:02
I tried using MinGW to get rsync installed, but couldn't get it working at all with Vagrant. (unrelated to Chef provisioning). I'd never tried before and am just going off of the [Vagrant rsync docs](http://docs.vagrantup.com/v2/synced-folders/rsync.html). Maybe you can share your Vagrantfile and setup?

My Vagrantfile otherwise, solves the Windows guest problems I was having before. 

```ruby
Vagrant.configure(2) do |config|

  config.vm.box = "kensykora/windows_2012_r2_standard"
  
  # Could not get rsync working...
  # config.vm.synced_folder '.', '/my_share', type: 'rsync'
  
  config.vm.provision 'chef_zero' do |chef|
    chef.provisioning_path = 'C:/vagrant-chef' # note forward slashes OK
    chef.file_backup_path = 'C:/chef/backup'
    chef.file_cache_path = 'C:/chef/cache'
    
    chef.roles_path = 'roles'
    chef.add_role 'windowsnode'
  end
end
```

If we can get the rsync/cygwin stuff figured out, would make a better case for changing the default paths for Windows.

**Comment by lonniev** [comment] 2015-06-25 18:08
The following comes from a Packer script for making vagrantized Windows boxes. One also has to setup OpenSSH on the image beforehand.

```powershell
rem install rsync
if not exist "C:\Windows\Temp\7z920-x64.msi" (
    powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://downloads.sourceforge.net/sevenzip/7z920-x64.msi', 'C:\Windows\Temp\7z920-x64.msi')" <NUL
)
msiexec /qb /i C:\Windows\Temp\7z920-x64.msi

pushd C:\Windows\Temp
powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://mirrors.kernel.org/sourceware/cygwin/x86_64/release/rsync/rsync-3.1.0-1.tar.xz', 'C:\Windows\Temp\rsync-3.1.0-1.tar.xz')" <NUL
cmd /c ""C:\Program Files\7-Zip\7z.exe" x rsync-3.1.0-1.tar.xz"
cmd /c ""C:\Program Files\7-Zip\7z.exe" x rsync-3.1.0-1.tar"
copy /Y usr\bin\rsync.exe "C:\Program Files\OpenSSH\bin\rsync.exe"
rmdir /s /q usr
del rsync-3.1.0-1.tar
popd

msiexec /qb /x C:\Windows\Temp\7z920-x64.msi

rem make symlink for c:/vagrant share
mklink /D "C:\Program Files\OpenSSH\vagrant" "C:\vagrant"
```

**Comment by NickMRamirez** [comment] 2015-06-26 20:18
I got rsync working with a Windows host and Windows guest. Steps I took:

1. Installed cygwin with its OpenSSH and rsync packages onto the host machine.
2. Used the following Vagrantfile that uses `kensykora/windows_2012_r2_standard` box (comes with OpenSSH already installed). The Vagrantfile uses  rsync fix, documented at [https://github.com/mitchellh/vagrant/issues/3230#issuecomment-62588180](https://github.com/mitchellh/vagrant/issues/3230#issuecomment-62588180)

```ruby
# rsync fix:
ENV["VAGRANT_DETECTED_OS"] = ENV["VAGRANT_DETECTED_OS"].to_s + " cygwin"

Vagrant.configure(2) do |config|

  config.vm.box = "kensykora/windows_2012_r2_standard"
  config.vm.network 'private_network', ip: '192.168.50.4'
  
  # Note: guest path uses /cygdrive, even though cygwin is only installed on the host
  config.vm.synced_folder './my_share', '/cygdrive/c/my_share', type: 'rsync'

  config.vm.provision 'chef_zero' do |chef|
    chef.provisioning_path = 'C:/vagrant-chef'
    chef.file_backup_path = 'C:/chef/backup'
    chef.file_cache_path = 'C:/chef/cache'
    
    chef.roles_path = 'roles'
    chef.add_role 'windowsnode'
  end
end
```

3. After `vagrant up`, vagrant rdp'ed into the machine so I could install rsync.
4. Copied [your commands](https://github.com/mitchellh/vagrant/issues/4974#issuecomment-115348411) for installing rsync to the guest into a CMD file on the guest and ran it. This installed rsync (The box already had OpenSSH installed). This could be skipped if the guest already had rsync.
5. Ran `vagrant reload`

That did it to sync up the `my_share` folders.

**Comment by lonniev** [comment] 2015-08-08 23:54
Status update: the combination of MacOS, Vagrant, Chef-Solo, Windows still has, in Vagrant 1.7.4 and Chef 12.4.1, issues with rsync and Windows paths.

I should create a new issue. If I recall, it is the Windows Capabilities Rsync ruby code in core Vagrant that is responsible for getting this resolved.

```bash
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /Users/lonniev/Vagrants/softlayer-windows-obeoteam/cookbooks/
Guest path: C:/vagrant-chef/f3c765f92a8356d41d4338281bc64a00/cookbooks
Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group -e ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i '/Users/lonniev/.vagrant.d/insecure_private_key' --exclude .vagrant/ /Users/lonniev/Vagrants/softlayer-windows-obeoteam/cookbooks/ vagrant@255.255.255.255:C:/vagrant-chef/f3c765f92a8356d41d4338281bc64a00/cookbooks
Error: Warning: Permanently added '255.255.255.255' (RSA) to the list of known hosts.
cygwin warning:
  MS-DOS style path detected: C:/vagrant-chef/f3c765f92a8356d41d4338281bc64a00/cookbooks
  Preferred POSIX equivalent is: /cygdrive/c/vagrant-chef/f3c765f92a8356d41d4338281bc64a00/cookbooks
  CYGWIN environment variable option "nodosfilewarning" turns off this warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
rsync: change_dir#1 "/cygdrive/c/Users/vagrant//C:/vagrant-chef/f3c765f92a8356d41d4338281bc64a00/cookbooks" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(631) [Receiver=3.1.0]
```
