### ISSUE TITLE
vagrant(1.9.7) vagrant --version failure "stdout is not a tty" on windows (gitbash or cygwin) when output is file or pipe

### ISSUE THREAD

**Issue by karlbunch** [mitchellh/vagrant#8833] opened 2017-07-29 12:38 UTC
### Vagrant version
1.9.7 specific (does not exist in 1.9.6)

### Host operating system
Windows 10
Using Gitbash 2.13.3.0 or Cygwin 2.8.2(0.313/5/3)

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
No ouput produced with --debug

### Expected behavior
Expected the version to be sent to the next command in the pipe or output file

### Actual behavior
Fails with "stdout is not a tty"

### References
Example usage https://github.com/Zonama/ZonamaDev/blob/master/bootstrap.sh#L264

### Steps to reproduce
1. Install latest vagrant
2. Install latest gitbash or cygwin
3. open a gitbash or cygwin64 window:
```bash
vagrant --version | cut -d' ' -f2
```

This used to work in 1.9.1 but broken recently in 1.9.7 release.  I'm updating automated scripts that check if the user has the correct version of various programs installed.

As of 1.9.7 it instantly dies:

```bash
$ vagrant --version | cut -d' ' -f2
stdout is not a tty
$ vagrant --version --no-color | cut -d' ' -f2
stdout is not a tty
$ vagrant --version --debug | cut -d' ' -f2
stdout is not a tty
$ vagrant --version --debug > test.out
stdout is not a tty
```

Interesting thing to note in "CMD" it doesn't seem to be an issue:
```
C:\> vagrant -v > test.out

C:\> type test.out
Vagrant 1.9.7

C:\>
```

**Comment by hantsy** [comment] 2017-07-30 11:31
I upgraded Vagrant 1.9.7 64bit, and encountered similar problems.

no output in cmd.

I have tried the commands like, no any output result.

```
> vagrant -h // no output
> vagrant init // does not create a Vagrantfile
```

**Comment by chrisroberts** [comment] 2017-07-31 22:24
Duplicate of #8764

**Closed by chrisroberts** 2017-07-31 22:24 UTC
