### ISSUE TITLE
Chef installer defaults to the current channel

### ISSUE THREAD

**Issue by coderanger** [mitchellh/vagrant#6979] opened 2016-02-05 00:19 UTC
This channel is used for nightly builds. Vagrant should default to the stable channel, which includes normal releases.

**Comment by ajkerr** [comment] 2016-02-05 00:31
Note that using the "current" channel with the Omnibus installer now completely ignores the requested version and installs the latest nightly build, which is obviously terrible default behaviour.

**Comment by coderanger** [comment] 2016-02-05 00:53
@ajkerr It isn't being ignored, you are getting the latest nightly for 12.6.0 that Omnitruck knows about. We are preparing the 12.7.0 release so currently nightlies have a newer version of Chef than the package version number.

**Comment by ajkerr** [comment] 2016-02-05 00:58
@coderanger I see. Either way, the default setting used by Vagrant results in unexpected and surprising results, so thanks for opening this issue.

**Comment by sethvargo** [comment] 2016-02-05 15:07
This is a duplicate of https://github.com/mitchellh/vagrant/issues/6767.

In short, the reason we use current is because that's where ChefDK lives. This was called out in the CHANGELOG and the user can specify the channel he/she prefers as an option in the provisioner. If ChefDK has moved to stable, we can change the default back to stable.

**Comment by coderanger** [comment] 2016-02-06 01:35
I'm confused, the default product seemed to be the chef-client omnibus installers (aka `"chef"`), not Chef DK?

**Comment by sethvargo** [comment] 2016-02-07 18:11
@coderanger yea, the default is "chef". The problem was that, defaulting to "stable" meant the user would have to change the value of "project" and "channel" whereas defaulting to "current" would only cause the user to change the "project". "chef" was available in both channels, so it seemed like a non-issue. I'm happy to change it, but I did add this [explicitly to the documentation](https://www.vagrantup.com/docs/provisioning/chef_common.html#channel) because I anticipated a pain point. It becomes even more confusing when Chef "promotes" something to stable. What do you think is the best course of action?

**Comment by coderanger** [comment] 2016-02-07 23:24
@sethvargo I think having safer defaults overall is more important than one vs. two changes for using ChefDK instead of chef-client. I agree that ChefDK installers should get published to the stable channel though, let's poke people on Thursday and make that happen?

**Comment by neovatar** [comment] 2016-02-08 10:44
Setting chef.channel will fail on Vagrant 1.7.x thus the Vagrantfile will only work with 1.8.x

Vagrant in its default should use chef stable and not a nightly build. I assume that is what you expect normally.

**Comment by sethvargo** [comment] 2016-02-08 15:43
Oh yea - I'll see you IRL on Thursday @coderanger. Will add to my notes.

**Closed** 2016-02-08 15:53 UTC
Labels: bug, provisioner/chef, waiting-reply

**Comment by lamont-granquist** [comment] 2016-02-08 17:09
Kind of half wish you'd revert the fix so people would actually be testing our nightlies...
