### ISSUE TITLE
rsync error with vagrant 1.7.2 ant puppet on a windows guest (from a linux host)

### ISSUE THREAD

**Issue by mfleurisson** [mitchellh/vagrant#5788] opened 2015-06-03 16:50 UTC
here is the error i have when i run vagrant up : 

```
==> default: Attempting graceful shutdown of VM...
==> default: The VM is already created
==> default: Calling vSphere PowerOn
==> default: Waiting for WinRM to become available...
==> default: Checking for host entries
==> default: Rsyncing folder: /home/mfn/CloudStation/Dev/Vagrant/wintest_vsphere/ => /cygdrive/c/vagrant_data
vagrant@192.168.1.104's password: 
==> default: Rsyncing folder: /home/mfn/CloudStation/Dev/Vagrant/wintest_vsphere/manifests/ => /cygdrive/c/Windows/temp/manifests
vagrant@192.168.1.104's password: 
==> default: Rsyncing folder: /home/mfn/CloudStation/Dev/Vagrant/wintest_vsphere/modules/ => /cygdrive/c/Windows/temp/modules
vagrant@192.168.1.104's password: 
==> default: Rsyncing folder: /home/mfn/CloudStation/Dev/Vagrant/wintest_vsphere/manifests/ => /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513
vagrant@192.168.1.104's password: 
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /home/mfn/CloudStation/Dev/Vagrant/wintest_vsphere/manifests/
Guest path: /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513
Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group -e ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '/home/mfn/.vagrant.d/insecure_private_key' --exclude .vagrant/ /home/mfn/CloudStation/Dev/Vagrant/wintest_vsphere/manifests/ vagrant@192.168.1.104:/tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513
Error: Warning: Permanently added '192.168.1.104' (ECDSA) to the list of known hosts.
rsync: mkdir "/tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(656) [Receiver=3.1.1]
```

**Comment by sethvargo** [comment] 2015-07-10 23:34
Hi @mfleurisson 

Is this still an issue on Vagrant 1.7.3? If so, can you please provide the complete vagrantfile as well as gist the output of the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html)? Thanks!

**Comment by de1m** [comment] 2015-08-11 07:52
Hi @sethvargo 
i've the same issue on vagrant 1.7.4

**Comment by sethvargo** [comment] 2015-08-11 15:14
Can you please provide a Vagrantfile and the output of the command in debug mode?

**Comment by de1m** [comment] 2015-08-12 10:00
Hi,
it's here https://gist.github.com/de1m/0b6db7c0efbfb521434d
this is output whne I use cygwin on Windows 8.1

Show line 2809

**Comment by bodinsamuel** [comment] 2015-08-15 12:34
Same issue in 1.7.3
it used to work correctly so look like a regression.

E:/Dev/www/=> /home/bn/

```bash
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /e/Dev/www/
Guest path: /home/bn

Command: rsync --verbose --archive -z --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p
 2222 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'E:/Dev/VM/.vagrant/machines
/default/virtualbox/private_key' --exclude .vagrant/ --exclude .git/ /e/Dev/www/ vagrant@127.0.0.1:/home/bn
Error: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
rsync: change_dir "/e/Dev/www" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [sender=3.1.1]
 INFO interface: Machine: error-exit ["Vagrant::Errors::RSyncError", "There was an error when attempting to rsync a sync
ed folder.\nPlease inspect the error message below for more info.\n\nHost path: /e/Dev/www/\nGuest path: /home/bn\nComma
nd: rsync --verbose --archive -z --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222
 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'E:/Dev/VM/.vagrant/machines/defa
ult/virtualbox/private_key' --exclude .vagrant/ --exclude .git/ /e/Dev/www/ vagrant@127.0.0.1:/home/bn\nError: Warning:
Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.\r\nrsync: change_dir \"/e/Dev/www\" failed: No
such file or directory (2)\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c
(1165) [sender=3.1.1]\n"]
```

**Comment by joth** [comment] 2015-09-17 20:00
+1 on this. I had an user upgrade to 1.7.4. It seems to be broken since 1.7.0. I had the user downgrade back to 1.6.3.

**Comment by chrisroberts** [comment] 2016-12-09 00:05
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Closed by chrisroberts** 2016-12-09 00:05 UTC
Labels: bug, guest/windows, provisioner/puppet, synced-folders/rsync
