### ISSUE TITLE
Using Vagrant while a VPN is active

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [mitchellh/vagrant#7310] opened 2016-05-12 11:08 UTC
### Expected behavior
That I be able to `vagrant up` or `vagrant ssh` while connected to a VPN.

### Actual behavior
Either:

1. `vagrant up` hangs on ‘Waiting for machine to boot’,

        > vagrant up
        Bringing machine 'vagrant-test-01' up with 'vmware_fusion' provider...
        ==> vagrant-test-01: Cloning VMware VM: 'coreos-alpha'. This can take some time...
        ==> vagrant-test-01: Checking if box 'coreos-alpha' is up to date...
        ==> vagrant-test-01: Verifying vmnet devices are healthy...
        ==> vagrant-test-01: Preparing network adapters...
        ==> vagrant-test-01: Starting the VMware VM...
        ==> vagrant-test-01: Waiting for machine to boot. This may take a few minutes...
            vagrant-test-01: SSH address: 192.168.131.145:22
            vagrant-test-01: SSH username: core
            vagrant-test-01: SSH auth method: private key

2. or `vagrant up` throws [a NetworkingHostOnlyCollision](https://gist.github.com/ELLIOTTCABLE/7510f7908b4700c4a1cf9fa2728f2ab5) error:

        The host only network with the IP '172.17.8.101' would collide with
        another device 'tun0'. This means that VMware cannot create
        a proper networking device to route to your VM. Please choose
        another IP or shut down the existing device.

Personally, this occurs with VyprVPN (they have [a free tier](https://www.goldenfrog.com/vyprvpn/buy-vpn) of service, so it should be pretty easy to reproduce this on OS X.); but I'm [not](https://github.com/mitchellh/vagrant/issues/5740) the [first](https://github.com/mitchellh/vagrant/issues/1936#issuecomment-126159440) person to [experience](https://github.com/mitchellh/vagrant/issues/391#issuecomment-5237884) this. :P

----

Ideally, Vagrant should: 1. throw a more informative error, and hopefully 2. allow for the selection or configuration of an alternative device, if the VPN configuration is creating some sort of conflicting network setup that is insurmountable from Vagrant's end. (I'm no networking guru, as I suspect is true of many Vagrant users; and that error is completely inscrutable to me!)

> Vagrant version: **Vagrant 1.8.1**
> Host operating system: **Mac OS X 10.11.3**
> Guest operating system: **CoreOS 1032.1.0**

**Comment by ELLIOTTCABLE** [comment] 2016-05-12 11:10
Ideally, Vagrant should: 1. throw a more informative error, and hopefully 2. allow for the selection or configuration of an alternative device, if the VPN configuration is creating some sort of conflicting network setup that is insurmountable from Vagrant's end. (I'm no networking guru, as I suspect is true of many Vagrant users; and that error is completely inscrutable to me!)

**Comment by sethvargo** [comment] 2016-05-27 21:45
Hi @ELLIOTTCABLE 

Thank you for opening an issue. Unfortunately the issue you are experiencing is a very common one, and there's no good solution. The problem is actually virtualbox or, more generally, virtualization among many networks. VyprVPN (along with Cloak, HYA, Viscosity, etc) all install their own bridged interface and basically "intercept" traffic. The problem is that your IP address space is conflicting with the IP address space assigned to you in your provider's data center. 

You can choose an alternate device to bind to in the Vagrantfile:

```ruby
config.vm.network "public_network", bridge: [
  "en1: Wi-Fi (AirPort)",
  "en6: Broadcom NetXtreme Gigabit Ethernet Controller",
]
```

You can also customize the IP address:

```ruby
config.vm.network "public_network", ip: "192.168.0.17"
```

**Closed by sethvargo** 2016-05-27 21:45 UTC

**Comment by ELLIOTTCABLE** [comment] 2016-07-11 16:36
Hm, @sethvargo; do you have more information on how to choose the entries in the list passed to `config.vm.network`? Do the names after the colons matter, i.e. must they match the name of the hardware; and if so, any idea how I might go about getting those names?

**Comment by ELLIOTTCABLE** [comment] 2016-07-11 16:53
Also, even given that info, I can't seem to circumvent this problem (and it's really, really a crucial one for me: I work very often on insecured networks!)

First off, I can't get `private_network` working, becase whatever IP I try (`192.168.123.123`, `127.0.0.2`, `10.0.1.2`), I'm getting the same error:

    The host only network with the IP '10.0.1.2' would collide with
    another device 'en0'. This means that VMware cannot create
    a proper networking device to route to your VM. Please choose
    another IP or shut down the existing device.

It's always conflicting with `en0`:

    en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
    	ether b8:e8:56:46:07:9a 
    	inet 104.194.117.28 netmask 0xfffff000 broadcast 104.194.127.255
    	media: autoselect
    	status: active

Meanwhile, trying to use the `public_network` configuration you gave, with `bridge`, doesn't seem to change the original issue reported? I still get an indefinite hang at the end of `vagrant up`, whenever the VPN is running:

      config.vm.network "public_network", ip: "10.0.1.2", bridge: [
        "en0: Wi-Fi (AirPort)"
      ]

----

On a related note: as you mention that ‘the issue you're experiencing is a very common one’, I'm actually really surprised that Vagrant doesn't have any meaningful error output for these various situations above. Generally speaking, Vagrant has very useful human-friendly error reporting; and I feel this case could really benefit from detection and reporting to the user. )=

**Comment by ELLIOTTCABLE** [comment] 2016-08-08 04:45
Bump, on the off-chance I can get some help with this … it's still *really* problematic, and I still run into it every single time I try to use Vagrant.

**Comment by tkellen** [comment] 2016-11-18 01:22
Just hitting this now for the first time myself. Have you found any resolution @ELLIOTTCABLE ?

**Comment by igloude** [comment] 2016-12-20 20:00
Bump - this is a rather large issue for my team right now.

**Comment by tknerr** [comment] 2017-07-16 00:11
Bump, same for me. Our corporate VPN takes over the whole routing table.

However, I have noticed that:

 * with the virtualbox provider I actually can work in the VPN
 * only with vmware provider I can't

The reason is that with the virtualbox provider vagrant always connects via the port-forwarded ssh port (127.0.0.1:2200 etc), whilst with the vmware provider it tries to connect via the VM's IP address.

I don't know why the behaviour is different in the two providers, but the approach taken in the virtualbox provider is much more resilient to such kind of issues.

@mitchellh @sethvargo do you see any chance that using the port-forwarded ssh port in the vmware provider too would solve this common problem?

**Comment by ELLIOTTCABLE** [comment] 2017-07-17 11:40
(Might want to add :+1: votes to my OP if this affects you too; that's becoming rather standard-practice on GitHub for “voting for” issues.)

**Comment by cdwilson** [comment] 2017-11-10 17:50
@tknerr FYI, the vmware_fusion provider behavior seems to have been fixed to use the 127.0.0.1:2222 port forwarded address, so things like `vagrant ssh` work while on VPN now.

See my comment in https://github.com/hashicorp/vagrant/issues/5740#issuecomment-343539795

**Comment by tknerr** [comment] 2017-11-14 09:40
Awesome, thanks @cdwilson for the ping!

Referring to your other comment, does that mean that `vagrant up` does not work from within the VPN yet, but if you do `vagrant up` outside the VPN and then switch back to VPN at least `vagrant ssh / provision` will work?

Or does everything work as expected with vagrant-vmware-plugin 5.0.3, including `vagrant up` from within the VPN?

**Comment by sodacrackers** [comment] 2018-03-15 18:10
Can someone summarize the steps for using a Vagrant VirtualBox when on a VPN? Thnx.

**Comment by anrizal** [comment] 2018-04-06 13:11
I have the same problem with Virtualbox on windows 10.

**Comment by Prem-Patel** [comment] 2018-06-29 02:32
I had the same issue. I got two solution for it.

Uninstall check point endpoint security application OR
added below line in vagrantfile
config.vm.network "public_network", ip: "{ip}" along with config.vm.network "private_network", ip: "{ip}"

![image](https://user-images.githubusercontent.com/8936144/42070144-b3a11ba8-7b72-11e8-8765-7b5ed35e8036.png)

**Comment by johnypony3** [comment] 2019-02-12 23:31
@Prem-Patel why would you use an image? :D

it also did not work for me
