### ISSUE TITLE
vagrant up with virtualbox internal networks creates extra interfaces

### ISSUE THREAD

**Issue by Cireo** [mitchellh/vagrant#7284] opened 2016-05-04 00:33 UTC
When 'vagrant up' is run, I see 6-10 interfaces with the below configuration (as opposed to the 4 expected).  The extra interfaces come in pairs duplicating the 3/4th interfaces (including IP address).  Running 'vagrant reload' works around this issue by correctly configuring 4 interfaces.

### Vagrant version
Vagrant 1.8.1

### Virtualbox version
$ VBoxManage --version
5.0.16r105871

### Host operating system
Darwin 15.4.0 Darwin Kernel Version 15.4.0: root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

### Guest operating system
debian/jessie64

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = {
  "local.e2e" => "192.168.33.11",
}

Vagrant.configure("2") do |config|
  hosts.each do |name, ip|
    config.vm.define name do |machine|
      machine.vm.box = "debian/jessie64"
      machine.vm.hostname = "%s" % name
      machine.vm.network :private_network, ip: ip
      machine.vm.provider "virtualbox" do |v|
        v.name = name
        v.customize ["modifyvm", :id, "--memory", 4096]
        v.customize ["modifyvm", :id, "--cpus", 4]
        machine.vm.network :private_network, ip: "172.31.0.10",
            virtualbox_intnet: "foo"
        v.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
        machine.vm.network :private_network, ip: "172.31.0.11",
            virtualbox_intnet: "foo"
      end
    end
  end
end
```

### Debug output
https://gist.github.com/username/78fcc17f6c9b552865087db1654dba6e
From 'up' and 'reload' commands, where 'username' is 'Cireo'.

### Expected behavior
Behavior seen with reload (4 interfaces)

### Actual behavior
Behavior seen with up (6-10 interfaces)
Each pair of interfaces past the 4th are copies of the 3rd and 4th interfaces.

### Steps to reproduce
1. vagrant up
2. Note multiple host adapters listed ("Slot 5: hostonly", etc.)
3. Inside VM or using virtualbox, note duplicate ip addresses

### References
None seemed appropriate.

**Comment by yew011** [comment] 2016-05-04 00:35
Hit the issue,

**Comment by BostonDriver** [comment] 2016-06-11 14:48
Possible duplicate of [https://github.com/mitchellh/vagrant/issues/7417](url)

**Closed** 2016-06-11 17:56 UTC
Labels: bug, core, provider/virtualbox
