### ISSUE TITLE
Vagrant 1.8.7 / MacOS Sierra - Boxes can't be added

### ISSUE THREAD

**Issue by jkanschik** [mitchellh/vagrant#8014] opened 2016-11-17 01:14 UTC
When calling `vagrant box add hashicorp/precise64`, the box is not fetched from the server.

Seems to be related to embedded curl:

```
DEBUG subprocess: stderr: dyld: Library not loaded: @rpath/libcurl.4.dylib
  Referenced from: /opt/vagrant/embedded/bin/curl
  Reason: Incompatible library version: curl requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0

```

### Vagrant version
Jenss-MBP:kubernetes jenskanschik$ vagrant -v
Vagrant 1.8.7

### Host operating system
MacOS Sierra, 10.12.1

### Guest operating system
Not possible.

### Vagrantfile
Not relevant.

### Debug output
https://gist.github.com/jkanschik/fb6ee980993b36367141916704a490e2

### Expected behavior
`vagrant box add hashicorp/precise64` should download the box.

### Actual behavior
Box could'nt be found.

### Steps to reproduce
1. Execute `vagrant box add hashicorp/precise64`

### Related to

This is a duplicate of: GH-8012 and GH-7997

### Version of curl in Sierra
```
Jenss-MBP:kubernetes jenskanschik$ curl --version
curl 7.49.1 (x86_64-apple-darwin16.0) libcurl/7.49.1 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets 
Jenss-MBP:kubernetes jenskanschik$ 
```

**Comment by X0o0Z** [comment] 2016-11-17 07:43
I've the same problem. On my MacOS Sierra, I've tried add boxes from server and local. 

The box "precise64.box" is downloaded from [https://hashicorp-files.hashicorp.com/precise64.box](url)

First, I run the command `vagrant init`.
Then, I edit the `Vagrantfile` as the following:

`config.vm.box="~/Downloads/precise64.box"`

And I add the file named metadata.json within the same directory:

{
    "name": "precise64",
    "versions": [
        {
            "version": "1.1.0",
            "providers": [
                {
                    "name": "virtualbox",
                    "url": "https://hashicorp-files.hashicorp.com/precise64.box"
                }
            ]
        }
    ]
}


Next, I run `vagrant up`:
_**Here is the output :**_
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box '~/Downloads/precise64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box '~/Downloads/precise64' (v0) for provider: virtualbox
    default: Downloading: ~/Downloads/precise64
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

_**Here is the output of adding boxes:**_
$ vagrant box add test ~/Downloads/precise64.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'test' (v0) for provider:
    box: Unpacking necessary files from: file:///Users/Xo_Oz/Downloads/precise64.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

**Vagrant Version**
Vagrant 1.8.7

**Host Operate System**
MacOS Sierra, 10.12

**Excepted behavior:**
`vagrant up ` or `vagrant box add test ~/Downloads/precise64.box` should success.

**Version of curl in Sierra:**
$ curl --version
curl 7.49.1 (x86_64-apple-darwin16.0) libcurl/7.49.1 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets


_**Debug output**_
https://gist.github.com/X0o0Z/4a787474a98a789288e28de726237789

**Comment by darkn3rd** [comment] 2016-11-17 20:26
Thanks @X0o0Z, you're my hero.  `sudo ln -nsf /usr/bin/curl /opt/vagrant/embedded/bin/curl` did the trick.  Great write up.

**Comment by adbrvn** [comment] 2016-11-18 12:57
The same bug affects in ElCapitan

**Comment by maxgorovenko** [comment] 2016-11-18 13:00
Hi, guys! 
We are still trying to use vagrant to unify our developer environment. At first we thought "what could be easier than running virtual machine with ansible provision and getting exactly the same environment". But how wrong we were.. 

Every release there is some critical bug in very-very common stuff. Last time it was with auth to new box at default ssh config (default config!!). It took you a couple months to make new build of vagrant with fix. (fix was done in a couple of days, the rest of the time you seem to be waiting for something)

This time even more common stuff is broken - downloading boxes on newest macOS

Do you run any tests or may be just test new releases?

Maybe you need some help to build basic CI environment?

**Comment by dduportal** [comment] 2016-11-18 19:20
@maxgorovenko Not sure if being sarcastic will help here. This is a free (and open) tool.
I'm totally suffering the same, but complaining like this won't help.

That's also a project life: bugs can appear.

You can freely propose a Pull Request that implements a set of functionnal tests or corrects this bug with a unit test case :)

**Comment by andydude** [comment] 2016-11-23 06:49
Confirmed http://pastie.org/10968105

**Comment by deviantintegral** [comment] 2016-11-23 14:37
Also mentioned in this closed issue: https://github.com/mitchellh/vagrant/issues/5016#issuecomment-260065012

**Comment by kikitux** [comment] 2016-11-25 20:43
duplicate of https://github.com/mitchellh/vagrant/issues/7969

**Closed by kikitux** 2016-11-25 20:43 UTC
Labels: bug, host/darwin, installer
