### ISSUE TITLE
`vagrant box update` should offer to delete old box versions

### ISSUE THREAD

**Issue by edmorley** [mitchellh/vagrant#6965] opened 2016-02-02 14:54 UTC
Every time there is a box update, I end up having to perform these steps:
1. `vagrant box update`
2. `vagrant box list` (to find out the old version number I need to delete)
3. `vagrant box remove ubuntu/trusty32 --box-version 20160120.0.1`
(And in practice there are normally several typoed attempts in the middle, eg #6964)

It would be great if `vagrant box update` offered to do this for me :-)

**Comment by sethvargo** [comment] 2016-02-02 15:07
Hi @edmorley 

Vagrant 1.8 added the ability to remove all boxes, so I think the desired workflow here would be:

```
vagrant box remove ubuntu/trusty32 --all && vagrant box add ubuntu/trusty32
```

Gonna tag this as an enhancement though.

**Comment by bbrala** [comment] 2016-02-08 18:17
I also want to add, I made a pr to remove all old versions of boxes in one command and made this pull request available as plugin also.

Bottom of: https://github.com/mitchellh/vagrant/issues/4412

**Comment by sethvargo** [comment] 2016-05-29 22:20
Duplicate of https://github.com/mitchellh/vagrant/issues/4412

**Closed by sethvargo** 2016-05-29 22:20 UTC
Labels: core, enhancement
