### ISSUE TITLE
Vagrant vsphere tries to use IPv6 address and fails to connect via WinRM 

### ISSUE THREAD

**Issue by ashokvaddevalli** [mitchellh/vagrant#8851] opened 2017-08-05 05:08 UTC
**Vagrant version**
Vagrant 1.9.7

**Host operating system**
Windows 7

**Guest operating system**
Windows7

**Vagrantfile**

Vagrant.configure("2") do |config|

config.vm.box = 'dummy'
config.vm.box_url = 'dummy.box'

config.vm.communicator = "winrm"
config.winrm.username = "administrator"
config.winrm.password = "xxx"
config.winrm.timeout = 1800

config.vm.provider :vsphere do |vsphere|
vsphere.host = 'xxx'
vsphere.compute_resource_name = 'XXX'
vsphere.data_center_name = 'DemoIAM'
vsphere.template_name = 'Templates/win7nsllatest'
vsphere.name = 'test'
vsphere.user = 'administrator@vsphere.local'
vsphere.password = 'xxx'
vsphere.insecure = true
end

end

**Expected behavior:**

VM should have started and provisioning process executed. The connection should be established through IPv4 once the VM gets its IP address from DHCP.

**Actual behavior:**

VM started but Vagrant for some reason grabbed its IPv6 autoconfigured address instead of the IPv4 address (assigned via DHCP) and was thereafter unable to connect to it for whatever reason via WinRM.

E:\Vagrant-vpshere\Vagrant>vagrant up --provider=vsphere
Bringing machine 'default' up with 'vsphere' provider...
==> default: Calling vSphere CloneVM with the following settings:
==> default: -- Template VM: Demo/vm/Templates/win7-vagrant
==> default: -- Target VM: Demo/vm/Templates/test
==> default: New virtual machine successfully cloned
==> default: Waiting for the machine to report its IP address...
default: Timeout: 240 seconds
default: IP: X.X.X.X
==> default: Waiting for machine to boot. This may take a few minutes...
default: WinRM address: X.X.X.X:5985
default: WinRM username: administrator
default: WinRM execution_time_limit: PT2H
default: WinRM transport: negotiate
bad URI(is not URI?): http://2002:a463:5ab4::a463:5ab4:5985/wsman

**Comment by ashokvaddevalli** [comment] 2017-08-07 08:31
For temporary solution, I have completely disabled ipv6 on guest VM template. After disable ipv6, I have run Vagrant up.

E:\Vagrant-vpshere\Vagrant>vagrant up --provider=vsphere
Bringing machine 'default' up with 'vsphere' provider...
==> default: Calling vSphere CloneVM with the following settings:
==> default: -- Template VM: DemoIAM/vm/Templates/win7latest2
==> default: -- Target VM: DemoIAM/vm/Templates/test
==> default: New virtual machine successfully cloned
==> default: Waiting for the machine to report its IP address...
default: Timeout: 240 seconds
default: IP: xxx
==> default: Waiting for machine to boot. This may take a few minutes...
default: WinRM address: xxx:5985
default: WinRM username: administrator
default: WinRM execution_time_limit: PT2H
default: WinRM transport: negotiate
==> default: Machine booted and ready!

Facing Issues:

It's hanged out after ==> default: Machine booted and ready!
It is not Synced folder Host machine to guest VM.
It is not running provisioning scripts.

Debug log:

==> default: Machine booted and ready!
INFO warden: Calling IN action: #Vagrant::Action::Builtin::Provision:0x00000003d82388
INFO provision: Checking provisioner sentinel file...
INFO warden: Calling IN action: #Vagrant::Action::Builtin::SyncedFolders:0x000000037db880
INFO synced_folders: SyncedFolders loading from cache: false
INFO subprocess: Starting process: ["C:\Windows\System32\WindowsPowerShell\v1.0\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "(new-object System.Security.Principal.WindowsPrincipal([System.Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)"]
INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: True

**Comment by chrisroberts** [comment] 2017-08-07 17:31
Duplicate of #8759

**Closed by chrisroberts** 2017-08-07 17:31 UTC
Labels: duplicate, networking
