### ISSUE TITLE
1.8.5 breaks VirtualBox shared folder mounting for `id -g` fallback

### ISSUE THREAD

**Issue by tomxtobin** [mitchellh/vagrant#7640] opened 2016-07-25 22:30 UTC
The changes in 7e88266999e0eaf86299421e99a4fb038b4f2b1c break VirtualBox shared folder mounting when the `id -g` fallback is needed for the guest OS.

Whereas before the following two commands in
`mount_virtualbox_shared_folder.rb` [would be run separately](https://github.com/mitchellh/vagrant/blob/61d2a50a54bcebb40aa476f8c14be8f14db2be7f/plugins/guests/linux/cap/mount_virtualbox_shared_folder.rb#L45):
```
mount -t vboxsf -o uid=`id -u username`,gid=`getent group username | cut -d: -f3`,ro home_username_dirname /home/username/dirname
mount -t vboxsf -o uid=`id -u username`,gid=`id -g username`,ro home_username_dirname /home/username/dirname
```
... [now they're run together](https://github.com/mitchellh/vagrant/blob/93f9528687b9a737585d22bc4db5d2ab5d9852d3/plugins/guests/linux/cap/mount_virtualbox_shared_folder.rb#L45), and the failure of `getent group username` causes the second `mount` to never be called because of `set -e`:

```
==> machinename: Mounting shared folders...
    machinename: /home/username/dirname => /home/username/dirname
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attemped was:

set -e
mount -t vboxsf -o uid=`id -u username`,gid=`getent group username | cut -d: -f3`,ro home_username_dirname /home/username/dirname
mount -t vboxsf -o uid=`id -u username`,gid=`id -g username`,ro home_username_dirname /home/username/dirname

The error output from the command was:

gid= requires an argument (i.e. gid==<arg>)
```

### Vagrant version

1.8.5

### Host operating system

Arch Linux

### Guest operating system

Ubuntu 12.04.5

### Vagrantfile

```ruby
vm_name = "machinename"

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  config.ssh.private_key_path = "~/.ssh/id_rsa"
  config.ssh.username = "username"
  config.vm.box = "precise-username"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1536"
  end
  config.vm.define vm_name
  config.vm.network "private_network", ip: "192.168.222.222"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../dirname", "/home/username/dirname", :mount_options => ["ro"]
end
```

### Debug output

I'm not sure I can adequately scrub the debug output of sensitive information.

### Expected behavior

My shared folder mounts properly, as it does in Vagrant 1.8.4.

### Actual behavior

My shared folder fails to mount with the above error.

### Steps to reproduce
1. Try to mount a VirtualBox shared folder in 1.8.5 from a guest for
   which `getent group username` would fail, but `id -g username` works.

**Comment by sethvargo** [comment] 2016-07-25 23:11
Dupe of https://github.com/mitchellh/vagrant/issues/7616. Sorry about that!

**Closed by sethvargo** 2016-07-25 23:11 UTC

**Comment by tomascreemers** [comment] 2016-08-11 10:10
Also hitting this. Workaround: supply a group name that is also a user name. On at least OpenSuSE 12.3, "nobody" is a user name and a group name. Example:
`config.vm.synced_folder ".", "/vagrant", owner: "wwwrun", group: "nobody"`
