### ISSUE TITLE
Vagrant fails to mount shared filesystem

### ISSUE THREAD

**Issue by tiferrei** [mitchellh/vagrant#8516] opened 2017-04-24 09:58 UTC
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 1.9.3

### Host operating system
macOS Sierra (10.12.5 16F60a)

### Guest operating system
Kali Linux amd64

### Vagrantfile
https://github.com/Sliim/pentest-env

### Debug output
https://gist.github.com/tiferrei/69444542970cce50af979abdb3e1ab84

### Expected behavior
Mount vagrant correctly.

### Actual behavior
Fails to mount, fs not found.

### Steps to reproduce
1. Update everything, VB, VB guest additions, extension kit, vagrant, vagrant plugins.
2. Vagrant up
3. Fails to mount vagrant shared folder, but boots, so I can ssh.

**Comment by GhaziTriki** [comment] 2017-04-24 13:48
I have the same issue, it seems to be related to the latest version of VirtualBox. https://www.virtualbox.org/ticket/16670

**Comment by tiferrei** [comment] 2017-04-24 14:02
Awesome @GhaziTriki , you just got us a quick-fix:
```
ln -sf /usr/lib/x86_64-linux-gnu/VBoxGuestAdditions/mount.vboxsf /sbin/mount.vboxsf
```
This will work for most Debian based distros.
Basically the `vboxsf` is incirrectly simlinked in the last release, we just have to simlink it to the right directory and this fixes the issue.

**Comment by chrisroberts** [comment] 2017-04-24 15:46
Duplicate of: #8502

**Closed by chrisroberts** 2017-04-24 15:46 UTC
Labels: duplicate, provider/virtualbox, upstream
