### ISSUE TITLE
Provision of aws windows image fails on chef-solo start.

### ISSUE THREAD

**Issue by visshal** [mitchellh/vagrant#7577] opened 2016-07-13 22:20 UTC
### Vagrant version
Vagrant 1.8.1 & 1.8.4

### Host operating system
Mac OS X El Capitan 10.11.5
### Guest operating system
Windows 8

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  #Username: IEUser
  #Password: Passw0rd!
  
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box   = "modernIE/w8-ie10"
  config.vm.guest = :windows
  config.vm.boot_timeout = 1200
  config.vm.hostname = "ld-epo"


  #config.vm.network "private_network", ip: "10.0.20.101"
  config.vm.network :forwarded_port, guest: 3389, host: 33389
  config.vm.network :forwarded_port, guest: 5985, host: 55985, id: "winrm", auto_correct: true

  config.winrm.username = 'IEUser'
  config.winrm.password = 'Passw0rd!'
  config.vm.communicator = :winrm

  config.windows.set_work_network = true

  config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, '--rtcuseutc', "on"]
        vb.customize ["modifyvm", :id, '--accelerate3d', "off"]
        vb.customize ["modifyvm", :id, '--natdnshostresolver1', "on"]
        vb.customize ["modifyvm", :id, '--natdnsproxy1', "on"]
        vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
  end

  
  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision 'chef_solo' do |chef|
    chef.cookbooks_path = 'cookbooks'
    chef.add_recipe 'fiddler'
  end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output

Debug link: https://gist.github.com/visshal/ea0fafd51e2130111a8152fd51dd929e#file-gistfile1-txt

==> default: Exception calling "Run" with "1" argument(s): "Element not found. (Exception 
==> default: from HRESULT: 0x80070490)"
==> default: At C:\tmp\vagrant-elevated-shell.ps1:73 char:1
==> default: + $registered_task.Run($null) | Out-Null
==> default: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> default:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> default:     + FullyQualifiedErrorId : ComMethodTargetInvocation
==> default:  
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

### Expected behavior
Vagrant up --provision  should build the machine with fiddler recipe installed.
### Actual behavior
Vagrant up -provision fails.
### Steps to reproduce
1. vagrant up --provision or vagrant reload --provision

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-6345

**Comment by sethvargo** [comment] 2016-07-13 22:28
Hi there,

Thank you for opening an issue. Unfortunately you are missing a very large portion of the debug output. Can you please run in [debug mode](https://www.vagrantup.com/docs/other/debugging.html) and update the gist? It should be a few thousand lines of output. Thanks!

**Comment by visshal** [comment] 2016-07-13 23:22
Hi Seth,

Uploaded detailed log file at following location.

https://gist.github.com/visshal/3ff42cc7962aeffa017df78b5677ce9f

**Comment by visshal** [comment] 2016-07-14 15:46
Thanks for accepting this one as a Bug. Meanwhile can you please suggest me which compatible versions of chef, vagrant and virtualbox would work fine for windows 2008 platform?

Please advise.

Thanks,
Vishal.

**Comment by lonniev** [comment] 2016-08-23 15:55
I'm hitting this for Mac 10.11.6 with Vagrant 1.8.5 going to Windows Server 2012 and Chef 12.13.37.

This occurs when the vm communicator is winrm.

I thought perhaps there was an issue with the winrm communicator not being able to run elevated scripts in powershell. (Based on google surfing finding some traffic on WinRM and Elevated scripts.)

Any guidance, anyone, on ways to patch around this?

**Comment by lonniev** [comment] 2016-09-22 23:49
This is a duplicate of #6418.

**Closed** 2016-09-22 23:54 UTC
Labels: bug, guest/windows, provisioner/chef
