### ISSUE TITLE
'shutdown -h now' failed on 'vagrant reload --provision'

### ISSUE THREAD

**Issue by kenorb** [mitchellh/vagrant#7244] opened 2016-04-19 17:41 UTC
### Vagrant version

Vagrant: 1.8.1
VBoxManage: 5.0.14r105127

### Host operating system

OS X 10.11.2

### Guest operating system

[CentOS 6 box](https://atlas.hashicorp.com/geerlingguy/boxes/centos6)

### Vagrantfile

VM: [geerlingguy/drupal-vm](https://github.com/geerlingguy/drupal-vm)

```
Vagrant.configure('2') do |config|
  config.vm.network :private_network, ip: '192.168.88.88'

  # SSH options.
  config.ssh.insert_key = false
  config.ssh.forward_agent = true

  # Vagrant box.
  config.vm.box = 'geerlingguy/centos6'

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
  end

  config.vm.provider :virtualbox do |v|
    v.name = 'drupalvm-base.dev'
    v.memory = 4096
    v.cpus = 4
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.hostname = 'drupalvm-base.dev'
end
```

with custom `config.yml`

### Debug output

```
 VAGRANT_LOG=debug vagrant reload --provision
 ...
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-f74463e404b58ea7c0fb33e1cc1c0127
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 6 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00000102c96a78>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::VagrantError: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

shutdown -h now

Stdout from the command:



Stderr from the command:

sudo: sorry, you must have a tty to run sudo
>
ERROR vagrant: The following SSH command responded with a non-zero exit status.

ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:236:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:246:in `sudo'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/guests/linux/cap/halt.rb:7:in `halt'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/capability_host.rb:111:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/capability_host.rb:111:in `capability'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/guest.rb:43:in `capability'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/graceful_halt.rb:50:in `call'
```

Full log at the following [gist](https://gist.github.com/kenorb/7dd2452c9dffe2f7b7aa352bbfe255fc).

### Expected behavior

VM should be reloaded.

### Actual behavior

VM failed to reload.

This was working before (like 1h before at the time of writing, then it just stopped).

It works when doing full `vagrant destroy -f` and `vagrant up`. So it fails only for `vagrant reload`.

### Steps to reproduce

1. `VAGRANT_LOG=debug vagrant reload --provision`

Also I did:

1. `vagrant destroy -f`
1. `rm -fr .vagrant/`
1. `vagrant up` - which worked
1. `vagrant reload` - didn't work, the same error as above

### References

- GH-6860
- GH-1482

**Comment by sethvargo** [comment] 2016-05-27 19:03
Hi @kenorb 

This looks like a duplicate of https://github.com/mitchellh/vagrant/issues/6449. In short - it's probably a problem with the box setup (or something a provisioner changed). The other thing that can cause this is SELinux. Please review the options in that post. Thanks! 😄

**Closed by sethvargo** 2016-05-27 19:03 UTC

**Comment by roberfern** [comment] 2019-02-12 17:11
I experienced this issue when I create a custom box and I don't have 'sudo' installed
