### ISSUE TITLE
chef solo provisioner issue

### ISSUE THREAD

**Issue by nckturner** [mitchellh/vagrant#7333] opened 2016-05-20 22:23 UTC
### Vagrant version
1.8.1

### Host operating system
OSX 10.10.5

### Guest operating system
Ubuntu 14.04

### Vagrantfile
```ruby
VAGRANTFILE_API_VERSION = '2'
Vagrant.require_version '>= 1.5.0'
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 config.vm.provider "virtualbox" do |v|
    v.gui = false 
 end
  config.vm.hostname = 'porch-nagios-berkshelf'
  if Vagrant.has_plugin?("vagrant-omnibus")
    config.omnibus.chef_version = 'latest'
  end
  config.vm.box = 'bento/ubuntu-14.04'
  config.vm.network :private_network, type: 'dhcp'
  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ['../']
    chef.data_bags_path = '../porch-chef/data_bags'
    chef.roles_path = '../porch-chef/roles'
    chef.environments_path = '../porch-chef/environments'
    chef.environment = 'dev'
    chef.json = {}

    chef.run_list = [
      'recipe[porch-base-packages]',
      'recipe[porch-ssh-monitoring::ssh_monitoring]',
      'recipe[porch-apt::default]',
      'recipe[porch-nagios::default]',
      'recipe[porch-nagios::pagerduty]',
      'recipe[chef-solo-search]'
    ]
  end
end
```

### Debug output
https://gist.github.com/nckturner/e1082e05df4eb3e75bd63b0eded96698

### Expected behavior
I have previously had no problems with the chef-solo provisioner and my current setup.  I expected `vagrant up` to provision the VM.  

### Actual behavior
`vagrant up` completes the vm creation successfully but fails on the chef solo provision.  It appears to be "falling back" on chef zero, even though the chef solo provisioner is called out in the vagrant file.  

The relevant output lines show it prints output referencing both chef-solo and chef-zero.  
```
==> default: Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: stdin: is not a tty
==> default: [2016-05-20T22:20:16+00:00] INFO: Started chef-zero at chefzero://localhost:8889 with repository at /tmp/vagrant-chef/ca728bc105c4e2273888faaf96c2d37c
==> default:   One version per cookbook
```

And the failure: 
```
==> default: ================================================================================
==> default: Chef encountered an error attempting to load the node data for "vagrant-dba34847"
==> default: ================================================================================
==> default:
==> default:
==> default: Resource Not Found:
==> default: -------------------
==> default: The server returned a HTTP 404. This usually indicates that your chef_server_url is incorrect.
==> default:
==> default:
==> default:
==> default: Relevant Config Settings:
==> default: -------------------------
==> default: chef_server_url "chefzero://localhost:8889"
```
I don't know where chef_server_url is coming from... 

I would be ok with using the chef-zero provisioner, but I switched to chef-solo previously so I could use the chef-solo-search recipe.  

### Steps to reproduce
1. A vagrant up or vagrant reload --provision should do it, but I'm not sure it will be easily reproduced as I have run this successfully with the same vagrantfile.

**Comment by sethvargo** [comment] 2016-05-21 14:25
Duplicate of https://github.com/mitchellh/vagrant/issues/7331

**Closed by sethvargo** 2016-05-21 14:25 UTC
