### ISSUE TITLE
Latest VMware Fusion Provider Not Following Symlinks

### ISSUE THREAD

**Issue by robneu** [mitchellh/vagrant#5474] opened 2015-03-13 07:06 UTC
After updating to `vagrant-vmware-fusion-3.2.4` from `vagrant-vmware-fusion-3.2.0` symlinks created on the host machine are no longer followed within the guest. I've verified that rolling back to the previous version of the provider fixes the problem, so it looks like something changed between those versions.

It's also not possible to force symlinks to be followed in a shared directory by passing them in through the vagrantfile. Setting `sharedFolder0.followSymlinks = "TRUE"` for any shared folder causes them to be set to `FALSE`.

## System Info:

Vagrant Version: `1.7.2`
VMware Version: `Version 7.1.1 (2498930)`
OS Version: `10.10.2 (14C1510)`

**Comment by sethvargo** [comment] 2015-03-17 15:03
Hey @robneu 

I am sorry you are having problems. I think @phinze has done some research and may be able to offer better insight than me.

**Comment by phinze** [comment] 2015-03-17 16:44
@robneu Sorry for the trouble on this! Turns out that proper symlink handling across various versions of Fusion and Workstation is pretty tricky. I'm committed to getting us to a place that works for everybody though. :+1: 

I see you have a support thread open with us - let's work out the back and forth details on that thread and I can follow up here with a summary of our findings.

**Comment by robneu** [comment] 2015-06-26 19:56
This is still a problem. VMWare update today killed symlinks again. Updated to the latest provider and it's still broken...

**Comment by phinze** [comment] 2015-06-26 19:58
@robneu oh no! So it was working for you until today's update? Which was the last working version?

**Comment by robneu** [comment] 2015-06-26 20:02
I had it working by rolling back to a previous version of the VMWare Vagrant plugin where symlinks were still working. It never worked on newer versions.

The last working configuration I had was

Vagrant `1.7.2.`
Vagrant VMWare Plugin `3.2.1`
VMware Fusion '7.1.1'

I'm not 100% sure about the plugin version, but I'll double check and update.

**Comment by phinze** [comment] 2015-06-26 20:13
I just went back and reviewed our support log. I'll reproduce a portion the last message from that thread here:

----

I just did a few quick smoke tests with Fusion 7.1.1 and version 3.2.4 of the plugin and everything is looking good from my side.

Our target behavior is that symlinks are mirrored into the guest precisely as they exist on the host.

So, for example, if you were to create this symlink on your host from the same directory as your Vagrantfile:

```
$ ln -s /var/www thewebsite
$ ls -l
# ...
lrwxr-xr-x  1 phinze  staff     5B Mar 17 13:01 thewebsite -> /var/www
# ...
```

In the guest you should expect the symlink to be there and have the same target:

```
$ vagrant ssh
[guest] $ ls -l /vagrant
# ...
lrwxr-xr-x  1 vagrant  vagrant     5B Mar 17 13:01 thewebsite -> /var/www
# ...
```

Now the important part here is that if you're not also mounting `/var/www` into the guest, it's possible that the link will resolve differently from your host and your guest. A common way of handling this in practice is the strategy of mounting a common parent directory into the same spot on the guest so that symlinks just work.

What I'm wondering is if you were previously experiencing the alternative "symlink flattening" behavior, whereby the shared folder is presented to the guest as simply a directory. In prior versions this behavior was activated in some setups but not on others. We've decided to consolidate on the default "symlink respecting" behavior, because it allows symlinks to be created and modified in the shared volumes - we had many more problems from users who were unable to use tools like npm with shared folders because of this limitation.

If you find you really do need the "symlink flattening" style of shared folder mounting for your workflow, then you can [drop down to a "manual" HGFS setup](https://gist.github.com/phinze/dfe3f912bb85f04d6a49) using linked the configuration snippets.

----

I never heard back from you after that message - is it true that you are expecting the "symlink flattening" behavior instead of the "symlink respecting" behavior we do? Have you tried the config snippets linked?

Let me know!

**Comment by robneu** [comment] 2015-06-26 20:44
It looks like I was getting the flattening style of shared folders previous. I just reverted back to the previous working configuration and symlinks are working for me again.

Here's a comparison of the two versions:

Vagrant VMWare Plugin `3.2.0`
VMware Fusion `7.1.1`
![screen shot 2015-06-26 at 3 34 33 pm](https://cloud.githubusercontent.com/assets/2184093/8386869/53ce5210-1c19-11e5-96d6-2d1df15ab968.png)

Vagrant VMWare Plugin `3.2.2`+
VMware Fusion `7.1.2`
![screen shot 2015-06-26 at 3 30 34 pm](https://cloud.githubusercontent.com/assets/2184093/8386882/75d43078-1c19-11e5-9a0a-feba61ab552e.png)

The second one does mirror the structure on the host exactly, but for whatever reason that directory can't be followed in the guest. If I try to navigate to the directory while connected to the guest it's empty.

I don't totally follow what you're saying about not mounting `var/www`. I honestly don't use vagrant much beyond spinning up a pre-configured environment, so I'm not sure the best way to handle this. I'd really rather not be stuck on an outdated version of both VMWare and the Vagrant plugin forever...

**Comment by robneu** [comment] 2015-06-26 21:02
I'm not sure if it's helpful, but here's the [vagrantfile](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile) for the dev environment that I use. 

Do you see anything in there that would explain the issues I'm having? Can you point out what I'd need to change RE that config that you linked to?

**Comment by robneu** [comment] 2015-08-17 19:51
Any update on this? I'm still stuck using outdated versions at the moment...

**Comment by bsuh** [comment] 2016-01-14 00:06
@phinze Please consider defaulting to symlink flattening for nix hosts with Windows guests, as nix symbolic links are useless unflattened on Windows guests.

**Comment by chrisroberts** [comment] 2016-10-06 23:32
With latest versions of fusion, vagrant, and the fusion plugin I am unable to reproduce. If there is still a problem, can you please let me know versions in use as well as the box (and its version) you are using. Thanks!

**Comment by tiwilliam** [comment] 2016-10-10 18:31
I'm seeing broken symlinks with:
* macOS Sierra (16A323)
* Vagrant 1.8.6
* vagrant-vmware-fusion 4.0.13
* VMWare Fusion 8.5.0 (4352717)
* Latest Ubuntu 14.04

HGFS module and VMWare tools are installed using built-in VMWare Fusion image.

Host:
```
lrwxr-xr-x  1 william  staff  21 Aug  9 12:05 tests/utils.py -> ../scripts/ttutils.py
lrwxr-xr-x  1 william  staff  30 Oct 10 12:11 tests/utils.py -> /-vagrant../scripts/ttutils.py
```

Guest:
```
lrwxr-xr-x  1 vagrant  vagrant  21 Aug  9 12:05 tests/utils.py -> s/ttutils.py
lrwxr-xr-x  1 vagrant  vagrant  30 Oct 10 12:11 tests/utils.py -> ../scripts/ttutils.py
```

**Comment by tiwilliam** [comment] 2016-10-10 19:58
Both links are created using `ln -s ../scripts/ttutils.py tests/utils.py`, once executed on the host machine, once on the VM. Output above is `ls -l` from the host, and guest.

**Comment by chrisroberts** [comment] 2016-10-10 20:03
and is the `ln -s ...` command run from the root of the shared directory?

**Comment by tiwilliam** [comment] 2016-10-10 20:05
Not the root, but inside the shared directory. Pwd is `/vagrant/Code/x/y/` and it creates `/vagrant/Code/x/y/tests/utils.py`. `/vagrant` mounts `/Users/william` from host.

**Comment by tiwilliam** [comment] 2016-10-10 20:12
Here's easier way to reproduce:
```
william vm /vagrant $ sudo ln -s /etc/debian_version
william vm /vagrant $
```
```
william host ~ $ ls -l debian_version
lrwxr-xr-x  1 william  staff  28 Oct 10 22:10 debian_version -> /-vagrant/etc/debian_version
william host ~ $
```

**Comment by chrisroberts** [comment] 2016-10-10 23:01
@tiwilliam Thanks for the feedback. I've got it successfully reproduced and will be getting a fix out soon.

**Comment by chrisroberts** [comment] 2016-10-17 14:36
@tiwilliam Thank you again for the feedback! It helped me to track down the root of the issue and a fix has been released.

https://github.com/hashicorp/vagrant-plugin-changelog/blob/master/vagrant-vmware-changelog.md#4014-october-14-2016

Cheers!

**Closed by chrisroberts** 2016-10-17 14:36 UTC
Labels: bug, provider/vmware, waiting-reply

**Comment by tiwilliam** [comment] 2016-10-17 16:18
Thanks!
