### ISSUE TITLE
(remote) ansible provisioner: the extra_args option (as a hash) is not passed properly

### ISSUE THREAD

**Issue by gildegoma** [mitchellh/vagrant#7255] opened 2016-04-23 21:47 UTC
### Vagrant version
Vagrant 1.8.1

### Ansible version (also affects 1.9.x in exact same way)

ansible-playbook 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides

### Host operating system

OSX 10.11.4

### Guest operating system
Centos7 / any linux that can be targeted by ansible really

#### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  # provisioning ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "play.yml"
    ansible.verbose = "vvvv"
    ansible.extra_vars = {
      # send a string of generated keycloak servers to the haproxy
      extra1: Array.new(3){ |n| "bla#{(1 + n).to_s.rjust(2,'0')}" },
      extra2: true
    }
  end # ansible provisioning

end
```

#### play.yml
```yaml
---
- hosts: all
  # strategy: debug
  gather_facts: no
  tasks:
    - debug: var=extra1

    - fail: msg="extra1 arg not set"
      when: extra1 is undefined
```

### Debug output

```sh
$ vagrant provision
==> default: Running provisioner: ansible...
    default: Running ansible-playbook...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true 
ANSIBLE_HOST_KEY_CHECKING=false 
ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s' 
ansible-playbook --connection=ssh --timeout=30 --limit='default' \
                           --inventory-file=/Users/fred/workspaces/extraargs/.vagrant/provisioners/ansible/inventory \
                           --extra-vars='{"extra1":["bla01","bla02","bla03"],"extra2":true}'\
                           -vvvv play.yml
No config file found; using defaults
Loaded callback default of type stdout, v2.0
1 plays in play.yml

PLAY ***************************************************************************

TASK [debug] *******************************************************************
task path: /Users/fred/workspaces/extraargs/play.yml:6
ok: [default] => {
    "extra1": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************
default                    : ok=1    changed=0    unreachable=0    failed=1
```

### Expected behavior

Extra args should be passed properly to the ansible playbook executable:

```sh
PYTHONUNBUFFERED=1 \
ANSIBLE_FORCE_COLOR=true \
ANSIBLE_HOST_KEY_CHECKING=false \
ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s' \
ansible-playbook --connection=ssh \
                 --timeout=30 \
                 --limit='default' \
                 --inventory-file=./.vagrant/provisioners/ansible/inventory \
                 --extra-vars='{"extra1":["bla01","bla02","bla03"],"extra2":true}' \
                 -vvvv play.yml

No config file found; using defaults
Loaded callback default of type stdout, v2.0
1 plays in play.yml

PLAY ***************************************************************************

TASK [debug] *******************************************************************
task path: /Users/fred/workspaces/extraargs/play.yml:6
ok: [default] => {
    "extra1": [
        "bla01", 
        "bla02", 
        "bla03"
    ]
}

PLAY RECAP *********************************************************************
default                    : ok=1    changed=0    unreachable=0    failed=0
```
### Actual behavior

`extra_args` are not passed properly by vagrant to the ansible-playbook process

### Steps to reproduce

1. copy `Vagrantfile` from above to empty folder
2. copy `play.yml` file from above into same folder
3. run vagrant up and watch ansible provisioning step fail

### References

This issue was initially reported by @bertramn as a [comment](https://github.com/mitchellh/vagrant/issues/6726#issuecomment-213640186) on GH-6726.

**Comment by gildegoma** [comment] 2016-04-23 21:54
As already mentioned in https://github.com/mitchellh/vagrant/issues/6726#issuecomment-213675468,
I couldn't reproduce this problem (Note that I have been testing on a Mac OS X 10.10.5, not 10.11).

Although the vagrant verbose output has nothing to do with the effective `Subprocess.execute` call to `ansible-playbook`, I'm very surprised by the above excerpts, because the output of the `ansible` provisioner in Vagrant 1.8.1 should be the following (except the manually-added `\` for shell line breaks):

```
vagrant provision
==> machine1: Configuring cache buckets...
==> machine1: Running provisioner: ansible...
    machine1: Running ansible-playbook...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false \
ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s' \
ansible-playbook --connection=ssh --timeout=30 --limit='machine1' \
--inventory-file=/.../.vagrant_resi/provisioners/ansible/inventory \
--extra-vars={"extra1":["bla01","bla02","bla03"],"extra2":true} \
-vvvv play.yml
```

Note the absence of single quotes compared to @bertramn excerpts in the problem description:

`--extra-vars='{"extra1":["bla01","bla02","bla03"],"extra2":true}'`

and Vagrant 1.8.1 (which is the original cause of the bug GH-6726 that affects the `ansible_local` provisioner):

`--extra-vars={"extra1":["bla01","bla02","bla03"],"extra2":true}`

This makes me wonder if you're really using a genuine Vagrant 1.8.1 version...

**Comment by gildegoma** [comment] 2016-05-26 07:10
@bertramn without any additional feedback, I'm going to close this issue as I cannot reproduce the problem you reported with the `ansible` provisioner. Thanks for your understanding...

**Comment by sethvargo** [comment] 2016-05-30 22:14
@gildegoma Go ahead and close this

**Closed** 2016-05-31 05:32 UTC
Labels: needs info, provisioner/ansible, waiting-reply

**Comment by bertramn** [comment] 2017-02-01 03:26
Hi @gildegoma, I tried to ignore this problem for the last year but I must admit I never got it working properly.  I moved to vagrant 1.8.7 and ansible 2.2.0.0 and the problem with using hashes in `--extra-vars` still exists.

The big disclaimer is that I run this all on Windows and have not really tested this on macOS or Ubuntu.

I wrote a go executable to allow Vagrant on Windows to run the ansible-playbook command to a Cygwin python instance. I documented a working setup and the windows wrapper [here](https://github.com/bertramn/ansible-win-wrapper).

After having a reliable way to determine what exactly Vagrant is sending to the `ansible-playbook` command, I discovered 2 problems that cause this issue. As usual only fixing the 2 make it work and the discussion on #6726 as well as the changes on #7103 do not consider the 2nd subtil problem that is actually an ansible bug I believe. What is really misleading here is all Vagrant debug output strings are actually constructed differently to the actual string that gets passed to the Subprocess for execution when the extra_vars are a hash.

Lets say we create a extra_vars hash in the `Vagrantfile`:
```rb
ansible.extra_vars = {
  my_special_param: Array.new(2){ |n| "#{(1 + n).to_s.rjust(2,'0')}" }
}
```

I'd expect this passed to the process:

`--extra-vars={ \"my_special_param\":[\"01\",\"02\"] }`

The actual argument passed to the `ansible-playbook` process is:

`--extra-vars={my_special_param:[01,02]}`

This problem is caused by the way the JSON is generated for a ruby hash.

The first problem is that the `to_json` derrived string does not escape the double quotes which will get lost in the Subprocess call out.

The other problem is that `ansible-playbook` is very picky in the way it receives and parses the json in the `--extra-vars` argument. In particular it expects a space after the opening bracket `{` and a space before the closig bracket `}`.

So if we apply the following changes to the vagrant file `$VAGRANT_HOME/embedded/gems/gems/vagrant-1.8.7/plugins/provisioners/ansible/provisioner/base.rb` we get desired result.

```rb
def extra_vars_argument
  if has_an_extra_vars_file_argument
    # A JSON or YAML file is referenced.
    config.extra_vars
  else
    # Expected to be a Hash after config validation.
    config.extra_vars.to_json.gsub('{', '{ ').gsub('}', ' }').gsub('"', '\\\"') # << the hacked line fixes space of the curlies and escapes the double quotes
  end
end
```

Remains to be tested on *nix and macOS but I am pretty sure this will work fine there too.
