### ISSUE TITLE
Second network interface down on vagrant up

### ISSUE THREAD

**Issue by Pupp3tm4st3r** [mitchellh/vagrant#8206] opened 2017-01-16 13:33 UTC
### Vagrant version
1.9.1

### Host operating system
Mac OSX 10.11.6

### Guest operating system
CentOS 7.3

### Vagrantfile
Vagrant.configure("2") do |config|

  config.vm.box = "centos-7.3-x86_64.box"

  config.vm.hostname = "xxxxxxxx"
  config.vm.network "private_network", ip: "192.168.33.243"

 #config.vbguest.auto_update = false

  config.ssh.forward_agent = true
  config.ssh.keep_alive = true
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--name", "xxxxxxxxxx"]
    v.customize ["modifyvm", :id, "--accelerate3d", "off"]
    v.customize ["modifyvm", :id, "--accelerate2dvideo", "off"]
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
    v.customize ["modifyvm", :id, "--largepages", "on"]
  end

end

### Error:
The second interface is "down" when "vagrant up". A "systemctl restart network" solves the error and it will work on "reboot", too. But "vagrant halt" and "vagrant up" won´t work - the interface will remain down.

### Expected behavior:
The Interface is up.

### Additional Information:
The basebox is built by myself.

Regards
Simon

**Comment by Pupp3tm4st3r** [comment] 2017-01-16 14:08
Just tested it with the centos/7 box from vagrant atlas - same behavior.

**Comment by kikitux** [comment] 2017-01-16 19:16
Hello

Seems duplicate of:
https://github.com/mitchellh/vagrant/issues/8166

Fix will be on next version

**Closed by kikitux** 2017-01-16 19:16 UTC

**Comment by Pupp3tm4st3r** [comment] 2017-01-16 21:03
oh sorry :( have had searched for it but didn´t found this issue :/
