### ISSUE TITLE
Port Collision issue after upgrading VMWare Fusion to 8.5.5

### ISSUE THREAD

**Issue by mondoshivan** [mitchellh/vagrant#8419] opened 2017-03-28 09:03 UTC
Hello,

end of last weed I upgraded VMWare Fusion  and Vagrant on our macOS servers and I am running into a port collision issue on each server. There are no forwarded ports configured in my Vagrantfile.

### Vagrant version
1.9.3

### Host operating system
macOS 10.12.3

### Guest operating system
Windows 10 - 64 Bit

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "win/eval-win10x64-enterprise/1.0.0/vmware/eval-win10x64-enterprise-1.0.0"

  config.vm.box_url = "http://vagrantshare/boxes/win/eval-win10x64-enterprise/1.0.0/vmware/eval-win10x64-enterprise-1.0.0.box"

  config.vm.network "public_network"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "vmware_fusion" do |vb|
    vb.gui = false
    vb.cpus = 1

    vb.memory = "4096"
  end
end
```

### Debug output
https://gist.github.com/mondoshivan/96737482029bf265e24ae477b5170b78#file-gistfile1-txt

### Expected behavior
vagrant up finishes without port collision issue

### Actual behavior
vagrant up finishes with port collision issue

### Steps to reproduce
1. I installed latest Vagrant (1.9.3) and VMWare Fusion (8.5.5) updates
2. vagrant up

### References
- GH-7948

**Comment by dotcarls** [comment] 2017-03-28 17:31
As mentioned in #7948, a [workaround for this](https://github.com/mitchellh/vagrant/issues/7948#issuecomment-264835320) is editing `/Library/Preferences/VMware Fusion/vmnet8/nat.conf` to remove the old entries. Wish this would be addressed.. feeling pretty salty about purchasing a plugin that's less stable than a free one like Virtualbox.

**Comment by chrisroberts** [comment] 2017-03-28 22:00
@dotcarls Hi! Recent releases of the vmware plugin include a fix for this issue. If there were existing entries that were previously "lost" within the `nat.conf` file, they need to be manually removed. 

https://github.com/mitchellh/vagrant/issues/7948#issuecomment-283108576

If you are still experiencing problems after that, please do reopen this issue or open a new one. Cheers!

**Closed by chrisroberts** 2017-03-28 22:00 UTC
Labels: bug, duplicate, provider/vmware

**Comment by dotcarls** [comment] 2017-03-28 22:12
@chrisroberts I'll upgrade and give it a shot! Cheers!

**Comment by mondoshivan** [comment] 2017-03-29 08:24
Hi, I uninstalled VMWare Fusion following this article:
[https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1017838](url)

Then I installed latest VMWare Fusion 8.5.6 (released yesterday).

When I do a "vagrant up", I get this:
![screen shot 2017-03-29 at 10 20 27](https://cloud.githubusercontent.com/assets/18459671/24445341/e5d5a7a4-1469-11e7-8768-d63ee9a92c15.png)

**Comment by chrisroberts** [comment] 2017-03-31 19:09
@mondoshivan When you re-installed VMware Fusion, did you place the VMware application into the `Applications` folder on the system?

**Comment by mondoshivan** [comment] 2017-04-01 09:06
No, I did a regular installation by running the app on the dmg.
If I create the following file after the installation, "vagrant up" works also without port collisions:
`sudo touch /Library/Preferences/VMware Fusion/networking`

But from time to time I am still experiencing collisions. Maybe after reboot of the host OS. I have to investigate.

**Comment by chrisroberts** [comment] 2017-04-01 15:14
Vagrant expects VMware to be installed into the Applications directory. When run directly from the dmg the paths are not always the same which can lead to unexpected behavior.

**Comment by Poisoned** [comment] 2017-04-04 13:56
Hi, I also upgraded VMWare Fusion and Vagrant on my machine and I'm experiencing the same issue.
The mentioned ![workaround](https://github.com/mitchellh/vagrant/issues/7948#issuecomment-264835320) worked for me once. But now the problem is persistent and the virtual machine won't boot anymore. 

I also tried to remove all entries from `nat.conf` and `networking`, but unfortunately 
without success.

```
$ vagrant -v
Vagrant 1.9.3

$ vagrant plugin list
vagrant-share (1.1.7)
  - Version Constraint: > 0
vagrant-vmware-fusion (4.0.18)
  - Version Constraint: > 0
```
VMware Fusion
Version 8.5.6 (5234762)

macOS Sierra
Version 10.12.4

Is there an ETA for a fix for this issue?

**Comment by mondoshivan** [comment] 2017-04-05 10:42
@chrisroberts VMWare is installed in the Applications directory! The app on the dmg triggers the installation routine, which places the VMWare Fusion.app inside the Applications folder. Like mentioned, on a clean system, after the installation of VMWare Fusion, I have to create this file:
`sudo touch /Library/Preferences/VMware Fusion/networking`
and 'vagrant up' works.

But I am still experiencing port collisions.
