### ISSUE TITLE
vagrant up  failing for fedora 24

### ISSUE THREAD

**Issue by tzvetkoff** [mitchellh/vagrant#7994] opened 2016-11-11 03:46 UTC
OS: `macOS Sierra 10.12.1`
Vagrant: `1.8.7`
Ruby: `2.3.1p112` (RVM)

I was trying to start my freshly installed Fedora box and I got this:

```
[w00t@phoenix(~/redacted)]$ vagrant up
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Cloning VMware VM: 'tzvetkoff/fedora-24'. This can take some time...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 172.16.26.143:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Forwarding ports...
    default: -- 22 => 2222
==> default: Configuring network adapters within the VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

# Restart network
service network restart


Stdout from the command:

Restarting network (via systemctl):  [FAILED]


Stderr from the command:

Job for network.service failed because the control process exited with error code. See "systemctl status network.service" and "journalctl -xe" for details.
```

Here are the logs from the VM:
```
[vagrant@localhost ~]$ journalctl -xe
Nov 11 05:35:29 localhost.localdomain audit[1970]: USER_CMD pid=1970 uid=1000 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='cwd="/home/vagrant" cmd=7365727669
Nov 11 05:35:29 localhost.localdomain audit[1970]: CRED_REFR pid=1970 uid=0 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_env,pam_
Nov 11 05:35:29 localhost.localdomain sudo[1970]: pam_systemd(sudo:session): Cannot create session: Already running in a session
Nov 11 05:35:29 localhost.localdomain sudo[1970]: pam_unix(sudo:session): session opened for user root by vagrant(uid=0)
Nov 11 05:35:29 localhost.localdomain audit[1970]: USER_START pid=1970 uid=0 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_ke
Nov 11 05:35:29 localhost.localdomain systemd[1]: Stopped LSB: Bring up/down networking.
-- Subject: Unit network.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit network.service has finished shutting down.
Nov 11 05:35:29 localhost.localdomain systemd[1]: Starting LSB: Bring up/down networking...
-- Subject: Unit network.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit network.service has begun starting up.
Nov 11 05:35:29 localhost.localdomain systemd-sysctl[2019]: Couldn't write '0' to 'net/bridge/bridge-nf-call-iptables', ignoring: No such file or directory
Nov 11 05:35:29 localhost.localdomain systemd-sysctl[2019]: Couldn't write '0' to 'net/bridge/bridge-nf-call-arptables', ignoring: No such file or directory
Nov 11 05:35:29 localhost.localdomain systemd-sysctl[2019]: Couldn't write '0' to 'net/bridge/bridge-nf-call-ip6tables', ignoring: No such file or directory
Nov 11 05:35:29 localhost.localdomain network[1992]: Bringing up loopback interface:  Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Nov 11 05:35:29 localhost.localdomain network[1992]: Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Nov 11 05:35:29 localhost.localdomain network[1992]: Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Nov 11 05:35:29 localhost.localdomain network[1992]: Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Nov 11 05:35:29 localhost.localdomain network[1992]: [  OK  ]
Nov 11 05:35:29 localhost.localdomain NetworkManager[651]: <info>  [1478835329.8763] audit: op="connection-activate" uuid="3b3413b9-a44d-3c69-a12a-8a925a2e7bbd" name="ens33" result="fail" reas
Nov 11 05:35:29 localhost.localdomain network[1992]: Bringing up interface ens33:  Error: Connection activation failed: No suitable device found for this connection.
Nov 11 05:35:29 localhost.localdomain network[1992]: [FAILED]
Nov 11 05:35:29 localhost.localdomain network[1992]: RTNETLINK answers: File exists
Nov 11 05:35:29 localhost.localdomain network[1992]: RTNETLINK answers: File exists
Nov 11 05:35:29 localhost.localdomain network[1992]: RTNETLINK answers: File exists
Nov 11 05:35:29 localhost.localdomain network[1992]: RTNETLINK answers: File exists
Nov 11 05:35:29 localhost.localdomain network[1992]: RTNETLINK answers: File exists
Nov 11 05:35:29 localhost.localdomain network[1992]: RTNETLINK answers: File exists
Nov 11 05:35:29 localhost.localdomain network[1992]: RTNETLINK answers: File exists
Nov 11 05:35:29 localhost.localdomain network[1992]: RTNETLINK answers: File exists
Nov 11 05:35:29 localhost.localdomain network[1992]: RTNETLINK answers: File exists
Nov 11 05:35:29 localhost.localdomain systemd-sysctl[2196]: Couldn't write '0' to 'net/bridge/bridge-nf-call-ip6tables', ignoring: No such file or directory
Nov 11 05:35:29 localhost.localdomain systemd-sysctl[2196]: Couldn't write '0' to 'net/bridge/bridge-nf-call-arptables', ignoring: No such file or directory
Nov 11 05:35:29 localhost.localdomain systemd-sysctl[2196]: Couldn't write '0' to 'net/bridge/bridge-nf-call-iptables', ignoring: No such file or directory
Nov 11 05:35:29 localhost.localdomain systemd[1]: network.service: Control process exited, code=exited status=1
Nov 11 05:35:29 localhost.localdomain systemd[1]: Failed to start LSB: Bring up/down networking.
-- Subject: Unit network.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit network.service has failed.
--
-- The result is failed.
Nov 11 05:35:29 localhost.localdomain systemd[1]: network.service: Unit entered failed state.
Nov 11 05:35:29 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=network comm="systemd" exe="/usr/lib/systemd
Nov 11 05:35:29 localhost.localdomain systemd[1]: network.service: Failed with result 'exit-code'.
Nov 11 05:35:29 localhost.localdomain sudo[1970]: pam_unix(sudo:session): session closed for user root
Nov 11 05:35:29 localhost.localdomain audit[1970]: USER_END pid=1970 uid=0 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_close grantors=pam_key
Nov 11 05:35:29 localhost.localdomain audit[1970]: CRED_DISP pid=1970 uid=0 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_env,pam_
...skipping...
-- All system services necessary queued for starting at boot have been
-- successfully started. Note that this does not mean that the machine is
-- now idle as services might still be busy with completing start-up.
--
-- Kernel start-up required KERNEL_USEC microseconds.
--
-- Initial RAM disk start-up required INITRD_USEC microseconds.
--
-- Userspace start-up required 23519 microseconds.
Nov 11 05:35:09 localhost.localdomain systemd[1]: Started User Manager for UID 1000.
-- Subject: Unit user@1000.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit user@1000.service has finished starting up.
--
-- The start-up result is done.
Nov 11 05:35:09 localhost.localdomain sshd[1924]: pam_unix(sshd:session): session opened for user vagrant by (uid=0)
Nov 11 05:35:09 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=user@1000 comm="systemd" exe="/usr/lib/syste
Nov 11 05:35:09 localhost.localdomain audit[1924]: USER_START pid=1924 uid=0 auid=1000 ses=3 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_selinux,pam_logi
Nov 11 05:35:09 localhost.localdomain audit[1934]: CRYPTO_KEY_USER pid=1934 uid=0 auid=1000 ses=3 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:d8:d7:3b:7e
Nov 11 05:35:09 localhost.localdomain audit[1934]: CRYPTO_KEY_USER pid=1934 uid=0 auid=1000 ses=3 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:27:8f:52:7a
Nov 11 05:35:09 localhost.localdomain audit[1934]: CRYPTO_KEY_USER pid=1934 uid=0 auid=1000 ses=3 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:69:23:c7:9c
Nov 11 05:35:09 localhost.localdomain audit[1934]: CRED_ACQ pid=1934 uid=0 auid=1000 ses=3 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_env,pam_unix acct="vagr
Nov 11 05:35:09 localhost.localdomain audit[1924]: USER_LOGIN pid=1924 uid=0 auid=1000 ses=3 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=login id=1000 exe="/usr/sbin/sshd" hostname=17
Nov 11 05:35:09 localhost.localdomain audit[1924]: USER_START pid=1924 uid=0 auid=1000 ses=3 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=login id=1000 exe="/usr/sbin/sshd" hostname=17
Nov 11 05:35:09 localhost.localdomain audit[1924]: CRYPTO_KEY_USER pid=1924 uid=0 auid=1000 ses=3 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:69:23:c7:9c
Nov 11 05:35:29 localhost.localdomain sudo[1970]:  vagrant : TTY=pts/0 ; PWD=/home/vagrant ; USER=root ; COMMAND=/sbin/service network restart
Nov 11 05:35:29 localhost.localdomain audit[1970]: USER_CMD pid=1970 uid=1000 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='cwd="/home/vagrant" cmd=7365727669
Nov 11 05:35:29 localhost.localdomain audit[1970]: CRED_REFR pid=1970 uid=0 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_env,pam_
Nov 11 05:35:29 localhost.localdomain sudo[1970]: pam_systemd(sudo:session): Cannot create session: Already running in a session
Nov 11 05:35:29 localhost.localdomain sudo[1970]: pam_unix(sudo:session): session opened for user root by vagrant(uid=0)
Nov 11 05:35:29 localhost.localdomain audit[1970]: USER_START pid=1970 uid=0 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_ke
Nov 11 05:35:29 localhost.localdomain systemd[1]: Stopped LSB: Bring up/down networking.
-- Subject: Unit network.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit network.service has finished shutting down.
Nov 11 05:35:29 localhost.localdomain systemd[1]: Starting LSB: Bring up/down networking...
-- Subject: Unit network.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit network.service has begun starting up.
Nov 11 05:35:29 localhost.localdomain systemd-sysctl[2019]: Couldn't write '0' to 'net/bridge/bridge-nf-call-iptables', ignoring: No such file or directory
Nov 11 05:35:29 localhost.localdomain systemd-sysctl[2019]: Couldn't write '0' to 'net/bridge/bridge-nf-call-arptables', ignoring: No such file or directory
Nov 11 05:35:29 localhost.localdomain systemd-sysctl[2019]: Couldn't write '0' to 'net/bridge/bridge-nf-call-ip6tables', ignoring: No such file or directory
Nov 11 05:35:29 localhost.localdomain network[1992]: Bringing up loopback interface:  Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Nov 11 05:35:29 localhost.localdomain network[1992]: Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Nov 11 05:35:29 localhost.localdomain network[1992]: Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Nov 11 05:35:29 localhost.localdomain network[1992]: Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Nov 11 05:35:29 localhost.localdomain network[1992]: [  OK  ]
Nov 11 05:35:29 localhost.localdomain NetworkManager[651]: <info>  [1478835329.8763] audit: op="connection-activate" uuid="3b3413b9-a44d-3c69-a12a-8a925a2e7bbd" name="ens33" result="fail" reas
Nov 11 05:35:29 localhost.localdomain network[1992]: Bringing up interface ens33:  Error: Connection activation failed: No suitable device found for this connection.
```

**Comment by jarrpa** [comment] 2016-11-18 21:31
Host OS: `Fedora 24`
Guest OS: `CentOS 7`
Vagrant: `1.8.7` (from rawhide)

Reproduces on CentOS 7. Initially, I get slightly different error messages from Fedora:

```
-- Unit network.service has begun starting up.
Nov 18 16:28:44 master NetworkManager[592]: <info>  parsing /etc/sysconfig/network-scripts/ifcfg-lo ...
Nov 18 16:28:44 master network[2650]: Bringing up loopback interface:  Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Nov 18 16:28:45 master NetworkManager[592]: <info>  parsing /etc/sysconfig/network-scripts/ifcfg-lo ...
Nov 18 16:28:45 master network[2650]: Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Nov 18 16:28:45 master NetworkManager[592]: <info>  parsing /etc/sysconfig/network-scripts/ifcfg-lo ...
Nov 18 16:28:45 master network[2650]: Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Nov 18 16:28:45 master NetworkManager[592]: <info>  parsing /etc/sysconfig/network-scripts/ifcfg-lo ...
Nov 18 16:28:45 master network[2650]: Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Nov 18 16:28:45 master network[2650]: [  OK  ]
Nov 18 16:28:45 master network[2650]: Bringing up interface eth0:  Error: Connection activation failed: Connection 'eth0' is already active on eth0
Nov 18 16:28:45 master network[2650]: [FAILED]
Nov 18 16:28:45 master network[2650]: RTNETLINK answers: File exists
Nov 18 16:28:45 master network[2650]: RTNETLINK answers: File exists
Nov 18 16:28:45 master network[2650]: RTNETLINK answers: File exists
Nov 18 16:28:45 master network[2650]: RTNETLINK answers: File exists
Nov 18 16:28:45 master network[2650]: RTNETLINK answers: File exists
Nov 18 16:28:45 master network[2650]: RTNETLINK answers: File exists
Nov 18 16:28:45 master network[2650]: RTNETLINK answers: File exists
Nov 18 16:28:45 master network[2650]: RTNETLINK answers: File exists
Nov 18 16:28:45 master network[2650]: RTNETLINK answers: File exists
Nov 18 16:28:45 master systemd[1]: network.service: control process exited, code=exited status=1
Nov 18 16:28:45 master systemd[1]: Failed to start LSB: Bring up/down networking.
```

But then if I disable NetworkManager and try to manually run `service network restart` (which is the failing command) I get similar results:

```
-- Unit network.service has begun starting up.
Nov 18 16:30:12 master network[2821]: Bringing up loopback interface:  [  OK  ]
Nov 18 16:30:13 master network[2821]: Bringing up interface eth0:  ERROR    : [/etc/sysconfig/network-scripts/ifup-eth] Device  does not seem to be present, delaying initialization.
Nov 18 16:30:13 master /etc/sysconfig/network-scripts/ifup-eth[2942]: Device  does not seem to be present, delaying initialization.
Nov 18 16:30:13 master network[2821]: [FAILED]
Nov 18 16:30:13 master network[2821]: RTNETLINK answers: File exists
Nov 18 16:30:13 master network[2821]: RTNETLINK answers: File exists
Nov 18 16:30:13 master network[2821]: RTNETLINK answers: File exists
Nov 18 16:30:13 master network[2821]: RTNETLINK answers: File exists
Nov 18 16:30:13 master network[2821]: RTNETLINK answers: File exists
Nov 18 16:30:13 master network[2821]: RTNETLINK answers: File exists
Nov 18 16:30:13 master network[2821]: RTNETLINK answers: File exists
Nov 18 16:30:13 master network[2821]: RTNETLINK answers: File exists
Nov 18 16:30:13 master network[2821]: RTNETLINK answers: File exists
Nov 18 16:30:13 master systemd[1]: network.service: control process exited, code=exited status=1
Nov 18 16:30:13 master systemd[1]: Failed to start LSB: Bring up/down networking.
```

**Comment by tzvetkoff** [comment] 2016-11-29 13:47
Well, I did a little digging on the subject.
RHEL-7 / Recent Fedora use NetworkManager to configure networks, thus `service network restart` might fail. `service NetworkManager restart` works out of the box.

Here's a log from a clean F25 installation:
```
[vagrant@localhost(~)]$ sudo service network restart
Restarting network (via systemctl):  Job for network.service failed because the control process exited with error code.
See "systemctl status network.service" and "journalctl -xe" for details.
                                                           [FAILED]
[vagrant@localhost(~)]$ sudo service NetworkManager restart
Redirecting to /bin/systemctl restart  NetworkManager.service
```

**Comment by marcindulak** [comment] 2016-12-10 15:32
Due to "RTNETLINK answers: File exists" I have been doing this, already for a long time in my Vagrantfiles which use https://atlas.hashicorp.com/centos/boxes/7 ...

    machine.vm.provision :shell, :inline => 'ifup eth1', run: 'always'
    # restarting network fixes RTNETLINK answers: File exists
    machine.vm.provision :shell, :inline => 'systemctl restart network'

I don't think issues like this can be solved without providing uses cases with  a bunch of Vagranfiles locked to various versions of boxes in order to run regression tests on them.

**Comment by chrisroberts** [comment] 2017-03-02 17:54
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Closed by chrisroberts** 2017-03-02 17:54 UTC

**Comment by jszakmeister** [comment] 2017-04-25 23:22
@chrisroberts I see this with Vagrant 1.9.4 on macOS Sierra using the box-cutter/fedora25 vm.  So I don't think it's fully resolved.

This is what I see in the logs when trying to bring up the VM:

```text
-- Unit network.service has begun starting up.
Apr 25 23:18:19 localhost.localdomain systemd-sysctl[2009]: Couldn't write '0' to 'net/bridge/bridge-nf-call-iptables', ignoring: No
Apr 25 23:18:19 localhost.localdomain systemd-sysctl[2009]: Couldn't write '0' to 'net/bridge/bridge-nf-call-arptables', ignoring: N
Apr 25 23:18:19 localhost.localdomain systemd-sysctl[2009]: Couldn't write '0' to 'net/bridge/bridge-nf-call-ip6tables', ignoring: N
Apr 25 23:18:19 localhost.localdomain network[1982]: Bringing up loopback interface:  [  OK  ]
Apr 25 23:18:19 localhost.localdomain NetworkManager[632]: <info>  [1493162299.8043] audit: op="connection-activate" uuid="b28bc47a-
Apr 25 23:18:19 localhost.localdomain network[1982]: Bringing up interface ens33:  Error: Connection activation failed: No suitable
Apr 25 23:18:19 localhost.localdomain network[1982]: [FAILED]
Apr 25 23:18:19 localhost.localdomain network[1982]: RTNETLINK answers: File exists
Apr 25 23:18:19 localhost.localdomain network[1982]: RTNETLINK answers: File exists
Apr 25 23:18:19 localhost.localdomain network[1982]: RTNETLINK answers: File exists
Apr 25 23:18:19 localhost.localdomain network[1982]: RTNETLINK answers: File exists
Apr 25 23:18:19 localhost.localdomain network[1982]: RTNETLINK answers: File exists
Apr 25 23:18:19 localhost.localdomain network[1982]: RTNETLINK answers: File exists
Apr 25 23:18:19 localhost.localdomain network[1982]: RTNETLINK answers: File exists
Apr 25 23:18:19 localhost.localdomain network[1982]: RTNETLINK answers: File exists
Apr 25 23:18:19 localhost.localdomain network[1982]: RTNETLINK answers: File exists
Apr 25 23:18:19 localhost.localdomain systemd-sysctl[2158]: Couldn't write '0' to 'net/bridge/bridge-nf-call-arptables', ignoring: N
Apr 25 23:18:19 localhost.localdomain systemd-sysctl[2158]: Couldn't write '0' to 'net/bridge/bridge-nf-call-iptables', ignoring: No
Apr 25 23:18:19 localhost.localdomain systemd-sysctl[2158]: Couldn't write '0' to 'net/bridge/bridge-nf-call-ip6tables', ignoring: N
Apr 25 23:18:19 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=network comm="sys
Apr 25 23:18:19 localhost.localdomain systemd[1]: network.service: Control process exited, code=exited status=1
Apr 25 23:18:19 localhost.localdomain systemd[1]: Failed to start LSB: Bring up/down networking.
-- Subject: Unit network.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit network.service has failed.
--
-- The result is failed.
```

**Comment by jszakmeister** [comment] 2017-04-25 23:33
Nevermind... this was fixed by applying the solution in the vagrant warning:

```text
WARNING: The VMX file for this box contains a setting that is automatically overwritten by Vagrant
WARNING: when started. Vagrant will stop overwriting this setting in an upcoming release which may
WARNING: prevent proper networking setup. Below is the detected VMX setting:
WARNING:
WARNING:   ethernet0.pcislotnumber = "33"
WARNING:
WARNING: If networking fails to properly configure, it may require this VMX setting. It can be manually
WARNING: applied via the Vagrantfile:
WARNING:
WARNING:   Vagrant.configure(2) do |config|
WARNING:     config.vm.provider :vmare_fusion do |vmware|
WARNING:       vmware.vmx["ethernet0.pcislotnumber"] = "33"
WARNING:     end
WARNING:   end
WARNING:
WARNING: For more information: https://www.vagrantup.com/docs/vmware/boxes.html#vmx-whitelisting
```
