### ISSUE TITLE
chef-solo log not being fully returned to vagrant

### ISSUE THREAD

**Issue by matt-richardson** [mitchellh/vagrant#4702] opened 2014-10-24 11:21 UTC
We are using vagrant 1.6.5, with both windows (2008/2012) and linux (RHEL 6) clients.

On windows, we often face an issue where the full log of the chef-solo run is not returned to the vagrant process (and therefore to the console). (On RHEL, it works fine.)

this is the output on the host: https://gist.github.com/matt-richardson/2b924408a0c8c8bea3fc
this is the output on the guest (in /tmp/vagrant-chef-4/chef-solo.log): https://gist.github.com/matt-richardson/707d9256927b9e4fd041

This example is on a windows 2008 r2 virtualbox guest, with a windows 8.1 host. This happens both with and without setting ```config.vm.communicator = "winrm"```.

Let me know what other information I can provide to help debug this.

**Comment by sethvargo** [comment] 2015-07-09 22:24
Hi @matt-richardson 

I just tired and I was unable to reproduce this issue locally. Vagrant 1.7.3 will come out later this week, but I would recommend upgrading to Vagrant 1.7.2 for now and seeing if the issue persists. Given that Vagrant has a fairly large Windows community and no one else has reported this issue, I am inclined to believe it may be an issue with your local Vagrant installation or perhaps the Windows guest itself.

I am going to close this, but if you are able to reproduce this on a recent version of Vagrant, can you please open a new issue and include the complete Vagrantfile as well as gist the output in debug mode? Thanks!

**Closed by sethvargo** 2015-07-09 22:24 UTC
Labels: bug, provisioner/chef, windows

**Comment by matt-richardson** [comment] 2015-07-10 10:09
Hi @sethvargo

I've actually moved on from the job where I was seeing this happen, but I'm pretty sure that it hasn't happened in a while. I think one of the upgrades post 1.6.5 fixed it. @tyrken can chime in if this is not the case. 

Happy to close the issue. Thanks for investigating.
