### ISSUE TITLE
`vagrant connect` issue with deleting the intermediary `connect-vm`

### ISSUE THREAD

**Issue by BrendanThompson** [mitchellh/vagrant#5945] opened 2015-07-13 04:13 UTC
When i try to do a connect to a remote Vagrant share, I am getting the following error, which is then not allowing me to connect to the remote session:

https://gist.github.com/BrendanThompson/fb2f3a32f6e656e68a75

**Comment by sethvargo** [comment] 2015-07-13 14:51
Hi @BrendanThompson 

Thank you for reaching out, and I am sorry you are having issues with the Vagrant VMware Fusion + Share functionality. Could you please share your complete Vagrantfile?

**Comment by nfloersch** [comment] 2015-07-13 15:29
Since we are merging #5944 and #5945 should I also produce a debug dump and post it as a gist? Or is that just redundant? I assume the cause is the same for both...

**Comment by sethvargo** [comment] 2015-07-13 15:33
@nfloersch all the debugging information you can provide helps! :smile:

**Comment by BrendanThompson** [comment] 2015-07-14 22:34
@sethvargo here is the `Vagrant` file, it's pretty stock:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "s12r2std"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
end
```

Mostly just comments :)

**Comment by nfloersch** [comment] 2015-07-15 04:12
Debug output from my crash... in this case the vagrant file of the machine I want to connect to is stock, although I've had the same issue with other slightly more customized vagrant files... either way same error.

https://gist.github.com/nfloersch/48c961abbd878d75b562

**Comment by nfloersch** [comment] 2015-07-17 14:08
@sethvargo or @mitchellh I would be willing to provide remote access to my Mac Pro with TeamViewer to either of you to help in exploring this issue.

**Comment by BrendanThompson** [comment] 2015-07-21 05:08
still having absolutely no luck with this. Updated my vagrant to `1.7.4` on both sides, and still nod ice.

**Comment by nfloersch** [comment] 2015-07-29 17:32
Can confirm what @BrendanThompson says - upgrading from 1.7.2 -> 1.7.3 did not fix this, and upgrading from 1.7.3 -> 1.7.4 did not fix this either. I just tried.

What does it mean that, in the error, it says "basename" is an undefined method. Is this only likely an issue with VMWare Fusion? If so, since we paid HashiCorp for the VMWare software, is it supported more via that route than using GitHub? Should we be complaining more directly?

**Comment by nfloersch** [comment] 2015-07-29 22:21
Following that thought - I installed VirtualBox and used the "VAGRANT_DEFAULT_PROVIDER" environment variable to make sure that it was my default. I then typed "vagrant connect <name>" and lo-and-behold it (sorta) worked! So it does seem to be specific to VMWare Fusion as a provider.

Although "vagrant connect" said it was successful it did not really seem to be working fully, but I think that is a different issue... so I can't say with 100%  confidence that simply using VirtualBox will fix this since I can't successfully test a connection to the remote machine... but based on the console output, everything appears to be working properly as far as Vagrant is concerned. Certainly better than the crash I get with VMWare Fusion as the provider.

**Comment by chrisroberts** [comment] 2016-12-09 00:13
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Closed by chrisroberts** 2016-12-09 00:13 UTC
Labels: bug, provider/vmware, share
