### ISSUE TITLE
vagrant trashes /tmp with a lot of files

### ISSUE THREAD

**Issue by pitchforks** [mitchellh/vagrant#6116] opened 2015-08-09 06:54 UTC
I am noticing that after I end working with vagrant - the `/tmp` directory is in a scary state - it has lots of `vagrant*` files which I have to manually clean up. It is not a matter of disk space, I'm just directly using `/tmp` for temporary tasks very often and after vagrant it becomes harder to find my files and directories there, because the size of the output that `ls` command produces grows up considerably.

Perhaps vagrant could use a subdirectory of `/tmp` for creating the temporary files it needs, to avoid cluttering `/tmp`?

**Comment by remram44** [comment] 2015-09-11 14:30
Duplicate of #6231?

**Comment by mitchellh** [comment] 2015-11-19 01:25
Agreed with @remram44, dup.

**Closed by mitchellh** 2015-11-19 01:25 UTC
Labels: bug, core
