### ISSUE TITLE
No usable default provider could be found for your vagrant-1.9.1, virtualbox-5.1.8, Centos7 host

### ISSUE THREAD

**Issue by banchy** [mitchellh/vagrant#8182] opened 2017-01-10 09:28 UTC
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
1.9.1

### Host operating system
Windows 7 Enterprise SP1

### Guest operating system
Centos 7

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
Command vagrant up doesn't work

### Actual behavior
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
vagrant up --provider=PROVIDER, which should give you a more specific
error message for that particular provider.

### Steps to reproduce
1. Install vagrant 1.9.1 and virtualbox 5.1.8 per official documentation
2. Run vagrant init
3. Run vagrant up --provider=virltualbox

### References
For older version: https://github.com/mitchellh/vagrant/issues/7767

**Comment by kikitux** [comment] 2017-01-12 00:50
Hello

After the installation of Vagrant, a reboot is required.

Could you please do this:

- reboot
- run vagrant as:

vagrant up --debug

and share a gist to the log file

**Comment by banchy** [comment] 2017-01-12 08:48
Hello, Thank you for jumping in.
Here is scenario: 
- my physical desktop running Windows 8 
- on Windows 8, I have installed ONLY Virtual Box 5.1
- then on VirtualBox I installed CentOS
- and on CentOS I have installed Vagrant and Ansible ( I didn't install any VirtualBox plugin)
My plan is to use mentioned CentOS as management machine to push new VMs with Vagrant and Ansible. With this scenario I am getting into issue as I described in firt post.
Also, last night I installed VirutalBox on CentOS and all is working fine but VMs was installed inside CentOS management machine and not like separate boxes.
I am sorry in advance if my description are confused as I am new user of those 2 tools.

**Comment by kikitux** [comment] 2017-01-12 09:54
Virtualbox doesnt allow nested VMs that are 64 bits.

If you create a 32bit VM, you can run virtualbox there and run 32bit vms nested.

its a Virtualbox limitation, so closing since its not a vagrant bug.

You a very welcome to use the mailing list to follow up this, but closing since not a bug.

**Closed by kikitux** 2017-01-12 09:54 UTC
Labels: host/windows, waiting-reply

**Comment by banchy** [comment] 2017-01-13 08:15
Thanks a lot !
