### ISSUE TITLE
/etc/exports occassionally initialized with public IP instead of private

### ISSUE THREAD

**Issue by vlovich** [mitchellh/vagrant#5137] opened 2015-01-08 03:48 UTC
I've seen /etc/exports occasionally be configured with the NAT ip address instead of the hostonly one, resulting in "mount.nfs: access denied by server while mounting ..." because /etc/exports is set up for the VM's NAT but the VM is mounting via the hostonly interface.

    config.vm.network :private_network, type: "dhcp"
    config.vm.synced_folder "../../", "/codebase/", type: "nfs", mount_options: ['rw', 'nolock', 'vers=3', 'udp', 'noexec', 'nosuid', 'rsize=32768', 'wsize=32768']

Sometimes when I run, I get the hostonly address configured in /etc/exports (i.e. 172.28.128.X).  Ocassionally, the IP address written out into /etc/exports is the public address which then makes the mount unavailable to virtualbox which is always mounting via the hostonly address.

**Comment by johnraz** [comment] 2015-01-13 13:40
I second the fact that its not clear what address should be used depending on the settings that are used... 

Could someone describe the expected behavior for these scenarios:

- Private OFF / Public OFF --> I guess and hope it would always be the nat interface ;-)
- Private ON / Public OFF --> ? 
- Private OFF / Pubic ON --> ? 
- Private ON / Public ON --> ?

Thanks !

**Comment by delitescere** [comment] 2015-01-16 05:30
I've been able to reproduce this fairly consistently. The issue is that Vagrant should wait until the "hostonly" (`config.vm.network "private_network", type: "dhcp"` in Vagrantfile) is up and has an address. It seems to be waiting but some non-determinism has it picking the first interface's address, in my case it's `docker0` (which is also a 172 address).

Follows is a shell session that reproduces the issue. I start with an empty `/etc/exports` file. Vagrant has sudoers access to update that file without asking for a password (that really should be in the brew, FWIW).

On the first `vagrant up`, the IP address for `docker0` is picked. It should have been `eth2`. On a `vagrant reload`, the correct IP is picked and put into `/etc/exports`:

```bash
16:20:48$ sudo nfsd checkexports
16:20:56$ cat /etc/exports
16:20:59$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: bridged
    default: Adapter 3: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'fsc,rsize=32768,wsize=32768,intr,noatime' 172.28.128.1:'/Users/josh/Code' /srv/code

Stdout from the command:



Stderr from the command:

stdin: is not a tty
mount.nfs: access denied by server while mounting 172.28.128.1:/Users/josh/Code

16:21:59$ cat /etc/expo
exports     exportsbak  
16:21:59$ cat /etc/exports
# VAGRANT-BEGIN: 501 cdd989d0-d6c8-4dad-a292-f5571065b947
"/Users/josh/.m2" 172.17.42.1 -alldirs -mapall=501:20
"/Users/josh/Code" 172.17.42.1 -alldirs -mapall=501:20
# VAGRANT-END: 501 cdd989d0-d6c8-4dad-a292-f5571065b947
16:22:15$ vagrant ssh
Welcome to Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-43-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Fri Jan 16 05:19:04 2015 from 10.0.2.2
vagrant@delitescere-ubuntu:~$ ifconfig
docker0   Link encap:Ethernet  HWaddr 56:84:7a:fe:97:99  
          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 08:00:27:98:dc:aa  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe98:dcaa/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:887 errors:0 dropped:0 overruns:0 frame:0
          TX packets:586 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:110228 (110.2 KB)  TX bytes:79952 (79.9 KB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:55:ea:44  
          inet addr:192.168.1.114  Bcast:192.168.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:278 errors:0 dropped:0 overruns:0 frame:0
          TX packets:271 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:28203 (28.2 KB)  TX bytes:30510 (30.5 KB)

eth2      Link encap:Ethernet  HWaddr 08:00:27:fd:a2:a9  
          inet addr:172.28.128.3  Bcast:172.28.128.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:933 errors:0 dropped:0 overruns:0 frame:0
          TX packets:943 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:55550 (55.5 KB)  TX bytes:71854 (71.8 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:192 errors:0 dropped:0 overruns:0 frame:0
          TX packets:192 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:14816 (14.8 KB)  TX bytes:14816 (14.8 KB)

vagrant@delitescere-ubuntu:~$ logout
Connection to 127.0.0.1 closed.
16:22:32$ vagrant reload
==> default: Attempting graceful shutdown of VM...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: bridged
    default: Adapter 3: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
==> default: Mounting NFS shared folders...
==> default: Mounting shared folders...
    default: /vagrant => /Users/josh/Code/canva/sde
    default: /home/vagrant/.aws => /Users/josh/.aws
    default: /home/vagrant/.ssh/vm => /Users/josh/.ssh/vm
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: to force provisioning. Provisioners marked to run always will still run.
16:23:25$ cat /etc/exports
# VAGRANT-BEGIN: 501 cdd989d0-d6c8-4dad-a292-f5571065b947
"/Users/josh/.m2" 172.28.128.3 -alldirs -mapall=501:20
"/Users/josh/Code" 172.28.128.3 -alldirs -mapall=501:20
# VAGRANT-END: 501 cdd989d0-d6c8-4dad-a292-f5571065b947
16:23:28$ 
```

**Comment by delitescere** [comment] 2015-01-16 06:22
@johnraz At this stage, *only* the private interface can be used for NFS exports. It is a bug that any other interface is chosen.

**Comment by delitescere** [comment] 2015-01-19 07:15
@johnraz what version of Vagrant are you running? `vagrant version`

I am having a hard time reproducing now on 1.7.2 (but 1.6.4 was easy). Also, based on the code, I can't see that it can go wrong now.

**Comment by mitchellh** [comment] 2015-02-25 01:50
OP hasn't verified what version of Vagrant he is running, and also hasn't responded since the initial one. Let's just close this out unless we see it again.

**Closed by mitchellh** 2015-02-25 01:50 UTC

**Comment by vlovich** [comment] 2015-02-25 01:59
Sorry - I think we're on 1.6.3 & 1.4.3.  We'll re-open if we see this when we upgrade.

**Comment by fastest963** [comment] 2015-06-16 21:32
We're running 1.7.2 and noticing an issue with an IPSec tunnel and Vagrant. When we start up vagrant using `vagrant up` it adds the ipsec tunnel's ip to the `/etc/exports` on the host instead of the host-only network ip. The guest is running CentOS 7.1 and the host is running Mac OSX Yosemite

Guest:
```
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:6a:37:62 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 76798sec preferred_lft 76798sec
    inet 10.42.9.2/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe6a:3762/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:93:3c:cc brd ff:ff:ff:ff:ff:ff
    inet 172.28.128.3/24 brd 172.28.128.255 scope global dynamic eth1
       valid_lft 1062sec preferred_lft 1062sec
    inet6 fe80::a00:27ff:fe93:3ccc/64 scope link
       valid_lft forever preferred_lft forever
```
```
# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::a00:27ff:fe6a:3762  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:6a:37:62  txqueuelen 1000  (Ethernet)
        RX packets 177866  bytes 43886427 (41.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 410934  bytes 55637013 (53.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.28.128.3  netmask 255.255.255.0  broadcast 172.28.128.255
        inet6 fe80::a00:27ff:fe93:3ccc  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:93:3c:cc  txqueuelen 1000  (Ethernet)
        RX packets 27261  bytes 2786051 (2.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 224  bytes 42666 (41.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 643466  bytes 82989217 (79.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 643466  bytes 82989217 (79.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Vagrantfile
```
# Create a private network, which allows host-only access to the machine
# using a specific IP.
config.vm.network :private_network, type: "dhcp", auto_config: false
```

Error:
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 172.28.128.1:'/shares/vagrant' /opt/share

Stderr from the command:

mount.nfs: access denied by server while mounting 172.28.128.1:/shares/vagrant
```

The `/etc/exports` has `10.42.9.2` instead of `172.28.128.3`. For some reason it seems to be picking the ipsec tunnel's ip instead of the host-only ip. Is there a way we can force it to look at `eth1` instead of `eth0`.

**Comment by m4ce** [comment] 2017-02-19 15:09
Same issue here - Vagrant is picking up the docker0's interface ip address when setting up the /etc/exports on the host.

Using VirtualBox 5.1.12 and Vagrant 1.9.1
