### ISSUE TITLE
Vagrant creates second entry of network interface configuration on second boot

### ISSUE THREAD

**Issue by bsn** [mitchellh/vagrant#5206] opened 2015-01-17 09:23 UTC
I set up interface in vagrantfile with static ip like this:

*node.vm.network :private_network, ip: '192.168.99.98',*

On first boot everything is ok, on second I see this error:

==> cm: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifup eth1

Stdout from the command:
Stderr from the command:
stdin: is not a tty
/etc/network/interfaces:28: interface eth2 declared allow-auto twice
/sbin/ifup: couldn't read interfaces file "/etc/network/interfaces"

and when I do *vagrant ssh* and remove both entries from configuration - it loads ok 1 time, and on next reload after that issue continues.

Please advice how to fix.

**Comment by dburba** [comment] 2015-01-18 09:05
The same problem to me.

**Comment by njam** [comment] 2015-01-18 13:46
Have the same.
Duplicate of #5180?

**Comment by sethvargo** [comment] 2015-01-18 21:59
Please track #5180 instead

**Closed by sethvargo** 2015-01-18 21:59 UTC
