### ISSUE TITLE
setting hostname fails for Ubuntu 15.10 VM

### ISSUE THREAD

**Issue by hxw** [mitchellh/vagrant#6616] opened 2015-11-30 09:07 UTC
Failure occurred when the line: `config.vm.hostname = 'onevm'`  was added to the Vagrantfile.
Prior to adding this setting the VM would start up correctly. (VM does have the correct new hostname if halted and restarted)

Problem seems to be that on 15.10 the hostname start/restart command e.g.: `service hostname restart`  or the systemd version: `systemctl restart hostname` fail with error:
~~~
Failed to start hostname.service: Unit hostname.service is masked.
~~~

The command: `sudo hostname onevm` seemed to work correctly, although I think the correct command  fo systemd-type systems should be:
~~~
sudo hostnamectl --static set-hostname onevm
~~~

Here is the snippet debugging output for the setting of the hostname:
~~~
==> onevm: Setting hostname...
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Re-using SSH connection.
 INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: Exit status: 0
DEBUG guest: Searching for cap: change_host_name
DEBUG guest: Checking in: ubuntu
DEBUG guest: Found cap: change_host_name in ubuntu
 INFO guest: Execute capability: change_host_name [#<Vagrant::Machine: onevm (VagrantPlugins::ProviderVirtualBox::Provider)>, "onevm"] (ubuntu)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: hostname -f (sudo=true)
DEBUG ssh: stderr: mesg: ttyname failed: Inappropriate ioctl for device

DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: echo; printf $SSH_AUTH_SOCK (sudo=false)
DEBUG ssh: stdout: 
/tmp/ssh-DDFbm1qv12/agent.729
DEBUG ssh: Exit status: 0
 INFO ssh: Setting SSH_AUTH_SOCK remotely: /tmp/ssh-DDFbm1qv12/agent.729
DEBUG ssh: stdout: vagrant.vm

DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: [ `lsb_release -c -s` = vivid ] (sudo=false)
DEBUG ssh: Exit status: 1
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: echo 'onevm' > /etc/hostname (sudo=true)
DEBUG ssh: stderr: mesg: ttyname failed: Inappropriate ioctl for device

DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: echo; printf $SSH_AUTH_SOCK (sudo=false)
DEBUG ssh: stdout: 
/tmp/ssh-DDFbm1qv12/agent.729
DEBUG ssh: Exit status: 0
 INFO ssh: Setting SSH_AUTH_SOCK remotely: /tmp/ssh-DDFbm1qv12/agent.729
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: grep 'vagrant.vm' /etc/hosts (sudo=false)
DEBUG ssh: stdout: 127.0.1.1	vagrant.vm	vagrant

DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: sed -ri 's@^(([0-9]{1,3}\.){3}[0-9]{1,3})\s+vagrant\.vm(\s.*)?$@\1 onevm onevm@g' /etc/hosts (sudo=true)
DEBUG ssh: stderr: mesg: ttyname failed: Inappropriate ioctl for device

DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: echo; printf $SSH_AUTH_SOCK (sudo=false)
DEBUG ssh: stdout: 
/tmp/ssh-DDFbm1qv12/agent.729
DEBUG ssh: Exit status: 0
 INFO ssh: Setting SSH_AUTH_SOCK remotely: /tmp/ssh-DDFbm1qv12/agent.729
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: [ `lsb_release -c -s` = hardy ] (sudo=false)
DEBUG ssh: Exit status: 1
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: [ `lsb_release -c -s` = vivid ] (sudo=false)
DEBUG ssh: Exit status: 1
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: service hostname start (sudo=true)
DEBUG ssh: stderr: sudo: unable to resolve host vagrant

DEBUG ssh: stderr: mesg: ttyname failed: Inappropriate ioctl for device

DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: echo; printf $SSH_AUTH_SOCK (sudo=false)
DEBUG ssh: stdout: 

DEBUG ssh: stdout: /tmp/ssh-DDFbm1qv12/agent.729
DEBUG ssh: Exit status: 0
 INFO ssh: Setting SSH_AUTH_SOCK remotely: /tmp/ssh-DDFbm1qv12/agent.729
DEBUG ssh: stderr: Failed to start hostname.service: Unit hostname.service is masked.

DEBUG ssh: Exit status: 1
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

service hostname start

Stdout from the command:

Stderr from the command:

sudo: unable to resolve host vagrant
mesg: ttyname failed: Inappropriate ioctl for device
Failed to start hostname.service: Unit hostname.service is masked.
~~~

**Comment by hxw** [comment] 2015-11-30 09:33
Running: Vagrant 1.7.4 on PC-BSD 10.2

**Comment by sethvargo** [comment] 2015-11-30 15:09
Dupe of https://github.com/mitchellh/vagrant/issues/6577 - will be fixed in Vagrant 1.8. Thanks!

**Closed by sethvargo** 2015-11-30 15:09 UTC

**Comment by abr4xas** [comment] 2016-03-21 02:52
Hi there, my issue is related to this:
```bash
==> Robbie: mesg: 
==> Robbie: ttyname failed
==> Robbie: : 
==> Robbie: Inappropriate ioctl for device
==> Robbie: Provisioning virtual machine...
==> Robbie: Please, wait...
==> Robbie: Installing few things for the server:...
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
```bash
$ vagrant -v
Vagrant 1.8.1

```

**Comment by abr4xas** [comment] 2016-04-13 01:56
Same problem with `ubuntu/wily64` :-1:

**Comment by hogepodge** [comment] 2016-04-27 14:33
Same problem with 1.8.1 booting 16.04 on the vmware fusion provider.

**Comment by LuisBL** [comment] 2016-04-27 22:35
same here
on wily64::
      
    $ grep ubun Vagrantfile
    config.vm.box = "ubuntu/wily64"
    vagrant.vm.hostname = "ubuntu"

vagrant up:

    ==> vagrant: Setting hostname...
    The following SSH command responded with a non-zero exit status.
    Vagrant assumes that this means the command failed!
   
    service hostname start
   
    Stdout from the command:

    Stderr from the command:
   
    mesg: ttyname failed: Inappropriate ioctl for device
    Failed to start hostname.service: Unit hostname.service is masked.

**Comment by emestee** [comment] 2016-05-03 16:08
Same on Debian Stretch with 1.8.1:

```
==> default: Checking if box 'fujimakishouten/debian-stretch64' is up to date...

==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: bridged
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
GuestAdditions 5.0.16 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown eth1 2> /dev/null

Stdout from the command:



Stderr from the command:

mesg: ttyname failed: Inappropriate ioctl for device
```

**Comment by ramonrails** [comment] 2016-05-23 06:49
vagrant 1.8.1 ubuntu/xenial64 fails too

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/xenial64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/xenial64' is up to date...
==> default: Setting the name of the VM: ubuntu-xenial-16.04-cloudimg
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostly
    default: Adapter 3: bridged
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customisations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: ubuntu
    default: SSH auth method: password
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown eth1 2> /dev/null

Stdout from the command:



Stderr from the command:

sudo: unable to resolve host ubuntu-denial
mesg: ttyname failed: Inappropriate ioctl for device

ruby-2.3.1 ~/sandbox-vagrant $ vagrant -v
Vagrant 1.8.1

```

**Comment by Ma27** [comment] 2016-06-22 13:18
ping @sethvargo is this a known bug or already fixed, but not released yet? (using Vagrant 1.8.4 and it still exists)

**Comment by sethvargo** [comment] 2016-06-22 15:14
The `ubuntu/xenial64` box is built wrong and horribly broken. Please note that "ubuntu" is the name of a user, not a representation of a canonical source for ubuntu images. Please try `bento/ubuntu-16.04` instead. Thanks.

**Comment by Ma27** [comment] 2016-06-22 15:39
thanks a lot @sethvargo, your suggestion seems to work now...

**Comment by Ma27** [comment] 2016-06-22 21:34
hmm @sethvargo it seems as there's a more general issue, see #7508

**Comment by sethvargo** [comment] 2016-06-22 21:47
No, I replied on there.
