### ISSUE TITLE
Vagrant 1.8.1 attempt to install VirtualBox even when Hyper-V is installed

### ISSUE THREAD

**Issue by Hondilla** [mitchellh/vagrant#6846] opened 2016-01-11 15:02 UTC
```
Provider 'virtualbox' not found. We'll automatically install it now...
```

It doesn't check if Hyper-V is installed on Windows 10.
Nor checks the provider in the Vagrantfile that is packaged in the box.

I can only start the box with

```
vagrant up --provider "hyperv"
```

Or by editing the Vagrantfile generated with

```
vagrant init
```

**Comment by LachlanArthur** [comment] 2016-01-21 11:05
Looks like a duplicate of #6708.

**Comment by jonathansd1** [comment] 2016-02-08 19:13
I can second this, except when I'm using the aws provider. Despite no mention of virtualbox in my Vagrantfile and aws being explicitly listened, I can only `vagrant up` when I explicitly set `--provider aws`. This was after an upgrade from 1.7.4 to 1.8.1.

**Comment by chrisroberts** [comment] 2016-12-09 00:57
Setting a provider in the Vagrantfile, even if not configuring it, will default Vagrant to that provider as seen: https://github.com/mitchellh/vagrant/issues/6846#issuecomment-181525653

**Closed by chrisroberts** 2016-12-09 00:57 UTC
Labels: bug, core
