### ISSUE TITLE
cannot load such file -- vagrant-parallels

### ISSUE THREAD

**Issue by iliyaZelenko** [mitchellh/vagrant#8260] opened 2017-02-04 15:59 UTC
Vagrant version is last 

OS: Windows 10

I use laravel/homestead
After i instal vagrant plugin vagrant-parallels(

> vagrant plugin install vagrant-parallels

)
When i 
> vagrant up

or other commands I get error:

> Vagrant failed to initialize at a very early stage:  The plugins failed to load properly. The error message given is shown below.  cannot load such file -- vagrant-parallels

**Comment by chrisroberts** [comment] 2017-02-06 18:19
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by chrisroberts** [comment] 2017-03-02 19:35
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2017-03-02 19:35 UTC
Labels: waiting-reply
