### ISSUE TITLE
Vagrant 1.9.4 cannot mount VirtualBox 5.1.20 shared folders: protocol error

### ISSUE THREAD

**Issue by twogee** [mitchellh/vagrant#8530] opened 2017-04-26 19:48 UTC
### Vagrant version
1.9.4

### Host operating system
macOS 10.12.4

### Guest operating system
Ubuntu Trusty (also tested with 16.04 Bento box)

### Vagrantfile
```ruby
VAGRANTFILE_API_VERSION = "2"

$script_tools = <<SCRIPT
echo Provisioning VM...
echo Installing dependencies...
apt-get update
apt-get -qy install openjdk-7-jre
echo Done.
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "trusty-server-cloudimg-amd64"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.define "tools" do |tools|
    tools.vm.hostname = "tools"
    tools.vm.provision :shell, :inline => $script_tools
    tools.vm.provider "virtualbox" do |vm|
      vm.customize [
                     'modifyvm', :id,
                     '--memory', '2048',
                     '--cpus', '2',
                 ]
    end
  end

  config.ssh.forward_x11 = true
end
```
### Expected behavior
Successful mount of cwd as /vagrant

### Actual behavior
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

Protocol error

### Steps to reproduce
vagrant up

**Comment by chrisroberts** [comment] 2017-04-26 20:18
Duplicate of: #8502

**Closed by chrisroberts** 2017-04-26 20:18 UTC
Labels: duplicate, provider/virtualbox, upstream
