### ISSUE TITLE
The host network interface with the given name could not be found

### ISSUE THREAD

**Issue by uruloke** [mitchellh/vagrant#5519] opened 2015-03-24 12:02 UTC
Hello, trying to setup laravel/homestead with Vagrant and getting this error:
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'laravel/homestead' is up to date...
==> default: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "ipconfig", "VirtualBox Host-Only Ethernet Adapter #3",
"--ip", "192.168.10.1", "--netmask", "255.255.255.0"]

Stderr: VBoxManage.exe: error: The host network interface with the given name co
uld not be found
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component Host,
interface IHost, callee IUnknown
VBoxManage.exe: error: Context: "FindHostNetworkInterfaceByName(name.raw(), hif.
asOutParam())" at line 218 of file VBoxManageHostonly.cpp
VBoxManage.exe: error: Could not find interface 'VirtualBox Host-Only Ethernet A
dapter #3'
```

This is on a Windows 10 computer, does anyone have a fix for this?

UPDATE 1:
Here is the Gist link for debug mode
https://gist.github.com/uruloke/9c1585ae9fd81abb1b42

**Comment by sethvargo** [comment] 2015-03-24 14:16
Hi @uruloke 

I am sorry you are having issues. Could you please run the command again in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html) and Gist the output? Thanks! :smile:

**Comment by uruloke** [comment] 2015-03-24 14:26
Hi @sethvargo 

Sorry I forgot to do that.
Here you have the full debug
https://gist.github.com/uruloke/9c1585ae9fd81abb1b42

**Comment by sethvargo** [comment] 2015-03-24 14:28
Cool thanks! Tagged as a bug.

**Comment by VedranLerenc** [comment] 2015-04-21 17:38
Hi,
I see the same behavior when I try to run Vagrant with VirtualBox as provider in a docker container.
Any idea what could be wrong/what I could do? Any workaround or older version that would work?
Thanks in advance, Vedran

**Comment by uruloke** [comment] 2015-04-21 17:59
@VedranLerenc  
It worked for me to use VMWare in almost a month, but it does not work anymore for me though (think it was a setting I changed that fucked it up). 
You could try with VMware, they have a moneyback policy on the vagrant plugin for VMware

**Comment by sumanta-ghosh** [comment] 2015-07-05 21:18
I also face the same problem
![vagrant](https://cloud.githubusercontent.com/assets/2699051/8513455/6e3c5e68-2389-11e5-93ec-79def127b07a.png)

**Comment by forivall** [comment] 2015-07-16 01:06
Could be a duplicate of #4970. I had the issue for a bit, and figured out a solution.

**Comment by Serphiroth** [comment] 2015-08-06 13:22
Maybe this will help :
http://stackoverflow.com/questions/31765581/the-host-network-interface-with-the-given-name-could-not-be-found/31856846#31856846

**Comment by italy-portugal** [comment] 2015-08-18 13:03
I was receiving a similar error and followed advice from [a ticket on the virtualbox website](https://www.virtualbox.org/ticket/14040#comment:54): 

- Find VboxManage.exe in C:\Program Files\Oracle\VirtualBox
- Right-Click and select Properties
- Select the Compatibility tab and run this program in compatibility mode for windows 8
- run vagrant up.

Hopefully this will work until Virtualbox can release a version that supports Windows 10.

**Comment by Gamezpedia** [comment] 2015-11-08 23:45
Getting this in window 10

homestead up

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "ipconfig", "VirtualBox Host-Only Ethernet Adapter", "--ip", "192.168.10.1", "--netmask", "255.255.255.0"]

Stderr: VBoxManage.exe: error: The host network interface with the given name could not be found
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component HostWrap, interface IHost, callee IUnknown
VBoxManage.exe: error: Context: "FindHostNetworkInterfaceByName(Bstr(pszName).raw(), hif.asOutParam())" at line 205 of file VBoxManageHostonly.cpp

**Comment by mitchellh** [comment] 2015-11-23 17:54
This is a known bug in VirtualBox. Upgrading seems to have fixed it for many people.

**Closed by mitchellh** 2015-11-23 17:54 UTC
Labels: bug, host/windows
