### ISSUE TITLE
Command: ["hostonlyif", "create"] error with windows 7 Professional 64bit

### ISSUE THREAD

**Issue by candyshien** [mitchellh/vagrant#6168] opened 2015-08-20 02:20 UTC
Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 70 of file VBoxManageHostonly.cpp

**Comment by sethvargo** [comment] 2015-08-20 02:49
Hi @candyshien 

Thank you for opening an issue. This is an error coming from VirtualBox, not Vagrant. Can you please try re-installing VirtualBox?

**Comment by candyshien** [comment] 2015-08-20 03:24
I try to re-install VirtualBox 5.0.2 for Windows, but it still show the error. Any other way to solve the problem?

**Comment by candyshien** [comment] 2015-08-20 03:25
I try to re-install VirtualBox 5.0.2 for Windows, but it still show the error. Any other way to solve the problem?

**Comment by sethvargo** [comment] 2015-08-20 03:26
Hi @candyshien 

Upon further inspection, it looks like this might be a duplicate of https://github.com/mitchellh/vagrant/issues/6059. Can you please track that issue? Thanks!

**Closed by sethvargo** 2015-08-20 03:26 UTC
Labels: waiting-reply

**Comment by maxiaoxiong** [comment] 2016-08-21 06:40
@sethvargo i try re-installing VirtualBox! it`s OK!! Thanks you
