### ISSUE TITLE
fork/exec error

### ISSUE THREAD

**Issue by HarrisonOg** [mitchellh/vagrant#8055] opened 2016-11-29 21:49 UTC
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.
1.9.0

### Host operating system
This is the operating system that you run locally.
MacOS 10.12.1

### Guest operating system
This is the operating system you run in the virtual machine.
ubuntu 16.04 bentobox

Could not even get to the plugin list

### Expected behavior
What should have happened?

### Actual behavior
What actually happened?

`Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: argument list too long
Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: argument list too long
Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: argument list too long`

### Steps to reproduce
1.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by chrisroberts** [comment] 2016-11-29 22:13
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by jenhsun** [comment] 2016-11-29 22:39
@HarrisonOg 1.9.0 runs smoothly on my Mac. My guess is you might have ruby setting problem on your machine.

**Comment by bassrock** [comment] 2016-12-01 05:14
I had the same issue. I had the following in my Vagrantfile at the top to auto install plugins if they weren't on the machines:

```ruby
required_plugins = %w(vagrant-omnibus vagrant-aws vagrant-berkshelf vagrant-vbguest vagrant-triggers vagrant-remove-old-box-versions vagrant-hostmanager)
required_plugins.each do |plugin|
  exec "vagrant plugin install #{plugin};vagrant #{ARGV.join(" ")}" unless Vagrant.has_plugin? plugin || ARGV[0] == 'plugin'
end
```

After commenting it out I then encountered an error relating to the next item in my file:

```ruby
class MyInstaller < VagrantVbguest::Installers::Linux
  def install(opts=nil, &block)
    communicate.sudo('rm -rf /etc/resolv.conf', opts, &block)
    communicate.sudo('echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf', opts, &block)
    communicate.sudo('apt-get update', opts, &block)
    communicate.sudo('apt-get install dkms build-essential linux-headers-generic linux-headers-$(uname -r) -y', opts, &block)
    # calling `super` will run the installation
    # also it takes care of uploading the right iso file into the box
    # and cleaning up afterward
    super
  end
end
```

With that block I had to add: 
``` ruby
require 'vagrant-vbguest' unless defined? VagrantVbguest::Config
```

So it looks like there may be 2 things that are happening:

1. Vagrant 1.9.0 changed how its autoloading works and does not load the plugins before the vagrant file now causing the require line to be needed.

2. I think there is an issue with https://github.com/mitchellh/vagrant/issues/8063 because when I removed the lines to check if it has plugins it works.

**Comment by bassrock** [comment] 2016-12-01 05:16
And actually looking at it I think that it all has to do with #8063 where the pull request stops it from loading the local vagrant file as I was just doing basic commands like vagrant status in my directory.

**Comment by chrisroberts** [comment] 2016-12-01 14:07
@bassrock Hi! When you say:

> I had the same issue.

Are you referring to the original fork/exec error described in this issue (`argument list too long`) ?

**Comment by BillyGriffiths** [comment] 2016-12-01 14:25
I also get the error, both on running 'vagrant status' and 'vagrant up'.

Brand new MBP (literally just out of the box) running new installation of Sierra. I initially installed Vagrant 1.9.0 from the '.dmg' which resulted in the error messages. I then uninstalled and reinstalled using 'brew cask install vagrant'. Same result. 

Will check my vagrantfile etc, but thought I'd just mention it also. 

![image](https://cloud.githubusercontent.com/assets/6160978/20797263/b068fa28-b7e2-11e6-9329-3eb2fdc35951.png)

**Comment by chrisroberts** [comment] 2016-12-01 14:28
@BillyGriffiths are you in a directory with a Vagrantfile when running these commands? If so, can you paste in that file? Thanks!

**Comment by chrisroberts** [comment] 2016-12-01 14:33
@BillyGriffiths Also, if you could post the output with the launcher debug on that would be great:

```
$ VAGRANT_DEBUG_LAUNCHER=1 vagrant status
```

Thanks!

**Comment by BillyGriffiths** [comment] 2016-12-01 14:34
> are you in a directory with a Vagrantfile when running these commands? If so, can you paste in that file? Thanks!

I am indeed. 

[Vagrantfile.txt](https://github.com/mitchellh/vagrant/files/624855/Vagrantfile.txt)

**Comment by BillyGriffiths** [comment] 2016-12-01 14:43
> Also, if you could post the output with the launcher debug on that would be great:

Output seems to loop. I did a force quit and copied the output available in my terminal. Does it help?

[vagrant_debug_1.txt](https://github.com/mitchellh/vagrant/files/624877/vagrant_debug_1.txt)

**Comment by jenhsun** [comment] 2016-12-01 15:10
I remember when I first done the 1.9.0 installation and do `vagrant up`, it automatically shows `vagrant repair` to repair my plugins. It "might" be the answer to this question. So, do a `vagrant repair` manually and see what will happen, or `vagrant plugin expunge` and reinstall all plugins manually.
I can't reproduce fork/exec issue, sorry.

**Comment by BillyGriffiths** [comment] 2016-12-01 15:16
> I remember when I first done the 1.9.0 installation and do vagrant up, it automatically shows vagrant repair to repair my plugins. It "might" be the answer to this question. So, do a vagrant repair manually and see what will happen, or vagrant plugin expunge and reinstall all plugins manually.
I can't reproduce fork/exec issue, sorry.

Both 'vagrant repair' and 'vagrant plugin expunge' results in the same output for me.

**Comment by BillyGriffiths** [comment] 2016-12-01 15:18
When I comment put the plugin installation lines, everything seems to run fine. 

#Install Required Plugins#
#required_plugins = %w(vagrant-hostsupdater vagrant-triggers)
#_retry = false
#required_plugins.each do |plugin|
#  unless Vagrant.has_plugin? plugin
#    system "vagrant plugin install #{plugin}"
#    _retry = true
#  end
#  if (_retry)
#    exec "vagrant " + ARGV.join(' ')
#  end
#end

**Comment by chrisroberts** [comment] 2016-12-01 15:21
@BillyGriffiths Right, that's just what I was typing out. Your Vagrantfile attempting to do plugin installation is what is causing the problem. If you go to a directory without a Vagrantfile (like your home directory) and install the plugins required, you should be all set.

**Comment by BillyGriffiths** [comment] 2016-12-01 15:23
Thanks @chrisroberts! 👍  Immediate problem solved.  

How would I, in future, get those to install as part of my vagrantfile?

**Comment by tmountjr** [comment] 2016-12-01 15:25
Just did @chrisroberts suggestion, worked for me. I was doing the same thing:

```
required_plugins = %w(vagrant-digitalocean)
plugins_to_install = required_plugins.select { |plugin| !Vagrant.has_plugin? plugin }
unless plugins_to_install.empty?
    puts "Installing plugins: #{plugins_to_install.join(' ')}"
    if system "vagrant plugin install #{plugins_to_install.join(' ')}"
        exec "vagrant #{ARGV.join(' ')}"
    else
        abort 'Installation of one or more plugins has failed. Aborting.'
    end
end
```

**Comment by chrisroberts** [comment] 2016-12-01 15:25
I'm going to be working on a supported way to request plugin installation from the Vagrantfile.

**Comment by BillyGriffiths** [comment] 2016-12-01 15:26
> I'm going to be working on a supported way to request plugin installation from the Vagrantfile.

That would be great.

**Comment by benesch** [comment] 2016-12-01 16:41
@BillyGriffiths here's a workaround for the time being from WhoopInc/vagrant-s3auth#32:

```
unless Vagrant.has_plugin?('vagrant-s3auth') || ARGV.include?("plugin")
  system('vagrant plugin install vagrant-s3auth') || exit!

  # Relaunch Vagrant so the plugin is detected. Exit with the same status code.
  exit system('vagrant', *ARGV)
end
```

Basically just wrap the entire plugin installation block in an ```unless ARGV.include?("plugin")``` block.

**Comment by bassrock** [comment] 2016-12-01 18:55
@chrisroberts  Yes I am referring to the ```argument to long``` error.

**Comment by cYbercOsmOnauT** [comment] 2016-12-04 12:22
Thanks for your [workaround](https://github.com/mitchellh/vagrant/issues/8055#issuecomment-264224331) benesch! Works like a charm!

**Comment by Deepakkothandan** [comment] 2016-12-05 10:24
Had the same issue and running `vagrant plugin repair` fixed it

**Comment by chrisroberts** [comment] 2016-12-09 17:03
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Closed by chrisroberts** 2016-12-09 17:03 UTC

**Comment by nuxy** [comment] 2018-07-06 23:47
Hello all:

I know I'm beating a dead horse over this topic.  In the latest version of OSX (10.13.5) none of the solutions above worked.  I ended up resolving this using the following code.

### The solution:
```
required_plugins = %w[vagrant-plugin-1 vagrant-plugin-2 vagrant-plugin-3]

return if !Vagrant.plugins_enabled?

plugins_to_install = required_plugins.select { |plugin| !Vagrant.has_plugin? plugin }

if plugins_to_install.any?
  system "vagrant plugin install #{plugins_to_install.join(' ')}"
  exit system 'vagrant up'
end
```

### What does this solve?

- Allows execution of `vagrant plugin install` and `vagrant plugin uninstall` in the same directory as the `Vagrantfile` itself.
- Forces `vagrant up` in cases where you `require` a dependency that has been recently installed in either the `Vagrantfile` or related library include.
- Supports multiple _gems_ or Vagrant plugins.

Hope this helps.

**Comment by silvae86** [comment] 2018-07-10 14:30
@nuxy thanks, this fixed an issue i was having while running vagrant in the latest Mojave public beta!

**Comment by apple4ever** [comment] 2018-08-03 17:14
@nuxy 

I get the following error with Vagrant 2.1.2 when I try that:

```Vagrantfile:20:in `block in <top (required)>': unexpected return (LocalJumpError)
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/config/loader.rb:126:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/config/loader.rb:119:in `each'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/config/loader.rb:119:in `block in load'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/config/loader.rb:116:in `each'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/config/loader.rb:116:in `load'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:777:in `new'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:777:in `vagrantfile'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:523:in `host'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:191:in `block in action_runner'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:510:in `hook'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:759:in `unload'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:164:in `ensure in <main>'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:164:in `<main>'
```

**Comment by techies23** [comment] 2018-08-13 14:59
@nuxy Perfect. This fixed the issue for me as well. Thanks !
