### ISSUE TITLE
Embedded ssh doesn't work with Cygwin

### ISSUE THREAD

**Issue by jonjhallettuob** [mitchellh/vagrant#8741] opened 2017-06-30 12:10 UTC
### Vagrant version
Vagrant 1.9.6

### Host operating system
Windows 7

### Guest operating system
CentOS 7

### Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
end

### Debug output
https://gist.github.com/jonjhallettuob/4dda192ff7ccd5f36564d7dba143cb1c

### Expected behavior
vagrant ssh should have connected to the VM using the Cygwin version of ssh, c:\cygwin\bin\ssh, rather than the HashiCorp embedded version.

### Actual behavior
vagrant ssh attempts to use the embedded version of ssh, "C:\\HashiCorp\\Vagrant\\embedded\\usr\\bin/ssh.EXE", which just hangs under Cygwin.

### Steps to reproduce
1. Install Cygwin
2. Start a Cygwin terminal
3. vagrant init centos/7
4. vagrant up
5. vagrant ssh

### References
Not that a search for "cygwin ssh" finds.

**Comment by kpb** [comment] 2017-07-03 20:26
+1
I have the same issue with 1.9.6

**Comment by chrisroberts** [comment] 2017-07-05 22:30
Closing as a duplicate of #8739

Cheers!

**Closed by chrisroberts** 2017-07-05 22:30 UTC
Labels: duplicate, host/windows
