### ISSUE TITLE
ansible_local systematically throws error when using AWS provider

### ISSUE THREAD

**Issue by vikas027** [mitchellh/vagrant#6984] opened 2016-02-05 14:25 UTC
##### Environment
OS : OSX 10.11.2   or  CentOS 6.7
Vagrant : 1.8.1
Vagrant AWS Plugin: 0.7.0
Ansible (on Guest) : 2.0.0.2 (installed through pip)

##### Vagrantfile
```ruby
config.vm.provision :ansible do |ansible|
  ansible.sudo = true
  ansible.verbose = true
  ansible.playbook = "common.yml"
end
```
##### Problem
[ansible](https://www.vagrantup.com/docs/provisioning/ansible.html) does not throw any error but [ansible_local](https://www.vagrantup.com/docs/provisioning/ansible_local.html) spits out below
```bash
$ vagrant provision  (or any vagrant command)
/Users/vikas/.vagrant.d/gems/gems/vagrant-aws-0.7.0/lib/vagrant-aws/action.rb:85:in `block in action_read_ssh_info': stack level too deep (SystemStackError)
	from /Users/vikas/.vagrant.d/gems/gems/vagrant-aws-0.7.0/lib/vagrant-aws/action.rb:84:in `tap'
	from /Users/vikas/.vagrant.d/gems/gems/vagrant-aws-0.7.0/lib/vagrant-aws/action.rb:84:in `action_read_ssh_info'
	from /Users/vikas/.vagrant.d/gems/gems/vagrant-aws-0.7.0/lib/vagrant-aws/provider.rb:16:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:187:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:530:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
	from /Users/vikas/.vagrant.d/gems/gems/vagrant-aws-0.7.0/lib/vagrant-aws/provider.rb:24:in `ssh_info'
	 ... 8135 levels...
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/ssh/command.rb:41:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:302:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:174:in `<main>'
```

**Comment by gildegoma** [comment] 2016-02-05 16:37
@vikas027 thanks for your problem report. It will greatly help us if you can give us a litte bit more details about your use case (ideally with a github repository, that can be used to reproduce the bug).

I also would like to first check the following points:

* [ ] From the log excerpt above, it seems that you're using the [`vagrant-aws (0.7.0)`](https://github.com/mitchellh/vagrant-aws/tree/v0.7.0) provider, do you have the same problem with other [vagrant provider(s)](https://www.vagrantup.com/docs/providers/) (e.g. `virtualbox`, etc.) ?
* [ ] With `ansible_local` provisioner configured, can you successfully apply the following steps?

```
$ vagrant up --no-provision
...
$ vagrant ssh
```

Many thanks in advance!

**Comment by vikas027** [comment] 2016-02-06 04:40
@gildegoma  Ignore my first post. I am listing out steps to reproduce the error while using [ansible_local](https://www.vagrantup.com/docs/provisioning/ansible_local.html) while using both AWS and Virtualbox.

I had created these Virtualbox Box and AWS AMIs through packer and ansible, so I am confident that Ansible is working as it should.

##### Environment
OS : OSX 10.11.2
Vagrant : 1.8.1
Vagrant AWS Plugin: 0.7.0
Ansible (on Guest) : 2.0.0.2   (installed through pip)
Virtualbox : 5.0.10

#### Error provisioning Virtualbox VM  - [Git Repo](https://github.com/vikas027/vagrant-bug-ansible-virtualbox.git)
Even if I use ansible_local, still it tries to find ansible on the host rather than on the guest machine.
```bash
$ vagrant up --no-provision  (runs fine)
$ vagrant provision
==> webserver: Running provisioner: shell...
    webserver: Running: inline script
==> webserver: /root
==> webserver: root
==> webserver: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
==> webserver: -rwxr-xr-x. 1 root root 3940 Feb  6  2016 /usr/bin/ansible
==> webserver: -rwxr-xr-x. 1 root root 3940 Feb  6  2016 /usr/bin/ansible-doc
==> webserver: -rwxr-xr-x. 1 root root 3940 Feb  6  2016 /usr/bin/ansible-galaxy
==> webserver: -rwxr-xr-x. 1 root root 3940 Feb  6  2016 /usr/bin/ansible-playbook
==> webserver: -rwxr-xr-x. 1 root root 3940 Feb  6  2016 /usr/bin/ansible-pull
==> webserver: -rwxr-xr-x. 1 root root 3940 Feb  6  2016 /usr/bin/ansible-vault
==> webserver: Running provisioner: ansible_local...
The Ansible software could not be found! Please verify
that Ansible is correctly installed on your guest system.

If you haven't installed Ansible yet, please install Ansible
on your Vagrant basebox, or enable the automated setup with the
`install` option of this provisioner. Please check
https://docs.vagrantup.com/v2/provisioning/ansible_local.html
for more information.
```

#### Error provisioning EC2 Instance  - [Git Repo](https://github.com/vikas027/vagrant-bug-ansible-aws.git)
I have tested the same on both OSX 10.11.2 and CentOS 6.7
```bash
$ vagrant up --no-provision (I cannot run any vagrant command with ansible_local)
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:203:in `rescue in action': stack level too deep (SystemStackError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:161:in `action'
	from /Users/vikas/.vagrant.d/gems/gems/vagrant-aws-0.7.0/lib/vagrant-aws/provider.rb:24:in `ssh_info'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:425:in `ssh_info'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:319:in `connect'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:125:in `ready?'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/provisioners/ansible/config/guest.rb:41:in `check_path'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/provisioners/ansible/config/guest.rb:53:in `check_path_is_a_file'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/provisioners/ansible/config/base.rb:78:in `validate'
	 ... 8135 levels...
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/up/command.rb:88:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:302:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:174:in `<main>'
$
$ sed -i '.bkup' 's/ansible_local/ansible/' Vagrantfile
$ vagrant up --no-provision (runs fine)
$ vagrant rsync
==> default: Rsyncing folder: /vagrant-bug-ansible-aws/ => /vagrant
==> default:   - Exclude: [".vagrant/", ".git/"]
$ vagrant ssh
Last login: Sat Feb  6 04:27:00 2016 from X.X.X.X

       __|  __|_  )
       _|  (     /   Amazon Linux AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-ami/2015.09-release-notes/
```

Hope this helps to find and fix the bug easily.

**Comment by gildegoma** [comment] 2016-02-06 06:11
@vikas027 thank you for the additional details. Now things are quite clear, I think (the first log excerpts was indeed not pointing the issue).

By using Ansible 2.0+, you're affected by the ansible/ansible#12004 regression. This has been tracked by issue #6793 and fixed by #6869. Unfortunately this can only be resolved in the next Vagrant release, or in future versions of Ansible.

You have (at least) two possible workarounds:
* Adapt your Packer configuration to install an Ansible 1.9 version instead (e.g. `sudo pip install ansible==1.9.4`)
* If for some reason you really need to run Ansible 2.0+, then you can manually patch your current Vagrant 1.8.1 installation(s) (it's only one word to add, see https://github.com/mitchellh/vagrant/commit/9dbdb9397a92d4fc489e9afcb022621df7f60d11)

I hope you can find a quick fix that suits your situation, and that we can get better integration between Ansible 2.0 and Vagrant "very soon" :-)

**Comment by vikas027** [comment] 2016-02-06 10:55
@gildegoma Thank you for the super quick response. 

I am forced to use Ansible 2.0+ since my playbooks are dependent on it. It would be quite a pain to make it backwards compatible.

My Virtualbox issue has been fixed via [9dbdb93](https://github.com/mitchellh/vagrant/commit/9dbdb9397a92d4fc489e9afcb022621df7f60d11). I modified file `/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/provisioners/ansible/provisioner/guest.rb` on OSX
and `/usr/lib/python2.6/site-packages/ansible/cli/galaxy.py` on the guest OS as suggested in [11b55be](https://github.com/ansible/ansible/commit/11b55be5bbb90b2bc917b2637d6fcdbe1a15092d).

But my AWS issue still persists. I cannot run any vagrant command if I have `ansible_local` in Vagranfile, even before running `vagrant up`; error is same as above.

**Comment by gildegoma** [comment] 2016-02-06 22:43
@vikas027 thanks for the additional details. Then I'll try with AWS next week and give you some feedbacks.

**Comment by gildegoma** [comment] 2016-02-13 08:09
I can reproduce the bug, which is caused by an infinite recursion between the AWS provider and the Ansible Local provisioner:

```
INFO box_collection: Box found: dummy-aws (aws)
 INFO loader: Set :"2162083720_vm_default_dummy-aws_aws" = ["[\"2\", #<Proc:0x0000010245fb20>]"]
 INFO loader: Loading configuration in order: [:home, :root, "2162083720_machine_default", :"2162083720_vm_default_dummy-aws_aws"]
 INFO machine: Initializing machine: default
 INFO machine:   - Provider: VagrantPlugins::AWS::Provider
 INFO machine:   - Box: #<Vagrant::Box:0x00000101b9ab20>
 INFO machine:   - Data dir: /tank/gildegoma/wip/support/vagrant/aws-ansible-local/aws-devops-bootstrap/.vagrant_resi/machines/default/aws
 INFO machine: Calling action: read_state on provider AWS (new)
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-41a6f55c91617f1d01336a0ff36644be
 INFO interface: Machine: action ["read_state", "start", {:target=>:default}]
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 5 hooks defined.
 INFO runner: Running action: machine_action_read_state #<Vagrant::Action::Builder:0x00000102405df0>
 INFO warden: Calling IN action: #<VagrantPlugins::Triggers::Action::Trigger:0x00000101afb390>
 INFO warden: Calling IN action: #<VagrantPlugins::Triggers::Action::Trigger:0x00000101af6070>
 INFO warden: Calling IN action: #<VagrantPlugins::Triggers::Action::Trigger:0x00000102385fb0>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x000001052e73f8>
 INFO machine: Calling action: read_ssh_info on provider AWS (new)
 INFO interface: Machine: action ["read_ssh_info", "start", {:target=>:default}]
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 5 hooks defined.
 INFO runner: Running action: machine_action_read_ssh_info #<Vagrant::Action::Builder:0x00000100c4f6e8>
 INFO warden: Calling IN action: #<VagrantPlugins::Triggers::Action::Trigger:0x00000100c36fa8>
 INFO warden: Calling IN action: #<VagrantPlugins::Triggers::Action::Trigger:0x0000010225fbb8>
 INFO warden: Calling IN action: #<VagrantPlugins::Triggers::Action::Trigger:0x0000010380c240>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000102236f10>
 INFO machine: Calling action: read_ssh_info on provider AWS (new)
 INFO interface: Machine: action ["read_ssh_info", "start", {:target=>:default}]
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 5 hooks defined.
 INFO runner: Running action: machine_action_read_ssh_info #<Vagrant::Action::Builder:0x000001021dc4c0>
 INFO warden: Calling IN action: #<VagrantPlugins::Triggers::Action::Trigger:0x000001021ce820>
 INFO warden: Calling IN action: #<VagrantPlugins::Triggers::Action::Trigger:0x00000102197eb0>
 INFO warden: Calling IN action: #<VagrantPlugins::Triggers::Action::Trigger:0x00000102167878>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000100bcc798>
 INFO machine: Calling action: read_ssh_info on provider AWS (new)
 INFO interface: Machine: action ["read_ssh_info", "start", {:target=>:default}]
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 5 hooks defined.

... (265 times) ...

ERROR warden: Error occurred: stack level too deep
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-41a6f55c91617f1d01336a0ff36644be
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 6 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00000101a3b1a8>
 INFO warden: Calling IN action: HashiCorp Background Check: End
 INFO logger: Cleaning up background activation thread...
 INFO warden: Calling IN action: #<VagrantPlugins::Triggers::Action::Trigger:0x000001022b7778>
 INFO warden: Calling IN action: #<VagrantPlugins::Triggers::Action::Trigger:0x00000100d3efb8>
 INFO warden: Calling IN action: #<VagrantPlugins::Triggers::Action::Trigger:0x00000100ce7308>
 INFO warden: Calling OUT action: #<VagrantPlugins::Triggers::Action::Trigger:0x00000100ce7308>
 INFO warden: Calling OUT action: #<VagrantPlugins::Triggers::Action::Trigger:0x00000100d3efb8>
 INFO warden: Calling OUT action: #<VagrantPlugins::Triggers::Action::Trigger:0x000001022b7778>
 INFO warden: Calling OUT action: HashiCorp Background Check: End
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:126:in `==': stack level too deep (SystemStackError)
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:126:in `block in index'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:124:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:124:in `each_with_index'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:124:in `index'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/hook.rb:89:in `block in apply'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/hook.rb:88:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/hook.rb:88:in `apply'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:158:in `block in to_app'
         ... 8243 levels...
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/up/command.rb:88:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/cli.rb:42:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:302:in `cli'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:174:in `<main>'
```

So far, I haven't investigated to figure out how the `vagrant-aws` provider does behave to generate this situation. For instance, the `vagrant-digitalocean` provider doesn't enter in a such dead loop and works fine for me (with the 4e451c6e991e96fc0f1968004581c3861725b053 fix).

Anyway, #6763 already showed that it was probably a bad idea of mine to assume that SSH communication is possible during the `config` stage of a provisioner plugin. As this configuration check step occurs before the execution of each vagrant command, it will more robust (and faster) to never try to perform any SSH communication during this stage (missing file errors will be finally raised by Ansible during the `provision` stage).

@vikas027 for now, you can easily patch your Vagrant 1.8.1 installation with the following workaround:

Replace the [original Config::Guest::check_path()](https://github.com/mitchellh/vagrant/blob/v1.8.1/plugins/provisioners/ansible/config/guest.rb#L39-L50) by this dummy implementation:

```ruby
  def check_path(machine, path, test_args, error_message_key = nil)
    true
  end
```

**Comment by gildegoma** [comment] 2016-02-13 08:10
I renamed the issue to focus on the AWS bug, as the "Virtualbox" use case above is actually tracked by #6793.

**Comment by gildegoma** [comment] 2016-02-13 08:20
@sethvargo can you please confirm (or infirm) the following statements:

The *Config* module of a Vagrant plugin shouldn't generate remote interactions with the guest system.

**Main Reason:**

The "Configuration Check" stage is thought to validate "things" that are available on the Vagrant Host, not on the guests.

----

I know that `plugins/provisioners/ansible/config/guest.rb` is currently the only `config` place where `machine.communicate` operations occur (compared to other core provisioners), which already answers quite well the above question. But I'd prefer to get an expert blame :smiley:

**Comment by krtek4** [comment] 2016-05-09 22:13
Any advance on this topic ?

The `vagrant-lxc` plugin seems to be affected by the same kind of bug (see https://github.com/fgrehm/vagrant-lxc/issues/398).

A project I've written currently has a workaround the force the use of `ansible` instead of `ansible_local` when the provider is not "Virtualbox" but I'd like to get rid of that "hack" :)

Happy to help in anyway if needed !

**Comment by gildegoma** [comment] 2016-05-21 15:15
@krtek4 thanks for the informative feedback and the friendly help offer.

I haven't taken time to figure out how `vagrant-aws` or `vagrant-lxc` (or even vagrant core) could be adapted to not enter this "hell recursion loop". But I am not sure if it makes sense to trigger a full Vagrant configuration check for each `ssh_info` calls, especially because many other machine providers don't do that. Maybe @sethvargo or @mitchellh can shed a light on this point...

Anyway, it is quite simple to avoid that `ansible_local` enter this dangerous path. So for now, I propose to fix this problem with #7335 (or even more radically by totally stopping with remote file detection in the `ansible_local` configuration validator).

**Comment by sethvargo** [comment] 2016-05-29 04:52
Hey @gildegoma 

Sorry for the delay here. I don't think we should ever be communicating with the guest in the config classes. This is typically reserved for the provisioner. If you take a look at the Chef provisioner, you'll see there's a [`verify_binary`](https://github.com/mitchellh/vagrant/blob/d9a9a7dd1bbec6e5a21d70426d3153d69276d091/plugins/provisioners/chef/provisioner/base.rb#L66-L81) method in the _provisioner_. I think this is probably the better approach instead of trying to do this in the config. The other reason you don't want to do this in the config is that configs are run multiple times during loading, so you could be sending a lot of commands to the remote guest for no real advantage. Provisioners, on the other hand, are only run after the configs are finalized.

**Comment by gildegoma** [comment] 2016-05-29 07:13
@sethvargo thanks for confirming this point. I am also convinced that's correct to move this to the _provisioner_. I reject the PR #7335, and will open a new one to move these sanity checks for both `ansible` and `ansible_local` provisioners.

**Closed** 2016-06-01 04:46 UTC
Labels: bug, provisioner/ansible
