### ISSUE TITLE
vagrant failed to mount folders in Linux guest when reload

### ISSUE THREAD

**Issue by xinwo** [mitchellh/vagrant#5504] opened 2015-03-20 10:06 UTC
vagrant up
no problem.

then 
vagrant reload
error below
---------------------------------------------------------------------------------------------------------
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant

The error output from the last command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
---------------------------------------------------------------------------------------------------------

**Comment by derek-adair** [comment] 2015-03-20 13:59
Duplicate of #5503

**Closed** 2015-03-20 14:04 UTC
