### ISSUE TITLE
Vagrant 1.7.3 fails sync folder from windows host to guest (VirtualBox 5.0) 

### ISSUE THREAD

**Issue by dharmsheta** [mitchellh/vagrant#5964] opened 2015-07-14 13:21 UTC
Vagrant 1.7.3 fails sync folder from windows host to guest (VirtualBox 5.0) preventing shell provisioners from execution.
 
> tf: /vagrant => D:/prestine-vagrant/vagrant-tf-buildbox-configs
> The following SSH command responded with a non-zero exit status.
> Vagrant assumes that this means the command failed!

> chown `id -u vagrant`:`id -g vagrant` /vagrant

Note that default synced folder is used
`config.vm.synced_folder ".", "/vagrant"`

However same vagrant version 1.7.3  works fine if guest is VirtualBox <= 4.3.28.

If you downgrade Vagrant to 1.7.2, it complains that VirtualBox versio 5.0 is not supported
`Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:
4.0, 4.1, 4.2, 4.3"`

**Comment by sethvargo** [comment] 2015-07-14 15:57
Hi @dharmsheta 

This looks like a duplicate of https://github.com/mitchellh/vagrant/issues/5933. Sorry about the regression - we have fixed this on master and will be released in 1.7.4!

**Closed by sethvargo** 2015-07-14 15:57 UTC
