### ISSUE TITLE
Vagrant shell provisioning does not execute sleep command

### ISSUE THREAD

**Issue by atluri1204** [mitchellh/vagrant#6289] opened 2015-09-21 02:15 UTC
Here is my vagrant file:

```ruby
$script = <<SCRIPT
my_password="Password"
rm --force root_user_script_1.sh
rm --force root_user_script_1.log
wget https://s3-us-west-2.amazonaws.com/myfiles2123/scripts/root_user_script_1.sh
chmod +x root_user_script_1.sh
./root_user_script_1.sh $my_password > root_user_script_1.log 2>&1
echo -e "\n\n\n" | ssh-keygen -t rsa -N "" -C user2@localhost
sleep 30
mkdir /home/rtbkit/.ssh
cat ~/.ssh/id_rsa.pub | cat >> /home/rtbkit/.ssh/authorized_keys
ssh -o "StrictHostKeyChecking no" user2@localhost "echo contents > 123.txt"
exit
SCRIPT

Vagrant.configure(2) do |config|
  config.ssh.private_key_path = "rackspace_rsa"
  config.vm.provider :rackspace do |rs|
    rs.username = "myrsusername"
    rs.api_key  = "a98wersf34432234edsst432ddef4697cc0036"
    rs.admin_password = "Password"
    rs.flavor   = /1 GB Performance/
    rs.image    = /Ubuntu 12.04/
    rs.rackspace_region = :dfw
    rs.server_name =  "box_box_1"
    rs.public_key_path  = "rackspace_rsa.pub"
  end

  config.vm.provision :shell, :inline => $script
end
```

Vagrant up command stops the provisioning script at this "echo -e "\n\n\n" | ssh-keygen -t rsa -N "" -C user2@localhost" step and finishes. It does not show any error on the terminal either.

Any ideas?

**Comment by sethvargo** [comment] 2015-09-21 13:08
Hi @atluri1204 

Can you please add a set -x and set -e to the top of the script and run it again? That will show you which commands are being run and exit on error.

**Comment by atluri1204** [comment] 2015-09-21 18:53
Hi @sethvargo 
Please find below my Vagrantfile and the output of "vagrant up" command. Vagrant does not execute the command '"ssh -o "StrictHostKeyChecking no" user2@localhost "echo sampleline > 123.txt"' which is right after 'sleep 10' command. Please help.

**Vagrantfile:**

'$script = <<SCRIPT
set -e
set -x
my_password="Password1"
rm --force user_script_1.sh
rm --force user_script_1.log
wget https://s3-us-west-2.amazonaws.com/shell-scripts/user_script_1.sh
chmod +x user_script_1.sh
./user_script_1.sh $my_password > user_script_1.log 2>&1
echo -e "\n\n\n" | ssh-keygen -t rsa -N "" -C user2@localhost
mkdir /home/rtbkit/.ssh
cat ~/.ssh/id_rsa.pub | cat >> /home/user2/.ssh/authorized_keys
sleep 10
ssh -o "StrictHostKeyChecking no" user2@localhost "echo sampletext > 123.txt"
exit
SCRIPT

Vagrant.configure(2) do |config|
  config.ssh.private_key_path = "rackspace_rsa"
  config.vm.provider :rackspace do |rs|
    rs.username = "nmark"
    rs.api_key  = "a342rwefwe34rf334234234ddef4697cc0036"
    rs.admin_password = "Password1"
    rs.flavor   = /1 GB Performance/
    rs.image    = /Ubuntu 12.04/
    rs.rackspace_region = :dfw
    rs.server_name =  "text_box_1"
    rs.public_key_path  = "rackspace_rsa.pub"
  end

  config.vm.provision :shell, :inline => $script
end'

**Output:**

'➜  dev-setup-scripts  vagrant destroy -f
==> default: Deleting server...
==> default: Running cleanup tasks for 'shell' provisioner...
➜  dev-setup-scripts  vagrant up
Bringing machine 'default' up with 'rackspace' provider...
==> default: Finding flavor for server...
==> default: Finding image for server...
==> default: Launching a server with the following settings...
==> default:  -- Flavor: 1 GB Performance
==> default:  -- Image: Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)
==> default:  -- Name: test_box_1
==> default: Waiting for the server to be built...
==> default: Waiting for ssh to become available at 104.239.240.109...
==> default: The server is ready!
==> default: Rsyncing folder: /dev-setup-scripts/ => /vagrant
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: ++ my_password=Password1
==> default: ++ rm --force user_script_1.sh
==> default: ++ rm --force user_script_1.log
==> default: ++ wget https://s3-us-west-2.amazonaws.com/shell-scripts/root_user_script_1.sh
==> default: --2015-09-21 18:39:10--  https://s3-us-west-2.amazonaws.com/rtbkit-files/shell-scripts/user_script_1.sh
==> default: Resolving s3-us-west-2.amazonaws.com
==> default: 54.231.151.48
==> default: Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|54.231.151.48|:443... 
==> default: connected.
==> default: HTTP request sent, awaiting response... 
==> default: 200 OK
==> default: Length: 
==> default: 3318
==> default:  (3.2K)
==> default:  [application/x-sh]
==> default: Saving to: `user_script_1.sh'
==> default: 
==> default:      0K
==> default:  
==> default: .
==> default: 100%
==> default:   153M
==> default: =0s
==> default: 
==> default: 2015-09-21 18:39:10 (153 MB/s) - `user_script_1.sh' saved [3318/3318]
==> default: ++ chmod +x user_script_1.sh
==> default: ++ ./user_script_1.sh Password1
==> default: ++ ssh-keygen -t rsa -N '' -C user2@localhost
==> default: ++ echo -e '
==> default: '
==> default: Enter file in which to save the key (/root/.ssh/id_rsa): 
==> default: Generating public/private rsa key pair.
==> default: Your identification has been saved in /root/.ssh/id_rsa.
==> default: Your public key has been saved in /root/.ssh/id_rsa.pub.
==> default: The key fingerprint is:
==> default: ab:00:c3:bb:6a:08:a0:18:e9:1c:c2:1c:8e:06:2c:85 rtbkit@localhost
==> default: The key's randomart image is:
==> default: +--[ RSA 2048]----+
==> default: |.o.              |
==> default: |Eo               |
==> default: |B..              |
==> default: |*B               |
==> default: |O.=     S        |
==> default: |+o +     .       |
==> default: |o . .   .        |
==> default: |.. . . .         |
==> default: |o..   .          |
==> default: +-----------------+
==> default: ++ mkdir /home/user2/.ssh
==> default: ++ cat
==> default: ++ cat /root/.ssh/id_rsa.pub
==> default: ++ sleep 10
➜  dev-setup-scripts  

**Output Ends Here**

**Comment by atluri1204** [comment] 2015-09-21 19:01
My goal  here is to create a Ubuntu box on rack-space and execute a shell script as root user and execute another shell script on the same box as "user2" user. I have to execute the two shell scripts sequentially one after the other. The reason why I had to add a sleep command is because Vagrant terminates at the ssh step inside the Vagrantfile. I thought that the SSH is not ready immediately after creating the VM. So, though of adding an additional sleep command to it enough time to get up and running.

**Comment by sethvargo** [comment] 2015-11-08 13:22
Hi @atluri1204 

Thank you for your reply. I am unable to reproduce your issue. I used the following Vagrantfile:

```ruby
$script = <<SCRIPT
  echo "foo"
  sleep 10
  echo "bar"
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.provision "shell", inline: $script
end
```

and the script sleeps for 10 seconds as expected:

```
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: foo
==> default: bar
```

I tried running your shell provisioner as well (without the script for S3 since I cannot download that), and it sleeps as expected.

**Comment by mitchellh** [comment] 2015-11-19 02:42
I've also been unable to reproduce with just about your identical Vagrantfile. At this point I'm going to close the issue but if we can get a clear repro case that works on multiple computers please do let us know!

Thanks.

**Closed by mitchellh** 2015-11-19 02:42 UTC
Labels: waiting-reply
