### ISSUE TITLE
Unable to up VM machine on Hyper-V

### ISSUE THREAD

**Issue by MrDeff** [mitchellh/vagrant#7906] opened 2016-10-17 15:05 UTC
### Vagrant version

Vagrant 1.8.6
### Host operating system

Windows 10
### Guest operating system

Centos 7
### Debug output

w:\vagrant\c7>vagrant up --provider hyperv
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Importing a Hyper-V instance
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm.ps1
Error:

В строке отсутствует завершающий символ: '.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
### Expected behavior

VM machine should be up.
### Steps to reproduce

1.vagrant init serveit/centos-7
2.vagrant up --provider hyperv

**Comment by chrisroberts** [comment] 2016-12-09 15:56
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by davidpodhola** [comment] 2017-01-02 20:47
This happened to me when I forgot to run `vagrant up` in elevated `cmd.exe`. Please try to open `cmd.exe` in `run as administrator`.

**Comment by chrisroberts** [comment] 2017-03-02 17:22
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2017-03-02 17:22 UTC
Labels: host/windows, provider/hyperv, waiting-reply
