### ISSUE TITLE
Support for long share paths on Windows hosts

### ISSUE THREAD

**Issue by Ingramz** [mitchellh/vagrant#6409] opened 2015-10-18 09:36 UTC
As @Pomax suggested, I am starting a new issue for the post-1.7.3 revert as noone else has done it yet and I am starting to need this at work, badly. 

In short, when a file or folder is created in a folder on a guest that has been shared by a Windows host, the operation can fail if the created item exceeds host's path length limit. The most common use case is attempting to run a Linux guest on Windows host and installing packages through NPM where long dependency chains can easily exceed 260 characters. To remedy this, the folder should be shared using UNC path, which does not have a 260 character length restriction.

We had a fix in #5495 but it got reverted because something broke regarding the UNC paths in VirtualBox at the last minute. As far as I know, the latest versions still have this issue~~, but I haven't the chance to test it yet. Update: test build 5.0.7-103382 has the issue, test build 4.3.31-103278 seems to be working fine with UNC paths.~~

The course of action should be following:
* [x] Find out VirtualBox versions where the UNC paths last worked.
  * Virtualbox 4.3 has had mostly working implemenation of UNC shares for a long time
  * Virtualbox 5.0 hasn't had UNC share support at all
* [x] Find out exactly what is broken.
  * Virtualbox 4.3 - `df -h` returns `df: '/vagrant’: Not a directory`, using files in share works flawlessly
  * Virtualbox 5.0 - UNC shares aren't working at all
* [x] Work with VirtualBox team on solving this.
  * VirtualBox 4.3 - [issue](https://www.virtualbox.org/ticket/14651), test build r103933 has the issue solved.
  * VirtualBox 5.0 - [an issue had been opened already](https://www.virtualbox.org/ticket/14651), test build r103713 ~~seems to be working, but more testing is needed~~ works.
* [x] Reintroduce changes to Vagrant.

~~I've been out of the loop since #5495 got merged, so any help would be appreciated filling the blanks.~~

Old issues #1953 #4815 

CC @jfbibeau @celtric @dhampik

**Comment by celtric** [comment] 2015-10-18 11:50
I haven't had this issue with flat dependencies (npm v3), which *may* be a strong reason to leave this feature unfixed. Apart from NPM, are there other use cases that would benefit from fixing this issue?

**Comment by dhampik** [comment] 2015-10-18 12:16
For me npm v3 didn't resolve the issue. Yes, dependencies became more flat, but not always. Some npm packages (e.g. webpack, which is pretty popular nowadays) still have deep enough nesting of node_modules to face that issue.

**Comment by Ingramz** [comment] 2015-10-18 12:17
@celtric Thank you for pointing out npm v3. However there is still going to be a long transition period till environments have been upgraded to npm v3. Node doesn't ship with npm v3 yet either.

I am not aware of any other real world cases where this issue has occured. But considering Linux paths are allowed to be about 16 times longer than on Windows without UNC and one file in Linux can be as long as the whole Windows path, this issue might arise at a later date with some other piece of software. In case of Vagrant I believe feature parity is in order.

**Comment by celtric** [comment] 2015-10-18 12:53
@dhampik Didn't know that :confused:

@Ingramz Ok, I understand and agree with what you say. Fixing it would be ideal, although in my limited experience with this issue, I've found that bypassing it has proven to be the most pragmatical approach. But +1 if people have the energy to invest in this.

**Comment by jfbibeau** [comment] 2015-10-18 16:00
Thanks for creating the new issue. Here's a thought: could we not re-enable this functionality only for VirtualBox 4? 

This is clearly broken in VirtualBox 5, but due to no fault of our own. Could we not re-add this fix in VirtualBox 4 drivers (https://github.com/mitchellh/vagrant/blob/master/plugins/providers/virtualbox/driver/version_4_3.rb) and leave it commented out in the VirtualBox 5 drivers https://github.com/mitchellh/vagrant/blob/master/plugins/providers/virtualbox/driver/version_5_0.rb ?

That way we can say it's supported and working if you're using VirtualBox 4, but until VBox fixes that issue in 5, it's left off?

**Comment by Ingramz** [comment] 2015-10-18 16:06
@jfbibeau sounds like a plan, but first I'd like to find out why was the change in 4.3 driver reverted.

**Comment by jfbibeau** [comment] 2015-10-18 16:10
@Ingramz Agreed, I always wondered that - I think it may have been a mistake, maybe someone reverted the entire PR without understanding the issue? I think there was a discussion thread on the revert commit with people discussing this, maybe we can dig it up.

**Comment by Ingramz** [comment] 2015-10-18 16:22
@jfbibeau that issue should be #5933

**Comment by jfbibeau** [comment] 2015-10-18 17:39
FWIW I've been using this patch locally at work with 4.3.20 and now with 4.3.30 and 50-100 devs are using Vagrant 1.7.2 (with this patch in the 4_3 drivers file) with no issues. I've never noticed the `df -h` output that you're reporting, I'll take a look Monday.

**Comment by Ingramz** [comment] 2015-10-18 17:45
See the post [here](https://github.com/mitchellh/vagrant/issues/5933#issuecomment-120883944) and the one following it. Until today I also believed that everything was just fine on 4.3

**Comment by Stanzilla** [comment] 2015-10-21 01:07
I thought about creating an account on the Oracle page...

![2015-10-21_03-05-07](https://cloud.githubusercontent.com/assets/75278/10625186/d13b583c-77a0-11e5-8a40-7e90dbe27a2c.png)

quickly nope'd out though. I also joined the vbox irc channel to maybe find someone that can help with our issue.

**Comment by maxidor** [comment] 2015-10-21 16:35
Updated VirtualBox ticket https://www.virtualbox.org/ticket/14651 on Stanzilla's request.

**Comment by vijayviji** [comment] 2015-10-24 19:57
+1. I'm too facing this issue. After upgrading to Virtualbox 5 in Windows, I'm facing lots of issues with shared folders and networking. Seems they're getting resolved one by one. But this issue is not yet resolved.

**Comment by maxidor** [comment] 2015-10-28 11:52
Feedback from VirtualBox devs:

Should be fixed in latest Windows build (r103713) from https://www.virtualbox.org/wiki/Testbuilds Please test.

**Comment by Ingramz** [comment] 2015-10-28 11:57
@maxidor thank you for notifying, I will start testing immediately.

**Comment by marvinroger** [comment] 2015-10-28 13:33
Could you please report back if it fixed the problem?
Le 28 oct. 2015 12:57 PM, "Indrek Ardel" <notifications@github.com> a
écrit :

**Comment by Ingramz** [comment] 2015-10-28 13:38
@marvinroger it fixed the problem for me on version 5, everything working perfectly. However, it would be appreciated if others can try it out as well. It's not really vagrant itself that I am concerned of but the  behavior of tools used inside the virtual machine.

**Comment by Stanzilla** [comment] 2015-10-28 15:32
I'm not sure links work. I tried a `npm install`and it would fail without `--no-bin-links`

**Comment by maxidor** [comment] 2015-10-28 15:43
@Stanzilla links are not supported on a shared folder

**Comment by Stanzilla** [comment] 2015-10-28 15:49
That's a problem then?

**Comment by maxidor** [comment] 2015-10-28 15:50
the problem is about special targets for the shared folder would break access to content, not the usage inside of it.

Rules still apply there, like links are not supported. They might work but no guarantee given.

**Comment by jfbibeau** [comment] 2015-10-28 15:51
Links will work on shared folders as long as you launch your VM as Administrator in Windows. Nonetheless that's a different issue than what is tracked with this issue :)

**Comment by maxidor** [comment] 2015-10-28 15:53
@Ingramz I've posted your feedback on the ticket for the vbox devs.

**Comment by jfbibeau** [comment] 2015-10-28 16:18
I confirm that I'm seeing the df -h issue with Vbox 4.3.30 (although shares work perfectly). I'll upgrade to the latest 4.3 build and confirm if the issue is gone or not, then upgrade to 5 and confirm if the issue is gone or not, just so we have a second confirmation.

**Comment by maxidor** [comment] 2015-10-30 14:49
@Ingramz Follow up from vbox devs:

    Thanks for feedback.
    Could you provide output of 'df -h' and 'mount' from VBox 4.3, where 'df' does not work? Thanks.

**Comment by jfbibeau** [comment] 2015-10-30 15:08
Output from 4.3.33 r103670:

```
[vagrant@latest ~]$ df -h
df: `/workspace': Not a directory
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/VolGroup-lv_root
                       38G  3.1G   33G   9% /
tmpfs                 1.5G     0  1.5G   0% /dev/shm
/dev/sda1             477M   30M  422M   7% /boot

[vagrant@latest ~]$ mount
/dev/mapper/VolGroup-lv_root on / type ext4 (rw)
proc on /proc type proc (rw)
sysfs on /sys type sysfs (rw)
devpts on /dev/pts type devpts (rw,gid=5,mode=620)
tmpfs on /dev/shm type tmpfs (rw,rootcontext="system_u:object_r:tmpfs_t:s0")
/dev/sda1 on /boot type ext4 (rw)
none on /proc/sys/fs/binfmt_misc type binfmt_misc (rw)
workspace on /workspace type vboxsf (uid=500,gid=500,rw)
```

I updated the VirtualBox support ticket.

**Comment by Ingramz** [comment] 2015-11-04 14:35
@jfbibeau @maxidor could one of you update the VirtualBox ticket with instructions how to patch Vagrant VirtualBox driver to use UNC paths.

That is, simply add

```rb
            if Vagrant::Util::Platform.windows?
              hostpath = Vagrant::Util::Platform.windows_unc_path(hostpath)
            end
```

after `plugins/providers/virtualbox/driver/version_4_3.rb:499`, where's
```rb
            hostpath = folder[:hostpath]
```

**Comment by maxidor** [comment] 2015-11-04 17:19
Done - https://www.virtualbox.org/ticket/14651#comment:7

**Comment by jfbibeau** [comment] 2015-11-04 18:25
Thanks! At least they are being responsive, maybe we'll get to the bottom of it!

**Comment by Ingramz** [comment] 2015-11-04 18:56
Thank you both. VirtualBox people (or at least that one person) have been amazing so far - I did not expect version 5 to be fixed that quickly and now that 4.3 is being looked into, things are looking pretty great.

**Comment by Ingramz** [comment] 2015-11-05 13:11
If you haven't noticed yet, there is a new test build out for 4.3. I will try it later today.

**Comment by Stanzilla** [comment] 2015-11-05 22:56
Yay for collaboration!

**Comment by maxidor** [comment] 2015-11-06 00:59
Indeed, very happy to see this resolved in such a nice way!

**Comment by Stanzilla** [comment] 2015-11-10 20:43
>Status changed from new to closed
Resolution set to fixed
Fixed in VBox 5.0.10.

5.0.10 was just released officially.

**Comment by Ingramz** [comment] 2015-11-10 22:00
@Stanzilla thanks for the heads-up.

**Comment by Ingramz** [comment] 2015-11-11 18:46
VirtualBox 4.3.34 was released as well, so now both versions have a release with fixes applied.

**Comment by jfbibeau** [comment] 2015-11-11 21:32
Now we need a PR to bring this functionality back in to Vagrant 4.3 and 5.x drivers, yes?

**Comment by Ingramz** [comment] 2015-11-11 21:35
Yes, I made that PR, which is #6493

**Closed** 2015-11-18 23:20 UTC
Labels: bug, host/windows

**Comment by jehy** [comment] 2015-11-23 08:53
Are there any new builds of vagrant with support of this feature?

**Comment by Ingramz** [comment] 2015-11-23 09:11
@jehy not yet, but you can use either vagrant 1.7.3 or apply the changes from the pull request manually to your v1.7.4 installation.

**Comment by Perni1984** [comment] 2015-12-18 19:40
a suitable workaround that worked for me and finally made npm useable, without any --no-bin-links workaround in vagrant boxes (using npm on windows natively is a desaster because of symlinks and nesting file structure), was to use smb synced folders together with smb3 and mfsymlinks extension:

```
config.vm.synced_folder "../.", "/var/www", type: "smb", mount_options: ["vers=3.02","mfsymlinks"]
```

Important: linux guest OS must have kernel version >= 3.18, otherwise mfsymlinks doesn't work.
