### ISSUE TITLE
Problem with   debian/jessie6 box

### ISSUE THREAD

**Issue by skornev** [mitchellh/vagrant#6685] opened 2015-12-18 10:39 UTC
Win 8.  After updating debian/jessie6 box to the latest version   and executing vagrant up, I've started to receive error messages "rsync could not be found". 
How to fix this:
1) Open vagrant file
2) Find section Vagrant.configure(2) do |config|
3) Add

```
config.vm.synced_folder ".", "/vagrant", disabled: true
```

**Comment by sethvargo** [comment] 2015-12-18 14:52
Duplicate of https://github.com/mitchellh/vagrant/issues/6631

**Closed by sethvargo** 2015-12-18 14:52 UTC
