### ISSUE TITLE
ansible_local installs, but cant find ansible

### ISSUE THREAD

**Issue by xahare** [mitchellh/vagrant#6870] opened 2016-01-14 08:52 UTC
the ansible_local provisioner installs ansible, but cant find it.
vagrant 1.8.1 os x 10.11.2

log and vagrant file here, https://gist.github.com/xahare/ad2cb60a2cc2ce7f38ec

**Comment by gildegoma** [comment] 2016-01-14 08:57
Closing as duplicate of #6793 (see https://gist.github.com/xahare/ad2cb60a2cc2ce7f38ec#file-typescript-L7580-L7591)

You can [patch](https://github.com/mitchellh/vagrant/commit/9dbdb9397a92d4fc489e9afcb022621df7f60d11) your vagrant installation until Vagrant 1.8.2 is released

**Closed by gildegoma** 2016-01-14 08:57 UTC
