### ISSUE TITLE
Multi-vm vagrant up works inconsistently

### ISSUE THREAD

**Issue by akamensky** [mitchellh/vagrant#7528] opened 2016-06-28 09:48 UTC
### Vagrant version
1.8.4

### Host operating system
Mac OS X 10.11.5

### Guest operating system
Centos (any)

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "centos7", autostart: false do |centos7|
    config.vm.box = "protodype/centos7"
    config.vm.hostname = "centos7"
    config.vm.provision "shell",
      inline: "ln -s /home/vagrant/sync/src/nc-configure.py /usr/bin/nc-configure"
  end
  config.vm.define "centos6", autostart: false do |centos6|
    config.vm.box = "protodype/centos6"
    config.vm.hostname = "centos6"
    config.vm.provision "shell",
      inline: "ln -s /home/vagrant/sync/src/nc-configure.py /usr/bin/nc-configure"
  end
end
```

### Debug output
https://raw.githubusercontent.com/akamensky/vagrant-bug-report/master/debug2.out

### Expected behavior
VM created/started/provisioned

### Actual behavior
Error shown

### Steps to reproduce
1. Multi-vm setup
2. Attempt `vagrant up [name]`

### Additional notes
The behavior is unpredictable. One time it works, another not.

![screen shot 2016-06-28 at 5 30 37 pm](https://cloud.githubusercontent.com/assets/985805/16411180/5fbec17a-3d58-11e6-8721-443a3db2a75b.png)

**Comment by sethvargo** [comment] 2016-06-28 11:02
Duplicate of https://github.com/mitchellh/vagrant/issues/7527

**Closed by sethvargo** 2016-06-28 11:02 UTC
