### ISSUE TITLE
when i use this cmd : sudo ssh-add ~/.vagrant.d/insecure_private_key. i get this error :Could not open a connection to your authentication agent.

### ISSUE THREAD

**Issue by ainux4mrvce** [mitchellh/vagrant#5682] opened 2015-05-06 06:26 UTC

**Comment by ainux4mrvce** [comment] 2015-05-06 06:28
when i use this cmd : sudo ssh-add ~/.vagrant.d/insecure_private_key. 
![screenshot from 2015-05-06 11 57 57](https://cloud.githubusercontent.com/assets/5284414/7488393/295c4e56-f3e7-11e4-81fe-a074e8c0a3c1.png)
i get this error :Could not open a connection to your authentication agent.

**Comment by simondrabble** [comment] 2015-05-11 22:30
The message you are seeing indicates there is no agent running. Try
    
    eval $(ssh-agent)
    ssh-add ~/.vagrant.d/insecure_private_key

**Comment by sethvargo** [comment] 2015-05-31 00:25
Duplicate of https://github.com/mitchellh/vagrant/issues/5681

**Closed by sethvargo** 2015-05-31 00:25 UTC
