### ISSUE TITLE
Vagrant fails to install plugin

### ISSUE THREAD

**Issue by voxik** [mitchellh/vagrant#6045] opened 2015-07-28 10:06 UTC
```
$ rpm -q vagrant
vagrant-1.7.2-1.x86_64

$ vagrant plugin install vagrant-openshift
Installing the 'vagrant-openshift' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ffi (1.9.10), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.10'` succeeds before bundling.

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /opt/vagrant/embedded/bin/ruby extconf.rb 
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/ruby
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:565:in `try_cpp'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:1044:in `block in have_header'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:895:in `block in checking_for'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:340:in `block (2 levels) in postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:340:in `block in postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:336:in `postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:894:in `checking_for'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:1043:in `have_header'
	from extconf.rb:16:in `<main>'


Gem files will remain installed in /home/vondruch/.vagrant.d/gems/gems/ffi-1.9.10 for inspection.
Results logged to /home/vondruch/.vagrant.d/gems/gems/ffi-1.9.10/ext/ffi_c/gem_make.out
```

Yes, I know I could probably fix this by installing ffi-devel package, but in the first place, there is already ffi-1.9.6 shipped with Vagrant, so why the updated version is downloaded?

The other possible explanation is that this is how Bundler works (https://github.com/bundler/bundler/issues/1964), but again, Vagrant is shipped as one big bundle, since it is tested like that and is should avoid issues like this, but this is apparently not true.

So is it possible to lock Vagrant to use its shipped versions? Why there isn't some Gemfile.lock which would achieve this? Why is the Gemfile always created on the fly with side effect like this?

**Comment by drcraig** [comment] 2015-07-31 17:04
I hit a similar issue. Only way I could resolve it was to run `sudo /opt/vagrant/embedded/bin/gem install ffi`before installing any plugins. I tried `vagrant plugin install ffi` but that just produced the same error.

**Comment by sethvargo** [comment] 2015-08-06 20:21
Hi @voxik 

This is actually a duplicate of https://github.com/mitchellh/vagrant/issues/5746, which is a core bundler issue :frowning:. We hope to find a good way to work around it in Vagrant 1.8.

**Closed by sethvargo** 2015-08-06 20:21 UTC
