### ISSUE TITLE
Vagrant issues setting hostname on 1.7.3 on MacOSX with Ubuntu VM

### ISSUE THREAD

**Issue by nathanpr** [mitchellh/vagrant#5960] opened 2015-07-13 22:52 UTC
Looks like there were changes to for setting the hostname on Windows VMs, but it looks like it broke this for Ubuntu VMs. 

Downgrading Vagrant to 1.7.2 fixes this issue.

Anyone else having this issue on 1.7.3?

**Comment by sethvargo** [comment] 2015-07-13 23:51
Hi @nathanpr 

This looks like a duplicate of https://github.com/mitchellh/vagrant/issues/5947. Can you please confirm? If it is not a duplicate, can you please share your complete Vagrantfile and the output of the Vagrant command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html)? Thanks!

**Comment by jatwork** [comment] 2015-07-14 03:28
I've encounter similar issue of v1.7.3. It's about ssh connection error. AND DOWNGRADING to v1.7.2 fixes the issue.

![Uploading 11733737_1005564059488688_232466990_o.jpg…]()

Not sure if it's related, but I'll suggest we follow semver in our future releases. So a big major change like v1.7.3 to support vbox 5.0 should be bumped to v2.0.0.

**Comment by nathanpr** [comment] 2015-07-14 03:55
@sethvargo, yes it looks like a duplicate of #5947 

Apologies -- I missed that searching earlier.

Also @jatwork, that makes sense. Although, FWIW, my 1.7.3 issue was with Virtualbox 4.3.20, 4.3.30, and 5.0

**Comment by sethvargo** [comment] 2015-07-14 15:50
Cool thanks! I am going to close this as a duplicate so we have the issues in one place :smile:

**Closed by sethvargo** 2015-07-14 15:50 UTC
Labels: waiting-reply
