### ISSUE TITLE
config.vm.provider not setting provider in multi-machine Vagrantfile

### ISSUE THREAD

**Issue by antoncohen** [mitchellh/vagrant#7135] opened 2016-03-13 08:19 UTC
### Vagrant version
Vagrant 1.8.1

### Host operating system
OS X 10.11.3

### Guest operating system
Linux

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'pp'

error = Vagrant::Errors::VagrantError

Vagrant.configure(2) do |config|
  config.vm.box_check_update = false

  machines = [
    {
      'name' => 'trusty',
      'box' => 'bento/ubuntu-14.04',
      'memory' => 1024,
      'default' => true
    },
    {
      'name' => 'centos7',
      'box' => 'bento/centos-7.2',
      'default' => false
    },
    {
      'name' => 'xenial',
      'box_name' => 'xenial-server-cloudimg-amd64',
      'box_url' => 'https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box',
      'providers' => ['virtualbox']
    }
  ]

  machines.each do |machine|
    name = machine['name']
    box = machine['box']
    box_url = machine['box_url']
    box_name = machine['box_name']
    providers = machine['providers'] || %w(vmware_fusion vmware_workstation virtualbox)
    memory = machine['memory'] || '512'
    default = machine['default'] || false

    fail error.new, 'machines must contain a name' if name.nil?

    config.vm.define name, primary: default, autostart: default do |cfg|
      # Find boxes at https://atlas.hashicorp.com/search
      if box
        cfg.vm.box = box
      elsif box_url && box_name
        cfg.vm.box = box_name
        cfg.vm.box_url = box_url
      else
        fail error.new, 'machines must contain box or box_name and box_url'
      end

      if providers.include? 'vmware_fusion'
        cfg.vm.provider :vmware_fusion do |v|
          v.vmx['memsize'] = memory
        end
      end

      if providers.include? 'vmware_workstation'
        cfg.vm.provider :vmware_workstation do |v|
          v.vmx['memsize'] = memory
        end
      end

      if providers.include? 'virtualbox'
        cfg.vm.provider :virtualbox do |v|
          v.memory = memory
        end
      end
      pp cfg.vm.__providers
    end
  end
end
```

### Expected behavior
In a multi-machine Vagrantfile I expect `config.vm.provider` to set the provider.

### Actual behavior
Machine attempts to use unsupported provider.

### Steps to reproduce
1. Use the above Vagrantfile
2. `vagrant status`
3. `vagrant up`
4. `vagrant up xenial`

```
$ env | grep -i vagrant

$ vagrant status 
[:vmware_fusion, :vmware_workstation, :virtualbox]
[:vmware_fusion, :vmware_workstation, :virtualbox]
[:virtualbox]
Current machine states:

trusty                    not created (vmware_fusion)
centos7                   not created (vmware_fusion)
xenial                    not created (vmware_fusion)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.

$ vagrant up
[:vmware_fusion, :vmware_workstation, :virtualbox]
Bringing machine 'trusty' up with 'vmware_fusion' provider...
==> trusty: Cloning VMware VM: 'bento/ubuntu-14.04'. This can take some time...
==> trusty: Verifying vmnet devices are healthy...
==> trusty: Preparing network adapters...
==> trusty: Starting the VMware VM...
==> trusty: Waiting for machine to boot. This may take a few minutes...
    trusty: SSH address: 192.168.109.161:22
    trusty: SSH username: vagrant
    trusty: SSH auth method: private key
    trusty: 
    trusty: Vagrant insecure key detected. Vagrant will automatically replace
    trusty: this with a newly generated keypair for better security.
    trusty: 
    trusty: Inserting generated public key within guest...
    trusty: Removing insecure key from the guest if it's present...
    trusty: Key inserted! Disconnecting and reconnecting using new SSH key...
==> trusty: Machine booted and ready!
==> trusty: Forwarding ports...
    trusty: -- 22 => 2222
==> trusty: Configuring network adapters within the VM...
==> trusty: Waiting for HGFS kernel module to load...
==> trusty: Enabling and configuring shared folders...
    trusty: -- <removed>: /vagrant

$ vagrant status
[:vmware_fusion, :vmware_workstation, :virtualbox]
[:vmware_fusion, :vmware_workstation, :virtualbox]
[:virtualbox]
Current machine states:

trusty                    running (vmware_fusion)
centos7                   not created (vmware_fusion)
xenial                    not created (vmware_fusion)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.

$ vagrant up xenial
[:virtualbox]
Bringing machine 'xenial' up with 'vmware_fusion' provider...
==> xenial: Box 'xenial-server-cloudimg-amd64' could not be found. Attempting to find and install...
    xenial: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    xenial: Box Version: >= 0
==> xenial: Box file was not detected as metadata. Adding it directly...
==> xenial: Adding box 'xenial-server-cloudimg-amd64' (v0) for provider: vmware_desktop, vmware_fusion, vmware_workstation
    xenial: Downloading: https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box
==> xenial: Box download is resuming from prior download progress
The box you attempted to add doesn't match the provider you specified.

Provider expected: vmware_desktop, vmware_fusion, vmware_workstation
Provider of box: virtualbox
$
```

`pp cfg.vm.__providers` prints the list of providers the box should support, yet it attempts to load with an unsupported provider. Environmental variable VAGRANT_DEFAULT_PROVIDER is not set.

**Comment by sethvargo** [comment] 2016-03-17 19:50
Hi @antoncohen 

Thank you for opening an issue. This is a duplicate of https://github.com/mitchellh/vagrant/issues/4654. Cheers!

**Closed by sethvargo** 2016-03-17 19:50 UTC

**Comment by darkn3rd** [comment] 2016-04-24 16:02
This may be a duplicated, but has some awesome creativity in the Vagrantfile that I will use... awesomesauce...

**Comment by antoncohen** [comment] 2016-04-24 20:41
@darkn3rd, thanks! That Vagrantfile was stripped down to submit this issue. I more complete one is here:

https://github.com/antoncohen/grocery_delivery-cookbook/blob/master/Vagrantfile

Regarding this being a duplicate, it does appear to be a duplicate of #4654. But #4654 has gone a bit off topic into discussing things like changing the .box format so providers can be detected before downloading the box.

I think I've shown this is actually a much simpler bug. The [documentation](https://www.vagrantup.com/docs/providers/basic_usage.html) states:

> Vagrant will go through all of the config.vm.provider calls in the Vagrantfile and try each in order. It will choose the first provider that is usable. For example, if you configure Hyper-V, it will never be chosen on Mac this way. It must be both configured and usable.

Looking at the code it appears that that list of providers is stored in the `__providers` variable, and is supposed to be used to pick a provider. As the output above shows, `__providers` is being set correctly. I think the bug might actually be in the vagrant-vmware-fusion plugin, which is overriding the intended behavior of Vagrant core.

**Comment by alexoj** [comment] 2016-08-23 20:37
@antoncohen 
I was having the same issue and tracked the bug to these lines in lib/vagrant/environment.rb:
```
      root_config.vm.__providers.reverse.each_with_index do |key, idx|
        config[key] = idx
      end
```

Later in the same function it increases the provider's priority if the provider was mentioned in the config:
```
        priority = config[key] + max_priority if config.key?(key)
```

However, if the index of the provider in the `__providers` list is 0, as it would be if it's the only one, priority ends up being set to the max priority instead of to the max priority + 1. That means there are 2 providers with the same priority, the one you specified and the one which originally had the max priority, which means that there's no reason to prefer the provider you specified over the original default.

Changing the previous snippet to this solved the issue for me:
```
      root_config.vm.__providers.reverse.each_with_index do |key, idx|
        config[key] = idx + 1
      end
```
