### ISSUE TITLE
does the packager command work post-Vagrant 1.7?

### ISSUE THREAD

**Issue by hardyoyo** [mitchellh/vagrant#5407] opened 2015-02-27 23:06 UTC
Hi, I recently upgraded from Vagrant 1.6.5 to 1.7.2, and I am working on creating a new vbox image for use with Vagrant. Here's the project I'm using:

https://github.com/DSpace/vagrantbox-ubuntu

Here is the error I'm seeing when I try to run vagrant package:

https://gist.github.com/hardyoyo/a0e93a47c5648b471f46

If in fact the "insecure" keypair thing is what's causing package to fumble, I'm wondering if this is still a viable way to package a vbox image for use with Vagrant? Is everyone using Packer now? Or am I doing something wrong?

**Comment by sethvargo** [comment] 2015-02-27 23:08
This looks like a duplicate of https://github.com/mitchellh/vagrant/issues/5056. Can you confirm?

**Comment by hardyoyo** [comment] 2015-02-28 02:27
Hard to say, I appreciate the tip and I am following up on it. So far, I've managed to confirm that the permissions on /home/vagrant/.ssh/authorized_keys are correct:

vagrant@vagrant-ubuntu-trusty-64:~$ cd .ssh
vagrant@vagrant-ubuntu-trusty-64:~/.ssh$ ls -al
total 12
drwx------ 2 vagrant vagrant 4096 Feb 28 02:02 .
drwxr-xr-x 4 vagrant vagrant 4096 Feb 28 02:02 ..
-rw------- 1 vagrant vagrant  466 Feb 28 02:02 authorized_keys

**Comment by hardyoyo** [comment] 2015-02-28 02:40
Aha! #4707, I will see if just disabling the key stuff "fixes" this issue.

**Comment by hardyoyo** [comment] 2015-02-28 03:12
Yep, adding this line to our Vagrantfile lets me successfully run package:

config.ssh.insert_key = false

**Comment by sethvargo** [comment] 2015-02-28 15:55
Sweet. I am going to close this as a dupe of #5065 and #4707. I am glad you were able to get it figured out! Hopefully we can improve this experience in the next release.

**Closed by sethvargo** 2015-02-28 15:55 UTC

**Comment by hardyoyo** [comment] 2015-03-02 18:38
@sethvargo are you sure this is really a duplicate? From where I sit, this looks like a different problem, having a root cause in #4707, and can be routed around using a suggestion from the comments on #4707, however, from what I can see... post 1.7, you can not package a base box without disabling #4707 with config.ssh.insert_key = false. That feels like a bug, with a known workaround. But not a fixed bug.
