### ISSUE TITLE
private_network interface stays in "down" state on "vagrant up"

### ISSUE THREAD

**Issue by dddpaul** [mitchellh/vagrant#8166] opened 2017-01-02 08:04 UTC
Hello.

Private network interface stays in "down" state without assigned IP address with Vagrant 1.9.1, VirtualBox 5.1.10 on MacOS Sierra (10.12.2) and Ubuntu 16.04 with Centos 7.3 (centos/7 box).

Box network settings in Vagrantfile:

```
node.vm.box = "centos/7"
node.vm.network :private_network, ip: "192.168.40.111"
```

Network configuration inside box:

```
cat /etc/sysconfig/network-scripts/ifcfg-eth1
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
NM_CONTROLLED=no
BOOTPROTO=none
ONBOOT=yes
IPADDR=192.168.40.111
NETMASK=255.255.255.0
DEVICE=eth1
PEERDNS=no
#VAGRANT-END
```

But `eth1` is in down state actually:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:22:5b:53 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 85838sec preferred_lft 85838sec
    inet6 fe80::5054:ff:fe22:5b53/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN qlen 1000
    link/ether 08:00:27:31:b1:bd brd ff:ff:ff:ff:ff:ff
```

There are couple of workarounds:

1.  Restart `network` service while provisioning. For example (for Ansible):

```
- name: ensure all interfaces are up 
  service: name=network enabled=yes state=restarted
```

The downside - provision has no effect when box is restarted by `reboot` command or `vagrant reload`.

2. Bring interface up in /etc/rc.local:

```
/sbin/ifup eth1
```

The downside - interface name may be changed sometimes by udev etc.

PS: I posted this text as a comment to #5590 because symptoms are quite similar. Then there was a bunch of comments from other people complaining about this problem with Vagrant 1.9.1 on different systems. They say mostly that downgrade to 1.8.7 solves the problem. So I've decided to start up a new issue.

**Comment by jairojunior** [comment] 2017-01-03 12:57
Decided to investigate this and I'm very suspicious of either `plugins/guests/redhat/cap/configure_networks.rb` or `plugins/guests/redhat/cap/change_host_name.rb` 

`network` service used to be restarted unconditionally, but it checks for `NetworkManager` instead in 191.

Not my area of expertise, but I'll try to fix locally.

https://github.com/mitchellh/vagrant/compare/v1.9.0...v1.9.1

PS: It works with v1.9.0

**Comment by jairojunior** [comment] 2017-01-03 13:09
Just confirmed that rolling back to `service network restart` in `plugins/guests/redhat/cap/configure_networks.rb` fixes the problem.

**Comment by jairojunior** [comment] 2017-01-03 13:14
It seems to already have an open PR for this: https://github.com/mitchellh/vagrant/pull/8148

**Comment by bwlz** [comment] 2017-01-04 16:02
Sounds like a fix is about squared away, but I'm seeing this as well in Vagrant 1.9.1 with Virtualbox 5.1.10_Debian r112026 and the box 'geerlingguy/centos7'. The issue does not manifest with the VMware provider.

**Comment by hardyjohnson** [comment] 2017-01-04 22:10
@bwlz just a warning you may run into issues with subsequent boots as provision shell will only run on provision.

**Comment by marrrt** [comment] 2017-01-06 09:47
I'm experiencing this problem as well.

On `vagrant up` I see the following in /var/log/messages

```
Jan  6 09:17:31 localhost NetworkManager[4207]: <info>  [1483694251.4576] ifcfg-rh: new connection /etc/sysconfig/network-scripts/ifcfg-eth1 (9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04,"System eth1")
Jan  6 09:17:31 localhost NetworkManager[4207]: <info>  [1483694251.4576] ifcfg-rh: Ignoring connection /etc/sysconfig/network-scripts/ifcfg-eth1 (9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04,"System eth1") due to NM_CONTROLLED=no. Unmanaged: interface-name:eth1.
```

I wonder if generating the `ifup-eth1` file with `NM_CONTROLLED=yes` would sort this out for using the NetworkManager to bring up the network interfaces.

Issuing `service network restart` brings up the private interface although the following shows up in /var/log/messages

```
Jan  6 09:25:04 localhost firewalld: ERROR: Failed to load '/etc/sysconfig/network-scripts/ifcfg-eth1': [Errno 13] Permission denied: '/etc/sysconfig/network-scripts/ifcfg-eth1'
Jan  6 09:25:04 localhost firewalld: ERROR: Calling post func <function ifcfg_set_zone_of_interface at 0x7f0fa088d7d0>(('', 'eth1')) failed: [Errno 13] Permission denied: '/etc/sysconfig/network-scripts/ifcfg-eth1'
```

Looking at `/etc/sysconfig/network-scripts/ifcfg-*` the permissions are as follows:

```
-rw-r--r--. 1 root    root    254 Sep 12 10:47 /etc/sysconfig/network-scripts/ifcfg-lo
-rw-r--r--. 1 root    root     86 Dec 15 11:14 /etc/sysconfig/network-scripts/ifcfg-eth0
-rw-------. 1 vagrant vagrant 213 Jan  6 09:17 /etc/sysconfig/network-scripts/ifcfg-eth1
```

Not sure if the latter should be a separate issue or not.

**Comment by marrrt** [comment] 2017-01-06 18:31
The `NM_CONTROLLED=yes` or commented out seems to do the trick for me for the network to come up.

**Comment by neilbryson** [comment] 2017-01-08 02:41
The private network of my Oracle Linux Vagrant box just randomly stopped working on v1.9.1. It was alright a few days ago but it just decided to stop working. Restarting the network service brings up the private network interface but I still cannot connect into it from my host machine.

Can confirm this issue does not occur when I downgraded to v1.8.7.

**Comment by chrisroberts** [comment] 2017-01-09 16:32
Fixed via #8148. Thanks for the report!

**Closed by chrisroberts** 2017-01-09 16:32 UTC

**Comment by utdrmac** [comment] 2017-01-09 16:34
Same experience. I have the following configured:
`node_config.vm.network :private_network, ip: local_vm_ip, adaptor: 2`

eth0 comes up fine with 10.0.2.15. eth1 is configured under /etc/sysconfig/.../ifcfg-eth1 with the proper IP, but it does not start when system boots.

Virtualbox 5.1.12
Vagrant 1.9.1
MacOS 10.12.2
CentOs 7.3.1611

**Comment by pipisco** [comment] 2017-01-29 13:02
Same experience. Private interface (eth1) cannot auto start after
`vagrant up`

My configuration.
MacOS: 10.10.5
CentOS: centos/7 (virtualbox, 1611.01)
Vagrant 1.9.1
VBox: 5.1.12r112440

**Comment by utdrmac** [comment] 2017-01-29 17:11
@chrisroberts please re-open this. The fix is not working for many still.

**Comment by retr0h** [comment] 2017-02-23 00:32
> @chrisroberts please re-open this. The fix is not working for many still.

Having the same issue.

**Comment by tomasdikk** [comment] 2017-02-23 14:29
I think I have a similar issue? With a clean `vagrant init`, then modifying Vagrantfile

`config.vm.box = "centos/7"`
`config.vm.network "private_network", ip: "10.0.0.10"`
`config.ssh.host = "10.0.0.10"`
`config.ssh.port = "2222"`

On MacOS Sierra 10.12.3, Virtualbox 5.1.14 r112924.

With the first `vagrant up` I get

`...` (all OK so far)
`default: SSH address: 10.0.0.10:2222`
`...`
`default: Warning: Host appears down. Retrying...`

(Without the private_network directive, vagrant up works, with the default 127.0.0.1:2222)

Any ideas whether I'm doing something wrong? Thanks guys!

**Comment by agusti-t** [comment] 2017-03-21 14:13
@chrisroberts The issue persists, please reopen this issue.

**Comment by kanaifu** [comment] 2017-07-17 13:38
Vagrant 1.9.7
Virtualbox 5.1.22 r115126
HOST: CentOS Linux release 7.3.1611
Box: CentOS Linux release 7.3.1611

Issue persists.

**Comment by emielmolenaar** [comment] 2017-07-26 12:35
Issue still present here on Ubuntu 16.04, Vagrant 1.9.7 and Virtualbox 5.1.24.

**Comment by bertjwregeer** [comment] 2017-10-11 17:36
Is there a way to configure the interface without `NM_CONTROLLED=no` being added? RHEL has gone all-in on NetworkManager and while the original "network service" still exists to bring up interface it has been heavily deprecated, and letting NetworkManager manage the interface is a much better solution.

**Comment by MBetters** [comment] 2017-10-18 15:12
On Windows 10, with Vagrant 1.9.6, I'm doing `vagrant up` on multiple CentOS 6 boxes.

Each box has a Vagrantfile that looks like this:
`
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/6"
  config.vm.hostname = "host_12"
  config.vm.network "private_network", ip: "10.0.0.12"
end
`

The only difference between each CentOS box is I give them different hostnames and private network IP addresses in the 10.0.0.0/24 subnet.

When I made some changes to one of the boxes, I packaged it, then I put the `package.box` file into its own folder and made a Vagrantfile to spin up a clone of the packaged box, from the package. That Vagrantfile looks like this:
`
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "package.box"
  config.vm.hostname = "web"
  config.vm.network "private_network", ip: "10.0.0.11"
end
`

Now, when I run `vagrant up` on this cloned box, I get the following output:

`
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Connection reset. Retrying...
==> default: Machine booted and ready!
[default] GuestAdditions 5.1.26 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

# Update sysconfig
sed -i 's/\(HOSTNAME=\).*/\1web/' /etc/sysconfig/network

# Update DNS
sed -i 's/\(DHCP_HOSTNAME=\).*/\1"web"/' /etc/sysconfig/network-scripts/ifcfg-*

# Set the hostname - use hostnamectl if available
echo 'web' > /etc/hostname
if command -v hostnamectl; then
  hostnamectl set-hostname --static 'web'
  hostnamectl set-hostname --transient 'web'
else
  hostname -F /etc/hostname
fi

# Prepend ourselves to /etc/hosts
grep -w 'web' /etc/hosts || {
  sed -i'' '1i 127.0.0.1\tweb\tweb' /etc/hosts
}

# Restart network
service network restart


Stdout from the command:

10.0.0.11 web
Shutting down interface eth0:  [  OK  ]
Shutting down interface eth2:  [  OK  ]
Shutting down loopback interface:  [  OK  ]
Bringing up loopback interface:  [  OK  ]
Bringing up interface eth0:
Determining IP information for eth0... done.
[  OK  ]
Bringing up interface eth1:  Device eth1 does not seem to be present, delaying initialization.
[FAILED]
Bringing up interface eth2:  Determining if ip address 10.0.0.11 is already in use for device eth2...
[  OK  ]
`

I noticed at the bottom of the output that restarting eth1 failed, but restarting eth0 and eth2 succeeded. I SSH'd into this new VM and tried pinging the other VMs in the private network. It worked. The other VMs can also ping it. This means it's successfully networked.

My question is, should I just ignore the failed eth1 interface restart? Is this expected behavior? Is the restart of eth2 a kind of "backup plan" that kicked in when eth1 failed?

I'm just trying to verify that vagrant is solving this issue reliably and that this behavior won't cause problems if I continue to follow the workflow of making changes to a VM, packaging it into a package.box file, putting the package.box file into a new folder, adding a Vagrantfile thats the same as others in the private network, changing the config.vm.hostname and private network IP address, then booting up. I don't wanna run into a mess later down the road and find out a copied VM isn't able to boot because vagrant ran out of eth interfaces to try.

Any clarification on my concern is appreciated!
