### ISSUE TITLE
Can't open long file name on mounted windows folder

### ISSUE THREAD

**Issue by jehy** [mitchellh/vagrant#6510] opened 2015-11-10 15:56 UTC
Hello! I have a mounted folder from windows to CentOS 6.7.
I am using virtualbox 5.0.2 and vagrant 1.7.4

My folder is mounted with line in Vagrantfile:

config.vm.synced_folder "D:\\WEB\\htdocs\\localhost", "/web"

My web project (in CentOS) creates files on path
/web/vks/Symfony/app/cache/dev_old/annotations/f7

File name is like
5b53796d666f6e795c42756e646c655c57656250726f66696c657242756e646c655c436f6e74726f6c6c65725c50726f66696c6572436f6e74726f6c6c6572235f5f636f6e737472756374405b416e6e6f745d5d5b315d.doctrinecache

I can read and delete those files from windows but I can`t delete them from CentOS - both cat and rm commands fail to execute with "no such file" error. Also ls gives very strange info - it can not understand owner and permissions.

```
[vagrant@localhost vks]$ cd /web/vks/Symfony/app/cache/dev_old/annotations/f7
[vagrant@localhost f7]$ rm *
rm: cannot remove `5b53796d666f6e795c42756e646c655c57656250726f66696c657242756e646c655c436f6e74726f6c6c65725c50726f66696c6572436f6e74726f6c6c6572235f5f636f6e737472756374405b416e6e6f745d5d5b315d.doctrinecache.data': No such file or directory
[vagrant@localhost f7]$ cat ./5b53796d666f6e795c42756e646c655c57656250726f66696c657242756e646c655c436f6e74726f6c6c65725c50726f66696c6572436f6e74726f6c6c6572235f5f636f6e737472756374405b416e6e6f745d5d5b315d.doctrinecache.data
cat: ./5b53796d666f6e795c42756e646c655c57656250726f66696c657242756e646c655c436f6e74726f6c6c65725c50726f66696c6572436f6e74726f6c6c6572235f5f636f6e737472756374405b416e6e6f745d5d5b315d.doctrinecache.data: No such file or directory
[vagrant@localhost f7]$ ls -a -l
ls: cannot access 5b53796d666f6e795c42756e646c655c57656250726f66696c657242756e646c655c436f6e74726f6c6c65725c50726f66696c6572436f6e74726f6c6c6572235f5f636f6e737472756374405b416e6e6f745d5d5b315d.doctrinecache.data: No such file or directory
total 48
drwxrwxrwx. 1 vagrant vagrant  8192 Nov 10 15:31 .
drwxrwxrwx. 1 vagrant vagrant 40960 Nov 10 15:36 ..
-?????????? ? ?       ?           ?            ? 5b53796d666f6e795c42756e646c655c57656250726f66696c657242756e646c655c436f6e74726f6c6c65725c50726f66696c6572436f6e74726f6c6c6572235f5f636f6e737472756374405b416e6e6f745d5d5b315d.doctrinecache.data
```

chown and chmod also fail.

**Comment by sethvargo** [comment] 2015-11-10 16:04
This is a duplicate of https://github.com/mitchellh/vagrant/issues/6409

**Closed by sethvargo** 2015-11-10 16:04 UTC

**Comment by jehy** [comment] 2015-11-10 16:06
Thanks!
