### ISSUE TITLE
Any plans to upgrade Vagrant for Debian Apt repositories?

### ISSUE THREAD

**Issue by kenorb** [mitchellh/vagrant#7529] opened 2016-06-28 14:20 UTC
I'm using Debian 7 and I've installed Vagrant via `apt-get`, however the release is very old: 1.0.3, on Mac I've got 1.8.1.

Are there any plans to upgrade that release for Debian repositories?

```
$ sudo apt-cache showpkg vagrant
Package: vagrant
Versions: 
1.0.3-1 (/var/lib/apt/lists/ftp.debian.org_debian_dists_wheezy_main_binary-amd64_Packages) (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/ftp.debian.org_debian_dists_wheezy_main_binary-amd64_Packages
                  MD5: d6778864e039532f9a7c6b23859e3b58
 Description Language: en
                 File: /var/lib/apt/lists/ftp.debian.org_debian_dists_wheezy_main_i18n_Translation-en
                  MD5: d6778864e039532f9a7c6b23859e3b58


Reverse Depends: 
Dependencies: 
1.0.3-1 - ruby-erubis (2 2.7.0) ruby (16 (null)) ruby-interpreter (0 (null)) ruby-archive-tar-minitar (0 (null)) ruby-childprocess (2 0.3.1) ruby-i18n (2 0.6.0) ruby-json (2 1.5.1) ruby-log4r (2 1.1.9) ruby-net-scp (2 1.0.4) ruby-net-ssh (2 2.2.2) rubygems (2 1.3.6) virtualbox (2 4.0) 
Provides: 
1.0.3-1 - 
Reverse Provides: 

```

**Comment by nickwright80** [comment] 2016-06-28 16:33
You can get Vagrant 1.8.1 from -unstable: https://packages.debian.org/source/sid/vagrant

**Comment by sethvargo** [comment] 2016-06-28 23:38
Duplicate of https://github.com/mitchellh/vagrant-installers/issues/12.

Please don't use the debian packages. They are a common source of problems because they are built against a version of Ruby that Vagrant is not tested against and links to system libraries. The recommended installer is the one from https://www.vagrantup.com/downloads.html, and there are more details in the linked issue about our stance on PPAs. Thanks! 😄

**Closed by sethvargo** 2016-06-28 23:38 UTC
