### ISSUE TITLE
Vmware provider is not using static ip with coreos guest.

### ISSUE THREAD

**Issue by johnraz** [mitchellh/vagrant#5006] opened 2014-12-17 11:33 UTC
Hi,

This has been tested on:
vagrant 1.7.1
vagrant-vmware-fusion 3.1.2
coreos box 494.5.0
vmware-fusion 7.1.0
Macos X Yosemite

Creating a very simple box with the following vagrant file:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "coreos-stable"
  config.ssh.insert_key = false
  config.vm.box_url = "http://%s.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json" % "stable"
  config.vm.network "private_network", ip: "10.10.10.22", netmask: "255.255.255.0"
end
```

Using the *virtualbox* provider the ip will be assigned correctly.

Using the *vmware_fusion* provider the guest machine will receive an ip from the dhcp in the 10.10.10.x pool of ip.

Please note that using an ubuntu box this is working perfectly fine with both providers.

**Comment by mitchellh** [comment] 2015-01-05 22:06
I copied the exact config and it works for me (with Ubuntu). This leads me to believe that if this still isn't working for you it may be a CoreOS issue or Vagrant's interaction with CoreOS for network configuration.

**Comment by berinle** [comment] 2015-01-06 19:17
This is also an issue for me using centos 6. Here is a minimal example...

	Vagrant.configure(2) do |config|
	  config.vm.box = "chef/centos-6.5"
	  config.ssh.insert_key = false
	  config.vm.box_url = "https://atlas.hashicorp.com/chef/boxes/centos-6.5"
	  config.vm.network "private_network", ip: "10.10.10.22"
	end

Here is the output of `vagrant ssh-config`

Host default
  HostName 172.16.102.158
  User vagrant
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/berinle/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL

Am I missing something?

**Comment by johnraz** [comment] 2015-01-06 19:55
@mitchellh , I can confirm I experienced the same, but still, having different behavior between virtualbox and vmware tends to point out that the issue is with vagrant's interaction with CoreOS.

**Comment by johnraz** [comment] 2015-01-06 19:57
@berinle : your case is not an issue, by default vagrant will assign a nat interface for every ssh actions AFAIK. The only way to change that ip is to mess around with the vmware dns. eg: assign a static ip to the interface's mac address. It's a different topic really.

**Comment by berinle** [comment] 2015-01-06 20:23
@johnraz oh really? ok. I have been able to assign static ips in the past using visualbox + ubuntu combo. Not sure why the same doesn't apply here.

**Comment by sethvargo** [comment] 2015-01-06 20:37
@mitchellh we just released v3.2.0 of the VMware Fusion/Workstation plugin - can you try that out?

**Comment by berinle** [comment] 2015-01-06 21:06
My bad. `vagrant ssh-config` wasn't what I needed to determine the ip-address of the box.. duh! After I ssh into it and check the ip, i can confirm it gets the static ip I assigned it.

	Last login: Fri Mar  7 16:55:51 2014 from 172.16.230.1
	[vagrant@localhost ~]$ ifconfig | grep inet
	          inet addr:172.16.208.133  Bcast:172.16.208.255  Mask:255.255.255.0
	          inet6 addr: fe80::20c:29ff:fec3:8f12/64 Scope:Link
	          inet addr:10.10.10.22  Bcast:10.10.10.255  Mask:255.255.255.0
	          inet6 addr: fe80::20c:29ff:fec3:8f1c/64 Scope:Link
	          inet addr:127.0.0.1  Mask:255.0.0.0
	          inet6 addr: ::1/128 Scope:Host

I am using v3.2.0 of the vmware fusion plugin.

Cheers

**Comment by johnraz** [comment] 2015-01-07 09:08
@sethvargo , @mitchellh : from the test I just ran with a fresh box, it seems to be working ;-)
Thx !

**Comment by sethvargo** [comment] 2015-01-07 15:45
I'm going to close this as @johnraz reported the issue is fixed. @athirn if you're having similar problems, can you please open a new issue with a Vagrantfile and debug output? Thanks!

**Closed by sethvargo** 2015-01-07 15:45 UTC
Labels: bug, provider/vmware
