### ISSUE TITLE
After uninstall and reinstalling 1.9.2, plugin install doesn't work

### ISSUE THREAD

**Issue by michaelHeimes** [mitchellh/vagrant#8324] opened 2017-03-02 17:47 UTC
Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-share (= 1.1.6)'

Installing 1.9.1 fixes this.

**Comment by chrisroberts** [comment] 2017-03-02 17:57
@michaelHeimes Can you provide a gist of the `--debug` output for the plugin install? Thanks!

**Comment by michaelHeimes** [comment] 2017-03-02 17:58
The command isn't found. Sorry. I've already gone back down to 1.9.1 so I can't reproduce it now.

**Comment by michaelHeimes** [comment] 2017-03-02 18:06
@chrisroberts I went back up to 1.9.2 and tried again. `--debug` says command not found. Sorry, I'm not that good with command line.

**Comment by chrisroberts** [comment] 2017-03-02 18:16
@michaelHeimes You'll want to run the full command with the debug flag like this:

```
vagrant plugin install vagrant-hostsupdater --debug
```

Copy all the output and paste it into a gist. Thanks!

**Comment by michaelHeimes** [comment] 2017-03-02 19:03
Like this?

https://gist.github.com/michaelHeimes/5b6db479991ed5741dac9264360b167b

**Comment by chrisroberts** [comment] 2017-03-02 19:09
Perfect, thanks!

**Comment by chrisroberts** [comment] 2017-03-02 19:12
@michaelHeimes does running this command:

```
vagrant plugin update
```

fix the problem? If not, does:

```
vagrant plugin expunge
```

allow you to re-install the plugins? Thanks!

**Comment by michaelHeimes** [comment] 2017-03-04 02:12
That fixed it! Thanks!

**Comment by chrisroberts** [comment] 2017-03-07 20:41
Closing this up as the issue is resolved. Cheers!

**Closed by chrisroberts** 2017-03-07 20:41 UTC
Labels: bug, bundler
