### ISSUE TITLE
Unhandled win32 exception occurred in vagrant.exe [7184]

### ISSUE THREAD

**Issue by AMartinNo1** [mitchellh/vagrant#5372] opened 2015-02-21 11:10 UTC
Good morning everybody.

first I want to mention that I could not reproduce it but it may be good to know "it happened already" if there are familiar issues in future.

Today I have copied the files "Vagrantfile" and "provision.sh" from one project into a new folder. I then edited the const or variable (not sure wether its a const or variable) "PROJECTFOLDER" in file "provision.sh".

Afterwards I proceeded with triggering "vagrant up" in the windows console. As expected the provisioning started but during the process windows came up with a pop asking me to debug or close the programme. I pressed debug in order to get further details about the issue. Well, I received the "Unhandled win32 exception occurred in vagrant.exe [7184]" as read in the title and you may see in the image.
![vagrant_unhandled_win32_exception](https://cloud.githubusercontent.com/assets/5464339/6313751/a0415526-b9bc-11e4-8687-2df29276edf2.png)

I did not hesitate to take a look on the console and noted the vagrant up process is running - wondering why but ok. After a while it stopped running and is stucked at "==> default: Use it: php composer.phar" now.

In order to check wether it is reproducable I have set VAGRANT_LOG to debug in a new vagrant project with same Vagrantfile and provision.sh. This lead to following result:
![vagrant_unhandled_win32_exception_trytoreproduce_1](https://cloud.githubusercontent.com/assets/5464339/6313857/477e7ffa-b9c0-11e4-9588-8d5e40262130.png)
![vagrant_unhandled_win32_exception_trytoreproduce_2](https://cloud.githubusercontent.com/assets/5464339/6313858/49698774-b9c0-11e4-83ba-fe48b89c2ce2.png)
![vagrant_unhandled_win32_exception_trytoreproduce_3](https://cloud.githubusercontent.com/assets/5464339/6313859/4cac7734-b9c0-11e4-8c0b-a34fcb518ab0.png)
![vagrant_unhandled_win32_exception_trytoreproduce_4](https://cloud.githubusercontent.com/assets/5464339/6313860/4e1cd33e-b9c0-11e4-9fdd-959ac79d2592.png)

Another try to reproduce it failed - windows did not came up with a pop up and the vagrant up process is not stucked at the php composer.phar step.

I know due to various hardware and software variations accross vagrant users I provide some further details. I share the content of the named files in second paragraph and some other information in following section:
Vagrantfile (I only changed the ip): http://www.codeshare.io/qeL4p
provision.sh: http://www.codeshare.io/L202H
original provision.sh (from the working project): http://www.codeshare.io/K7cV7
Operation System: Windows 8.1 64bit
Location: My Vagrant projects, vagrant installation and VirtualBox is installed under an extern drive connected via USB-Drive-Hub (USB-Drive-Hub -> USB 3.0 HUB -> My computer).

I just checked the status of both virtual machines. The status of both is "running" but I halted them.

**Comment by sethvargo** [comment] 2015-07-10 20:32
Hi there,

Since you are not able to reproduce this issue (and since Vagrant has a fairly large user base and no one else has reported this), I am going to close this as an isolated incident. Thank you for reporting, but this appears to be something that is not wide-spread or it may be a local environment issue. Thanks! :smile:

**Closed by sethvargo** 2015-07-10 20:32 UTC
Labels: bug, windows
