### ISSUE TITLE
stop when vagrant up 

### ISSUE THREAD

**Issue by skyscreen** [mitchellh/vagrant#8560] opened 2017-05-05 08:24 UTC
### Vagrant version
1.9.3

### Host operating system
MacOS Sierra

### Guest operating system
Ubuntu

.

### Expected behavior
What should have happened?
When I manually suspend the vm using 'vagrant suspend', then use 'vagrant up' to start the vm
should can started and logined using 'vagrant ssh'

### Actual behavior
What actually happened?
it stopped to ssh key part below:

==> greeting-service-vm: Resuming suspended VM...
==> greeting-service-vm: Booting VM...
==> greeting-service-vm: Waiting for machine to boot. This may take a few minutes...
    greeting-service-vm: SSH address: 127.0.0.1:2222
    greeting-service-vm: SSH username: vagrant
    greeting-service-vm: SSH auth method: private key

**Comment by chrisroberts** [comment] 2017-05-16 02:15
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by chrisroberts** [comment] 2017-07-26 17:30
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2017-07-26 17:30 UTC
Labels: question, waiting-reply
