### ISSUE TITLE
Vagrant documentation about default insecure key should be updated

### ISSUE THREAD

**Issue by gou1** [mitchellh/vagrant#5059] opened 2014-12-24 09:41 UTC
Hi,

Vagrant supposedly uses the same insecure private key by default, which allows for easy ssh to the VMs. But lately vagrant has been replacing my private key when booting a VM.

Here's my setup:
- Windows 7 Pro x64
- VirtualBox 4.3.20
- Vagrant 1.7.1

Here's my Vagrantfile:
```
Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty32"
end
```

And when i run `vagrant up` i get:

```
Vagrant insecure key detected. Vagrant will automatically replace this with a newly generated keypair for better security.
```

**How to force the use of the default insecure key?** On Windows, because "vagrant ssh" is not pratical to use, the typical workflow is to have a putty session for vagrant boxes. Having a newly generated key per box hinders this.

**Comment by isimmons** [comment] 2015-02-26 17:41
Hi, I have a problem with running laravel/homestead due to this automatic insertion of secure keys.

I should not be editing the vagrant file as it is part of the source for homestead. Somehow 'homestead ssh' works but is very slow so I would like to continue using plain old ssh from the cli
```
ssh vagrant@127.0.0.1 -p 2222
```
But now when I do this I get the following message.
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that the RSA host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
f4:4e:31:f6:f1:a7:bb:97:b3:e3:2b:ac:65:19:c0:e1.
Please contact your system administrator.
Add correct host key in /c/Users/lotus/.ssh/known_hosts to get rid of this message.
Offending key in /c/Users/lotus/.ssh/known_hosts:18
RSA host key for [127.0.0.1]:2222 has changed and you have requested strict checking.
Host key verification failed.
```
Where can I find the correct key to add to the known hosts file?

**Comment by gregorskii** [comment] 2015-03-03 18:57
It is in ~/.ssh/known_hosts

**Comment by ploxiln** [comment] 2015-03-03 19:13
This issue is not about `known_hosts`. vagrant does not automatically insert keys into known_hosts, what you're seeing is normal default ssh behavior regarding known_hosts.

For hostnames / ip addresses which you expect to change identity (new VM, new ssh host key generated inside the VM), you can use the ssh config options which vagrant does for "vagrant ssh":

```
[pierce@plo-pro dockerdev]$ vagrant ssh-config
...
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
...
```

**Comment by isimmons** [comment] 2015-03-04 15:57
Thanks for the reply but I'm not understanding. According to the message I get from using ssh the problem is that the correct host key is not in the known_hosts file.

So how do I get the correct host key so I can manually insert it into the known_hosts file?

vagrant ssh-config does not work because there is no vagrantfile. Even if I cd to the directory where the vagrant file exists "C:\Users\lotus\AppData\Roaming\Composer\vendor\laravel\homestead" I get the following message
```
The provider for this Vagrant-managed machine is reporting that it
is not yet ready for SSH. Depending on your provider this can carry
different meanings. Make sure your machine is created and running and
try again. Additionally, check the output of `vagrant status` to verify
that the machine is in the state that you expect. If you continue to
get this error message, please view the documentation for the provider
you're using.
``` 

I get the same message if I first do homestead up to start up the machine.

But I still don't see what vagrant ssh-config has to do with me using plain old ssh like 
```
ssh vagrant@127.0.0.1 -p 2222
```

**Comment by ploxiln** [comment] 2015-03-04 17:41
What you need to do now is *remove* the key for host "127.0.0.1" in your known_hosts. I wasn't suggesting using "vagrant ssh-config", just using the ssh config options which "vagrant ssh" uses,. I ran "vagrant ssh-config" to show how I knew of them. Those two options I pointed out cause ssh to not use known_hosts, which is appropriate in this case. You should research how to configure ssh (you'll probably want to edit `~/.ssh/config`) and how known_hosts is used.

**Comment by isimmons** [comment] 2015-03-07 19:21
Thanks @ploxiln . Sorry I misunderstood. I removed the local host entry and then when I used ssh again it added it back to the known_hosts file with the correct rsa key on the first time and now works as it should. Also 'homestead ssh' which calls 'vagrant ssh' still works so all is good. 

I agree that I need to research ssh config options but also think this should be added to documentation. Basically if  user has a basic default ssh setup using openssh (at least on Windows systems) the known_hosts file will be used by default and the current entry for 127.0.0.1 will be incorrect because vagrant changed it so that entry will need to be deleted and re-created again in order for plain old ssh connections to work.

**Comment by mitchellh** [comment] 2015-07-07 05:16
This should be fixed now! We now honor `private_key_path` and take that over the inserted key.

**Closed by mitchellh** 2015-07-07 05:16 UTC
Labels: core, documentation

**Comment by sethvargo** [comment] 2015-07-07 15:17
Since there is a lot of participation on this issue, I am going to lock the thread to prevent additional "issues" from being reported. If you are using Vagrant 1.7.3 and still have errors with the generated SSH private key, please open a new issue on the issue tracker. Thank you! :smile:
