### ISSUE TITLE
repetition of issue https://github.com/mitchellh/vagrant/issues/6754

### ISSUE THREAD

**Issue by stopsopa** [mitchellh/vagrant#7149] opened 2016-03-17 13:50 UTC
I would like to notice that it would be good thing to throw exception saying verbally what is necessary to properly work vagrant up in this case, for example:

"vagrant can't download xxxxx because you need to install Microsoft Visual C++ 2010 SP1 Redistributable Package (x86)"

i (i guess not only i) spent approximately 3 hours to find what is going on, it would be really helpful to have such exception.

**Comment by sethvargo** [comment] 2016-03-17 14:17
Hi @stopsopa 

Thank you for opening an issue. https://github.com/mitchellh/vagrant/issues/6754 is a duplicate of https://github.com/mitchellh/vagrant/issues/6852, which will be fixed in the next release. It's a bug in the installer, and Vagrant should just work under this situation. Thanks! :smile:

**Closed by sethvargo** 2016-03-17 14:17 UTC
