### ISSUE TITLE
New Vagrant New Virtualbox New cent\7 no ssh

### ISSUE THREAD

**Issue by athingisathing** [mitchellh/vagrant#7760] opened 2016-08-27 13:55 UTC
brew cask install vagrant --force
brew cask install virtualbox --force
vagrant box update --insecure --box  centos/7
vagrant init centos/7
vagrant up

you get 

`E, [2016-08-26T17:13:53.138230 #17073] ERROR -- net.ssh.authentication.session[814f4e40]: all authorization methods failed (tried none, publickey)

DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO ssh: SSH not ready: #<Vagrant::Errors::SSHAuthenticationFailed: SSH authentication failed! This is typically caused by the public/private
keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well.>
 INFO subprocess: Starting process: ["/usr/local/bin/VBoxManage", "showvminfo", "b3af67de-1ff8-41ea-9251-e3c28a3be008", "--machinereadable"]`

you also can not ssh -i .... into the box

but if you add

config.ssh.insert_key = false

it all works.

**Comment by sethvargo** [comment] 2016-08-29 14:58
Hi @athingisathing

Thank you for opening an issue, and sorry this is causing you problems. What version of Vagrant is getting installed from cask and what version of VirtualBox? 

There is a bug that is already fixed on master where SSH key replacement is broken. The fix, as you discovered, is to add `config.ssh.insert_key = false` in your Vagrantfile. We will be releasing a new Vagrant version this week, and we'll followup to ask you to confirm the fix.

/cc @chrisroberts

**Comment by athingisathing** [comment] 2016-08-29 15:13
Thanks.

Version 5.1.2 r108956

Vagrant 1.8.5

FYI

my issue is that when building a box based on the cent/7 I get in that one time with this fix, but once I reset the key's and vagrant package the resulting box can not be re used no matter what. 

Any idea's on what i might be missing on the base box?

**Comment by sethvargo** [comment] 2016-08-29 15:19
Hi there,

Sorry, but I'm not sure I follow. Could you please explain your steps in more detail? Please keep in mind that we have no context about your project or usage of Vagrant, so providing reproducible Vagrantfiles and commands are very helpful.

**Comment by athingisathing** [comment] 2016-08-29 15:39
Sure Thanks again...

We are using a highly modified version of beack to build puppet master .box, but taking that out of the equation we can simulate with the commands above plus a couple commands.

once you do this 

config.ssh.insert_key = false

and the box comes up you then change the machine reset the insecure_key settings and then use vagrant package to make a new .box.

When you try to then use that box with any vagrant file configuration it will not get past the ssh issue.

So basicly it is a dead.box build from that point on.

hopefully the new fix will also fix that.

Can I beta test :)

**Comment by sethvargo** [comment] 2016-08-29 15:51
Hi there,

> We are using a highly modified version of beaker to build puppet master .box

I don't know what Beaker is, and we don't have access to your puppet modules.

> once you do this

Once you do what? Where are you putting that? Can we see the rest of your Vagrantfile? Debug output? https://www.vagrantup.com/docs/other/debugging.html

> and the box comes up you then change the machine reset the insecure_key settings 

I'm not following. What are you doing here? Do you have some scripts or commands you are running?

**Comment by athingisathing** [comment] 2016-08-29 16:01
As i said we are doing something that is very complicated to explain but you dont need to know it to be able to reproduce the issue. 

The commands to reproduce are as follows.

brew cask install vagrant --force
brew cask install virtualbox --force
vagrant box update --insecure --box centos/7
vagrant init centos/7
change vagrant file 
config.ssh.insert_key = false
vagrant up
  modify box as needed
  reset vagrant insecure key files
vagrant package "BOXNAME"
  make new .box
  make new vagrant file referencing the new custom .box
vagrant up from the new file 
  with the insert_key = false
  and error as follow

E, [2016-08-26T17:13:53.138230 #17073] ERROR -- net.ssh.authentication.session[814f4e40]: all authorization methods failed (tried none, publickey)

DEBUG ssh: == Net-SSH connection debug-level log END ==
INFO ssh: SSH not ready: # keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well.>
INFO subprocess: Starting process: ["/usr/local/bin/VBoxManage", "showvminfo", "b3af67de-1ff8-41ea-9251-e3c28a3be008", "--machinereadable"]

Hopefully that is what you need.

**Comment by chrisroberts** [comment] 2016-10-04 16:56
I _believe_ that box generation may have ended up with an inserted insecure key. This should be fixed in the latest release. Can you confirm if it has fixed the issue you described? Thanks!

**Comment by chrisroberts** [comment] 2016-10-25 20:16
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2016-10-25 20:16 UTC
Labels: waiting-reply
