### ISSUE TITLE
Can't set Default VM's dir, also no VM's visible in VB gui. Linux Mint.

### ISSUE THREAD

**Issue by RomkaLTU** [mitchellh/vagrant#7856] opened 2016-10-03 05:23 UTC
### Vagrant version

Vagrant 1.8.6
### Host operating system

Linux Mint 18 Cinnamon
### Guest operating system

Ubuntu 14
### Vagrantfile

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.12"
    config.vm.hostname = "wplugins.dev"
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]

    # Optional NFS. Make sure to remove other synced_folder line too
    #config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }

end
```
### Expected behavior

VM's should be created under specified dir.
### Actual behavior

VM's creating in default root/VirtualBox Vm's dir.
### Steps to reproduce
1. Change default machines folder to something else.
2. Run vagrant up

Also I can't see created VM's in VB gui. It's empty even after vagrant up. 

Running: `sudo VBoxManage list vms`  nothing returned...

VirtualBox version 5.1.6r110634

**Comment by chrisroberts** [comment] 2016-12-09 15:32
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by chrisroberts** [comment] 2017-02-22 16:01
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2017-02-22 16:01 UTC
Labels: provider/virtualbox, waiting-reply
