### ISSUE TITLE
/sbin/ifup eth1 2> /dev/null on SUSE 13

### ISSUE THREAD

**Issue by lanox** [mitchellh/vagrant#5429] opened 2015-03-04 05:34 UTC
Hi 
I am getting above error on suse 13.2
Here is complete error.
```
==> suseagent: Attempting graceful shutdown of VM...
==> suseagent: Booting VM...
==> suseagent: Waiting for machine to boot. This may take a few minutes...
    suseagent: SSH address: 127.0.0.1:2200
    suseagent: SSH username: lpuljic
    suseagent: SSH auth method: private key
    suseagent: Warning: Connection timeout. Retrying...
    suseagent: Warning: Connection timeout. Retrying...
==> suseagent: Machine booted and ready!
==> suseagent: Checking for guest additions in VM...
==> suseagent: Setting hostname...
==> suseagent: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
/sbin/ifup eth1 2> /dev/null
Stdout from the command:

Stderr from the command:
```
 System info
```
openSUSE 13.2 (x86_64)
VERSION = 13.2
CODENAME = Harlequin
# /etc/SuSE-release is deprecated and will be removed in the future, use /etc/os-release instead
```
Vagrant version
```
vagrant --version
Vagrant 1.7.2
```
I have read other issues that where reported but they where all based on CentOS.
Also i have checked
```
ll /etc/udev/rules.d/
total 248
-rw-r--r-- 1 root root 193434 Oct 11 03:41 55-libsane.rules
-rw-r--r-- 1 root root  51180 Oct 11 03:41 56-sane-backends-autoconfig.rules
-rw-r--r-- 1 root root    134 Mar  4 16:20 60-vboxadd.rules
```
 and i do not have ```70-persistent-net.rule```
Also i have noticed that i have ```ifcfg-eth1``` with following content in the file
```
VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
BOOTPROTO='static'
IPADDR='192.168.0.4'
NETMASK='255.255.255.0'
DEVICE='eth1'
PEERDNS=no
STARTMODE='auto'
USERCONTROL='no'
#VAGRANT-END
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
BOOTPROTO='static'
IPADDR='192.168.0.4'
NETMASK='255.255.255.0'
DEVICE='eth1'
PEERDNS=no
STARTMODE='auto'
USERCONTROL='no'
#VAGRANT-END
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
BOOTPROTO='static'
IPADDR='192.168.0.4'
NETMASK='255.255.255.0'
DEVICE='eth1'
PEERDNS=no
STARTMODE='auto'
USERCONTROL='no'
#VAGRANT-END
```
hopefully all this info will help someone help me :)

thanks in advance

**Comment by lanox** [comment] 2015-03-05 03:07
any suggestion ?

**Comment by lanox** [comment] 2015-05-10 10:32
Does anyone actually look at this issues any more ?

**Comment by kaltokri** [comment] 2015-06-12 12:09
I've got the same problem with 'chef/opensuse-13.1' but only when I use
config.vm.network :private_network, ip: '192.168.50.15'

If I deactivate the private_network configuration line the problem doesn't occur.

Same configuration (with private_network!) but changed to centos works: 
config.vm.box = 'chef/centos-6.5'

And when I use 'webhippie/opensuse-13.2' it's working, too:
config.vm.box = 'webhippie/opensuse-13.2'

**Comment by SqiSch** [comment] 2015-06-23 11:22
Same issue here after doing a vagrant up --no-provision:

```
=> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifup eth1

Stdout from the command:



Stderr from the command:

stdin: is not a tty
/etc/network/interfaces:38: interface eth2 declared allow-auto twice
/sbin/ifup: couldn't read interfaces file "/etc/network/interfaces"

```

caused by double entries in the  /etc/network/interfaces
```
vagrant@install-server:~$ cat /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet dhcp
pre-up sleep 2
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth1
iface eth1 inet static
      address 10.4.0.5
      netmask 255.255.0.0
#VAGRANT-END

#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth2
iface eth2 inet static
      address 10.2.0.5
      netmask 255.255.0.0
#VAGRANT-END

#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth3
iface eth3 inet static
      address 192.168.56.16
      netmask 255.255.255.0
#VAGRANT-END

#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth2
iface eth2 inet static
      address 10.2.0.5
      netmask 255.255.0.0
#VAGRANT-END

#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth3
iface eth3 inet static
      address 192.168.56.16
      netmask 255.255.255.0
#VAGRANT-END

```

Vagrantfile:
```
...
config.vm.network :public_network, ip: "10.4.0.5",  :netmask => "255.255.0.0", :adapter => 2
  config.vm.network :private_network, ip: "10.2.0.5",   :netmask => "255.255.0.0",   :adapter => 3
  config.vm.network :private_network, ip: "192.168.56.16",            :netmask => "255.255.255.0", :adapter => 4
....
```

**Comment by vchrisb** [comment] 2015-06-29 19:00
for me it looks like that vagrant currently can't handle Predictable Network Interface Names for opensuse 13.
The first interface is configured with dhcp and therefore the ifcfg-xxx script doesn't have to be modified. While when using a privat_network, vagrant needs to create a proper ifcfg-xxx file. Vagrant is creating a file but not using the Predictable Network Interface Name but rather eth1, ifcfg-eth1. Therefore private_network configuration fails.
The basebox from webhippie fixed that by applying a kernel paramter to use the stick with the old naming scheme ethX. This can be accomplished by adding in the packer JSON file "net.ifnames=0 netdevice=eth0" to the boot_command.

**Comment by MesterJoda** [comment] 2015-07-01 12:44
Same problem here. I was hoping that this was resolved with Vagrant 1.6.2, and did a lot of gymnastics to no avail. This is quite a trouble for me. Family of OpenSuSE 13 is not new on the market, nor is Predictable Network Naming, nor is Vagrant unfamiliar with this issue. I'm really hoping that this is going to be resolved soon. I'm begging here, to be honest. Cheers

**Comment by lanox** [comment] 2015-07-05 09:12
yeah i was hoping to get some responds from hashicorp

**Comment by mitchellh** [comment] 2015-07-07 06:27
We'll take a look at this this week.

**Comment by lanox** [comment] 2015-07-07 11:10
@mitchellh thank you.

**Comment by MesterJoda** [comment] 2015-07-09 05:53
@mitchellh thank you.

**Comment by lanox** [comment] 2015-07-31 23:46
@mitchellh did you have a chance to look at this issue ? cheers mate.

**Comment by mitchellh** [comment] 2015-11-19 19:31
We made a lot of changes to suse networking in 1.8, can you please try that once it is released and report back? If the issue persists, please open a new issue.

**Closed by mitchellh** 2015-11-19 19:32 UTC
Labels: bug, guest/suse
