### ISSUE TITLE
Vagrant adding \\?\ to start of all shares

### ISSUE THREAD

**Issue by sharpn** [mitchellh/vagrant#5965] opened 2015-07-14 16:15 UTC
Whenever i try Vagrant up after upgrading to 1.4.3 all my synced folders are appended with \\\\?\\ which makes them unreadable by vitualbox.

I have tried this with both 4.3 and 5 and both end in the same result.

I am running a Windows 7 host and VM

**Comment by sethvargo** [comment] 2015-07-14 16:29
Hi @sharpn 

I am sorry you are having problems. Vagrant 1.4.3 is a very old version of Vagrant - the latest version of Vagrant is 1.7.3 and can be downloaded from https://vagrantup.com/downloads.html. Can you please try the newest release of Vagrant and, if the issue persists, share the complete Vagrantfile and output of the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html). Thanks! :smile:

**Comment by sharpn** [comment] 2015-07-14 16:30
Sorry i meant 1.7.3

**Comment by swagopopotamus** [comment] 2015-07-14 17:00
Also experiencing this issue on Windows 7 with Vagrant 1.7.3 
<img width="435" alt="capture" src="https://cloud.githubusercontent.com/assets/2365861/8679192/0aaa9410-2a0e-11e5-9d78-1bb0ddc8d95a.PNG">


Made a barebones version of my Vagrantfile and the issue persists.

```
Vagrant.configure(2) do |config|

  config.ssh.forward_agent = true

  config.vm.box = "centos6.6"
  config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box"

  config.omnibus.chef_version = '12.3.0'
end
```

**Comment by swagopopotamus** [comment] 2015-07-14 17:11
Debug log is too large, here is the relevant error
```
 INFO interface: error: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chown `id -u vagrant`:`id -g vagrant` /vagrant

Stdout from the command:



Stderr from the command:

chown: changing ownership of `/vagrant': Not a directory

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chown `id -u vagrant`:`id -g vagrant` /vagrant

Stdout from the command:



Stderr from the command:

chown: changing ownership of `/vagrant': Not a directory
 INFO interface: Machine: error-exit ["Vagrant::Errors::VagrantError", "The following SSH command responded with a non-zero exit status.\nVagrant assumes that this means the command failed!\n\nchown `id -u vagrant`:`id -g vagrant` /vagrant\n\nStdout from the command:\n\n\n\nStderr from the command:\n\nchown: changing ownership of `/vagrant': Not a directory\n"]
```

**Comment by sethvargo** [comment] 2015-07-14 17:31
Hi @sharpn 

That looks like a duplicate of https://github.com/mitchellh/vagrant/issues/5933, can you confirm?

**Comment by sharpn** [comment] 2015-07-14 18:54
@sethvargo looks like its the same issue yea.

**Comment by sethvargo** [comment] 2015-07-14 18:56
Cool @sharpn 

I am going to close this as a duplicate if that's okay. Trying to keep all the 1.7.4 stuff in one place :smile:. Thanks!

**Closed by sethvargo** 2015-07-14 18:56 UTC
Labels: waiting-reply
