### ISSUE TITLE
Shell provisioner is run twice

### ISSUE THREAD

**Issue by felixnutella** [mitchellh/vagrant#5518] opened 2015-03-23 16:56 UTC
Trying the example for multiple provisioners under the http://docs.vagrantup.com/v2/provisioning/basic_usage.html causes all provisioners to be run twice. 

My Vagrantfile looks like this:

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.provision "shell", inline: "echo foo"
  config.vm.define "web" do |web|
    web.vm.provision "shell", inline: "echo bar"
  end
  config.vm.provision "shell", inline: "echo baz"
end
```

And the output looks like this:

```text
==> web: Running provisioner: shell...
    web: Running: inline script
==> web: stdin: is not a tty
==> web: foo
==> web: Running provisioner: shell...
    web: Running: inline script
==> web: stdin: is not a tty
==> web: baz
==> web: Running provisioner: shell...
    web: Running: inline script
==> web: stdin: is not a tty
==> web: foo
==> web: Running provisioner: shell...
    web: Running: inline script
==> web: stdin: is not a tty
==> web: baz
==> web: Running provisioner: shell...
    web: Running: inline script
==> web: stdin: is not a tty
==> web: bar
==> web: Running provisioner: shell...
    web: Running: inline script
==> web: stdin: is not a tty
==> web: bar
```

Anyone that can shed some light on that problem ??

**Comment by sethvargo** [comment] 2015-03-23 17:06
Hi @felixnutella 

Which command are you running? Can you provide the [debug output](http://docs.vagrantup.com/v2/other/debugging.html).

**Comment by felixnutella** [comment] 2015-03-23 18:51
Yup - I added a gist here -> https://gist.github.com/felixnutella/7b930a30e70339fb44c5#file-vagrantdebug1

The command I'm running is a simple vagrant up in same directory as the Vagrantfile

**Comment by sethvargo** [comment] 2015-05-30 17:43
Hi @felixnutella 

I cannot reproduce this issue with the latest version of Vagrant:

```
==> web: Enabling and configuring shared folders...
    web: -- /Users/sethvargo/Desktop/test: /vagrant
==> web: Running provisioner: shell...
    web: Running: inline script
==> web: stdin: is not a tty
==> web: foo
==> web: Running provisioner: shell...
    web: Running: inline script
==> web: stdin: is not a tty
==> web: baz
==> web: Running provisioner: shell...
    web: Running: inline script
==> web: stdin: is not a tty
==> web: bar
```

Are you able to share any additional information?

**Comment by manifestonosuke** [comment] 2015-06-10 10:26
I got the same problem. 
Here is my Vagrantfile :

>Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #config.vm.provision "shell", inline: "yum install -y salt-master"
  config.vm.provision "shell", inline: "echo '#{iprange}#{supip}    salt' >> /etc/hosts "
  config.vm.provision "shell", inline: "echo done #{supname}"
  config.vm.define :"#{supname}" do |this|
    this.vm.box = "#{basebox}"
    this.vm.hostname = "#{supname}"
    this.vm.network "private_network", ip: "#{iprange}.99", :netmask => "255.255.255.0"
    this.vm.network "forwarded_port", guest:22, host:"#{pref}01".to_i, id:"ssh"
    this.vm.network "forwarded_port", guest:3080, host:"#{pref}02".to_i, id:"dsup"
    this.vm.synced_folder "/data/soft/", "/vagrant"
    this.vm.provider "virtualbox" do |v|
      v.memory = supmem
    end
  end
end

I tried different setup but always run twice 
>==> sup: Running provisioner: shell...
    sup: Running: inline script
==> sup: Running provisioner: shell...
    sup: Running: inline script
==> sup: done sup
==> sup: Running provisioner: shell...
    sup: Running: inline script
==> sup: Running provisioner: shell...
    sup: Running: inline script
==> sup: done sup

Not critical but annoying (running vagrant 1.7.2 on centos7)

**Comment by mitchellh** [comment] 2015-07-07 06:18
This should be fixed

**Closed by mitchellh** 2015-07-07 06:18 UTC
Labels: waiting-reply
