### ISSUE TITLE
Vagrant runs customization multiple times on the same machine

### ISSUE THREAD

**Issue by coderdba** [mitchellh/vagrant#7504] opened 2016-06-20 17:04 UTC
VAGRANTFILE:  
(this is from Seth Vargo's suggestion in https://github.com/mitchellh/vagrant/issues/5778)

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "xyz"

  config.vm.provider "virtualbox" do |vb|
    puts ("INFO - in config.vm.provider")
    vb.memory = 512
    vb.cpus = 1
  end

  3.times do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.network :private_network, type: "dhcp"
      node.vm.provision "shell", inline: "echo GATHER_IPS $(hostname -i)"
    end
  end
end
```

MESSAGES:  (I expect the customization to run at the most three times for 3 nodes being created)

```
$ vagrant up
INFO - in config.vm.provider
INFO - in config.vm.provider
INFO - in config.vm.provider
INFO - in config.vm.provider
INFO - in config.vm.provider
INFO - in config.vm.provider
INFO - in config.vm.provider
INFO - in config.vm.provider
INFO - in config.vm.provider
INFO - in config.vm.provider
Bringing machine 'node-0' up with 'virtualbox' provider...
Bringing machine 'node-1' up with 'virtualbox' provider...
Bringing machine 'node-2' up with 'virtualbox' provider...
==> node-0: Box 'xyz' could not be found. Attempting to find and install...
    node-0: Box Provider: virtualbox
    node-0: Box Version: >= 0
==> node-0: Waiting f
oG:\cookbooks\multinode>r cleanup before exiting...
```

**Comment by sethvargo** [comment] 2016-06-20 18:07
Hi @coderdba 

Thank you for opening an issue. The Vagrantfile is _evaluated_ multiple times as Ruby. So throwing a `puts` statement is going to appear each time the Vagrantfile is evaluated and merged. There's a fundamental difference between "evaluating" (reading) and actually making calls to vbox. 

Here is a Vagrantfile and the output. You can see that the provisioner is run exactly once on all machines:

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.provider "virtualbox" do |vb|
    puts ("INFO - in config.vm.provider")
    vb.memory = 512
    vb.cpus = 1
  end

  3.times do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.network :private_network, type: "dhcp"
      node.vm.provision "shell", inline: "echo 'I am node-#{i}'"
    end
  end
end
```

```
INFO - in config.vm.provider
INFO - in config.vm.provider
INFO - in config.vm.provider
INFO - in config.vm.provider
INFO - in config.vm.provider
INFO - in config.vm.provider
INFO - in config.vm.provider
Bringing machine 'node-0' up with 'virtualbox' provider...
Bringing machine 'node-1' up with 'virtualbox' provider...
Bringing machine 'node-2' up with 'virtualbox' provider...
==> node-0: Importing base box 'hashicorp/precise64'...
==> node-0: Matching MAC address for NAT networking...
==> node-0: Checking if box 'hashicorp/precise64' is up to date...
==> node-0: Setting the name of the VM: foo_node-0_1466445929429_40490
==> node-0: Clearing any previously set network interfaces...
==> node-0: Preparing network interfaces based on configuration...
    node-0: Adapter 1: nat
    node-0: Adapter 2: hostonly
==> node-0: Forwarding ports...
    node-0: 22 (guest) => 2222 (host) (adapter 1)
==> node-0: Running 'pre-boot' VM customizations...
==> node-0: Booting VM...
==> node-0: Waiting for machine to boot. This may take a few minutes...
    node-0: SSH address: 127.0.0.1:2222
    node-0: SSH username: vagrant
    node-0: SSH auth method: private key
    node-0:
    node-0: Vagrant insecure key detected. Vagrant will automatically replace
    node-0: this with a newly generated keypair for better security.
    node-0:
    node-0: Inserting generated public key within guest...
    node-0: Removing insecure key from the guest if it's present...
    node-0: Key inserted! Disconnecting and reconnecting using new SSH key...
==> node-0: Machine booted and ready!
==> node-0: Checking for guest additions in VM...
    node-0: The guest additions on this VM do not match the installed version of
    node-0: VirtualBox! In most cases this is fine, but in rare cases it can
    node-0: prevent things such as shared folders from working properly. If you see
    node-0: shared folder errors, please make sure the guest additions within the
    node-0: virtual machine match the version of VirtualBox you have installed on
    node-0: your host and reload your VM.
    node-0:
    node-0: Guest Additions Version: 4.2.0
    node-0: VirtualBox Version: 5.0
==> node-0: Configuring and enabling network interfaces...
==> node-0: Mounting shared folders...
    node-0: /vagrant => /Users/sethvargo/Desktop/test/foo
==> node-0: Running provisioner: shell...
    node-0: Running: inline script
==> node-0: stdin: is not a tty
==> node-0: I am node-0
==> node-1: Importing base box 'hashicorp/precise64'...
==> node-1: Matching MAC address for NAT networking...
==> node-1: Checking if box 'hashicorp/precise64' is up to date...
==> node-1: Setting the name of the VM: foo_node-1_1466445948242_21608
==> node-1: Fixed port collision for 22 => 2222. Now on port 2200.
==> node-1: Clearing any previously set network interfaces...
==> node-1: Preparing network interfaces based on configuration...
    node-1: Adapter 1: nat
    node-1: Adapter 2: hostonly
==> node-1: Forwarding ports...
    node-1: 22 (guest) => 2200 (host) (adapter 1)
==> node-1: Running 'pre-boot' VM customizations...
==> node-1: Booting VM...
==> node-1: Waiting for machine to boot. This may take a few minutes...
    node-1: SSH address: 127.0.0.1:2200
    node-1: SSH username: vagrant
    node-1: SSH auth method: private key
    node-1:
    node-1: Vagrant insecure key detected. Vagrant will automatically replace
    node-1: this with a newly generated keypair for better security.
    node-1:
    node-1: Inserting generated public key within guest...
    node-1: Removing insecure key from the guest if it's present...
    node-1: Key inserted! Disconnecting and reconnecting using new SSH key...
==> node-1: Machine booted and ready!
==> node-1: Checking for guest additions in VM...
    node-1: The guest additions on this VM do not match the installed version of
    node-1: VirtualBox! In most cases this is fine, but in rare cases it can
    node-1: prevent things such as shared folders from working properly. If you see
    node-1: shared folder errors, please make sure the guest additions within the
    node-1: virtual machine match the version of VirtualBox you have installed on
    node-1: your host and reload your VM.
    node-1:
    node-1: Guest Additions Version: 4.2.0
    node-1: VirtualBox Version: 5.0
==> node-1: Configuring and enabling network interfaces...
==> node-1: Mounting shared folders...
    node-1: /vagrant => /Users/sethvargo/Desktop/test/foo
==> node-1: Running provisioner: shell...
    node-1: Running: inline script
==> node-1: stdin: is not a tty
==> node-1: I am node-1
==> node-2: Importing base box 'hashicorp/precise64'...
==> node-2: Matching MAC address for NAT networking...
==> node-2: Checking if box 'hashicorp/precise64' is up to date...
==> node-2: Setting the name of the VM: foo_node-2_1466445967077_14958
==> node-2: Fixed port collision for 22 => 2222. Now on port 2201.
==> node-2: Clearing any previously set network interfaces...
==> node-2: Preparing network interfaces based on configuration...
    node-2: Adapter 1: nat
    node-2: Adapter 2: hostonly
==> node-2: Forwarding ports...
    node-2: 22 (guest) => 2201 (host) (adapter 1)
==> node-2: Running 'pre-boot' VM customizations...
==> node-2: Booting VM...
==> node-2: Waiting for machine to boot. This may take a few minutes...
    node-2: SSH address: 127.0.0.1:2201
    node-2: SSH username: vagrant
    node-2: SSH auth method: private key
    node-2:
    node-2: Vagrant insecure key detected. Vagrant will automatically replace
    node-2: this with a newly generated keypair for better security.
    node-2:
    node-2: Inserting generated public key within guest...
    node-2: Removing insecure key from the guest if it's present...
    node-2: Key inserted! Disconnecting and reconnecting using new SSH key...
==> node-2: Machine booted and ready!
==> node-2: Checking for guest additions in VM...
    node-2: The guest additions on this VM do not match the installed version of
    node-2: VirtualBox! In most cases this is fine, but in rare cases it can
    node-2: prevent things such as shared folders from working properly. If you see
    node-2: shared folder errors, please make sure the guest additions within the
    node-2: virtual machine match the version of VirtualBox you have installed on
    node-2: your host and reload your VM.
    node-2:
    node-2: Guest Additions Version: 4.2.0
    node-2: VirtualBox Version: 5.0
==> node-2: Configuring and enabling network interfaces...
==> node-2: Mounting shared folders...
    node-2: /vagrant => /Users/sethvargo/Desktop/test/foo
==> node-2: Running provisioner: shell...
    node-2: Running: inline script
==> node-2: stdin: is not a tty
==> node-2: I am node-2
```

This is not a bug in Vagrant. The Vagrantfile is evaluated as Ruby, and it's evaluated multiple times. You can read more about Vagrantfile loading and merging here: https://www.vagrantup.com/docs/vagrantfile/

**Closed by sethvargo** 2016-06-20 18:07 UTC

**Comment by coderdba** [comment] 2016-06-21 13:26
Seth,  thank you!!  

It worked as you explained.
