### ISSUE TITLE
Arch network device is not enabled by guest capabilities

### ISSUE THREAD

**Issue by kampka** [mitchellh/vagrant#5737] opened 2015-05-19 20:31 UTC
The Archlinux guest capabilities create a new configuration for networking and start it, but is it not enabled, meaning it is not activated again when the machine restarts (halt-up, reboot, etc.).
Running `vagrant up --provision` will also not restart the device, meaning it will stay unconfigured until the user enables and restarts it manually each time the machine boots.
IMO this is unexpected behavior, especially since other guest capabilities behave differently. Debian and Ubuntu for example do not suffer from this.
Therefore, the capabilities plugin should take care of enabling the new device after configuring it.

**Comment by sethvargo** [comment] 2015-05-31 00:47
Hi there,

I am going to close this as a duplicate of https://github.com/mitchellh/vagrant/issues/5751 even though this issue was reported first. 5751 has more debugging output and information. Thank you for reporting!

**Comment by kampka** [comment] 2015-05-31 07:01
Hi,

sorry, but this does not describe an issue with arch hosts but with arch guests.
It's also in no way related to any virtualizer.
Therefore the two issues are not related, please reopen this issue.

**Comment by kampka** [comment] 2015-07-01 06:42
@sethvargo Since the issue is unlikely to be resolved while being closed I'll ask again: Please reopen the issue, your reason for closing it does not apply. 
Thank you.

**Comment by sethvargo** [comment] 2015-07-01 14:20
Hi @kampka 

Can you please provide a complete Vagrantfile as well as the debug output in a GitHub gist?

**Comment by kampka** [comment] 2015-07-01 20:06
I'll do you one better, the pull request shows how this could be fixed, but I am not fluent enough with the life cycle of network devices in vagrant to argue whether it is sufficient or in the right place.

**Comment by mitchellh** [comment] 2015-11-19 19:39
Done

**Closed by mitchellh** 2015-11-19 19:39 UTC
Labels: bug, guest/arch
