### ISSUE TITLE
cannot access virtualbox in vagrant with ssh

### ISSUE THREAD

**Issue by oska874** [mitchellh/vagrant#6044] opened 2015-07-28 07:57 UTC
I tried to package a clean box with clean virtualbox images as below:
1. install ubuntu in virtualbox
2. add user "vagrant" with password "VAGRANT"
3. vagrant package --base ubuntu
then use it in vagrant as below
1. vagrant box add vag_test ubuntu.box
2. vagrant init vag_test
3. vagrant up

```
then the erros occurs:
==> default: Importing base box 'sdk'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: sdk_default_1438069640418_90289
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
```
so I stopped and try to use "vagrant ssh",this is ok,shows as below:

```
vagrant ssh
vagrant@127.0.0.1's password:<typed the password>
Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.16.0-30-generic i686)
```

I don't know which procedure is wrong.

**Comment by doctapp** [comment] 2015-07-28 11:25
This one is linked to #5186 which shows the same problems using Vagrant 1.7.4 and VirtualBox 5.0

**Comment by sethvargo** [comment] 2015-08-06 20:20
Duplicate of #5186

**Closed by sethvargo** 2015-08-06 20:20 UTC
