### ISSUE TITLE
Unexpected error occurred - unexpected response

### ISSUE THREAD

**Issue by kevinburke** [mitchellh/vagrant#4985] opened 2014-12-16 00:28 UTC
Here's a stack trace: 

```
unexpected response  (#<Net::SSH::Packet:0x000001010ceea8 @named_elements={}, @content="", @position=0, @type=nil>)

/opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:462:in `dispatch_incoming_packets'
/opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:221:in `preprocess'
/opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
/opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
/opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
/opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
/opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:269:in `wait'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/communicators/ssh/communicator.rb:576:in `shell_execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/communicators/ssh/communicator.rb:215:in `block in execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/communicators/ssh/communicator.rb:312:in `connect'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/communicators/ssh/communicator.rb:209:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/docker/executor/vagrant.rb:32:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/docker/driver.rb:155:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/docker/driver.rb:81:in `running?'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/docker/driver.rb:61:in `state'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/docker/provider.rb:156:in `state'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/docker/provider.rb:134:in `ssh_info'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:405:in `ssh_info'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/docker/communicator.rb:135:in `container_ssh_command'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/docker/communicator.rb:28:in `ready?'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/plugin/v2/communicator.rb:61:in `block in wait_for_ready'
/opt/vagrant/embedded/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/plugin/v2/communicator.rb:59:in `wait_for_ready'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'
```

I booted the Vagrant Ubuntu VM + 3 docker images, restarted my laptop, and then tried running "vagrant up"

The relevant Vagrantfile section:

```
  config.vm.define "api" do |v|
    v.vm.provider "docker" do |d|
      d.build_dir = "."
      d.name = "api"
      d.has_ssh = true
      d.remains_running = true
      d.link "db:db"
      d.link "redis:redis"
      d.ports = ["1337:1337"]
      d.volumes = ["/opt/api:/opt/api"]
    end

    v.ssh.username = "root"
    v.ssh.private_key_path = "./docker/keys/insecure_key"
  end

**Comment by mitchellh** [comment] 2015-01-05 19:06
This is a dupe of #5027

**Closed by mitchellh** 2015-01-05 19:06 UTC
