### ISSUE TITLE
Vagrant/Ansible reruns the playbook.

### ISSUE THREAD

**Issue by dheerajchand** [mitchellh/vagrant#8294] opened 2017-02-19 06:56 UTC
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version

```╭─ OSX  L 1.81  ~/Doc…nts/Pro…nal/Mau…noa/Code/transaction_simulat  00:18  19.02.17 
╰─ vagrant -v
Vagrant 1.8.6
```

### Host operating system

`Mac OS Mavericks`
### Guest operating system

`Ubuntu 16.04`

### Vagrantfile
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provider :virtualbox do |v|
    host = RbConfig::CONFIG['host_os']
    mem = 8192
    v.customize ["modifyvm", :id, "--memory", mem]

    config.vm.network :private_network, ip: "192.168.33.10"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 8080, host:8081
    config.ssh.forward_x11 = true

    config.vm.hostname = "vagrant-gisvm"
    config.vm.synced_folder ".", "/vagrant",
    owner: "vagrant", group: "www-data"

   config.vm.provision "ansible" do |ansible|
     ansible.playbook = "ansible/deployment/site.yml"
     ansible.verbose = "v"
   end
 end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/dheerajchand/40c8daae8fb34bdbe0b5355f5fd48cd6

### Expected behavior

The playbook should run once through.

### Actual behavior

THe playbook runs _twice_ and causes errors in the machine's Python environment because of it.
### Steps to reproduce

I wish I knew, this seems almost stochastic.

**Comment by gildegoma** [comment] 2017-02-19 11:25
Thank you @dheerajchand for reporting this issue. 

Everything looks good in your `Vagrantfile` example, and I can't reproduce the described problem (`ansible-playbook` executed _twice_) with Vagrant 1.9.1 (on macOS Sierra).

>[...] this seems almost stochastic.

Do you mean that you can't systematically produce/observe the problem ? How many times did you encounter the problem?

Since your use case is pretty standard, I don't think we're hitting a bug in Vagrant, and will close it for now. Though, I'm ready to reopen if you bring more details that can help to identify the cause of this misbehaviour. Thanks for your understanding!

**Closed by gildegoma** 2017-02-19 11:25 UTC
