### ISSUE TITLE
Vagrant stops working after upgrading to Mac OS X El Capitan beta

### ISSUE THREAD

**Issue by rtorcato** [mitchellh/vagrant#5810] opened 2015-06-09 15:10 UTC
i tried uninstalling vagrant and installing but get same result. No errors on

vagrant: command not found

**Comment by sethvargo** [comment] 2015-06-09 15:20
Closing as a duplicate of https://github.com/mitchellh/vagrant/issues/5807

**Closed by sethvargo** 2015-06-09 15:20 UTC
