### ISSUE TITLE
Vagrant up with a second machine clobbers existing port forwardings on an already up machine

### ISSUE THREAD

**Issue by dragon788** [mitchellh/vagrant#5602] opened 2015-04-16 20:41 UTC
I have a Vagrantfile in my projects directory. I do a 'vagrant up' and it configures 3 port forwards plus maps ssh to 22 on my host.

I go into my projects/hacks directory and using a different Vagrantfile (with no mappings) I do a 'vagrant up' and when I try to access the ports on my first VM, they are inaccessible. The only port mapping showing up is the 2222 host to 22 guest for the second VM.

They both share a common Vagrantfile in my .vagrant.d directory that provisions some things using some scripts in .vagrant.d/scripts, but that is the ONLY thing that they have in common.

**Comment by sethvargo** [comment] 2015-05-31 00:54
Hi @dragon788 

Can you please share the complete `Vagrantfile` as well as the output of the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html)? Thanks!

**Comment by mitchellh** [comment] 2015-07-07 06:05
I can't reproduce this with basic scripts. A repro would be great. Closing until then since it has been over a month.

**Comment by dragon788** [comment] 2015-07-07 15:38
Sorry about the delay, got distracted by some other fire during our Vagrant+VMware rollout.

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Ensure that VMWare Tools recompiles kernel modules
# when we update the linux images
$fix_vmware_tools_script = <<SCRIPT
sed -i.bak 's/answer AUTO_KMODS_ENABLED_ANSWER no/answer AUTO_KMODS_ENABLED_ANSWER yes/g' /etc/vmware-tools/locations
sed -i.bak 's/answer AUTO_KMODS_ENABLED no/answer AUTO_KMODS_ENABLED yes/g' /etc/vmware-tools/locations
SCRIPT

# You can comment out a port mapping by putting a # at the beginning of the line
# The port mappings are in guest port (vm) => host port order
# The two ports don't always need to match, you may use an alternate on either

UDP_PORTS_LIST={
    "1508" => 1508,
	"1597" => 1597,
	"1598" => 1598,
	"1599" => 1599,
	"1600" => 1600,
	"1601" => 1601,
	"1602" => 1602,
	"2002" => 2002,
	"2004" => 2004,
	"2006" => 2006,
	"2008" => 2008,
	"5050" => 5050,
	"5051" => 5051,
	"6060" => 6060,
	"9000" => 9000,
	"10000" => 10000,
    # Icecream Begin # https://github.com/icecc/icecream
    "8765" => 8765,
    # Icecream End #
    # Custom Mappings Begin #
    # "guest" => host, # Don't forget the comma
    # Custom Mappings End #
}

TCP_PORTS_LIST={
    "2002" => 2002,
    "8000" => 8000,
    "8080" => 8080,
    # Icecream Begin # https://github.com/icecc/icecream
    "8765" => 8765,
    "8766" => 8766,
    "10245" => 10245,
    # Icecream End #
    # Custom Mappings Begin #
    # "guest" => host, # Don't forget the comma
    # Custom Mappings End #
}

# Vagrantfile API/syntax version. Don"t touch unless you know what you"re doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "trusty64"
  config.vm.box_url = "http://artifactory/vagrant/trusty/metadata.json"
  config.vm.box_check_update = false
  config.vm.post_up_message = "
    This system is provisioned via Salt Configuration Management
    "
  
  config.vm.network :forwarded_port, guest: 22, host: 22, id: "ssh"

  UDP_PORTS_LIST.each do |guest, host|
    config.vm.network "forwarded_port", guest: "#{guest}", host: "#{host}", protocol: "udp"
  end
  TCP_PORTS_LIST.each do |guest, host|
    config.vm.network "forwarded_port", guest: "#{guest}", host: "#{host}", protocol: "tcp"
  end
  
  config.vm.provision "shell", inline: $fix_vmware_tools_script
  config.vm.provider "vmware_fusion" do |vmf|
      vmf.gui = true
  end
  config.vm.provider "vmware_workstation" do |vmw|
      vmw.gui = true
  end
end

**Comment by dragon788** [comment] 2015-07-07 19:51
So when I up a VM using this Vagrantfile, and then up a second copy in another folder, this apparently "breaks" the port in use detection of Vagrant, as it replaces or simply wipes out the existing port mappings.

Note I typically do my vagrant stuff in Babun (cygwin shell) but in this case I did it through cmd.exe and only used Babun for grepping the port mappings (below).

```
{ ~ }  » grep -A1000 "# VAGRANT-BEGIN"  C:/ProgramData/VMware/vmnetnat.conf | grep -B1000 "# VAGRANT-END" | grep -v -P "VAGRANT"
22 = 10.66.166.132:22
2002 = 10.66.166.132:2002
8000 = 10.66.166.132:8000
8080 = 10.66.166.132:8080
8765 = 10.66.166.132:8765
8766 = 10.66.166.132:8766
10245 = 10.66.166.132:10245

[incomingudp]
# UDP port forwarding example
#6000 = 192.168.27.128:6001
1508 = 10.66.166.132:1508
1597 = 10.66.166.132:1597
1598 = 10.66.166.132:1598
1599 = 10.66.166.132:1599
1600 = 10.66.166.132:1600
1601 = 10.66.166.132:1601
1602 = 10.66.166.132:1602
2002 = 10.66.166.132:2002
2004 = 10.66.166.132:2004
2006 = 10.66.166.132:2006
2008 = 10.66.166.132:2008
5050 = 10.66.166.132:5050
5051 = 10.66.166.132:5051
6060 = 10.66.166.132:6060
9000 = 10.66.166.132:9000
10000 = 10.66.166.132:10000
8765 = 10.66.166.132:8765
{ ~ }  » grep -A1000 "# VAGRANT-BEGIN"  C:/ProgramData/VMware/vmnetnat.conf | grep -B1000 "# VAGRANT-END" | grep -v -P "VAGRANT"
22 = 10.66.166.128:22
2002 = 10.66.166.128:2002
8000 = 10.66.166.128:8000
8080 = 10.66.166.128:8080
8765 = 10.66.166.128:8765
8766 = 10.66.166.128:8766
10245 = 10.66.166.128:10245

[incomingudp]
# UDP port forwarding example
#6000 = 192.168.27.128:6001
1508 = 10.66.166.128:1508
1597 = 10.66.166.128:1597
1598 = 10.66.166.128:1598
1599 = 10.66.166.128:1599
1600 = 10.66.166.128:1600
1601 = 10.66.166.128:1601
1602 = 10.66.166.128:1602
2002 = 10.66.166.128:2002
2004 = 10.66.166.128:2004
2006 = 10.66.166.128:2006
2008 = 10.66.166.128:2008
5050 = 10.66.166.128:5050
5051 = 10.66.166.128:5051
6060 = 10.66.166.128:6060
9000 = 10.66.166.128:9000
10000 = 10.66.166.128:10000
8765 = 10.66.166.128:8765
{ ~ }  »
```

**Comment by bdaniel7** [comment] 2016-01-24 15:32
I think I'm having the same problem, using Virtualbox as provider:
(A modified Vagrantfile from https://github.com/rancher/os-vagrant/blob/master/Vagrantfile)

$number_of_nodes = 4
(1..$number_of_nodes).each do |i|
    hostname = "rancher-%02d" % i

    config.vm.define hostname do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.memory = $vm_mem
            vb.gui = $vb_gui
        end

     ip = "172.19.8.#{i+100}"
     node.vm.network "private_network", ip: ip
     node.vm.hostname = hostname
     node.vm.network "forwarded_port", guest: 500, host: 500, protocol: "udp", host_ip: "127.0.0.1"
     node.vm.network "forwarded_port", guest: 4500, host: 4500, protocol: "udp", host_ip: "127.0.0.1"
     node.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
     node.vm.network "forwarded_port", guest: 27017, host: 27017, host_ip: "127.0.0.1"
     node.vm.network "forwarded_port", guest: 5222, host: 5222, host_ip: "127.0.0.1"
  end
end

But then I can add the same port to the forwarding in the Network properties of the NAT adapter of each VM in VirtualBox.

**Comment by kylemacfarlane** [comment] 2016-03-23 20:13
I saw this too when researching #5838 and I think it's the same bug that hyphens in the path to the Vagrantfile seem to corrupt `vmnetnat.conf`.

**Comment by chrisroberts** [comment] 2016-08-25 18:11
Just leaving a note to confirm this is reproducible, though I'm still working through making it _consistently_ reproducible.

**Comment by dragon788** [comment] 2016-08-25 21:53
I'm not currently using the same setup I was when I discovered this, but I recall that consistently around the same time when we had an issue, the vmnetnat.conf would occasionally end up with corruption that caused repeating port blocks that would wipe out the entire UDP section and create multiple TCP sections.

**Comment by kylemacfarlane** [comment] 2016-08-25 22:04
@dragon788 That's the same problem I saw with #5838. Did you by any chance have hyphens in the paths to any of your Vagrantfiles?

I found that vagrant uping a Vagrantfile with a hyphen in its path would >50% of the time (as @chrisroberts says it's not consistent) corrupt vmnetnat.conf and play havoc with ports on all vagrant machines. Removing hyphens from all my paths has resolved the issue for me for the last six months.

However I've found that since the Windows 10 Anniversary Update my forwarded ports are often lost after resuming from sleep and I have to reload the machines. Don't have a solution for that yet.

**Comment by dragon788** [comment] 2016-08-25 22:09
We were running on Windows 7 with VMware Workstation 10 and Vagrant 1.7.2/1.7.4. I don't think we intentionally put hyphens in the path, but I know for a period of time Vagrant itself was using the hyphen when adding the default VMware Shared folder as `-vagrant` due to some limitation that was eventually worked around. I wonder if that has anything to do with it?

I really think the problem is a race condition somewhere in the ruby calls that was exacerbated by some of the magic tricks we did in our Vagrantfile with loops, so Vagrant was trying to modify the VMX and vmnetnat.conf files and if Ruby hiccuped or was killed too soon bad things ensued, and it takes a full reset of the VMware network stack to fix it.

**Comment by dragon788** [comment] 2016-08-25 22:13
Another thought that just struck me, how many folks here are using Git(Hub) for Windows and/or Git Bash on their systems, and did you allow it to add the executables to the system path? I believe there are versions of at least git and ssh, and if it is prepending itself to the path, if there is a ruby.exe or anything else that Vagrant is looking for, it could be finding the wrong one if it's not a hardcoded path.

**Comment by chrisroberts** [comment] 2016-09-15 18:42
Hi. The latest release of the vmware plugin includes a fix that should resolve this issue:

https://github.com/hashicorp/vagrant-plugin-changelog/blob/master/vagrant-vmware-changelog.md#4011-august-29-2016

If the issue persists after updating, please let me know. Thanks!

**Comment by chrisroberts** [comment] 2016-09-28 12:56
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2016-09-28 12:56 UTC
Labels: bug, host/windows, provider/vmware

**Comment by zoff99** [comment] 2016-09-28 13:01
i don't understand. what do i have to update?

i have sort of the same issues on ubuntu 14.04
when running more than 1 vagrant at the same time, it seems the machines mix up the ports, and nothing works correctly. only when i run just 1 at a time, all works, without any config change

**Comment by kylemacfarlane** [comment] 2016-09-28 13:04
It seems fixed to me. I upgraded to VMWare 12.5, Vagrant 1.8.5, and vagrant-plugin 4.0.11 and haven't seen the hyphen related problem since.

**Comment by zoff99** [comment] 2016-09-28 13:25
what excatly is the vagrant plugin?
i have installed this on ubuntu:
```
vagrant/now 1:1.8.5 amd64 [installed,local]
virtualbox/trusty-updates,trusty-security,now 4.3.36-dfsg-1+deb8u1ubuntu1.14.04.1 amd64 [installed]
virtualbox-dkms/trusty-updates,trusty-security,now 4.3.36-dfsg-1+deb8u1ubuntu1.14.04.1 all [installed,automatic]
virtualbox-qt/trusty-updates,trusty-security,now 4.3.36-dfsg-1+deb8u1ubuntu1.14.04.1 amd64 [installed,automatic]
```

**Comment by kylemacfarlane** [comment] 2016-09-28 13:35
@zoff99 This ticket is about VMWare which requires this plugin: https://www.vagrantup.com/vmware/

**Comment by chrisroberts** [comment] 2016-09-28 15:03
@zoff99 Hey, if you're experiencing a related problem with virtual box, please open a new issue and provide all the requested details and I'll have a closer look. Thanks!

**Comment by zoff99** [comment] 2016-09-28 16:17
i did, thanks
