### ISSUE TITLE
CURL need Microsoft Visual C++ 2010 Redistributable Package (x86) 

### ISSUE THREAD

**Issue by rrzaripov** [mitchellh/vagrant#7099] opened 2016-03-04 13:05 UTC
After updating to 1.8.1 version, boxes not downloaded from remote boxes hub. 

### Vagrant version
1.8.1

### Host operating system
Windows 7 Professional x64 

### Guest operating system
Any 

### Actual behavior
Downloading metadata failed with error:

```
==> pacs: Box file was not detected as metadata. Adding it directly...
You specified a box version constraint with a direct box file
path. Box version constraints only work with boxes from Vagrant
Cloud or a custom box host. Please remove the version constraint
and try again.
```

In [debug](https://gist.githubusercontent.com/rrzaripov/ad75fb61583ae419198b/raw/6327d94e2d67fac03f8d57ad40c01cb88527654a/gistfile1.txt) exit code for curl looks as error. Actually if run curl from cmd, the error message box is shown, with text about MSVCR100.dll. Installation Microsoft Visual C++ 2010 Redistributable Package (x86) solves issue. But the error message don't say anything about the subprocess failure. Possible this is outdated dependency, and problem may solved by updating curl in next builds.

**Comment by sethvargo** [comment] 2016-03-04 15:55
Dupe of https://github.com/mitchellh/vagrant/issues/6764. Thank you for reporting!

**Closed by sethvargo** 2016-03-04 15:55 UTC
