### ISSUE TITLE
vagrant up errors

### ISSUE THREAD

**Issue by aohan237** [mitchellh/vagrant#7112] opened 2016-03-07 04:17 UTC
```
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/platform.rb:164:in `downcase': invalid byte sequence in GB2312 (ArgumentError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/platform.rb:164:in `block (2 levels) in fs_real_path'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/platform.rb:163:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/platform.rb:163:in `block in fs_real_path'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/platform.rb:162:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/platform.rb:162:in `fs_real_path'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:121:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:165:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:165:in `<main>'
```

**Comment by sethvargo** [comment] 2016-03-07 15:46
Hi @aohan237 

Thank you for opening an issue. A crash is certainly a bug. Could you please share the step(s) you took to get this error so we can reproduce it?

**Comment by sethvargo** [comment] 2016-03-07 15:47
Could be related to #5896

**Comment by Anderath** [comment] 2016-03-07 22:27
Same issue here, it seems my virtualbox provider still continues to work.

The timeline is strange here...This happened after most of the openssl updates and other updates around that timeline. I can try and find out what else was updated but I'm at work right now.

Perhaps it's related? Not sure what dependencies vagrant has exactly.

Here's what happens on my digital ocean provider:

Bringing machine 'default' up with 'digital_ocean' provider...
==> default: Using existing SSH key: Vagrant
==> default: Creating a new droplet...
==> default: Assigned IP address: ##.##.##.##
==> default: Destroying the droplet...
/home/**home**/.vagrant.d/gems/gems/vagrant-digitalocean-0.7.10/lib/vagrant-digitalocean/actions/create.rb:60:in `block in call': not ready (RuntimeError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/retryable.rb:17:in `retryable'
	from /home/**home**/.vagrant.d/gems/gems/vagrant-digitalocean-0.7.10/lib/vagrant-digitalocean/actions/create.rb:58:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/**home**/.vagrant.d/gems/gems/vagrant-digitalocean-0.7.10/lib/vagrant-digitalocean/actions/setup_key.rb:33:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:224:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:199:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

**Comment by sethvargo** [comment] 2016-03-07 22:54
Hi @aohan237 

Unfortunately we are unable to support third-party plugins, and the error you are getting is completely different. Please open an issue on the vagrant-digitalocean repo. Thanks! :smile:

**Comment by aohan237** [comment] 2016-03-12 02:18
want to say that  my problems is the Chinese code  GB1232's   problem.
i use mac ,when i  change to english code,this problems  will be solved.
it's the char code's problem.

hope you know that.   It's supposed to be the  Chinese character support issue

**Comment by chrisroberts** [comment] 2017-07-26 16:42
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Closed by chrisroberts** 2017-07-26 16:42 UTC
Labels: bug
