### ISSUE TITLE
error vagrant up - timeout windows 10 :(

### ISSUE THREAD

**Issue by GlauberF** [mitchellh/vagrant#7843] opened 2016-09-29 00:43 UTC
error vagrant up - timeout windows 10

### Vagrant up
follow all the guidelines of the documentation, I generated the keys and when I run on my machine with Windows 10 timeout error in the attached image has all the configuration information and error.

![homested](https://cloud.githubusercontent.com/assets/11314585/18937211/87a170ac-85c4-11e6-97bb-8e1f0eed21bd.png)

**Comment by anthony-sitbon** [comment] 2016-09-29 08:50
http://superuser.com/questions/1111027/fix-vagrant-up-after-windows-10-anniversary-update

**Comment by GlauberF** [comment] 2016-09-29 11:24
It has the latest versions installed on my machine, it will not help me

**Comment by chrisroberts** [comment] 2016-09-29 14:05
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by chrisroberts** [comment] 2016-10-25 20:13
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2016-10-25 20:13 UTC
Labels: waiting-reply
