### ISSUE TITLE
MacOSX: requested NFS version or transport protocol is not supported

### ISSUE THREAD

**Issue by razbakov** [mitchellh/vagrant#7646] opened 2016-07-26 12:41 UTC
Everything worked perfectly last week. I assume my Mac was updated automatically.

I also tried:
- to clear `/etc/exports` 
- to use `mount_options` in `Vagrantfile`
- to run `sudo nfsd start` which shows `The nfsd service is already running.` on my host system
- to recreate folders from scratch

### Vagrant version
Vagrant 1.8.5

### Host operating system
OS X El Capitan 10.11.6 (15G31)

### Guest operating system
Ubuntu Trusty 14.04.4 LTS

### Vagrantfile
```ruby
require 'rbconfig'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.name = "test-nfs-share"
  end

  config.vm.network "private_network", ip: "192.168.33.99"

  config.vm.synced_folder ".", "/home/vagrant/projects", nfs: true
end
```

### Debug output
https://gist.github.com/razbakov/bae56e1440b09b6833982fd3dc210993

### Expected behavior
Folder is shared with NFS

### Actual behavior
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

set -e
mkdir -p /home/vagrant/projects
mount -o vers=3,udp 192.168.33.1:/Users/xxx/Projects/simplebox-test/simpleboxtest /home/vagrant/projects
if command -v /sbin/init && /sbin/init --version | grep upstart; then
  /sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/home/vagrant/projects
fi


Stdout from the command:



Stderr from the command:

stdin: is not a tty
mount.nfs: requested NFS version or transport protocol is not supported
```

### Steps to reproduce
`vagrant up`

### References

Those stackoverflow questions can be related, but didn't help me:

- http://stackoverflow.com/questions/37681200/vagrant-windows-synced-folder-no-such-file-or-directory
- http://stackoverflow.com/questions/32468002/vagrant-error-while-mounting-nfs-shared-folders-following-roots-bedrocktrellis

**Comment by sethvargo** [comment] 2016-07-26 16:26
Hi there,

Can you please try setting `nfs_version: 4` in your Vagrantfile? It's possible OSX dropped support for v3 or something, but I'm unable to reproduce this on the same version of OSX myself.

**Comment by razbakov** [comment] 2016-07-26 16:28
I tried. It throws this error

```
set -e
mkdir -p /home/vagrant/projects
mount -o vers=3,udp,nfsvers=4,vers=4,actimeo=1,rsize=8192,wsize=8192,timeo=14,nolock,udp,intr,user,auto,exec,rw 192.168.33.1:/Users/razbakov/Projects/simplebox-test/simpleboxtest /home/vagrant/projects
if command -v /sbin/init && /sbin/init --version | grep upstart; then
  /sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/home/vagrant/projects
fi
```

**Comment by sethvargo** [comment] 2016-07-26 16:30
https://www.vagrantup.com/docs/synced-folders/nfs.html#nfs_version

**Comment by razbakov** [comment] 2016-07-26 16:57
@sethvargo 

doesn't help either:

```
==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

set -e
mkdir -p /home/vagrant/projects
mount -o vers=4,udp 192.168.33.1:/Users/razbakov/Projects/simplebox-test/simpleboxtest /home/vagrant/projects
if command -v /sbin/init && /sbin/init --version | grep upstart; then
  /sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/home/vagrant/projects
fi


Stdout from the command:



Stderr from the command:

stdin: is not a tty
mount.nfs: an incorrect mount option was specified
```

**Comment by RichVel** [comment] 2016-07-26 21:36
Try using TCP on IPv4 - I found that for some reason UDP on IPv4 wasn't supported (ran rpcinfo against the Mac NFS server to find this out, using `rpcinfo 172.28.128.1 |egrep "service|nfs"`).

Example of what worked for me - note the `nfs_udp: false`:

` config.vm.synced_folder ".", "/home/myuser/proj", type: "nfs", nfs_udp: false, mount_options: ['rw', 'async', 'fsc' ,'actimeo=2']`

Background: [useful StackOverflow thread](http://unix.stackexchange.com/questions/205529/nfs-mount-nfs-protocol-not-supported)

**Comment by razbakov** [comment] 2016-07-27 13:46
@RichVel doesn't help, I tried your suggestion with nfs 3 and nfs 4:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

set -e
mkdir -p /home/vagrant/projects
mount -o vers=4,rw,async,fsc,actimeo=2 192.168.33.1:/Users/razbakov/Projects/simplebox-test/simpleboxtest /home/vagrant/projects
if command -v /sbin/init && /sbin/init --version | grep upstart; then
  /sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/home/vagrant/projects
fi


Stdout from the command:



Stderr from the command:

stdin: is not a tty
mount.nfs: Protocol not supported
```

**Comment by RichVel** [comment] 2016-07-27 13:55
@razbakov suggest you try rpcinfo command, your solution may be different to mine but rpcinfo was very useful as a guide.

**Comment by razbakov** [comment] 2016-07-27 14:00
@RichVel `rpcinfo` shows nothing about nfs. Does it mean that nfs service is not running on my Mac? 

But if I run this on Mac `sudo nfsd start` it says me `The nfsd service is already running.`

**Comment by bjoernhaeuser** [comment] 2016-07-28 07:20
@razbakov you need todo "vagrant -p <your host ip address>"

**Comment by razbakov** [comment] 2016-07-28 09:55
@bjoernhaeuser it gives nothing new. My host OS provides no nfs. Or at least virtualbox can't see it.

**Comment by razbakov** [comment] 2016-08-06 03:18
I ran `vagrant up` today and everything works fine. I didn't update anything. I have the same version. And everything works. I can't give any explanation why. That's very strange.

**Comment by ivanfrolovmd** [comment] 2016-08-08 00:18
I had the same issue with vagrant 1.8.5 + virtualbox 5.1.2. I fixed it with a temporary workaround by downgrading NFS to v3 like so:
```
  config.vm.synced_folder "/path1", "/path2", type: "nfs", nfs_version: 3
```

Looks like there is a bug in vagrant v.1.8.5. Everything worked without issues in 1.8.4.

**Comment by chrisroberts** [comment] 2016-08-18 23:50
@ivanfrolovmd does nfsv4 work for you if you disable udp?

```
config.vm.synced_folder "/path1", "/path2", type: "nfs", nfs_version: 4, nfs_udp: false
```

**Comment by chrisroberts** [comment] 2016-08-19 17:35
Reading through this ticket and reading up on NFS I think there are a couple different things going on. Initially, it seems as though an upgrade may have been applied to a running nfs server which caused the initial problems and were automatically resolved later due to a reboot, or service restart (my assumption as the issue fixed itself). 

What compounds this problem is depending on the version of the nfs server, it may default to version 4 and not properly fallback to version 3 if the UDP option is set. And the errors received from the `mount` command are not very indicative of the actual problem (things like `incorrect mount option was specified`).

#7740 adds a warning to vagrant's output when UDP is enabled with NFSv4 and includes some documentation updates calling out that specific configuration pairing. I'm going to close this issue up with #7740 being the resolution, but if more problems are encountered, please open a new issue.

Thanks!

**Closed by chrisroberts** 2016-08-19 17:35 UTC
Labels: bug, synced-folders/nfs

**Comment by razbakov** [comment] 2016-09-12 08:30
I have the same problem again. It didn't work. Then I changed nothing and it started working. Nothing changed. It is not working again.

**Comment by jerm** [comment] 2016-10-08 05:56
This is happening to me as well. It appeared out of nowhere after a system crash/reboot, and hung in through a few version upgrades.  Sadly, I don't have the original version of vagrant I was running, but the problem persisted in 1.8.6.

Downgrading to 1.8.4 got me going again, but in a weird way. It now skips the shared folder config i have listed in Vagrantfile and goes and mounts the default /vagrant to pwd via vboxfs

Logging in and trying to mount manually gives the same old error.

**Comment by fubarhouse** [comment] 2016-11-03 02:26
I've had a dealing with this issue today on 1.8.4, 1.8.5 and 1.8.6 and I've had to disable NFS in order to mount the drives. Tried many things using both VBox 5.0 and 5.1, but nothing worked.

I'm open to suggestions but I'm confident I've tried all I can.

**Comment by razbakov** [comment] 2016-12-15 13:46
@chrisroberts 
Please reopen the ticket. It is not solved.

It is randomly works and doesn't work again.

**Comment by razbakov** [comment] 2016-12-15 13:50
Adding the line 127.0.0.1 localhost to the /etc/hosts file worked for me
http://stackoverflow.com/questions/23753523/vaprobash-create-new-vm-failed

**Comment by rdonkin** [comment] 2016-12-15 15:54
@razbakov Is it possible this is IPv6 related?  I've had some issues with OS X hosts and VirtualBox VMs where forcing use of 127.0.0.1 made SSH work.  

Maybe try replacing that /etc/hosts line with `::1 localhost` to see if forcing IPv6 breaks it.

**Comment by razbakov** [comment] 2016-12-16 08:43
@rdonkin i added IPv6 to hosts. It is not breaking.

**Comment by razbakov** [comment] 2016-12-22 09:43
The problem occurs again.

> Adding the line 127.0.0.1 localhost to the /etc/hosts file

Doesn't help anymore.

**Comment by pestbarn** [comment] 2017-02-07 09:43
@razbakov I'm having similar issues, running Vagrant 1.7.4 and VirtualBox 5.0.32 r112930 on macOS Sierra 10.12.1. Tried upgrading Vagrant to 1.9.1, but no go.

A temporary solution which is working for me is to
- halt and/or force exit Vagrant
- do a physical reboot
- comment out rows/clean `/etc/exports`
- run Vagrant again

It's a real pain in the ass, but it seems to be working (second day in a row for me, at least).

**Comment by fubarhouse** [comment] 2017-02-15 03:03
It seems this problem boils down to a corrupt exports file, though Vagrant should be reporting this as it normally does - but whatever the cause here it isn't.

I've had another machine come back with the problem, but the following process has fixed it for us:
* vagrant halt
* move exports file to backup location, to ensure /etc/exports either doesn't exist or contain information on the affected virtual machine
* vagrant up

**Comment by hgajjar-sessiondigital** [comment] 2017-02-20 12:24
I faced the similar issue, and the solution from @fubarhouse worked for me too. I have just removed the entries of my vm from /etc/exports and did `vagrant reload`.

**Comment by rdonkin** [comment] 2017-02-20 14:06
This worked for me too, using Vagrant 1.8.7 and VirtualBox 5.1.10 on macOS 10.11.6 - just commented out lines in `/etc/exports` and did `vagrant destroy && vagrant up`.

**Comment by fubarhouse** [comment] 2017-02-21 00:56
For anybody continuing to have the problems after using the temporary fix in my previous comment:

We've noticed that on those machines have the error come back afterwards, to fix it again (and permanently) we did the following:

* vagrant halt
* **reset the hosts file to be the default** (as shipped) - http://osxdaily.com/2014/04/12/restore-original-hosts-file-mac/
* move exports file to backup location, to ensure /etc/exports either doesn't exist or contain information on the affected virtual machine
* vagrant up

**Comment by bkmorse** [comment] 2017-03-03 19:25
I had 127.0.0.1 localhost commented out in my /etc/hosts file on my mac and I uncommented it and now nfs mounting works.

**Comment by broekhuisgavin** [comment] 2017-05-11 08:19
@bkmorse Yes, indeed. This was the solution for me!

**Comment by mgamshad** [comment] 2017-05-18 02:48
@bkmorse's solution was also what helped me out.

**Comment by timbroder** [comment] 2018-01-18 13:23
Reporting this still as an issue on 2.0.1

**Comment by sandstrom** [comment] 2018-05-21 10:56
I had this very issue and solved it like this: https://github.com/hashicorp/vagrant/issues/9666#issuecomment-390601602

Please let me know if the solution in that comment solved your issue too.
