### ISSUE TITLE
Vagrant up hangs forever on Windows 7, Vagrant 1.9.7, VirtualBox 5.1.22.r115126

### ISSUE THREAD

**Issue by hopoffbaby** [mitchellh/vagrant#8777] opened 2017-07-13 14:27 UTC
### Vagrant version
C:\MyFiles\VagrantLSF>vagrant -v
Vagrant 1.9.7

### Host operating system
Windows 7 64bit

### Guest operating system
Centos/7

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
end
```

### Debug output
https://gist.github.com/hopoffbaby/be10d4873bdbe00cba23a58b48e00166

### Expected behavior
Start virtual box vm with centos 7

### Actual behavior
hang indefinitely after:
DEBUG push: finalizing
 INFO subprocess: Starting process: ["C:\\windows\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "(new-object System.Security.Principal.WindowsPrincipal([System.Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: False

### Steps to reproduce
1. install vagrant & virtual box - latest
2. vagrant up --debug

**Comment by pnedkov** [comment] 2017-07-13 17:06
Same issue here. I started seeing this yesterday with Vagrant 1.9.6. I upgraded to 1.9.7 but I got the same result - it hangs after `SSH auth method: private key`. I am on Arch Linux and using VirtualBox 5.1.22.r115126.

**Comment by hopoffbaby** [comment] 2017-07-13 17:29
It seems that this issue is caused by 1.9.7. downgrading to 1.9.6 avoids this issue

**Comment by pnedkov** [comment] 2017-07-13 18:10
For me the problem started yesterday with 1.9.6. I upgraded to 1.9.7 - same problem. I just downgraded to 1.9.5 - same problem.

**Comment by pnedkov** [comment] 2017-07-13 19:14
I found what is causing my problem. It is the network adapter type. I am using `82545EM`. When I changed it to `82540EM` it works back again even with Vagrant 1.9.7. HTH

**Comment by Parithi** [comment] 2017-07-14 03:26
@pnedkov  I'm new to vagrant, can you tell me how to change the network adapter type?

I'm having the same setup, following @hopoffbaby and downgrading to vagrant 1.9.6 fixed my issue.

**Comment by MaxLap** [comment] 2017-07-14 12:34
Had the same issue, downgrading to 1.9.6 solved the issue.

After a windows update restarted my PC when things when running, i had to vagrant destroy to start it over. When I did, i had mounting issues, so i trying to update VirtualBox to 5.1.22 and vagrant to 1.9.7.

After doing so, all the commands hung and had no output. Using the debug, it also finished with 

```
INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: False
```

(Sorry, I didn't think of copying the exact Starting Process line i was getting, and since vagrant needs a reboot to install and to uninstall, I don't have it)

I tried repair and reinstall of vagrant 1.9.7 and nothing changed. 
Downgrading to 1.9.6 solved that issue. Now, for some reason, `vagrant ssh` won't give me a prompt when used from gitbash, but it does from cmd. So i'll stay with that for now, i just want to run tests on this.

On Windows 7 Pro 64bit.
VirtualBox 5.1.22
It's for a rails dev box, which uses Ubuntu Zesty 17.04.

**Comment by pnedkov** [comment] 2017-07-14 16:50
@Parithi 

`vb.customize ["modifyvm", :id, "--nictype1", "82540EM"]`

Refer to my vagrant repo if you want the complete Vagrantfile. I am not saying this will solve everyone's problem. But in my case 82545EM was the issue.

**Comment by ikus060** [comment] 2017-07-14 19:08
Seams to be duplicate of #8783

**Comment by digash** [comment] 2017-07-25 19:25
Same issue here. I noticed that it gets hung on powershell, killing the powershell using process explorer allows the vagrant to continue with no issue.

**Comment by inverbis** [comment] 2017-07-28 11:23
Cheers @digash, saved me from banging my head into the wall

**Comment by pscheit** [comment] 2017-08-01 09:32
killing powershell did not help, because i need vagrant to know that i am administrator so it is able to use smb. I am on vagrant 1.9.6 and it is still happening

**Comment by thanamanil** [comment] 2017-08-01 19:21
I exactly had the same problem with vagrant 1.9.7 on 2 of my machines. Downgrading the Vagrant to 1.9.3 fixed the issue.

**Comment by nurid** [comment] 2017-08-01 22:52
The same problem with me (vagrant version 1.9.7).
here are the last lines of vagrant up --debug:

DEBUG push: finalizing
 INFO subprocess: Starting process: ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfi

le", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "(new-object System.Security.Principal.WindowsPrincipal([S

...
ystem.Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administr

ator)"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: False

**Comment by thanamanil** [comment] 2017-08-02 02:32
@nurid: Try downgrading the vagrant version. I had the same issue and it was resolved after downgrading.

**Comment by pscheit** [comment] 2017-08-02 07:17
upgrade powershell to fix it

**Comment by nurid** [comment] 2017-08-03 09:24
@thanamanil : Thanks, it works. I downgraded the software from vagrant 1.9.7 to 1.9.6.

@pscheit  : Thanks, my powershell version is 2.0 (c) 2009; I haven't tried your suggestion. 

I checked the version as per this article:
https://4sysops.com/archives/powershell-versions-and-their-windows-version/
using a command inside the powershell console window:
`$PSVersionTable`

And I found the latest powershell update info:
https://docs.microsoft.com/en-us/powershell/wmf/5.0/requirements
in case I need it in the future.

**Comment by pscheit** [comment] 2017-08-03 10:48
I have a windows 7 installation where vagrant version 1.8.6 had the same behaviour

**Comment by tlongren** [comment] 2017-08-03 19:04
@nurid, updating powershell, as suggested by @pscheit, resolved this for me.

**Comment by marcoebbinghaus** [comment] 2017-08-05 12:05
Downgrade to 1.9.6 solved the same issue for me too, thanks. Was stuck with 1.9.7 at the same line nurid stated.

**Comment by ashokvaddevalli** [comment] 2017-08-07 10:06
I am also getting same issue on using Vagrant 1.9.6 version.

INFO subprocess: Starting process: ["C:\Windows\System32\WindowsPowerShell\v1.0\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "(new-object System.Security.Principal.WindowsPrincipal([System.Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)"]
INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: True

**Comment by goodwinb99** [comment] 2017-08-07 13:45
Colleague of mine had the same issue.  Upgrading from PowerShell 2.0 to 5.1 resolved the issue.

**Comment by ashokvaddevalli** [comment] 2017-08-07 14:25
Ok. Thanks.


I am getting another issue Synced Folders on below.

=> default: Machine booted and ready!
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::Provision:0x00000003d82388>
 INFO provision: Checking provisioner sentinel file...
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::SyncedFolders:0x000000037db880>
 INFO synced_folders: SyncedFolders loading from cache: false
 INFO subprocess: Starting process: ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "(new-object System.Security.Principal.WindowsPrincipal([System.Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: True

**Comment by flashfs** [comment] 2017-08-17 13:58
Same problem here.. it just hangs. Vagrant 1.9.7, Windows 7 and Power Shell 2.0.

```
 INFO subprocess: Starting process: ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoP
rofile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "(new-object System.Security.Principal.WindowsPrin
cipal([System.Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([System.Security.Principal.WindowsBuiltInRole
]::Administrator)"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: True
```

**Comment by tiagolpadua** [comment] 2017-08-17 23:40
Samething here, in Windows 10 works fine, but in Windows 7 it hangs

**Comment by Purple90** [comment] 2017-08-21 18:32
Same problem here. Windows, latest vagrant.

**Comment by Jose9123** [comment] 2017-08-24 15:29
Windows 7 Pro 64-bit (recent fresh install)
VirtualBox 5.1.26 
Vagrant 1.9.8

Issue resolved by upgrading Powershell from 2.0 to 5.0 ...

![image](https://user-images.githubusercontent.com/3801892/29673568-a6395f82-88bd-11e7-8b43-578f1e3ed5ed.png)

![image](https://user-images.githubusercontent.com/3801892/29673611-c096fa42-88bd-11e7-9b46-4f75ca1989aa.png)

**Comment by chrisroberts** [comment] 2017-08-28 17:03
Closing as a duplicate of #8783

https://github.com/mitchellh/vagrant/issues/8783#issuecomment-325411772

Cheers!

**Closed by chrisroberts** 2017-08-28 17:03 UTC
Labels: host/windows

**Comment by Sathiyarajan** [comment] 2017-11-07 10:35
Killing the powershell.exe process from Windows Task Manager has resolved the issue in Windows 7.

**Comment by Purple90** [comment] 2017-11-07 19:29
For me, the issue was actually a ssh process inside the VM that couldn't
connect to the destination and would put it in a loop lasting 45 min!

On Nov 7, 2017 4:37 AM, "sathyadev" <notifications@github.com> wrote:

Killing the powershell.exe process from Windows Task Manager has resolved
the issue in Windows 7.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/hashicorp/vagrant/issues/8777#issuecomment-342441971>,
or mute the thread

**Comment by KingGeneral** [comment] 2017-11-19 07:36
first you need to force close the powershell with taskmanager like @digash say. 

then it will show the error where it stuck.
for me i need to upgrade my powershell, 
then restart the computer
run the vagrant up,

if stuck then after you type vagrant up,  search power shell , 
run windows powershell ISE
now it works

**Comment by Gaurav2586** [comment] 2017-12-28 05:33
Updating powershell to v3.0 solved this issue: http://www.microsoft.com/en-us/download/details.aspx?id=34595

**Comment by felixtheflex** [comment] 2017-12-28 16:05
Yep updating powershell did the trick :-)

**Comment by felixtheflex** [comment] 2017-12-28 16:06
Yep, updating PowerShell did the trick

**Comment by kclay** [comment] 2017-12-28 17:41
Thanks @Gaurav2586 just ran into this problem!

**Comment by NdubuisiO** [comment] 2018-02-18 23:46
Solved it by updating powershell here  https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-windows?view=powershell-6
it took me to this link https://www.microsoft.com/en-us/download/confirmation.aspx?id=54616

**Comment by renatoadsumus** [comment] 2018-03-06 19:19
Same problem here. Windows, latest Vagrant 2.0.2, Oracle Virtual Box 5.2.8 and PowerShell 2.0.

I have done update to PowerShell 5.0 and "vagrant up" have back working normally.

choco upgrade powershell

**Comment by gabriellacerda** [comment] 2018-03-14 14:58
This fix is from a google+ group
Just run:
````
vagrant up --provider virtualbox
````
And be happy!
https://groups.google.com/forum/#!topic/vagrant-up/MAbhSWNIxYk

**Comment by shahkerali** [comment] 2018-03-16 09:13
Hi gabriellacerda,

Thank you very much, this is fixed the issue.

**Comment by LiuHD** [comment] 2018-05-07 05:50
it works!!! 
just follow gabriellacerda, `vagrant up --provider virtualbox`
