### ISSUE TITLE
Windows 10 Pro - SSL certificate problem - possible curl issue in version 1.7.4

### ISSUE THREAD

**Issue by flado** [mitchellh/vagrant#6572] opened 2015-11-21 04:03 UTC
OS: Windows 10 Pro
Vagrant: 1.7.4
```
D:\temp\test1>vagrant box add ubuntu/trusty64

The box 'ubuntu/trusty64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ubuntu/trusty64"]
Error: SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

I managed to add a box using --insecure option:

```
vagrant box add ubuntu/trusty64  --debug --insecure
```

What embedded curl says:
```
D:\temp\test1>C:\tools\HashiCorp\Vagrant\embedded\bin\curl.exe -V

curl 7.29.0 (i386-pc-win32) libcurl/7.29.0 OpenSSL/1.0.1c zlib/1.2.7
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM SSL libz
```

When trying to spin-up the box:
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: There was a problem while downloading the metadata for your box
==> default: to check for updates. This is not an error, since it is usually due
==> default: to temporary network problems. This is just a warning. The problem
==> default: encountered was:
==> default:
==> default: SSL certificate problem: unable to get local issuer certificate
==> default: More details here: http://curl.haxx.se/docs/sslcerts.html
==> default:
==> default: curl performs SSL certificate verification by default, using a "bundle"
==> default:  of Certificate Authority (CA) public keys (CA certs). If the default
==> default:  bundle file isn't adequate, you can specify an alternate file
==> default:  using the --cacert option.
==> default: If this HTTPS server uses a certificate signed by a CA represented in
==> default:  the bundle, the certificate verification probably failed due to a
==> default:  problem with the certificate (it might be expired, or the name might
==> default:  not match the domain name in the URL).
==> default: If you'd like to turn off curl's verification of the certificate, use
==> default:  the -k (or --insecure) option.
==> default:
==> default: If you want to check for box updates, verify your network connection
==> default: is valid and try again.
==> default: Setting the name of the VM: vagrant_default_1448078785537_65133
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

``` 

The box looks like it is running after the messages from above:

```
$ vagrant global-status
id       name    provider   state   directory
------------------------------------------------------------------------
a14c8ce  default virtualbox running D:/temp/vagrant
```

But I can't SSH into the box:

```
$ vagrant ssh
ssh_exchange_identification: read: Connection reset by peer
```

**Comment by sethvargo** [comment] 2015-11-21 04:32
This has been fixed in the installer (there's another issue that was recently closed) and will be fixed when we release Vagrant 1.8. Thanks! :smile:

**Closed by sethvargo** 2015-11-21 04:32 UTC

**Comment by flado** [comment] 2015-11-21 04:38
cool thanks ! Happy to hear ! But how can I fix it on my system? What's the workaround until 1.8 release ?

**Comment by flado** [comment] 2015-11-21 04:50
In case anyone else wonders ... my workaround is to Uninstall 1.7.4 and use an older version Vagrant 1.7.3 which doesn't seem to have this SSL issue. 

Get 1.7.3 from https://releases.hashicorp.com/vagrant/

**Comment by alfredorueda** [comment] 2015-12-05 20:25
I still have the same problem with 1.7.3.

![image](https://cloud.githubusercontent.com/assets/8808034/11610011/a3566852-9b96-11e5-8134-9595e28ca25c.png)


Thanks for your support!!!

**Comment by karneaud** [comment] 2016-10-07 21:14
+1 I still get this issue using the latest Vagrant on windows 10

**Comment by chrisroberts** [comment] 2016-10-07 23:14
@karneaud Hi! I'm running latest vagrant on windows 10 and cannot reproduce this error. If you are experiencing this issue, would you please create a new issue and provide the information it requests. Thanks!

**Comment by karneaud** [comment] 2016-10-11 13:45
### Expected Behaviour
Running `vagrant up` or `vagrant box update --box` should either  update the box if necessary
### Actual Behaviour

`vagrant box update --box scotch/box`

> Checking for updates to 'scotch/box'
> Latest installed version: 2.0
> Version constraints: > 2.0
> Provider: virtualbox
> There was an error while downloading the metadata for this box.
> The error message is shown below:
> 
> SSL certificate problem: unable to get local issuer certificate
> More details here: http://curl.haxx.se/docs/sslcerts.html
> 
> curl performs SSL certificate verification by default, using a "bundle"
>  of Certificate Authority (CA) public keys (CA certs). If the default
>  bundle file isn't adequate, you can specify an alternate file
>  using the --cacert option.
> If this HTTPS server uses a certificate signed by a CA represented in
>  the bundle, the certificate verification probably failed due to a
>  problem with the certificate (it might be expired, or the name might
>  not match the domain name in the URL).
> If you'd like to turn off curl's verification of the certificate, use
>  the -k (or --insecure) option.
> 

### Hardware/ Sotfware Versions
Vagrant 1.8.6
Virtual Box 5.0.14
Windows 8.1. Pro
