### ISSUE TITLE
Vagrant 1.8.7 is not working

### ISSUE THREAD

**Issue by enesterenko** [mitchellh/vagrant#8012] opened 2016-11-16 21:34 UTC
### Vagrant version
Vagrant 1.8.7

### Host operating system
macOS Sierra
10.12.1

### Guest operating system
hashicorp/precise64

### Vagrantfile
None

### Expected behavior
I am following the Getting Started guide and trying to add a box:
vagrant box add hashicorp/precise64
I expect it to download hashicorp/precise64 to my local box.

### Actual behavior
hashicorp/precise64 can't be downloaded.
Instead an error is shown.

The box 'hashicorp/precise64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.

### Steps to reproduce
1. Download latest vagrant 1.8.7
2. Run vagrant box add hashicorp/precise64

**Comment by enesterenko** [comment] 2016-11-16 21:38
I just tried to generate a sample Vagrantfile with vagrant init and tried to vagrant up.
The following error is being thrown:

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'base' (v0) for provider: virtualbox
    default: Downloading: base
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

**Comment by googlb** [comment] 2016-11-17 03:27
I have the same problem.
Mac OS X EI 10.11.6 
Vagrant 1.8.7

**Comment by guiyang** [comment] 2016-11-18 02:20
I meet the same problem.
macOS Sierra 10.12.1
Vagrant 1.8.7

When I degraded it to 1.8.6, It's works.

**Comment by chuckreynolds** [comment] 2016-11-18 05:27
same. seems 'fixed' here https://github.com/mitchellh/vagrant/issues/7997

**Comment by kikitux** [comment] 2016-11-25 20:41
duplicate of https://github.com/mitchellh/vagrant/issues/7969

**Closed by kikitux** 2016-11-25 20:41 UTC
Labels: bug, host/darwin, installer
