### ISSUE TITLE
Windows UNC path is crashing with \\\\?\\ prefix

### ISSUE THREAD

**Issue by kloining** [mitchellh/vagrant#8352] opened 2017-03-09 19:35 UTC
Vagrant 1.9.2
Virtualbox 5.1.16
Windows 10

With Virtualbox 5.1.16 the windows UNC path for 
shared folder is registered as \\?\C:\Users\username\git\repository.
Mounting /vagrant fails with The folder ... not found.

lib/vagrant/util/platform.rb
By changing 
"\\\\?\\" + path.gsub("/", "\\")
to 
path.gsub("/", "\\")
everything started to work again.

**Comment by drealecs** [comment] 2017-03-09 22:44
I'm having the same issue and from what I can understand it is because of the update of Virtualbox to 5.1.16

**Comment by abathur** [comment] 2017-03-10 00:23
Ran into the same issue; installed 5.1.14 which works fine for the moment.

**Comment by legoabram** [comment] 2017-03-10 00:25
Also having this problem with the same configuration. I can also confirm that reverting to 5.1.14 makes everything work again.

**Comment by adipriyantobpn** [comment] 2017-03-10 03:25
just update virtualbox to 5,1.16 and got same issue here..
@kloining 's solution is just work

**Comment by l00tr** [comment] 2017-03-10 06:31
It is the same for me including the workaround fixing the issue for now.

Note: The Guest Additions version does not matter in my setup using the box ubuntu/xenial64, updating does not solve the issue. The question related to [this answer at stackoverflow](http://stackoverflow.com/a/42696608/4635513) may offer some additional information. At least it describes what has been tried without success.

**Comment by lukasz-karolewski** [comment] 2017-03-10 07:30
it's the same thing that happened 2 years ago #5933

**Comment by chrisroberts** [comment] 2017-03-10 15:47
Closing this as it is an upstream issue and downgrading resolves the issue. Thanks for the report and confirmation that downgrade does resolve the issue. Cheers!

**Closed by chrisroberts** 2017-03-10 15:47 UTC
Labels: bug, provider/virtualbox, upstream

**Comment by l8nite** [comment] 2017-03-10 18:24
@chrisroberts is there a link to the upstream bug somewhere?

**Comment by chrisroberts** [comment] 2017-03-10 18:52
@l8nite Right now there is a thread running here:

https://forums.virtualbox.org/viewtopic.php?f=6&t=82165

There is a claim in that thread that VirtualBox does not support UNC paths for shared folders, but it seems that the claim is conflating remote share paths with local long paths.

**Comment by cbj4074** [comment] 2017-03-11 03:49
At this point, Vagrant is blaming VirtualBox, and VirtualBox is blaming Vagrant.

Here's what we know:

- Upgrading from VirtualBox 5.1.14 to 5.1.16 causes this problem. Downgrading resolves it.
- While NFS mounts *also* seem to fail, VirtualBox's native "Shared Folder" mounts fail, too (and perhaps cause the subsequent NFS mounting failures).
- The issue seems to affect Windows hosts only. We have confirmed reports from Windows 7 and Windows 10 thus far (that I've seen, anyway).
- Updating the Guest Additions and by extension rebuilding the kernel modules in the guest OS does not change the behavior.
- The guest OS seems to be irrelevant; we have reports of failures in both RedHat and Ubuntu guest OSes.

**Comment by nashsophie** [comment] 2017-03-11 08:05
i got the save problem.
VirtualBox  Downgrade  VirtualBox 5.1.16 to 5.1.14

**Comment by jimfrenette** [comment] 2017-03-11 15:05
Time to switch to HyperV

**Comment by kloining** [comment] 2017-03-11 17:30
I do not agree @chrisroberts that this should be closed as an "upstream issue", when more and more users are going to upgrade VirtualBox the coming days. This problem is just going to be bigger and bigger, until either VirtualBox reverts their changes in the closest future - or Vagrant makes the needed change.

If VirtualBox doesn't do the change quite soon, Vagrant will have to adapt.

**Comment by lystor** [comment] 2017-03-11 17:43
I don't understand why Vagrant developers don't remove ugly "\\?\" prefix to fix the bug in their product?!

Virtualbox 5.1.16 perfectly mount shared folders with correct path (without "\\?\" prefix).

https://www.virtualbox.org/manual/ch04.html#sharedfolders
VBoxManage sharedfolder add "VM name" --name "sharename" --hostpath "C:\test"

Vagrant tries to mount it with "\\?\C:\test"

**Comment by cbj4074** [comment] 2017-03-11 18:55
@lystor Disclaimer: I'm not a Vagrant developer.

My best guess is that the `\\?\` notation is intended to avoid problems that arise due to the Windows path length limitations that exist in older Windows API methods. I provided a link to the relevant documentation a couple of posts back, which explains this notation's purpose.

If you've ever used a package manager (npm for JS, Composer for PHP, etc.) with mounted filesystems, you may have noticed that filesystem operations sometimes fail due to the excessive path lengths that result from deeply-nested repository structures, which often contain extremely long file and directory names.

Perhaps the Vagrant developers sought to mitigate some of the problems associated with the age-old limitations on Windows path lengths by taking advantage of this `\\?\` syntax.

That said, I agree with you and the OP that Vagrant may have no choice but to implement some form of workaround in the interest of not bringing the VirtualBox users to a grinding halt over this issue.

**Comment by chrisroberts** [comment] 2017-03-13 14:52
Hi there everyone. Just wanted to drop a couple notes here.

First, the `\\?\` path prefix is the Windows defined method for specifying long path names. There is currently work underway within the Vagrant internals to automatically modify all path usage to this style to prevent bugs that occur when long paths are generated due to directory depths combined with long path names. While the path may "look" ugly, this is how long paths should be handled on Windows. You can find more information about that in @cbj4074's comment here: https://github.com/mitchellh/vagrant/issues/8352#issuecomment-285839441

Second, this has been confirmed as a regression in VirtualBox. The relevant ticket which has been re-opened is here: https://www.virtualbox.org/ticket/14651

If you are using VirtualBox on Windows and running into this problem, it will be easiest to downgrade to 5.1.14 until the regression is fixed.

Thanks for all the reports and apologies for the inconvenience. Cheers!

**Comment by kloining** [comment] 2017-03-13 14:57
Great report @chrisroberts.
The reopened ticket on VirtualBox confirms this is an issue in VirtualBox, which is a totally different status than in the first referenced thread at VB (where Vagrant got all the blame). Is it possible to make this issue show as visible under issues, even though it's closed? This thread will probably help quite a few people.

**Comment by chrisroberts** [comment] 2017-03-13 15:12
@kloining The first referenced thread on the VirtualBox forums acknowledges that it is a regression at the bottom of the thread.

**Comment by GWSB** [comment] 2017-03-13 18:39
Was having the same issue. Can confirm that uninstalling VirtualBox-5.1.16 and reinstalling 5.1.14 solved my issue.

**Comment by yunusemreuveyik** [comment] 2017-03-14 19:23
lib/vagrant/util/platform.rb where is it ? can you please enter the complete path please ı just couldnt find it to change :/ @kloining

**Comment by rikertothebridge** [comment] 2017-03-15 10:46
This issue is resolved in VirtualBox preview build 5.1.17 revision 113984

**Comment by vadviktor** [comment] 2017-03-16 08:19
This issue looks like to be fixed in the new Virtualbox version 5.1.18.

**Comment by pearcec** [comment] 2017-03-16 15:08
Confirmed it is fixed in 5.1.18

**Comment by gshiva** [comment] 2017-04-28 04:52
stopped working again with  Virtualbox version 5.1.20.

**Comment by drealecs** [comment] 2017-04-28 05:02
Only if you install latest VirtualBox Guest Additions.

Workaround for now could be to disable vb-guest plugin for ubuntu/trusty.

VirtualBox problem IMO.

**Comment by jamiejackson** [comment] 2017-05-01 17:40
[5.1.22 just came out on Friday](https://www.virtualbox.org/wiki/Changelog). Has anyone tested yet? (I'm on a Mac, but most of my team is on Windows.)

**Comment by vortexau** [comment] 2017-05-26 05:21
I'm new to Vagrant and running VirtualBox 5.1.22. This appears to still be an issue, unfortunately.

I'd just like to use Vagrant. I don't wish to break all my other working non-Vagrant VMs by downgrading VirtualBox and their installed vmtools. That seems unnecessary.

**Comment by vortexau** [comment] 2017-05-26 06:03
I am running VirtualBox 5.1.22, and once the correct VM Tools are installed, this appears to work as expected.

**Comment by edenreich** [comment] 2017-06-09 20:18
I'm Using Windows 10 and Vagrant version 1.9.5

Recently I've downloaded Docker Toolbox, as a part of the installation they asked me to upgrade to Virtualbox from version 4.3.40 to 5.1.20, so I did.
Mounting shared folders did not work sense then with Vagrant, so I had to downgrade my virtualbox unfurtonetly to 4.3.40 and it all back to work again.
So I can confirm this issue

**Comment by SnowQueenWolf** [comment] 2018-07-31 17:34
Hello, I am totally not anywhere near your realm of being when it comes to programing. However I am compelled to help myself, especially since there is no one around to assist me. So I am hoping some one will be able to assist me. I am adding email accounts to my iMac. when I try to add a <www.homestead.com> email account it ask me for a (path prefix) I am howling for assistance. Yes, I looked up what it means....it's all greek to me. Can someone assist me with obtaining a (path prefix) so I can add my email account. I am using (pop@homestead.com). HELP, HELP!

SnowQueenWolf
