### ISSUE TITLE
Weird stdout behavior with vagrant up

### ISSUE THREAD

**Issue by erg0dic** [mitchellh/vagrant#6291] opened 2015-09-21 15:36 UTC
### Vagrant version
```
rcj@mcdouble:seo-phase-1 $ vagrant --version
Vagrant 1.7.4
```
### My Vagrantfile
```ruby
require 'yaml'

# Load user config
# Based on: http://stackoverflow.com/questions/16708917/how-do-i-include-variables-in-my-vagrantfile
current_dir    = File.dirname(File.expand_path(__FILE__))
vagrant_config = YAML.load_file("#{current_dir}/config.yaml")

Vagrant.configure(2) do |config|
  # Preconditions
  unless ENV['SITE_SEO']
    puts 'Error!'
    raise 'You must set the SITE_SEO environment variable to the path ' +
          'of the SEO project on the host machine!'
  end

  config.vm.box = vagrant_config['box']
  config.vm.network :private_network, ip: '192.168.128.128'
  config.vm.network :forwarded_port, guest: 8080, host: vagrant_config['seo_port']
  config.vm.synced_folder ENV['SITE_SEO'], '/opt/seo'

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = vagrant_config['vb_memory']
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.inventory_path = 'ansible/seo'
    ansible.groups = {
      'seo' => ['default']
    }
    ansible.playbook = 'ansible/site.yml'
    ansible.sudo = true
    ansible.sudo_user = 'root'
    ansible.extra_vars = {
      ansible_ssh_user: 'vagrant'
    }
  end
end
```

### Output of ``vagrant up`` when unless block entered
```
rcj@mcdouble:seo-phase-1 $ vagrant up
Error!
Error!
/Users/rcj/code/seo-phase-1/Vagrantfile:12:in `block in <top (required)>': You must set the SITE_SEO environment variable to the path of the SEO project on the host machine! (RuntimeError)
<snip>
```

### Source of my confusion
Why is Error! output twice when the exception is only thrown once?

**Comment by erg0dic** [comment] 2015-09-21 15:52
It is worth noting that I observe the same behavior when ``abort`` is used in place of ``puts``, which means stderr is also being duplicated

**Comment by Temikus** [comment] 2015-09-22 11:33
@erg0dic Doing a quick skim with a debugger it looks like it just evaluates the config twice, once on start and once on env.unload.

Let's try the following Vagrantfile:
```
Vagrant.configure("2") do |config|

  puts "Error!"
  binding.pry
  raise "Something happened"
```

If we insert a debugger right after 'puts' statement we see our error immidiately:
```
λ vagrant up
...

Error!

From: /home/temikus/code/vagrant-google/Vagrantfile @ line 7 :

     2:
     3: Vagrant.configure("2") do |config|
     4:
     5:   puts "Error!"
     6:   binding.pry
 =>  7:   raise "Something happened"
     8:
     9:   config.vm.box = "gce"
    10:
    11:   config.vm.synced_folder "test/", "/srv/test"
    12:
```
Alright, let's continue in the loop
```

[1] pry(main)> next

From: /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-06c1e1ee1b94/bin/vagrant @ line 177 :

    172:   begin
    173:     # Execute the CLI interface, and exit with the proper error code
    174:     exit_status = env.cli(argv)
    175:   ensure
    176:     # Unload the environment so cleanup can be done
 => 177:     env.unload
    178:   end
    179:
    180:   # Exit with the exit status from our CLI command
    181:   exit(exit_status)
    182: rescue Exception => e

```
Now, we reached unload and after stepping through we immidiately see the error again and get back into the Vagrantfile:
```
[1] pry(main)> next

Error!

From: /home/temikus/code/vagrant-google/Vagrantfile @ line 7 :

     2:
     3: Vagrant.configure("2") do |config|
     4:
     5:   puts "Error!"
     6:   binding.pry
 =>  7:   raise "Something happened"
     8:
     9:   config.vm.box = "gce"
    10:
    11:   config.vm.synced_folder "test/", "/srv/test"
    12:

[1] pry(main)> exit
```
If we try to call env.unload, we will see that it's seems to be evaluating the Vagrantfile again:
```
> env.unload
Error!
RuntimeError: Something happened
from /home/temikus/code/vagrant-google/Vagrantfile:7:in `block in <top (required)>'
```
I'm not quite sure how the `:environment_unload` hook works, but if you want to dig deeper, I would probably look into that.

**Comment by sethvargo** [comment] 2015-11-08 01:03
Hi @erg0dic 

Thank you for opening an issue. This is actually the intended behavior of Vagrant. You can read more here: https://docs.vagrantup.com/v2/vagrantfile/, but the Vagrantfile is evaluated, loaded, and merged multiple times during a single invocation of `vagrant`. If you move your check outside of the `configure` block, you will only see the output once :smile: 

```ruby
if ENV["THING"]
end

Vagrantfile.configure(2) do
# ...
end
```

**Closed by sethvargo** 2015-11-08 01:03 UTC
