### ISSUE TITLE
v1.7.3 Ubuntu 12.04 chown: changing ownership of `/var/www': Not a directory

### ISSUE THREAD

**Issue by archy-bold** [mitchellh/vagrant#5959] opened 2015-07-13 21:52 UTC
Hi. I get the below error when trying to bring up a new Ubuntu 12.04 box (specifically [Scotch Box](https://box.scotch.io/)) using Vagrant 1.7.3 and VirtualBox 5.0.

I don't know if it's an issue with the box itself, but I've experienced the Ubuntu hostname bug so thought it could be something in Vagrant. When logging into the box, I can `cd` into the `/var/www` directory, but get a similar error if I try to `ls` in there. It's as if it's not being seen as a directory.

Maybe a sharing issue?

Thanks,
Simon

```
chown `id -u vagrant`:`id -g vagrant` /var/www

Stdout from the command:



Stderr from the command:

stdin: is not a tty
chown: changing ownership of `/var/www': Not a directory
```

**Comment by archy-bold** [comment] 2015-07-13 21:57
Actually, I get the same issue when trying to bring up a Homestead machine too. I'm using Windows 8.1.

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chown `id -u vagrant`:`id -g vagrant` /vagrant

Stdout from the command:



Stderr from the command:

chown: changing ownership of ???/vagrant???: Not a directory
```

**Comment by sethvargo** [comment] 2015-07-13 21:58
Hi @archy-bold 

This is a duplicate of https://github.com/mitchellh/vagrant/issues/5933. We have mixed the issue on master and will be in 1.7.4. Sorry about the regression!

**Closed by sethvargo** 2015-07-13 21:58 UTC

**Comment by hickeroar** [comment] 2015-12-29 21:55
@sethvargo This issue seems to be back in Vagrant 1.8.0 and 1.8.1

**Comment by edrevo** [comment] 2016-02-19 08:09
+1. I'm also seeing this in 1.8.1:

```bash
C:\Users\ximo.HI\git\smallcell [add-rpm +6 ~1 -0 !]> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
GuestAdditions 5.0.6 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/ximo.HI/git/smallcell
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chown `id -u vagrant`:`id -g vagrant` /vagrant

Stdout from the command:



Stderr from the command:

chown: changing ownership of â?~/vagrantâ?T: Not a directory

C:\Users\ximo.HI\git\smallcell [add-rpm +6 ~1 -0 !]> vagrant version
Installed Version: 1.8.1
Latest Version: 1.8.1

You're running an up-to-date version of Vagrant!
```

**Comment by infinitencreative** [comment] 2016-04-26 06:11
same error in 1.8.1 on windows 7.

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chown `id -u vagrant`:`id -g vagrant` /vagrant

Stdout from the command:

Stderr from the command:

chown: changing ownership of ‘/vagrant’: Not a directory
```
