### ISSUE TITLE
Vagrant 1.8.5 Not Work the SSH Auth. But Vagrant 1.8.4 is Work.

### ISSUE THREAD

**Issue by ytooyama** [mitchellh/vagrant#7631] opened 2016-07-23 13:00 UTC
Vagrant 1.8.5 Not Work the SSH Auth. But Vagrant 1.8.4 is Work.

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.
Vagrant 1.8.5

### Host operating system
This is the operating system that you run locally.
Mac OS X El Capitan 10.11.6

### Guest operating system
This is the operating system you run in the virtual machine.
Fedora 24
CentOS 6
CentOS 7

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

#custum config
Vagrant.configure(2) do |config|
VAGRANTFILE_API_VERSION = "2"

#Global
  config.vm.provider "virtualbox" do |vb|
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize [
      "modifyvm", :id,
      #"--cpus", "2",
      "--memory", "1024",
      "--paravirtprovider", "kvm",
    ]
  end

#Fedora 24
 config.vm.define :node1 do |node1|
  node1.vm.box = "fedora/24"
  node1.vm.hostname = "node1"
  node1.vm.network "public_network"
 end

 config.vm.define :node2 do |node2|
  node2.vm.box = "fedora/24"
  node2.vm.hostname = "node2"
  node2.vm.network "public_network"
 end

 config.vm.define :node3 do |node3|
  node3.vm.box = "fedora/24"
  node3.vm.hostname = "node3"
  node3.vm.network "public_network"
 end

 config.vm.define :node4 do |node4|
  node4.vm.box = "fedora/24"
  node4.vm.hostname = "node4"
  node4.vm.network "public_network"
 end

#CentOS7
 config.vm.define :cent1 do |cent1|
  cent1.vm.box = "cent/7"
  cent1.vm.hostname = "cent1"
  cent1.vm.network "public_network"
 end

 config.vm.define :cent2 do |cent2|
  cent2.vm.box = "cent/7"
  cent2.vm.hostname = "cent2"
  cent2.vm.network "public_network"
 end

 config.vm.define :cent3 do |cent3|
  cent3.vm.box = "cent/7"
  cent3.vm.hostname = "cent3"
  cent3.vm.network "public_network"
 end

 #CentOS6
 config.vm.define :cent6n1 do |cent6n1|
  cent6n1.vm.box = "cent/6"
  cent6n1.vm.hostname = "cent6-1"
  cent6n1.vm.network "public_network"
 end

 config.vm.define :cent6n2 do |cent6n2|
  cent6n2.vm.box = "cent/6"
  cent6n2.vm.hostname = "cent6-2"
  cent6n2.vm.network "public_network"
 end

 config.vm.define :cent6n3 do |cent6n3|
  cent6n3.vm.box = "cent/6"
  cent6n3.vm.hostname = "cent6-3"
  cent6n3.vm.network "public_network"
 end

#eof
end
```

### Steps to reproduce
(1) vagrant up
(2) Show the This messages.

```
default: Warning: Authentication failure. Retrying...
default: Warning: Authentication failure. Retrying...
default: Warning: Authentication failure. Retrying...
...
```

(3) But downgrade the Vagrant 1.8.4 is Good Work.

**Comment by sethvargo** [comment] 2016-07-23 15:39
This is a known issue that has already been fixed on master. Sorry about that!

**Closed by sethvargo** 2016-07-23 15:39 UTC

**Comment by ytooyama** [comment] 2016-07-24 03:55
Thanks!

**Comment by ytooyama** [comment] 2016-07-24 04:13
We need download the Vagrant 1.8.4. or Fixed version.

**Comment by vriera** [comment] 2016-08-17 00:08
What's the commit that fixed the problem?

**Comment by vriera** [comment] 2016-08-17 00:09
@sethvargo What's the commit that fixed the problem?

**Comment by tanujchinnu** [comment] 2016-08-17 02:16
I don't think the issue is resolved. I'm using mac and I'm having an ssh issue with vagrant 1.8.5 version. I also tried uninstalling the latest and installed 1.8.0 but it still shows me the same 1.8.5 version. Not sure why.

**Comment by benFlightStats** [comment] 2016-08-22 22:43
I also uninstalled 1.8.5 and repeatedly tried installing 1.8.4 - but still get
```
-> % vagrant version
Installed Version: 1.8.5
Latest Version: 1.8.5
```

**Comment by Amar-Chaudhari** [comment] 2016-08-29 15:51
@sethvargo Should we be expecting 1.8.6 release any time soon ?

**Comment by ddavisgraphics** [comment] 2016-09-12 18:03
@benFlightStats this is happening to me to, did you figured out how to solve the problem yet of un-installing and getting 1.8.4 to install.

**Comment by seymourduncandevops** [comment] 2016-09-12 18:45
I'm assuming this is the same chmod issue discussed in https://github.com/mitchellh/vagrant/issues/7610 but am wondering if we have a target release date for the fix?
For others, if you `vagrant up`, then when it fails on the ssh auth, `vagrant ssh` in and run `chmod 0600 ~/.ssh/authorized_keys`. Then `exit` out of the vm terminal and run `vagrant reload --provision` to complete the process.

**Comment by tanujchinnu** [comment] 2016-09-12 18:59
tried ssh into machine it shows permission denied (public key, gssapi-key,
gssapi-with-mic). As it's ssh authentication issue, I'm not able to do SSH
into the machine.

On 12 Sep 2016 14:45, "Seymour Duncan DevOps" <notifications@github.com>
wrote:

I'm assuming this is the same chmod issue discussed in #7610
<https://github.com/mitchellh/vagrant/issues/7610> but am wondering if we
have a target release date for the fix?
For others, if you vagrant up, then when it fails on the ssh auth, vagrant
ssh in and run chmod 0600 ~/.ssh/authorized_keys. Then exit out of the vm
terminal and run vagrant reload --provision to complete the process.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mitchellh/vagrant/issues/7631#issuecomment-246449765>,
or mute the thread

**Comment by bobo52310** [comment] 2016-09-26 16:32
@ddavisgraphics @benFlightStats 

I figured out the way to solve the problem,
the keypoint is uninstall vagrant 1.8.5 by uninstall.tool

Step 1. Download vagrant 1.8.4 from 
https://releases.hashicorp.com/vagrant/1.8.4/

Step 2. uninstall.tool

Step 3. install vagrant 1.8.4 + VirtualBox 5.0

Done! Everything is going well.
