### ISSUE TITLE
Ansible provisioning fails when directory's name contains a space character

### ISSUE THREAD

**Issue by pbuyle** [mitchellh/vagrant#6270] opened 2015-09-15 15:46 UTC
When using Ansible, provisioning fails with the follow error message:
```
==> default: Running provisioner: ansible...
ERROR: /random/path/with/a space/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory:3: Invalid ini entry: - - need more than 1 value to unpack
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

The offending line in the inventory file looks like this
```
default ansible_ssh_host=10.0.3.220 ansible_ssh_port=22 ansible_ssh_private_key_file=/random/path/with/a space/.vagrant/machines/default/lxc/private_key
```
The issue is with the space character. Because of this space, the path should be enclosed in ".

**Comment by pbuyle** [comment] 2015-09-15 15:48
The fix could be as simple as adding the missing double quotes at https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/ansible/provisioner.rb#L130

**Comment by gildegoma** [comment] 2015-09-15 20:23
@pbuyle thanks for your report. I'm closing it as duplicate of #6209 though.

**Closed by gildegoma** 2015-09-15 20:23 UTC
