### ISSUE TITLE
Chef Client does not run, when console does not support colours

### ISSUE THREAD

**Issue by MartinSGill** [mitchellh/vagrant#6257] opened 2015-09-11 10:34 UTC
Host: Windows (Win 7)
Guest: Windows (2012, not R2)
Vagrant: 1.7.4
Chef: 12.4.1

Vagrant creates a scheduled task to use as a proxy for running the chef client with elevated privileges.
When this task is created from a shell that does not declare it supports ANSI colours this task tries to invoke the chef client with the `--no-color ` flag. For some reason this causes the task to fail (silently).

If the shell does support ANSI colours (e.g. running it in ConEmu, or defining environment variables `ANSICON="119x1000 (119x53)"` & `ANSICON_DEF = "7"`) the scheduled task is created without the `--no-color` flag" and the chef client runs fine.

Symptoms: Vagrant up output from provision/up as follows:

```
PS> vagrant up
...
Generating chef JSON and uploading...
==> default: Running chef-client...
PS> 
```

Work-around: 

```
PS> $env:ANSICON = "119x1000 (119x53)"
PS> $env:ANSICON_DEF = "7" 
PS> vagrant up
...
Generating chef JSON and uploading...
==> default: Running chef-client...
==> default: Starting Chef Client, version 12.4.1
...
```

**Comment by partamonov** [comment] 2015-10-07 06:10
The issue is in windows task restrictions
STDERR: ERROR: Value for '/TR' option cannot be more than 261 character(s).
```
---- End output of schtasks /CREATE /TN "\Chef client scheduled run" /F  /SC minute /MO 30 /TR "C:\opscode\chef\bin\chef-client.bat -c c:\chef\client.rb -L C:/chef/log/chef_scheduled_run.log -l info -r 'very long run list'"  /RU VAGRANT-2012\User /RP Paswword /RL HIGHEST  ----

**Comment by sethvargo** [comment] 2015-11-19 19:55
Hi @MartinSGill 

I am unable to reproduce this issue. Could you perhaps share your Vagrantfile? Vagrant does not create a scheduled task or anything to run Chef; it just runs the Chef Client via the shell.

**Comment by sethvargo** [comment] 2015-11-20 00:23
Hi @MartinSGill 

I just tried again, and I cannot reproduce this issue, even with `--no-color`. I think this might be an issue with Chef that might have been fixed in later versions. Nonetheless, I don't think there's anything Vagrant can do here to make the experience better. Sorry!

**Closed by sethvargo** 2015-11-20 00:23 UTC
Labels: guest/windows, provisioner/chef, waiting-reply

**Comment by partamonov** [comment] 2015-11-29 22:04
Just to clarify here. Issue is on Windows side. There are limitation on length of task command. And if you exceeded it, task won't run. Not observed on Windows 2012 R2.

The way to reproduce is to specify very-very long runlist for Chef, just to be sure.
