### ISSUE TITLE
Vagrant 1.7.1 package failure - wrong number of arguments stack trace

### ISSUE THREAD

**Issue by jmenchacavr** [mitchellh/vagrant#5098] opened 2015-01-02 21:55 UTC
As per [instructions](http://docs.vagrantup.com/v2/cli/package.html), I create a VirtualBox titled "win7-puppet".  I try this command, and these are the results I get:

```
$ vagrant package --base "win7-puppet"
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:153:in `action': wrong number of arguments (2 for 1) (ArgumentError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:83:in `package_vm'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:66:in `package_base'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.1/bin/vagrant:174:in `<main>'
```

**Comment by jmenchacavr** [comment] 2015-01-02 21:56
Same command with debug: https://gist.github.com/jmenchacavr/06a6ecf364cb714909fe

**Comment by sethvargo** [comment] 2015-01-02 22:00
This is a duplicate of #4960 and is already fixed on master

**Closed** 2015-01-03 11:57 UTC
