### ISSUE TITLE
multiple instances of 'vagrant box update' collide 

### ISSUE THREAD

**Issue by lungetech** [mitchellh/vagrant#5343] opened 2015-02-16 21:46 UTC
'vagrant box update' does not use a per environment download path, which can cause updates in two different environments to have the downloads collide, causing downloads to fail.

**Comment by sethvargo** [comment] 2015-07-10 20:21
Duplicate of https://github.com/mitchellh/vagrant/issues/4897. Let's track that please. Thanks!

**Closed by sethvargo** 2015-07-10 20:21 UTC
Labels: bug, core
