### ISSUE TITLE
`rsync` doesn't work on Vagrant 1.8.0

### ISSUE THREAD

**Issue by arthuroy** [mitchellh/vagrant#6702] opened 2015-12-22 02:45 UTC
`rsync` doesn't work on Vagrant **1.8.0**, but it was ok on **1.7.4**.

- Microsoft Windows 10 build 10586
- Vagrant 1.8.0
- rsync 3.1.1-1 from msys2-i686-20150916.exe (32-bit)
- openssh 7.1p1-1 from msys2-i686-20150916.exe (32-bit)

From MSYS2 Shell:
```bash
    coreos-01: Rsyncing folder: /d/vagrant-lab/ => /vagrant
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /d/vagrant-lab/
Guest path: /vagrant

Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o ControlMaster=auto -o ControlPath=C:/msys32/tmp/ssh.740 -o ControlPersist=10m -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'C:/Users/<user_name>/.vagrant.d/insecure_private_key' --exclude .vagrant/ /d/vagrant-lab/ core@127.0.0.1:/vagrant

Error: This rsync lacks old-style --compress due to its external zlib.  Try -zz.
Continuing without compression.

Warning: Permanently added '[127.0.0.1]:2222' (ED25519) to the list of known hosts.

mm_receive_fd: no message header
process_mux_new_session: failed to receive fd 0 from slave
mux_client_request_session: read from master failed: Connection reset by peer
Failed to connect to new control master
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.1]
```

see also #4586 #4073

**Comment by arthuroy** [comment] 2015-12-22 04:18
From Cygwin Terminal:
```bash
    coreos-01: Rsyncing folder: /cygdrive/d/vagrant-lab/ => /vagrant
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /cygdrive/d/vagrant-lab/
Guest path: /vagrant

Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o ControlMaster=auto -o ControlPath=C:/cygwin/tmp/ssh.625 -o ControlPersist=10m -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'C:/Users/<user_name>/.vagrant.d/insecure_private_key' --exclude .vagrant/ /cygdrive/d/vagrant-lab/ core@127.0.0.1:/vagrant

Error: Warning: Permanently added '[127.0.0.1]:2222' (ED25519) to the list of known hosts.

mm_receive_fd: no message header
process_mux_new_session: failed to receive fd 0 from slave
mux_client_request_session: read from master failed: Connection reset by peer
Failed to connect to new control master
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.1]
```

**Comment by arthuroy** [comment] 2015-12-22 04:33
Another issue issue introduced in #6568 - [commit 6e6172e](https://github.com/mitchellh/vagrant/commit/6e6172ee775c875101171991f41930076d23c77e)

plugins/synced_folders/rsync/helper.rb

**Comment by jraviotta** [comment] 2015-12-22 23:04
@arthuroy thank you. Removing lines 77-79 from helper.rb worked for me.

**Comment by berlincount** [comment] 2015-12-25 22:57
I can confirm.

Windows 10 Build 10240
Vagrant 1.8.0

Same issue, fix helps the same way :)

**Comment by matevarga** [comment] 2015-12-26 21:13
Same issue here on 1.8.1. Removed the lines, now it works.

**Comment by mariomka** [comment] 2015-12-27 12:50
Windows 10, Vagrant 1.8.0, fix working <3

**Comment by stellis** [comment] 2015-12-27 23:04
I was able to reproduce this with 1.8.1 on Windows 10

**Comment by Flightfreak** [comment] 2015-12-28 15:05
Windows 8.1 64, Vagrant 1.8.1, removed above lines and it works.

**Comment by davincho** [comment] 2015-12-29 12:04
Thanks for the workaround - Windows 10, Vagrant 1.8.0

**Comment by thewebists** [comment] 2016-01-04 06:08
+1 For the solution.

When Googling this issue I came across mentions that there are problems with using SSH ControlMaster under Cygwin.

Maybe there should be an environment check on this code.

**Comment by chuckyz** [comment] 2016-01-04 07:16
Can anyone confirm if this is only or MinGW (Cygwin) versions of OpenSSH?

If so, a simple check like...

```
if (/mingw/ =~ RUBY_PLATFORM) != nil
  - disable ControlMaster
end
```

Would work.

**Comment by jamiejackson** [comment] 2016-01-05 17:01
Thanks, https://github.com/mitchellh/vagrant/issues/6702#issuecomment-166503021 got me running on Windows 7/Cygwin/Vagrant 1.8.1. (Obviously, my path has a `vagrant-1.8.1` node, instead of `vagrant-1.8.0`, though.)

**Comment by huangsam** [comment] 2016-01-07 07:59
I'm currently using cwRsync 3.1.0 on Windows 7/Git Bash/Vagrant 1.8.1. The [previous comment](https://github.com/mitchellh/vagrant/issues/6702#issuecomment-166503021) was not enough for my machine as it caused the following error:

```
Error: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
rsync: change_dir "/c/Users/huangsam/git/sample" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [sender=3.1.0]
```

I used solutions from #3230 to resolve my problem.

**Comment by ryanlraines** [comment] 2016-01-10 08:02
Win10 Pro
Virtual Box 5.0
Vagrant 1.8.1
rsync 3.1.1
centos/7 box

Same symptoms as first reported.  I tried the workaround (remove lines 77-79), but I'm still experiencing the same symptoms. 

Any Ideas?  Thanks.

**Comment by reedolph** [comment] 2016-01-11 22:26
Had the same issue on Windows 10 / VirtualBox 5 / MSYS2 rsync & openssh (from msys2-i686-20150916.exe) / Vagrant 1.8.1.

Workaround in https://github.com/mitchellh/vagrant/issues/6702#issuecomment-166503021 fixed it, thanks for that.

**Comment by redcenter** [comment] 2016-01-20 10:14
Same issue on:
- Windows 10
- Vagrant 1.8.1
- VirtualBox 5.0.14
- Rsync 3.1.1 (protocol version 31)

Workaround in the comment worked like a charm. Thanks!

**Comment by stellis** [comment] 2016-01-20 15:46
This issue is now a month old, and the fix seems to be very simple. This, along with a few other baffling issues, has been a disappointing look into quality assurance at HashiCorp.

I hope that this is fixed soon and that we're also given more insight into the testing and release process at HashiCorp (which seems as though it has a lot of room for improvement at the moment).

**Comment by mumhero** [comment] 2016-01-25 11:11
Same problem here

* Windows 8.1
* Vagrant 1.8.1
* VirtualBox 4.3.18
* cwRsync 5.5.0 

Workaround doesn't work.

```
Error: Warning: Permanently added '[127.0.0.1]:2222' (RSA) to the list of known
hosts.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(605) [Receive
r=3.0.9]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=
3.1.2]
```

**Comment by steroyle** [comment] 2016-01-25 23:55
I have been experiencing the same issue:

* Windows 8.1
* Vagrant 1.8.1
* Virtual Box 4.3.20
* rsync 3.1.0 (protocol version 31)

**rsync error:**
```
Error: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known
hosts.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.0]
```

I removed Vagrant 1.8.1 and installed an older version that I know works on another machine (1.7.4) and it now works fine.

**Comment by slavajacobson** [comment] 2016-01-27 23:04
Same problem here. 

Windows 10
CYGWIN_NT-10.0 DESKTOP-O1A4SV5 2.4.1(0.293/5/3) 2016-01-24 11:26 x86_64 Cygwin
rsync v3.1.1
vagrant 1.8.1

**Comment by blah238** [comment] 2016-01-28 23:21
Same problem here -- workaround here works: https://github.com/mitchellh/vagrant/issues/6702#issuecomment-166503021

  - Windows 7 64-bit SP1
  - Git for Windows 64-bit SDK 1.0.1 (msys2-runtime 2.3.1.33884.84870b7-1)
  - rsync 3.1.2 (protocol version 31)
  - vagrant 1.8.1
  - virtualbox 5.0.14

**Comment by swquinn** [comment] 2016-02-01 18:53
I can confirm that on Windows 10 64-bit, with rsync 3.1.2, Vagrant 1.8.1 and VirtualBox 5.0.12 the workaround noted here: https://github.com/mitchellh/vagrant/issues/6702#issuecomment-166503021 resolves issues I've had with rsync.

**Comment by davidski** [comment] 2016-02-07 14:54
Another :+1: on the fix from @arthuroy working for a Windows 10 x64, Vagrant 1.8.1, VMWare Workstation user. Any word from a Hashicorp org person on getting a fix into a released version? Makes it really hard to promote Vagrant internally when these sorts of basics don't work out of the box.

**Comment by kanmaniselvan** [comment] 2016-02-08 08:52
+1 and Thanks for fix @arthuroy. It worked.

**Comment by penguincoder** [comment] 2016-02-11 03:13
I think I have figured out the root cause. You really want `ControlMaster` enabled. It speeds along your rsync-over-ssh connections a whole lot. The problem is that the `controlpath` variable doesn't translate the path to a cygwin-compatible path. The rest of the paths are converted in the command, so that one needs translated too. I will have a PR coming later tonight with the complete fix.

**Comment by penguincoder** [comment] 2016-02-11 03:41
I spoke too soon, cygwin does not support file descriptors over unix sockets at all. The ControlMaster feature will just not work in cygwin.

**Comment by rclilly** [comment] 2016-02-11 15:59
- Windows 7 Pro SP1 64-bit
- VirtualBox Version 5.0.14 r105127
- Vagrant 1.8.1
- git version 2.7.1.windows.1 (Using git-bash)
- rsync  version 3.1.1  protocol version 31

Adding `ENV["VAGRANT_DETECTED_OS"] = ENV["VAGRANT_DETECTED_OS"].to_s + " cygwin"` to `Vagrantfile` does **_not_** help.

Note: I don't **_NOT_** have Cygwin installed

[vagrant-files.zip](https://github.com/mitchellh/vagrant/files/126643/vagrant-files.zi

**Comment by penguincoder** [comment] 2016-02-11 16:09
@rclilly You log file shows the same kind of error as my installation (I have cygwin). The root issue is resolved in https://github.com/mitchellh/vagrant/pull/7012

If you follow the instructions listed above (https://github.com/mitchellh/vagrant/issues/6702#issuecomment-166503021) and remove the lines pertaining to ControlMaster, your rsync should begin working again.

**Comment by rclilly** [comment] 2016-02-11 20:03
@penguincoder Thank you for your reply.

I have removed the three lines indicated from `helper.rb` but continue to get the same error message. I've tried the `Vagrantfile` with, and without `ENV["VAGRANT_DETECTED_OS"] = ENV["VAGRANT_DETECTED_OS"].to_s + " cygwin"`. I have put a copy of the edited `helper.rb` file into the attached zip file, along with the current version of `Vagrantfile` and the output from the git-bash window.

[vagrant-files-201602111151.zip](https://github.com/mitchellh/vagrant/files/127038/vagrant-files-201602111151.zip)

Again, I do **_NOT_** have Cygwin installed. I am using the Bash from the latest version of Git for Windows. I am using the standalone version of cwRsync 5.4.1, and it's in my PATH.

**Comment by robertkent87** [comment] 2016-02-18 12:48
I'm running a CentOS Vagrant machine on Windows 10. Forgive me for sounding stupid but where do I find `$VAGRANT_HOME\embedded\gems\gems\vagrant-1.8.0\plugins\synced_folders\rsync\helper.rb`? In Windows? In the virtual machine?

**Comment by mkuzmin** [comment] 2016-02-18 15:36
@robertkent87 It's on your Windows host machine, usually inside `C:\HashiCorp\Vagrant\`.

**Comment by grizzlylab** [comment] 2016-02-22 12:49
I confirm this fix is working with Vagrant 1.8.1.

**Comment by smolinari** [comment] 2016-02-29 05:28
Can someone get this fixed in 1.8.2? Please?

Scott

**Comment by smolinari** [comment] 2016-02-29 05:29
@robertkent87 - It is under the Hashi Corp directory on your C drive, if you used the standard installation location for Vagrant.

Scott

**Comment by penguincoder** [comment] 2016-02-29 20:46
PR #7012 will resolve the issue. I have been running the code with great success for a few weeks now. If one of the maintainers will merge it, our issue should be resolved with pristine Vagrant!

**Comment by pgibler** [comment] 2016-03-02 02:13
@arthuroy That fixed the issue for me, many thanks!

**Comment by davidlaym** [comment] 2016-03-03 20:39
The @arthuroy fix actually stopped the code 12 error for me, but rsync does not propagate changes to the guest when making file changes on the win10 host (using atom) or in the cygwin shell (using vim). I'm using vagrant from the cygwin shell as admin.

 Is rsync somehow not being notified by the OS that a file changed? how to fix this?

**Comment by penguincoder** [comment] 2016-03-03 20:41
@davidlaym The host should propagate changes only if you are also running `vagrant rsync-auto`. Regular `vagrant rsync` will only perform a one-shot update.

**Comment by davidlaym** [comment] 2016-03-03 20:50
I'm using it as a synced folder with rsync (I have some fs watchers that don't trigger on the default windows synced folder) with the flag `rsync__auto: true`, even when the docs says it's defaulted to true.

**Comment by ckubescha** [comment] 2016-03-06 03:58
Thank you @arthuroy! Removing lines 77-79 from helper.rb worked for me too!

**Comment by juliusza** [comment] 2016-03-08 13:28
+1

**Comment by tiQT** [comment] 2016-03-11 10:56
Worked for me too!! Thanks @arthuroy

**Comment by dhagberg** [comment] 2016-03-16 20:03
+1 to removing lines 77-79 from helper.rb with git-bash 1.7.2 and an rsync.exe copied from an msys2 installation to /mingw64/bin/rsync.

Is there a way for us to vote for @penguincoder 's #7012 ?

**Comment by thepeted** [comment] 2016-03-28 16:39
Just to add that removing lines 77-79 from helper.rb fixed the issue for me too. 

Windows 10 with Cygwin / Vagrant 1.8.1 / VirtualBox5

**Comment by geekkean** [comment] 2016-04-12 17:35
win 8.1 64bit 
Version 5.0.16 r105871
Vagrant 1.8.1
git version 2.5.3
rsync version 3.1.1 protocol version 31

works like charm.

just need to comment out line 77 to 79

NO NEED TO ADD -  ENV["VAGRANT_DETECTED_OS"] = ENV["VAGRANT_DETECTED_OS"].to_s + " cygwin" to Vagrantfile

and make sure cygwin path set corrently... this will work.

**Comment by rclilly** [comment] 2016-04-12 18:01
Just a reminder, this solution of commenting out lines 77-79 works for Cygwin only. It does **_not_** resolve rsync issues under Windows using other shells, like Git Bash.

**Comment by blah238** [comment] 2016-04-12 18:17
@rclilly Are you sure? My experience as well as some of the others here says otherwise. Don't use cwRsync, since that requires cygwin.

**Comment by rclilly** [comment] 2016-04-12 19:18
@blah238 Actually, I'm not 100% sure. I only know that I can't get the `centos/7` box on Windows 7 to work using Git Bash. Apparently that box requires Cygwin paths. I installed Cygwin, got the reported `rsync` error, commented out the relevant lines, and it worked. When I try to `vagrant up` using Git Bash I get an error about expecting `cygdrive` paths. This may be more of a CentOS 7 on Windows issue than an `rsync` issue in Vagrant. I will have to try `rsync` functionality with an Ubuntu box and see what happens.

**Comment by blah238** [comment] 2016-04-12 20:00
@rclilly It's because you're using cwRsync instead of GNU rsync. Nothing to do with the box, at least I'm pretty sure.

**Comment by rclilly** [comment] 2016-04-12 20:49
@blah238 Thanks!

**Comment by amoe** [comment] 2016-04-28 10:08
As @blah238 commented, pretty sure cwRsync is still not working with @arthuroy's workaround.  I have no information that it ever worked to begin with, however.  It doesn't seem to understand the special paths `/c` that it gets from Vagrant and wants a `/cygdrive` prefix instead.  Also it seems to be flat-out broken in `git-bash` perhaps due to some tty issue, the symptom being "`dup() in/out/err failed`".

**Comment by laggingreflex** [comment] 2016-05-13 20:53
cwRsync folks, try this: http://stackoverflow.com/questions/7261029/how-to-solve-rsync-error-error-in-rsync-protocol-data-stream-code-12-at-io-c

**Comment by msimkunas** [comment] 2016-05-15 16:02
Are there any plans to include a fix for this issue in future Vagrant releases? The posted workaround works for me as well, but I'd rather use an official release than try to hack individual files to get it working properly.

Just to confirm, downgrading to 1.7.4 fixes the issue.

**Comment by huangyanxiong01** [comment] 2016-05-20 03:20
非常感谢

**Comment by agavazov** [comment] 2016-05-28 14:28
Same problem here
Vagrant 1.8.1
Windows 10
VirtualBox 5.0.20
where rsync -> C:\HashiCorp\cwRsync_5.5.0_x86_Free\bin\rsync.exe
where ssh -> C:\HashiCorp\cwRsync_5.5.0_x86_Free\bin\ssh.exe
where ssh-keygen -> C:\HashiCorp\cwRsync_5.5.0_x86_Free\bin\ssh-keygen.exe

When I remove the following codes (line 77~79) the problem still exists

**Comment by agavazov** [comment] 2016-05-28 15:14
Wokrs fine with MInGW rsync

1st remove every rsync from windows path (jst write where rsync in console) after that install MinGW and mingw rsync

**Comment by DevNIX** [comment] 2016-06-05 11:47
Same problem here. I've even reverted to Vagrant 1.7.4 and the problem persists. I'm using the Docker provider, which is working on Ubuntu 15.10

**Comment by jianyunet** [comment] 2016-06-21 05:14
Thanks, worked for me on vagrant 1.8.3 / virtualbox 5.0.22, win 7

**Comment by rafd123** [comment] 2016-07-04 03:38
@sethvargo @mitchellh Is there anything we can do as a community to help expedite getting the fix for this issue (see https://github.com/mitchellh/vagrant/pull/7012) in an official Vagrant release sooner than later? A couple of releases have gone out without it so far.

It's a particular bummer that our Windows users of vagrant-aws have to choose between being able to use rsync by reverting to Vagrant 1.7.4, or forgoing rsync to take advantage of the new winrm.transport functionality added in 1.8.x. Instructing our users to manually patch Vagrant is kinda a support headache.

**Comment by kminek** [comment] 2016-07-16 21:49
arthuroy solution worked for me (Win7 + rsync + Vagrant 1.8.4 + DigitalOcean plugin) - after spending almost whole day i accidentally came across this ticket - thx man. it's really pain in the ass to make vagrant + rsync to work in Windows :((((

**Closed** 2016-07-19 02:05 UTC
Labels: bug, has-pr, synced-folders/rsync

**Comment by richard-melvin** [comment] 2016-08-12 12:33
v1.8.5 (including above commit) fixes this issue for me, but _only if run in a windows shell_. A cygwin terminal window presumably doesn't count as enough like Windows to trigger the workaround.

**Comment by penguincoder** [comment] 2016-08-12 14:33
This is working for me in a cygwin terminal. I am really only familiar with Unix shells, so I don't use any of the Window shells unless it is absolutely necessary.

I know it might be a pain in the butt, but could you try reinstalling cygwin? There could be something amiss in your particular installation that is tricking Vagrant into thinking it's not in Windows when it definitely is.

**Comment by chrisroberts** [comment] 2016-08-12 16:52
@richard-melvin Hi! I've tested synced folders using rsync with a cygwin terminal and do not see an issue. If you are having problems, can you please open an issue with the `Vagrantfile` you're using and the debug output of your `vagrant up`. Closed issues aren't closely tracked for new content and I'd like to make sure this is fully resolved. Thanks!

**Comment by richard-melvin** [comment] 2016-08-12 17:54
I couldn't reproduce it on a quick try-out. I guess if it is still an issue, someone else will report.

**Comment by frimik** [comment] 2016-08-17 09:57
this is broken with the SSH client that comes in Git Bash.

**Comment by shrmrf** [comment] 2016-08-17 10:01
@frimik I don't think Git bash has `rsync`. I use `rsync` that comes with Cygwin. It works.

**Comment by frimik** [comment] 2016-08-17 10:35
@shrmrf indeed, but rsync in turn use ssh, and it uses whatever client is on path. And while in the git Bash shell where I run pretty much all my things, it picks that SSH client.

Removing the `ControlPersist` option rolls onto the next issue though.

```
Host path: /cygdrive/c/Users/foo
rsync: change_dir "/cygdrive/c/Users/foo" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at /usr/src/rsync/rsync-3.0.8

$ pwd
/c/Users/foo
```
my Rsync (mingw) expects `/c/Users/...` style paths ....

```ruby
if Vagrant::Util::Platform.windows?
          # rsync for Windows expects cygwin style paths, always.
          hostpath = Vagrant::Util::Platform.cygwin_path(hostpath)
        end
```

Guess I need to decouple these things :). For now I've hack both things above and *my* rsync works at the moment :).

**Comment by shrmrf** [comment] 2016-08-17 10:57
I see... 
I tested with mingw (paths below):
```bash
> which ssh
/c/MinGW/msys/1.0/bin/ssh
> which rsync
/c/MinGW/msys/1.0/bin/rsync
```
I can confirm that this works too.

I don't think this is the right place to ask.. but do you know if we can use `Bash on Ubuntu on Windows` feature recently rolled out with Vagrant? Would be awesome!

**Comment by eug3n** [comment] 2016-08-22 14:56
@frimik Thank you for pointing out that this is broken with the SSH client that comes with Git Bash.

Installing openssh and rsync packages with mingw-get (http://www.mingw.org/wiki/getting_started) and copying all files from `C:\MinGW\msys\1.0\bin` to `C:\Program Files\Git\mingw64` solved the issue for me (Windows 10, Vagrant 1.8.5).

**Comment by dnadle** [comment] 2016-08-22 15:05
You don't have to overwrite your Git installation, just put the MinGW bin folder earlier in your PATH than then any other rsync binary.

**Comment by blah238** [comment] 2016-08-22 17:34
You can also uninstall the normal Git for Windows and install the Git for Windows SDK which has a package manager that can install rsync.

**Comment by czukowski** [comment] 2016-08-23 14:07
Managed to resolve the issue by installing msys2 using MSYS2 installer, then installing rsync package with `pacman -S rsync` (I suppose this step will be the same as with Git for Windows SDK) and moving the resulting `rsync.exe` to the Git's usr/bin folder (sys2 installation can then be removed). Not sure what else is included in GfW SDK, I gave this approach a try to avoid ending up with the stuff I didn't really need.

**Comment by czukowski** [comment] 2016-08-23 14:10
Note: using just cwRsync isn't going to work as of now, because it expects "cygwin-branded" paths (like `/cygwin/c/path/to/my/repo/`) and Vagrant will generate that only if it detects a full Cygwin installation.

**Comment by baderas** [comment] 2016-09-26 13:04
This error is still occuring when using msys2 and vagrant:
Versions:
vagrant 1.8.5
rsync  version 3.1.2  protocol version 31

I am also using the openstack plugin from https://github.com/ggiamarchi/vagrant-openstack-provider

Error:
```
==> default: Rsyncing folder: XXXXXXXXXX => /vagrant
There was an error when attempting to rsync a share folder.
Please inspect the error message below for more info.

Host path: XXXXXXXXXX
Guest path: /vagrant
Error: This rsync lacks old-style --compress due to its external zlib.  Try -zz.
Continuing without compression.
```

Any ideas? Disabling rsync via Vagrantfile did not work.

**Comment by shrmrf** [comment] 2016-09-26 13:38
@baderas can you try checking rsync with an `ubuntu/trusty64` machine?

It is working for me. Here's my env:
```
>which rsync
/c/MinGW/msys/1.0/bin/rsync

>which ssh
/c/MinGW/msys/1.0/bin/ssh
```

**Comment by baderas** [comment] 2016-09-26 14:18
Just for clarification: I'm using msys2, not msys.
I tried to fix it by editing /etc/fstab, but that did not work.
Using ubuntu/trusty64 is working without openstack plugin.
I also tried it with trusty on openstack - same error as above. It seems that https://github.com/ggiamarchi/vagrant-openstack-provider uses hard coded path to /cygwin/c/... which brakes it on msys2.

**Comment by baderas** [comment] 2016-09-26 14:29
I opened a bug report there: https://github.com/ggiamarchi/vagrant-openstack-provider/issues/304

**Comment by taliesins** [comment] 2016-10-06 14:36
I think we should be checking for the existence of cygpath in the path as well. Then as long as your ssh, rsync and cygpath work together you should be all right. No need to install cygwin then.

Here is the monkey patch I would apply to C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.8.6\lib\vagrant\util\platform.rb:
```
		def which(cmd)
		  exts = ENV['PATHEXT'] ? ENV['PATHEXT'].split(';') : ['']
		  ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
			exts.each { |ext|
			  exe = File.join(path, "#{cmd}#{ext}")
			  return exe if File.executable?(exe) && !File.directory?(exe)
			}
		  end
		  return nil
		end		
		
        # This takes any path and converts it from a Windows path to a
        # Cygwin or msys style path.
        #
        # @param [String] path
        # @return [String]
        def cygwin_path(path)		
          if cygwin?
            begin
              # First try the real cygpath
              process = Subprocess.execute("cygpath", "-u", "-a", path.to_s)
              return process.stdout.chomp
            rescue Errors::CommandUnavailableWindows
            end
          end

		  if which('cygpath')
            # First try the real cygpath
            process = Subprocess.execute("cygpath", "-u", "-a", path.to_s)
            return process.stdout.chomp
		  end
		  
          # Sometimes cygpath isn't available (msys). Instead, do what we
          # can with bash tricks.
          process = Subprocess.execute(
            "bash",
            "--noprofile",
            "--norc",
            "-c", "cd #{Shellwords.escape(path)} && pwd")
          return process.stdout.chomp
        end
```

**Comment by pizjix** [comment] 2016-11-02 06:14
One thing to check, if the workarounds do not work and you have git bash installed on Windows, is which ssh and rsync is used. Had the same error, and turned out that was using rsync from cygwin, but ssh from git bash. Changed the sequence in %PATH%, so that cygwin bin dir is before git bin dir, and it worked.

**Comment by yoplait** [comment] 2016-11-18 19:44
Hi, same problem here,
<<<<<
Complete!
Copy iso file C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
mount: /dev/loop0 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 5.1.8 - guest version is unknown
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.1.8 Guest Additions for Linux...........
VirtualBox Guest Additions installer
Copying additional installer modules ...
Installing additional modules ...
vboxadd.sh: Building Guest Additions kernel modules.
vboxadd.sh: Starting the VirtualBox Guest Additions.

Could not find the X.Org or XFree86 Window System, skipping.

==> default: Checking for guest additions in VM...
==> default: Rsyncing folder: /cygdrive/c/vm/centos/ => /vagrant
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /cygdrive/c/vm/centos/
Guest path: /vagrant
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--chmod=ugo=rwX" "--no-perms" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2222 -o LogLevel=FATAL   -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i 'C:/vm/centos/.vagrant/machines/default/virtualbox/private_key'" "--exclude" ".vagrant/" "/cygdrive/c/vm/centos/" "vagrant@127.0.0.1:/vagrant"
Error: rsync: Failed to exec ssh: No such file or directory (2)
rsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.1.2]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]


C:\vm\centos>vagrant ssh
`ssh` executable not found in any directories in the %PATH% variable. Is an
SSH client installed? Try installing Cygwin, MinGW or Git, all of which
contain an SSH client. Or use your favorite SSH client with the following
authentication information shown below:

Host: 127.0.0.1
Port: 2222
Username: vagrant
Private key: C:/vm/centos/.vagrant/machines/default/virtualbox/private_key

C:\vm\centos>vagrant --version
Vagrant 1.8.7

C:\vm\centos>ver

Microsoft Windows [Version 10.0.14393]

C:\vm\centos>

>>>

**Comment by ulkuniem** [comment] 2016-11-22 05:52
Had the rsync issue aswell using Git Bash.
Solution:
Installed MinGW with  Rsync and OpenSSH with MinGW Installation Manager Gui
C:\MinGW\libexec\mingw-get\guimain.exe

Added:
export PATH=/c/MinGW/msys/1.0/bin:$PATH
at the end of
"C:\Program Files\Git\etc\bash.bashrc"

So both ssh and rsync are used from C:/MinGW/msys/1.0/bin instead of Git Bash Mingw64 installation.

**Comment by valoujjal** [comment] 2016-11-22 14:04
Ho to export path in windows10

**Comment by ulkuniem** [comment] 2016-11-22 14:40
@valoujjal 
If you want to just export path to current console (and session) there are two ways:
CMD.exe:
`set PATH=C:/MinGW/msys/1.0/bin;%PATH%`
PowerShell.exe
`$env:Path = "C:/MinGW/msys/1.0/bin;$env:Path"`

If you want to persistent edit to the PATH environment variable:
-In Search, search for and then select: System (Control Panel)
-Click the Advanced system settings link.
-Click Environment Variables. ...
-In the Edit System Variable (or New System Variable) window, specify the value of the PATH environment variable.

If you mean to export like in bashrc, there are ways.
Powershell has profile.ps1 files.
The location is in $profile varialbe.
It might not exist so create one with
`New-Item $profile -ItemType File`
Edit with
`Notepad.exe $profile`
and add the $env:PATH modification.
More on the powershell profiles
[technet](https://blogs.technet.microsoft.com/heyscriptingguy/2012/05/21/understanding-the-six-powershell-profiles/)

and with cmd.exe profiles I'm not that familiar with but fast googling gave me this blog post that might be helpful: [cachemiss](http://blog.cachemiss.com/articles/My%20cmd.exe%20Profile.pod)

**Comment by Dannymx** [comment] 2016-11-29 00:41
@ulkuniem Adding the path to the Git bashrc worked for me! (I added the path to cygwin though).

**Comment by vladap** [comment] 2017-04-07 17:59
It is line 53 on Vagrant 1.9.3

**Comment by superhawk610** [comment] 2018-01-10 20:11
@ulkuniem Thanks! I only installed rsync via MinGW and that seemed to solve the issue for me, I didn't have to install ssh.

**Comment by andilabs** [comment] 2018-01-19 10:51
Running vagrant `1.9.4` on Mac OS X edited:
`/opt/vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/synced_folders/rsync/helper.rb` commented out line 84 `#control_options = "-o ControlMaster=auto -o ControlPath=#{controlpath} -o ControlPersist=10m "` but still no luck

```
[localhost] local: rsync  --exclude ".git" --exclude "*.pyc" -pthrvz  --rsh='ssh -i /Users/andi/Projects/acorn/shopify-data-fetcher/.vagrant/machines/default/virtualbox/private_key -p 2200  ' temp/shopify-data-fetcher/ vagrant@127.0.0.1:/var/www/shopify_data_fetcher
building file list ... done
rsync: connection unexpectedly closed (8 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52/rsync/io.c(453) [sender=2.6.9]

Fatal error: local() encountered an error (return code 12) while executing 'rsync  --exclude ".git" --exclude "*.pyc" -pthrvz  --rsh='ssh -i /Users/andi/Projects/acorn/shopify-data-fetcher/.vagrant/machines/default/virtualbox/private_key -p 2200  ' temp/shopify-data-fetcher/ vagrant@127.0.0.1:/var/www/shopify_data_fetcher'
```
