### ISSUE TITLE
private_network race condition with NetworkManager on Centos 7.1 with Vagrant 1.7.2

### ISSUE THREAD

**Issue by bcc** [mitchellh/vagrant#5590] opened 2015-04-13 15:46 UTC
Vagrant 1.7.2
CentOS 7.1
Virtualbox 4.3.22

It seems that NetworkManager on CentOS 7.1 is more aggressive about handling unconfigured interfaces on start than it was in with CentOS 7, and the way that Vagrant handles the configuration of the interfaces doesn't seem to be compatible with this.

I've updated a base box from Centos 7 to 7.1 (both built with the same packer configuration), and the 7.1 box fails to retain the private ip address. Looking at debug output (and adding some additional debug commands), the configuration does get set correctly during provisioning, but is undone shortly after the machine boots. It seems that this is due to NetworkManager waiting for DHCP to fail (as there's no dhcp configured on that private network), then unconfiguring the interface. 

As the /etc/sysconfig/network-scripts/ifcfg-enp0s8 file (in my case) which is generated (and indeed created) by Vagrant, has NM_CONTROLLED=no, NM doesn't handle the ifdown from configure_networks.rb, and the ifup happens while NM is still waiting for DHCP to finish.

```
[root@puppet vagrant]# nmcli dev
DEVICE  TYPE      STATE                                  CONNECTION         
enp0s3  ethernet  connected                              enp0s3             
enp0s8  ethernet  connecting (getting IP configuration)  Wired connection 1 
lo      loopback  unmanaged                              --                 
[root@puppet vagrant]# ip addr sh enp0s8
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:6f:44:44 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe6f:4444/64 scope link 
       valid_lft forever preferred_lft forever
```

As a workaround, I've found that enabling DHCP makes the problem go away (you end up with both IPs on the interface), or restarting NetworkManager so it gives up on the private interface also works, but it's a bit of a bodge. 

Similarly, forcing NetworkManager to give up on the interface in configure_networks.rb by inserting:
 
    machine.communicate.sudo("nmcli dev disconnect #{interface}")

Between the ifup and ifdown commands also seems to resolve the issue, although not especially cleanly.

```
[vagrant@puppet ~]$  nmcli dev
DEVICE  TYPE      STATE      CONNECTION 
enp0s3  ethernet  connected  enp0s3     
enp0s8  ethernet  connected  enp0s8     
lo      loopback  unmanaged  --         
[vagrant@puppet ~]$ ip addr sh enp0s8
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:70:d7:dc brd ff:ff:ff:ff:ff:ff
    inet 192.168.60.101/24 brd 192.168.60.255 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe70:d7dc/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by olivernaaris** [comment] 2015-04-14 07:49
+1. I had the same problem

**Comment by berendt** [comment] 2015-04-14 19:30
I can confirm the issue, but not the solution. After restarting the `network` service the interface are coming up with the correct IP address for several seconds.

```
[root@compute1 vagrant]# nmcli dev
DEVICE  TYPE      STATE                                  CONNECTION         
enp0s3  ethernet  connected                              enp0s3             
enp0s8  ethernet  connecting (getting IP configuration)  Wired connection 1 
enp0s9  ethernet  connecting (getting IP configuration)  Wired connection 2 
lo      loopback  unmanaged                              --                 
```

```
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:0b:76:65 brd ff:ff:ff:ff:ff:ff
    inet 10.100.50.20/16 brd 10.100.255.255 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe0b:7665/64 scope link 
       valid_lft forever preferred_lft forever
4: enp0s9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:95:62:55 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.20/24 brd 10.0.0.255 scope global enp0s9
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe95:6255/64 scope link 
       valid_lft forever preferred_lft forever
```

After a few seconds I got the following message in `dmesg`:

```
[ 2162.506993] IPv6: ADDRCONF(NETDEV_UP): enp0s8: link is not ready
[ 2162.508435] e1000: enp0s8 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[ 2162.508714] IPv6: ADDRCONF(NETDEV_CHANGE): enp0s8: link becomes ready
[ 2165.067404] IPv6: ADDRCONF(NETDEV_UP): enp0s9: link is not ready
[ 2165.067994] e1000: enp0s9 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[ 2165.068325] IPv6: ADDRCONF(NETDEV_CHANGE): enp0s9: link becomes ready
```

IP addresses are dropped:

```
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:0b:76:65 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe0b:7665/64 scope link 
       valid_lft forever preferred_lft forever
4: enp0s9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:95:62:55 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe95:6255/64 scope link 
       valid_lft forever preferred_lft forever
```

Looking inside `journalctl -xn`:

```
Apr 14 19:23:24 compute1 NetworkManager[466]: <info>  (enp0s8): Activation: Stage 4 of 5 (IPv6 Configure Timeout) scheduled...
Apr 14 19:23:24 compute1 NetworkManager[466]: <info>  (enp0s8): Activation: Stage 4 of 5 (IPv6 Configure Timeout) started...
Apr 14 19:23:24 compute1 NetworkManager[466]: <info>  (enp0s8): Activation: Stage 4 of 5 (IPv6 Configure Timeout) complete.
Apr 14 19:23:26 compute1 NetworkManager[466]: <info>  (enp0s9): Activation: Stage 4 of 5 (IPv6 Configure Timeout) scheduled...
Apr 14 19:23:26 compute1 NetworkManager[466]: <info>  (enp0s9): Activation: Stage 4 of 5 (IPv6 Configure Timeout) started...
Apr 14 19:23:26 compute1 NetworkManager[466]: <info>  (enp0s9): Activation: Stage 4 of 5 (IPv6 Configure Timeout) complete.
```

**Comment by bcc** [comment] 2015-04-15 13:14
I think that still makes sense - restarting the network service doesn't reload NetworkManager, so it will still be under the impression it is managing that interface: 

    [root@puppet vagrant]# ps -Af|grep -i NetworkManager
    root       663     1  0 Apr13 ?        00:00:00 /usr/sbin/NetworkManager --no-daemon

    [root@puppet vagrant]# systemctl restart network
    ...

    [root@puppet vagrant]# ps -Af|grep NetworkManager
    root       663     1  0 Apr13 ?        00:00:00 /usr/sbin/NetworkManager --no-daemon

**Comment by ogrange** [comment] 2015-05-27 12:10
Workaround for this problem (as suggested [here](http://qiita.com/kutsushitaneko/items/18ed70bdc6075c1d46df)) before #5709 gets merged: running  ```nmcli connection reload; systemctl restart network.service``` with shell provisioning, ie adding ```config.vm.provision "shell", inline: "nmcli connection reload; systemctl restart network.service"``` to your ```Vagrantfile```.

**Comment by sethvargo** [comment] 2015-05-31 04:50
Fixed in #5709. Thanks!

**Closed by sethvargo** 2015-05-31 04:50 UTC

**Comment by dddpaul** [comment] 2016-12-20 08:23
Hello.

I have the similar issue with Vagrant 1.9.1, VirtualBox 5.1.10 on MacOS Sierra (10.12.2) and Ubuntu 16.04 with Centos 7.3 (centos/7 box).

Box network settings in Vagrantfile:

```
node.vm.box = "centos/7"
node.vm.network :private_network, ip: "192.168.40.111"
```

Network configuration inside box:

```
cat /etc/sysconfig/network-scripts/ifcfg-eth1
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
NM_CONTROLLED=no
BOOTPROTO=none
ONBOOT=yes
IPADDR=192.168.40.111
NETMASK=255.255.255.0
DEVICE=eth1
PEERDNS=no
#VAGRANT-END
```

But `eth1` is in down state actually:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:22:5b:53 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 85838sec preferred_lft 85838sec
    inet6 fe80::5054:ff:fe22:5b53/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN qlen 1000
    link/ether 08:00:27:31:b1:bd brd ff:ff:ff:ff:ff:ff
```

The workaround is to restart `network` service while provisioning. For example (for Ansible):

```
- name: ensure all interfaces is up 
  service: name=network enabled=yes state=restarted

```

**Comment by lauriii** [comment] 2016-12-22 05:16
I'm running Ubuntu 16.10 and Centos 7 on the guest. I'm having similar networking issues where a private_network IP is not being assigned for the guest even though though the virtual network exists. Downgrading from Vagrant 1.9.1 to 1.8.7 fixed this for me.

**Comment by andrewrothstein** [comment] 2016-12-23 18:23
Host: Fedora 25
Guest: CentOS 7
Virtualbox: 5.1.12r112440
Vagrant: v1.9.1

I'm suffering from this issue corresponding to the 1.8.7 to 1.9.1 upgrade. The proposed workaround by @ogrange works for me.

**Comment by dddpaul** [comment] 2016-12-26 12:26
Should we open a new issue?

**Comment by rumatoest** [comment] 2016-12-27 14:16
The same degradation Issue on ubuntu 16.10 and vagrant 1.9.1.
Downgrade to 1.8.7 helped.

**Comment by gkristic** [comment] 2017-01-02 02:00
Same thing here with CentOS 7. @dddpaul I think this deserves a new issue indeed.

**Comment by guilhemmarchand** [comment] 2017-01-07 11:55
Hi, same issue experienced here, all CentOS 7.x box affected, host Ubuntu 16.10 and vagrant 1.9.1
Using Ansible with network manager restart workaround fixes unless the host is rebooted.

**Comment by sfarmer11** [comment] 2017-01-19 21:39
Confirmed replication of this issue. Host OSX 10.12.2, Guest CentOS7.2, Virtualbox 5.0.30 and 5.0.32. Vagrant 1.9.1. I've confirmed that this issue goes away if I revert Vagrant to 1.9.0.

**Comment by bbaassssiiee** [comment] 2017-02-07 21:39
When I use NFS for the config.vm.synced_folder then I have no chance to do anything in provisioner because vagrant never gets there.
